"use client";

import { ArrowsClockwiseIcon, ChartLineUpIcon, ClockCounterClockwiseIcon, DatabaseIcon, GaugeIcon, GearIcon, TrendUpIcon, WalletIcon } from "@phosphor-icons/react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { evaluateOosActionGate } from "@/lib/oos-action-gate";
import type { DashboardPayload, EquityPoint } from "@/lib/types";

type Tab="overview"|"universe"|"ranking"|"portfolio"|"oos"|"backtest"|"schedule";
const tabs=[["overview","概要",GaugeIcon],["universe","Dynamic Universe",DatabaseIcon],["ranking","Momentum順位",TrendUpIcon],["portfolio","ポートフォリオ",WalletIcon],["oos","OOS",ChartLineUpIcon],["backtest","バックテスト",ClockCounterClockwiseIcon],["schedule","設定",GearIcon]] as const;
const mobile:Partial<Record<Tab,string>>={portfolio:"保有",backtest:"検証",schedule:"設定"};
const num=new Intl.NumberFormat("ja-JP",{maximumFractionDigits:2});
const pct=(v:number|null|undefined,d=1)=>v==null?"—":`${(v*100).toFixed(d)}%`;
const money=(v:number|null|undefined)=>v==null?"—":`$${num.format(v)}`;
const date=(v:string|null|undefined)=>v?v.replaceAll("-","."):"—";
const updatedAt=(value:string)=>new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(value)).replaceAll("/",".");
const usOpen=(value:string|null)=>{if(!value)return"—";const[y,m,d]=value.split("-").map(Number),target=Date.UTC(y,m-1,d,9,30);const f=new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false});let instant=new Date(target);for(let i=0;i<2;i++){const p=f.formatToParts(instant),g=(t:Intl.DateTimeFormatPartTypes)=>Number(p.find(x=>x.type===t)?.value??0),rendered=Date.UTC(g("year"),g("month")-1,g("day"),g("hour"),g("minute"));instant=new Date(instant.getTime()+target-rendered)}return updatedAt(instant.toISOString())};

function Section({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="dynamic-card"><header><h2>{title}</h2>{action}</header>{children}</section>}
function Metric({label,value,tone}:{label:string;value:string;tone?:"good"|"bad"}){return <div className="dynamic-metric"><span>{label}</span><strong className={tone?`tone-${tone}`:""}>{value}</strong></div>}
function Badge({value}:{value:string}){const good=value==="NORMAL"||value==="GREEN";return <span className={`state-badge ${good?"good":"cash"}`}>{value}</span>}
function TargetList({data}:{data:DashboardPayload}){return <div className="position-list">{data.portfolioState.targets.map(t=><div className="position-row" key={`${t.role}-${t.symbol}`}><div><strong>{t.symbol}</strong><span>{t.role==="FIXED60"?"Fixed60 Top2":t.role==="DIVERSIFIER"?"Gold diversifier":"Cash"}</span></div><strong>{pct(t.weight)}</strong></div>)}</div>}

export function MomentumApp({initialDashboard}:{initialDashboard:DashboardPayload}){
 const[tab,setTab]=useState<Tab>("overview"),[data,setData]=useState(initialDashboard),[refreshing,setRefreshing]=useState(false),[message,setMessage]=useState<string|null>(null);
 const load=useCallback(async(interactive:boolean)=>{if(interactive){setRefreshing(true);setMessage(null)}try{const base=process.env.NEXT_PUBLIC_BASE_PATH??"",r=await fetch(`${base}/data/dashboard.json?t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error("配信済みデータを読み込めませんでした。");const body=await r.json() as {dashboard?:DashboardPayload};if(!body.dashboard)throw new Error("dashboardが見つかりませんでした。");setData(body.dashboard);if(interactive)setMessage(`更新: ${updatedAt(body.dashboard.generatedAt)}`)}catch(e){if(interactive)setMessage(e instanceof Error?e.message:"更新に失敗しました") }finally{if(interactive)setRefreshing(false)}},[]);
 useEffect(()=>{const timer=window.setInterval(()=>void load(false),5*60_000);return()=>window.clearInterval(timer)},[load]);
 const title=tabs.find(([key])=>key===tab)?.[1]??"概要";
 return <div className="app-shell dynamic-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><TrendUpIcon weight="bold"/></div><div><strong>Momentum</strong><span>Stage21 Console</span></div></div><nav>{tabs.map(([key,label,Icon])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}><Icon size={18}/><span className="tab-label-default">{label}</span><span className="tab-label-mobile">{mobile[key]??label}</span></button>)}</nav><div className="sidebar-foot"><span>Production strategy</span><strong>{data.portfolioConfig.strategyId}</strong></div></aside><main><div className="topbar"><div><span>SBI / Point-in-Time / next-open</span><strong>{title}</strong></div><div className="topbar-refresh"><span className="last-updated"><b>最終更新</b> {updatedAt(data.generatedAt)}</span><button className="refresh-button" disabled={refreshing} onClick={()=>void load(true)}><ArrowsClockwiseIcon className={refreshing?"spin":""} size={20}/>最新データを読込</button></div></div><div className="dynamic-content">{data.warning&&<div className="data-warning">{data.warning}</div>}{message&&<div className="refresh-message">{message}</div>}{tab==="overview"&&<Overview data={data}/>} {tab==="universe"&&<Universe data={data}/>} {tab==="ranking"&&<Ranking data={data}/>} {tab==="portfolio"&&<Portfolio data={data}/>} {tab==="oos"&&<Oos data={data}/>} {tab==="backtest"&&<Backtest data={data}/>} {tab==="schedule"&&<Schedule data={data}/>}</div></main></div>
}

function Overview({data}:{data:DashboardPayload}){
 const gate=evaluateOosActionGate(data.oos),p=data.portfolioState,action=p.nextAction;
 return <div className="dynamic-stack"><Section title="Stage21 Next Action" action={<Badge value={p.regime}/>}><div className="next-action" style={{gridTemplateColumns:"repeat(6,minmax(0,1fr))"}}><div style={{gridColumn:"span 2"}}><span>Action gate</span><div className="next-action-copy"><strong>{gate.level}</strong><p>{gate.blocksNewEntries?"新規買付停止":"継続"}</p></div></div><div style={{gridColumn:"span 2"}}><span>次回注文</span><div className="next-action-copy"><strong>{action.type==="REBALANCE_NEXT_OPEN"?"REBALANCE":"HOLD"}</strong><p>{action.reason}</p></div></div><div style={{gridColumn:"span 2"}}><span>予定時刻</span><div className="next-action-copy"><strong>{usOpen(action.executionDate)}</strong></div></div></div></Section>
 <div className="dynamic-metric-grid five"><Metric label="Regime" value={p.regime}/><Metric label="CFTC" value={p.cftc.yellow?"YELLOW":"CLEAR"}/><Metric label="CFTC report" value={date(p.cftc.reportDate)}/><Metric label="M3 Deep" value={p.m3.deep?"ON":"OFF"}/><Metric label="M3 gap" value={pct(p.m3.gap)}/></div>
 <div className="overview-two"><Section title="現在の資金配分"><TargetList data={data}/></Section><Section title="Fixed60 inner engine"><div className="dynamic-metric-grid"><Metric label="Inner state" value={data.liveState.state}/><Metric label="Top2" value={p.fixed60.symbols.join(" / ")||"CASH"}/><Metric label="Inner weight" value={p.fixed60.innerWeights.map(w=>pct(w,0)).join(" / ")||"—"}/><Metric label="QQQ 10M MA" value={money(data.qqq.monthlyMa)}/></div><p className="muted-copy">Fixed60は銘柄選定・内側のstop/circuit/recoveryを担当します。実口座の最終配分は上のStage21 targetです。</p></Section></div>
 <Section title="OOS status" action={<Badge value={gate.level}/>}><div className="dynamic-metric-grid five"><Metric label="開始" value={date(data.oos.startedAt)}/><Metric label="As of" value={date(data.oos.asOf)}/><Metric label="OOS CAGR" value={data.oos.asOf?pct(data.oos.stats.cagr):"評価前"}/><Metric label="OOS MaxDD" value={data.oos.asOf?pct(data.oos.stats.maxDrawdown):"評価前"}/><Metric label="Phase" value={gate.phase}/></div><p className="muted-copy">{gate.reason}</p></Section></div>
}

function Universe({data}:{data:DashboardPayload}){const u=data.currentUniverse;return <div className="dynamic-stack"><Section title="Dynamic Universe"><div className="dynamic-metric-grid five"><Metric label="Signal month" value={u?.signalMonth??"—"}/><Metric label="As of" value={date(u?.asOf)}/><Metric label="Universe size" value={String(u?.symbols.length??0)}/><Metric label="N-PORT mode" value={data.nportOperations?.universeMode??"—"}/><Metric label="取込期限" value={data.nportOperations?.nextImportDeadlineAt?updatedAt(data.nportOperations.nextImportDeadlineAt):"—"}/></div></Section><Section title="SEC N-PORT Breadth Ranking"><div className="ranking-table"><div className="ranking-head"><span>#</span><span>Ticker</span><span>ETF count</span><span>Aggregate weight</span><span>Score</span></div>{u?.symbols.map(m=><div className="ranking-row" key={m.symbol}><span>{m.universeRank}</span><strong>{m.symbol}</strong><span>{m.etfCount}</span><span>{m.aggregateWeight.toFixed(2)}</span><span>{m.universeScore.toFixed(2)}</span></div>)}</div></Section></div>}

function Ranking({data}:{data:DashboardPayload}){const s=data.currentSignal;return <div className="dynamic-stack"><Section title="Fixed60 Momentum Signal"><div className="dynamic-metric-grid five"><Metric label="Signal date" value={date(s?.signalDate)}/><Metric label="Risk" value={s?.marketRiskOn?"ON":"OFF"}/><Metric label="QQQ score" value={pct(s?.qqqScore)}/><Metric label="Top2" value={s?.selectedSymbols.join(" / ")||"CASH"}/><Metric label="Inner allocation" value={s?.targetWeights.map(w=>pct(w,0)).join(" / ")||"—"}/></div></Section><Section title="Momentum順位"><div className="ranking-table"><div className="ranking-head"><span>#</span><span>Ticker</span><span>3M</span><span>6M</span><span>Score</span></div>{s?.candidates.filter(c=>c.rank!=null).sort((a,b)=>(a.rank??999)-(b.rank??999)).slice(0,80).map(c=><div className="ranking-row" key={c.symbol}><span>{c.rank}</span><strong>{c.symbol}</strong><span>{pct(c.threeMonth)}</span><span>{pct(c.sixMonth)}</span><span>{pct(c.score)}</span></div>)}</div></Section></div>}

function Portfolio({data}:{data:DashboardPayload}){const p=data.portfolioState,w=data.portfolioConfig.weights[p.regime];return <div className="dynamic-stack"><Section title="Stage21 funded portfolio" action={<Badge value={p.regime}/>}><TargetList data={data}/></Section><div className="overview-two"><Section title="Regime allocation"><div className="dynamic-metric-grid"><Metric label="Fixed60 sleeve" value={pct(w.fixed60)}/><Metric label="GLDM" value={pct(w.gldm)}/><Metric label="Cash" value={pct(w.cash)}/><Metric label="Gross exposure" value={pct(w.fixed60+w.gldm)}/></div></Section><Section title="Risk signals"><div className="dynamic-metric-grid"><Metric label="CFTC net" value={p.cftc.net==null?"—":num.format(p.cftc.net)}/><Metric label="4週前 net" value={p.cftc.priorNet==null?"—":num.format(p.cftc.priorNet)}/><Metric label="M3 core 20D" value={pct(p.m3.coreReturn20)}/><Metric label="QQQ 20D" value={pct(p.m3.qqqReturn20)}/></div></Section></div><Section title="Broker execution"><p className="muted-copy">SBIでは整数株で実行します。研究監査では$10k〜$250kの整数株simulationでCAGR差は最大約0.36pt、全ケースでMaxDD 17%以内でした。targetに不足する端数はCashとして残します。</p></Section></div>}

function Oos({data}:{data:DashboardPayload}){const gate=evaluateOosActionGate(data.oos),records=[...data.oos.records].reverse().slice(0,30);return <div className="dynamic-stack"><Section title="Stage21 True Forward OOS" action={<Badge value={gate.level}/>}><div className="dynamic-metric-grid five"><Metric label="Start" value={date(data.oos.startedAt)}/><Metric label="As of" value={date(data.oos.asOf)}/><Metric label="CAGR" value={data.oos.asOf?pct(data.oos.stats.cagr):"評価前"}/><Metric label="MaxDD" value={data.oos.asOf?pct(data.oos.stats.maxDrawdown):"評価前"}/><Metric label="Records" value={String(data.oos.records.length)}/></div><p className="muted-copy">{gate.instruction} {gate.reason}</p></Section><Section title="Daily state audit"><div className="ranking-table"><div className="ranking-head"><span>Date</span><span>Regime</span><span>Target</span><span>CFTC</span><span>Execution</span></div>{records.map(r=><div className="ranking-row" key={r.recordDate??r.signalDate}><span>{date(r.recordDate??r.signalDate)}</span><strong>{r.portfolioState??r.riskState}</strong><span>{r.portfolioTargets?.map(t=>`${t.symbol} ${pct(t.weight,0)}`).join(" / ")??r.selectedSymbols.join(" / ")}</span><span>{r.cftc?.yellow?"YELLOW":"CLEAR"}</span><span>{date(r.executionDate)}</span></div>)}</div></Section></div>}

function CurveChart({curve}:{curve:EquityPoint[]}){const rows=useMemo(()=>curve.map(p=>({date:p.date,equity:p.equity})),[curve]);return <div style={{height:320}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={rows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" minTickGap={42}/><YAxis/><Tooltip/><Area type="monotone" dataKey="equity" fillOpacity={.14}/></AreaChart></ResponsiveContainer></div>}
function Backtest({data}:{data:DashboardPayload}){const r=data.portfolioConfig.researchReference;return <div className="dynamic-stack"><Section title="Stage21 historical backtest"><div className="dynamic-metric-grid five"><Metric label="CAGR" value={pct(data.backtest.stats.cagr)}/><Metric label="MaxDD" value={pct(data.backtest.stats.maxDrawdown)}/><Metric label="Volatility" value={pct(data.backtest.stats.annualizedVolatility)}/><Metric label="Calmar" value={data.backtest.stats.calmar?.toFixed(2)??"—"}/><Metric label="Final equity" value={`${data.backtest.stats.finalEquity.toFixed(2)}x`}/></div><CurveChart curve={data.backtest.equityCurve}/></Section><Section title="Research planning reference"><div className="dynamic-metric-grid five"><Metric label="Planning proxy" value={pct(r.planningCagrProxy)}/><Metric label="Rolling36 median" value={pct(r.rolling36MedianCagr)}/><Metric label="Rolling36 P10" value={pct(r.rolling36P10Cagr)}/><Metric label="Rolling36 worst" value={pct(r.rolling36WorstCagr)}/><Metric label="PIT historical DD" value={pct(r.historicalMaxDrawdown)}/></div><p className="muted-copy">{r.note} 24–36か月ではCAGR 40%を下回るwindowも普通に存在するため、Planning proxyを毎年の期待収益率として扱いません。</p></Section></div>}

function Schedule({data}:{data:DashboardPayload}){const c=data.portfolioConfig,p=data.portfolioState;return <div className="dynamic-stack"><Section title="Production specification"><div className="dynamic-metric-grid five"><Metric label="Production ID" value={c.strategyId}/><Metric label="Inner Fixed60" value={c.legacyInnerStrategyId}/><Metric label="OOS start" value={date(c.oosStartDate)}/><Metric label="Execution" value="Next open"/><Metric label="Cost model" value={pct(c.execution.transactionCost,2)}/></div></Section><Section title="State weights"><div className="ranking-table"><div className="ranking-head"><span>State</span><span>Fixed60</span><span>GLDM</span><span>Cash</span><span>Current</span></div>{(["NORMAL","YELLOW","DEEP"] as const).map(state=>{const w=c.weights[state];return <div className="ranking-row" key={state}><strong>{state}</strong><span>{pct(w.fixed60)}</span><span>{pct(w.gldm)}</span><span>{pct(w.cash)}</span><span>{p.regime===state?"●":""}</span></div>})}</div></Section><Section title="Frozen risk logic"><p className="muted-copy"><b>CFTC Yellow:</b> Nasdaq Mini Asset Manager net positionを1週lagで利用し、最新値が4レポート前より低ければYellow。絶対閾値なし。</p><p className="muted-copy"><b>M3 Deep:</b> 85% Fixed60 + 15% Gのshadow coreを20営業日で測定。core return &lt; 0 かつQQQ比 -10pp以下でDeep、gap &gt; -3ppを5営業日確認して解除。Gは資金配分されません。</p><p className="muted-copy"><b>Fixed60 inner:</b> SEC N-PORT Universe 80、Momentum 0/20/80、Top2 60/40、QQQ 10M MA、stop 17.5%、circuit 15%、100DMA/20D/10-close recovery。</p></Section></div>}
