import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { performanceStats } from "../src/lib/backtest";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import type { EquityPoint, PricePoint, StrategyConfig, UniverseMonth } from "../src/lib/types";
const VARIANTS=[
{id:"PRODUCTION",base:0.5,conc:0.7,gap:0.25},
{id:"HYBRID55",base:0.55,conc:0.7,gap:0.25},
{id:"HYBRID60",base:0.6,conc:0.7,gap:0.25},
{id:"HYBRID65",base:0.65,conc:0.7,gap:0.25},
] as const;
function cfg(v:any):StrategyConfig{return {...PRODUCTION_STRATEGY,allocation:{baseTop1Weight:v.base,concentratedTop1Weight:v.conc,concentrationZGap:v.gap,maxTop1Weight:0.7}} as StrategyConfig;}
function sim(hist:Record<string,PricePoint[]>,universe:UniverseMonth[],v:any){const c=cfg(v),qqq=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=qqq.map(p=>p.date),di=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(universe.map(u=>[u.asOf,u]));let st=initialEngineState(c);const curve:EquityPoint[]=[];for(let i=0;i<dates.length;i++){const date=dates[i];if(date<c.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),u=um.get(date),sig=u?buildMonthlySignal({universe:u,histories:hist,qqq,nextSessionDate:next,config:c}):null,sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));st=transitionDay(st,{date,prices,qqqHistoryThroughClose:qqq.slice(0,(di.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},c);curve.push({date,equity:st.currentEquity,drawdown:st.drawdown});}return curve;}
function slice(curve:EquityPoint[],start:string,end:string){const xs=curve.filter(p=>p.date>=start&&p.date<=end);if(xs.length<2)return null;const prev=[...curve].reverse().find(p=>p.date<start),rows=prev?[prev,...xs]:xs,b=rows[0].equity;return performanceStats(rows.map(p=>({...p,equity:p.equity/b})));}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]},universe=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),rs=VARIANTS.map(v=>({v,curve:sim(market.histories,universe,v)})),last=rs[0].curve.at(-1)!.date,years=[2021,2022,2023,2024,2025,2026],full=rs.map(r=>({id:r.v.id,base:r.v.base,stats:performanceStats(r.curve)})),yearly=years.map(y=>({year:y,...Object.fromEntries(rs.map(r=>[r.v.id,slice(r.curve,`${y}-01-01`,y===2026?last:`${y}-12-31`)]))})),rolling=[] as any[];for(const months of [12,24]){for(let i=0;i<rs[0].curve.length;i+=21){const end=rs[0].curve[i].date;const d=new Date(end+"T00:00:00Z");d.setUTCMonth(d.getUTCMonth()-months);const start=d.toISOString().slice(0,10);if(start<"2020-01-01")continue;const row:any={months,start,end};for(const r of rs)row[r.v.id]=slice(r.curve,start,end)?.cagr??null;rolling.push(row);}}const prod=full.find(x=>x.id==="PRODUCTION")!,summary=full.filter(x=>x.id!=="PRODUCTION").map(x=>({id:x.id,cagrDelta:x.stats.cagr-prod.stats.cagr,maxDdDelta:x.stats.maxDrawdown-prod.stats.maxDrawdown,yearsBeatProduction:yearly.filter((y:any)=>(y[x.id]?.cagr??-99)>(y.PRODUCTION?.cagr??-99)+1e-12).length,yearsTieProduction:yearly.filter((y:any)=>Math.abs((y[x.id]?.cagr??0)-(y.PRODUCTION?.cagr??0))<=1e-12).length,yearsLostProduction:yearly.filter((y:any)=>(y[x.id]?.cagr??-99)<(y.PRODUCTION?.cagr??-99)-1e-12).length}));const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,architectureHindsightRemains:true,noLeverage:true,purpose:"Neighborhood robustness only; 55/60/65 base weights are not a new optimization grid. Concentrated weight and zGap remain fixed at Production 70% and 0.25."},full,yearly,summary,rolling};const dir=path.join(process.cwd(),"data/research/allocation-hybrid-neighborhood");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(out,null,2));console.log(JSON.stringify({generatedAt:out.generatedAt,validity:out.validity,full,yearly,summary},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});