import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import type { MonthlySignal, PricePoint, StrategyConfig, UniverseMonth } from "../src/lib/types";

type Market={histories:Record<string,PricePoint[]>}; type UF={history:UniverseMonth[]};
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
const sd=(x:number[])=>{const m=avg(x);return x.length?Math.sqrt(avg(x.map(v=>(v-m)**2))):0};
function latestU(us:UniverseMonth[],d:string){let a=us[0];for(const u of us){if(u.asOf<=d)a=u;else break}return a}
const score=(r3:number,r6:number)=>.2*r3+.8*r6;
function makeSignal(date:string,next:string|null,u:UniverseMonth,monthly:Map<string,number[]>):MonthlySignal{const q=monthly.get("QQQ")??[],ret=(x:number[],n:number)=>x.length>n?x.at(-1)!/x.at(-(n+1))!-1:null,q1=ret(q,1),q3=ret(q,3),q6=ret(q,6),qs=q1==null||q3==null||q6==null?null:score(q3,q6),ma=q.slice(-10),risk=ma.length===10&&q.at(-1)!>avg(ma),c:any[]=[];for(const m of u.symbols){const x=monthly.get(m.symbol)??[],r1=ret(x,1),r3=ret(x,3),r6=ret(x,6);if(r1==null||r3==null||r6==null||qs==null){c.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:null,qqqScore:qs,scoreSpread:null,eligible:false,exclusionReason:"INSUFFICIENT_PRICE_HISTORY",rank:null});continue}const s=score(r3,r6),reason=r1>=.8?"ONE_MONTH_SURGE":s<=qs?"NOT_ABOVE_QQQ":null;c.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:s,qqqScore:qs,scoreSpread:s-qs,eligible:!reason,exclusionReason:reason,rank:null})}const e=c.filter(x=>x.eligible&&x.score!=null).sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol));e.forEach((x,i)=>x.rank=i+1);const chosen=e.slice(0,2),valid=chosen.length===2,d=sd(e.map(x=>x.score)),zg=valid&&d>0?(chosen[0].score-chosen[1].score)/d:valid?0:null,conc=zg!=null&&zg>=.25,w=conc?.7:.5;return {strategyId:PRODUCTION_STRATEGY.strategyId,signalMonth:date.slice(0,7),signalDate:date,executionDate:next,marketRiskOn:risk,qqqClose:q.at(-1)??null,qqqMonthlyMa:ma.length===10?avg(ma):null,qqqScore:qs,universe:u.symbols.map(x=>x.symbol),candidates:c,selectedSymbols:valid?chosen.map(x=>x.symbol):[],targetWeights:valid?[w,1-w]:[],zGap:zg,allocationMode:!valid?"CASH":conc?"70/30":"50/50"} as MonthlySignal}
function metrics(curve:number[]){let peak=curve[0]??1,dd=0;for(const v of curve){peak=Math.max(peak,v);dd=Math.min(dd,v/peak-1)}const years=(curve.length-1)/252,wealth=curve.at(-1)!/(curve[0]||1);return{cagr:wealth**(1/years)-1,maxDrawdown:dd,finalWealth:wealth}}
async function main(){const market=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8")) as Market,uf=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8")) as UF,us=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),hist=market.histories,dates=(hist.QQQ??[]).filter(p=>p.date>=PRODUCTION_STRATEGY.backtestStart).map(p=>p.date),symbols=[...new Set(["QQQ",...us.flatMap(u=>u.symbols.map(x=>x.symbol))])],maps=new Map(symbols.map(s=>[s,new Map((hist[s]??[]).map(p=>[p.date,p]))])),monthly=new Map<string,number[]>(symbols.map(s=>[s,[]])),signals:Record<string,MonthlySignal>={};
 for(let i=0;i<dates.length;i++){const d=dates[i],next=dates[i+1]??null,me=!next||next.slice(0,7)!==d.slice(0,7);if(me){for(const s of symbols){const p=maps.get(s)?.get(d);if(p)monthly.get(s)!.push(p.close)}signals[d]=makeSignal(d,next,latestU(us,d),monthly)}}
 const variants=[
  {name:"production",cfg:PRODUCTION_STRATEGY,forceRiskOn:false},
  {name:"no_individual_stop",cfg:{...PRODUCTION_STRATEGY,risk:{...PRODUCTION_STRATEGY.risk,individualStop:1}} as StrategyConfig,forceRiskOn:false},
  {name:"no_portfolio_circuit",cfg:{...PRODUCTION_STRATEGY,risk:{...PRODUCTION_STRATEGY.risk,portfolioCircuit:1}} as StrategyConfig,forceRiskOn:false},
  {name:"no_stop_no_circuit",cfg:{...PRODUCTION_STRATEGY,risk:{individualStop:1,portfolioCircuit:1}} as StrategyConfig,forceRiskOn:false},
  {name:"no_market_gate",cfg:PRODUCTION_STRATEGY,forceRiskOn:true},
  {name:"recovery_5d",cfg:{...PRODUCTION_STRATEGY,recovery:{...PRODUCTION_STRATEGY.recovery,confirmationDays:5}} as StrategyConfig,forceRiskOn:false},
 ];
 const results:any[]=[];
 for(const v of variants){let st=initialEngineState(v.cfg),qh:PricePoint[]=[],curve:number[]=[1],cashDays=0;const events:Record<string,number>={};for(let i=0;i<dates.length;i++){const d=dates[i],next=dates[i+1]??null,prices:Record<string,PricePoint|undefined>={};for(const s of symbols){const p=maps.get(s)?.get(d);if(p)prices[s]=p}if(prices.QQQ)qh.push(prices.QQQ);let sig=signals[d]??null;if(sig&&v.forceRiskOn)sig={...sig,marketRiskOn:true};const prevEvents=st.events.length;st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:qh,monthlySignal:sig,nextSessionDate:next},v.cfg);curve.push(st.currentEquity);if(st.currentPositions.length===0)cashDays++;for(const e of st.events.slice(prevEvents))events[e.reason]=(events[e.reason]??0)+1}results.push({name:v.name,...metrics(curve),cashRate:cashDays/dates.length,eventCounts:events})}
 const base=results.find(x=>x.name==="production");for(const r of results){r.deltaCagrVsProduction=r.cagr-base.cagr;r.deltaFinalWealthVsProduction=r.finalWealth-base.finalWealth;r.deltaMaxDrawdownVsProduction=r.maxDrawdown-base.maxDrawdown}
 const out={generatedAt:new Date().toISOString(),strategyId:PRODUCTION_STRATEGY.strategyId,period:{start:dates[0],end:dates.at(-1),sessions:dates.length},method:"actual chronological PIT signals; one-rule-off counterfactuals through the same transitionDay engine; deltas are non-additive",results};await mkdir(resolve("data/research/alpha-loss"),{recursive:true});await writeFile(resolve("data/research/alpha-loss/decomposition.json"),JSON.stringify(out,null,2));console.log("RESULT_JSON="+JSON.stringify(out))}
main().catch(e=>{console.error(e);process.exit(1)});