import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { performanceStats } from "../src/lib/backtest";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay, type EngineState } from "../src/lib/strategy/state-machine";
import type { EquityPoint, PricePoint, UniverseMonth } from "../src/lib/types";

type MarketDataFile = { histories?: Record<string, PricePoint[]> };
type UniverseFile = { history: UniverseMonth[] };

const END = "2026-08-25";

function runWithExtraExecutionSessions(args: {
  histories: Record<string, PricePoint[]>;
  universeHistory: UniverseMonth[];
  extraSessions: number;
}) {
  const config = PRODUCTION_STRATEGY;
  const qqq = [...(args.histories.QQQ ?? [])].filter((p) => p.date <= END).sort((a, b) => a.date.localeCompare(b.date));
  const tradingDates = qqq.map((p) => p.date);
  const dateIndex = new Map(tradingDates.map((date, index) => [date, index]));
  const priceMaps = Object.fromEntries(
    Object.entries(args.histories).map(([symbol, points]) => [
      symbol,
      new Map(points.filter((p) => p.date <= END).map((p) => [p.date, p])),
    ]),
  );
  const universeBySignalDate = new Map(args.universeHistory.map((month) => [month.asOf, month]));
  let state: EngineState = initialEngineState(config);
  const curve: EquityPoint[] = [];

  for (let index = 0; index < tradingDates.length; index++) {
    const date = tradingDates[index];
    if (date < config.backtestStart) continue;
    const executionDate = tradingDates[index + 1 + args.extraSessions] ?? null;
    const universe = universeBySignalDate.get(date);
    const signal = universe
      ? buildMonthlySignal({ universe, histories: args.histories, qqq, nextSessionDate: executionDate, config })
      : null;
    const symbols = new Set([
      "QQQ",
      ...state.currentPositions.map((position) => position.symbol),
      ...(state.pendingSignal?.selectedSymbols ?? []),
      ...state.nextAction.symbols,
      ...(signal?.selectedSymbols ?? []),
    ]);
    const prices = Object.fromEntries([...symbols].map((symbol) => [symbol, priceMaps[symbol]?.get(date)]));
    state = transitionDay(
      state,
      {
        date,
        prices,
        qqqHistoryThroughClose: qqq.slice(0, (dateIndex.get(date) ?? index) + 1),
        monthlySignal: signal,
        nextSessionDate: executionDate,
      },
      config,
    );
    curve.push({ date, equity: state.currentEquity, drawdown: state.drawdown });
  }

  const stats = performanceStats(curve);
  const eventCounts = Object.fromEntries(
    [...new Set(state.events.map((event) => event.type))].sort().map((type) => [type, state.events.filter((event) => event.type === type).length]),
  );
  return { stats, eventCounts, finalState: { state: state.state, asOf: state.asOf, lastTrigger: state.lastTrigger } };
}

async function main() {
  const market = JSON.parse(await readFile(resolve("public/data/market-data.json"), "utf8")) as MarketDataFile;
  const universe = JSON.parse(await readFile(resolve("data/universe-history.json"), "utf8")) as UniverseFile;
  const histories = market.histories ?? {};
  const universeHistory = universe.history.filter((month) => month.asOf >= PRODUCTION_STRATEGY.backtestStart && month.asOf <= END);

  const baseline = runWithExtraExecutionSessions({ histories, universeHistory, extraSessions: 0 });
  const plus1 = runWithExtraExecutionSessions({ histories, universeHistory, extraSessions: 1 });
  const plus2 = runWithExtraExecutionSessions({ histories, universeHistory, extraSessions: 2 });

  const output = {
    generatedAt: new Date().toISOString(),
    period: { start: PRODUCTION_STRATEGY.backtestStart, end: END },
    strategyId: PRODUCTION_STRATEGY.strategyId,
    method: "Full state-machine causal execution-delay stress. Every order generated by monthly signals, stops, portfolio circuit, and recovery is scheduled extra US trading sessions later. Positions remain live until the delayed open, and all subsequent daily equity, stops, circuit, recovery, and future signals are recomputed from the resulting state. Production logic and costs are otherwise unchanged.",
    caveat: "This models deterministic whole-session operational delay, not intraday slippage/VWAP. It intentionally delays all next-open actions, including risk exits and recovery entries.",
    baseline,
    plus1Session: plus1,
    plus2Sessions: plus2,
    differences: {
      plus1Cagr: plus1.stats.cagr - baseline.stats.cagr,
      plus1MaxDrawdown: plus1.stats.maxDrawdown - baseline.stats.maxDrawdown,
      plus1Calmar: (plus1.stats.calmar ?? 0) - (baseline.stats.calmar ?? 0),
      plus2Cagr: plus2.stats.cagr - baseline.stats.cagr,
      plus2MaxDrawdown: plus2.stats.maxDrawdown - baseline.stats.maxDrawdown,
      plus2Calmar: (plus2.stats.calmar ?? 0) - (baseline.stats.calmar ?? 0),
    },
  };

  const out = resolve("data/research/full-state-execution-delay.json");
  await mkdir(dirname(out), { recursive: true });
  await writeFile(out, JSON.stringify(output, null, 2) + "\n");
  console.log(JSON.stringify(output, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
