import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import {fetchYahooHistory} from "../src/lib/yahoo";
import type {EquityPoint,PricePoint,UniverseMonth} from "../src/lib/types";

type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};
const START="2020-01-01",END="2026-08-25";
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/(x.length||1);const median=(x:number[])=>{const a=[...x].sort((p,q)=>p-q),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function runG(h:Record<string,PricePoint[]>,us:UniverseMonth[]){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date).filter(d=>d>=START&&d<=END),rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))])),idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))])),maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di],nd=dates[di+1]??null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>{const r=(maps[x.s] as Map<string,PricePoint>).get(d);return z+x.sh*(r?.open??r?.close??x.e)},0)*.999;pos=[];pout=null;hold=0;peak=cash}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===5&&os.every(x=>x&&x>0)){const per=cash/5;pos=pin.ss.map((s,i)=>({s,sh:per*.999/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*.88);if(stop||dd<=-.15||hold>=20)pout=nd}if(!pos.length&&!pin&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<99||i<20)continue;const close=r[i].close;if(close<=mean(r.slice(i-99,i+1).map(x=>x.close)))continue;const hi=Math.max(...r.slice(i-20,i).map(x=>x.close));if(close>hi)ca.push({s,v:close/hi-1})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=5)pin={d:nd,ss:ca.slice(0,5).map(x=>x.s)}}}return curve}
function rm(c:EquityPoint[]){const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m}
function asset(a:PricePoint[]){const r=[...a].sort((x,y)=>x.date.localeCompare(y.date)).filter(x=>x.date>=START&&x.date<=END);let e=1,p=1;const o:EquityPoint[]=[{date:r[0].date,equity:1,drawdown:0}];for(let i=1;i<r.length;i++){e*=r[i].close/r[i-1].close;p=Math.max(p,e);o.push({date:r[i].date,equity:e,drawdown:e/p-1})}return o}
function core(f:EquityPoint[],g:EquityPoint[]){const fm=rm(f),gm=rm(g),dates=f.slice(1).map(x=>x.date).filter(d=>gm.has(d));let e=1,p=1;const o:EquityPoint[]=[{date:f[0].date,equity:1,drawdown:0}];for(const d of dates){e*=1+.85*(fm.get(d)??0)+.15*(gm.get(d)??0);p=Math.max(p,e);o.push({date:d,equity:e,drawdown:e/p-1})}return o}
async function fredOas(){const r=await fetch("https://fred.stlouisfed.org/graph/fredgraph.csv?id=BAMLH0A0HYM2");if(!r.ok)throw new Error(`FRED ${r.status}`);const t=await r.text(),a:Array<{date:string;v:number}>=[];for(const line of t.trim().split(/\r?\n/).slice(1)){const [date,raw]=line.split(","),v=Number(raw);if(/^\d{4}-\d{2}-\d{2}$/.test(date)&&Number.isFinite(v))a.push({date,v})}if(a.length<1000)throw new Error(`Insufficient FRED OAS rows ${a.length}`);return a}
function oasOn(a:Array<{date:string;v:number}>,d:string){let lo=0,hi=a.length-1,ans=-1;while(lo<=hi){const m=(lo+hi)>>1;if(a[m].date<=d){ans=m;lo=m+1}else hi=m-1}return ans}
function apply(f:EquityPoint[],g:EquityPoint[],bt:EquityPoint[],qqq:PricePoint[],oas:Array<{date:string;v:number}>,kind:"AR"|"AS"|"AT",cost=.001,lag=0){const fm=rm(f),gm=rm(g),bm=rm(bt),sh=core(f,g),sm=new Map(sh.map((x,i)=>[x.date,i])),q=[...qqq].sort((a,b)=>a.date.localeCompare(b.date)).filter(x=>x.date>=START&&x.date<=END),qm=new Map(q.map((x,i)=>[x.date,i])),dates=f.slice(1).map(x=>x.date).filter(d=>gm.has(d)&&bm.has(d)&&sm.has(d));let e=1,p=1,state=false,confirm=0;const out:EquityPoint[]=[{date:f[0].date,equity:1,drawdown:0}];for(const d of dates){const ci=sm.get(d) as number,si=Math.max(0,ci-1-lag),sd=sh[si].date;let slow=false,slowClear=true;if(si>=20){const qi=qm.get(sd);if(qi!=null&&qi>=20){const cr=sh[si].equity/sh[si-20].equity-1,qr=q[qi].close/q[qi-20].close-1,gap=cr-qr;slow=cr<0&&gap<=-.10;slowClear=gap>-.03}}const oi=oasOn(oas,sd),level=oi>=0?oas[oi].v:NaN,delta=oi>=20?level-oas[oi-20].v:NaN;const macro=kind==="AR"?level>=5:kind==="AS"?delta>=1:(level>=5||delta>=1),macroClear=kind==="AR"?level<5:kind==="AS"?delta<1:(level<5&&delta<1);const enter=slow||macro;if(!state&&enter){state=true;confirm=0}else if(state){if(slowClear&&macroClear)confirm++;else confirm=0;if(confirm>=5){state=false;confirm=0}}const wf=state?.30:.85,wg=.15,wb=state?.35:0;let rr=wf*(fm.get(d)??0)+wg*(gm.get(d)??0)+wb*(bm.get(d)??0);const prev=out.length>1?(out[out.length-1] as any)._state as boolean|undefined:undefined;if(prev!==undefined&&prev!==state)rr-=.55*cost;e*=1+rr;p=Math.max(p,e);const pt:any={date:d,equity:e,drawdown:e/p-1};pt._state=state;out.push(pt)}return out.map(({date,equity,drawdown})=>({date,equity,drawdown}))}
function rolling36(c:EquityPoint[]){const a:number[]=[];for(let i=0;i<c.length;i++){const ed=new Date(c[i].date+"T00:00:00Z"),t=new Date(ed);t.setUTCFullYear(t.getUTCFullYear()-3);let j=i;while(j>0&&new Date(c[j].date+"T00:00:00Z")>t)j--;const y=(ed.getTime()-new Date(c[j].date+"T00:00:00Z").getTime())/86400000/365.25;if(y>=2.9)a.push((c[i].equity/c[j].equity)**(1/y)-1)}return a}
function trim(c:EquityPoint[],s:string){const z=c.filter(x=>x.date>=s),b=z[0].equity;let p=1;return z.map(x=>{const e=x.equity/b;p=Math.max(p,e);return{date:x.date,equity:e,drawdown:e/p-1}})}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));if(!m.histories.BTAL||m.histories.BTAL.length<200)m.histories.BTAL=await fetchYahooHistory("BTAL");const oas=await fredOas(),f=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(x=>x.date>=START&&x.date<=END),g=runG(m.histories,us),bt=asset(m.histories.BTAL),res:any={};for(const k of ["AR","AS","AT"] as const){const mk=(c=.001,l=0)=>apply(f,g,bt,m.histories.QQQ,oas,k,c,l),base=mk(),stress=[mk(.003),mk(.001,1),mk(.001,2),trim(mk(),"2021-01-01")],sc=stress.map(x=>performanceStats(x).cagr),rw=rolling36(base),st=performanceStats(base),proxy=Math.min(median(sc),median(rw));res[k]={stats:st,stressMedianCAGR:median(sc),rolling36MedianCAGR:median(rw),rolling36Worst:Math.min(...rw),planningProxy:proxy,pass:proxy>=.40&&st.maxDrawdown>=-.17}}console.log(JSON.stringify({architecture:"Frozen M3 core plus one-session-lagged FRED HY OAS guard",normal:{fixed:.85,g:.15},defensive:{fixed:.30,g:.15,btal:.35,cash:.20},rules:{AR:"OAS>=5%",AS:"20-observation OAS increase>=1pp",AT:"AR OR AS",exit:"M3 and macro clear for 5 sessions"},objective:{planningCAGR:.40,maxDrawdown:-.17},results:res},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});