import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import {fetchYahooHistory} from "../src/lib/yahoo";
import type {EquityPoint,PricePoint,UniverseMonth} from "../src/lib/types";
type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};type Flow={date:string;ratio:number};type State="NORMAL"|"YELLOW"|"DEEP";const START="2020-01-01",END="2026-08-25";
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/(x.length||1);const median=(x:number[])=>{const a=[...x].sort((p,q)=>p-q),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function runG(h:Record<string,PricePoint[]>,us:UniverseMonth[]){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date).filter(d=>d>=START&&d<=END),rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))])),idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))])),maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di],nd=dates[di+1]??null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>{const r=(maps[x.s] as Map<string,PricePoint>).get(d);return z+x.sh*(r?.open??r?.close??x.e)},0)*.999;pos=[];pout=null;hold=0;peak=cash}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===5&&os.every(x=>x&&x>0)){const per=cash/5;pos=pin.ss.map((s,i)=>({s,sh:per*.999/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*.88);if(stop||dd<=-.15||hold>=20)pout=nd}if(!pos.length&&!pin&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<99||i<20)continue;const close=r[i].close;if(close<=mean(r.slice(i-99,i+1).map(x=>x.close)))continue;const hi=Math.max(...r.slice(i-20,i).map(x=>x.close));if(close>hi)ca.push({s,v:close/hi-1})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=5)pin={d:nd,ss:ca.slice(0,5).map(x=>x.s)}}}return curve}
function rm(c:EquityPoint[]){const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m}
function asset(a:PricePoint[]){const r=[...a].sort((x,y)=>x.date.localeCompare(y.date)).filter(x=>x.date>=START&&x.date<=END);let e=1,p=1;const o:EquityPoint[]=[{date:r[0].date,equity:1,drawdown:0}];for(let i=1;i<r.length;i++){e*=r[i].close/r[i-1].close;p=Math.max(p,e);o.push({date:r[i].date,equity:e,drawdown:e/p-1})}return o}
function core(f:EquityPoint[],g:EquityPoint[]){const fm=rm(f),gm=rm(g),dates=f.slice(1).map(x=>x.date).filter(d=>gm.has(d));let e=1,p=1;const o:EquityPoint[]=[{date:f[0].date,equity:1,drawdown:0}];for(const d of dates){e*=1+.85*(fm.get(d)??0)+.15*(gm.get(d)??0);p=Math.max(p,e);o.push({date:d,equity:e,drawdown:e/p-1})}return o}
const N={f:.7225,g:.1275,b:0,d:.15,c:0},D={f:.1275,g:.1275,b:.14875,d:.29875,c:.2975},Y={f:.425,g:.1275,b:.074375,d:.224375,c:.14875};function targets(s:State){return s==="DEEP"?D:s==="YELLOW"?Y:N}
async function fetchOne(date:string){const url=`https://www.cboe.com/markets/us/options/market-statistics/daily?dt=${date}`;for(let k=0;k<3;k++){try{const r=await fetch(url,{headers:{"user-agent":"Mozilla/5.0 momentum-research/1.0"}});if(!r.ok)continue;const t=await r.text(),m=t.match(/TOTAL PUT\/CALL RATIO[\s\S]{0,500}?([0-9]+\.[0-9]+)/i);if(m)return {date,ratio:Number(m[1])}}catch{}await new Promise(z=>setTimeout(z,250*(k+1)))}return null}
async function flows(dates:string[]){const out:Flow[]=[];let i=0;const workers=Array.from({length:16},async()=>{while(i<dates.length){const n=i++,r=await fetchOne(dates[n]);if(r&&Number.isFinite(r.ratio))out.push(r);if(n%100===0)console.log(`PUTCALL_PROGRESS ${n}/${dates.length}`)}});await Promise.all(workers);return out.sort((a,b)=>a.date.localeCompare(b.date))}
function flowStress(rows:Flow[],date:string){const ds=rows.filter(x=>x.date<date);if(ds.length<20)return false;const x=ds.slice(-20).map(r=>r.ratio);return mean(x.slice(-5))>mean(x)}
function apply(f:EquityPoint[],g:EquityPoint[],bt:EquityPoint[],db:EquityPoint[],qqq:PricePoint[],flow:Flow[],cost=.001,lag=0){const fm=rm(f),gm=rm(g),bm=rm(bt),dm=rm(db),sh=core(f,g),sm=new Map(sh.map((x,i)=>[x.date,i])),q=[...qqq].sort((a,b)=>a.date.localeCompare(b.date)).filter(x=>x.date>=START&&x.date<=END),qm=new Map(q.map((x,i)=>[x.date,i])),dates=f.slice(1).map(x=>x.date).filter(d=>gm.has(d)&&bm.has(d)&&dm.has(d)&&sm.has(d));let m3=false,confirm=0,peak=1,lastMonth="",state:State="NORMAL";let bal={...N};const out:EquityPoint[]=[{date:f[0].date,equity:1,drawdown:0}];for(const d of dates){const ci=sm.get(d) as number,si=Math.max(0,ci-1-lag);let enter=false,exit=false;if(si>=20){const qi=qm.get(sh[si].date);if(qi!=null&&qi>=20){const cr=sh[si].equity/sh[si-20].equity-1,qr=q[qi].close/q[qi-20].close-1,gap=cr-qr;enter=cr<0&&gap<=-.10;if(m3){if(gap>-.03)confirm++;else confirm=0;exit=confirm>=5}}}if(!m3&&enter){m3=true;confirm=0}else if(m3&&exit){m3=false;confirm=0}const fs=flowStress(flow,sh[si]?.date??d),desired:State=m3?"DEEP":fs?"YELLOW":"NORMAL";bal.f*=1+(fm.get(d)??0);bal.g*=1+(gm.get(d)??0);bal.b*=1+(bm.get(d)??0);bal.d*=1+(dm.get(d)??0);const month=d.slice(0,7),rebalance=month!==lastMonth||desired!==state;if(rebalance){let total=bal.f+bal.g+bal.b+bal.d+bal.c;const t=targets(desired),cur={f:bal.f/total,g:bal.g/total,b:bal.b/total,d:bal.d/total,c:bal.c/total},turn=(Math.abs(cur.f-t.f)+Math.abs(cur.g-t.g)+Math.abs(cur.b-t.b)+Math.abs(cur.d-t.d)+Math.abs(cur.c-t.c))/2;total*=1-cost*turn;bal={f:total*t.f,g:total*t.g,b:total*t.b,d:total*t.d,c:total*t.c};lastMonth=month;state=desired}const e=bal.f+bal.g+bal.b+bal.d+bal.c;peak=Math.max(peak,e);out.push({date:d,equity:e,drawdown:e/peak-1})}return out}
function rolling36(c:EquityPoint[]){const a:number[]=[];for(let i=0;i<c.length;i++){const ed=new Date(c[i].date+"T00:00:00Z"),t=new Date(ed);t.setUTCFullYear(t.getUTCFullYear()-3);let j=i;while(j>0&&new Date(c[j].date+"T00:00:00Z")>t)j--;const y=(ed.getTime()-new Date(c[j].date+"T00:00:00Z").getTime())/86400000/365.25;if(y>=2.9)a.push((c[i].equity/c[j].equity)**(1/y)-1)}return a}
function trim(c:EquityPoint[],s:string){const z=c.filter(x=>x.date>=s),b=z[0].equity;let p=1;return z.map(x=>{const e=x.equity/b;p=Math.max(p,e);return{date:x.date,equity:e,drawdown:e/p-1}})}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));for(const s of ["BTAL","DBMF"]){if(!m.histories[s]||m.histories[s].length<200)m.histories[s]=await fetchYahooHistory(s)}const qdates=[...(m.histories.QQQ??[])].filter(x=>x.date>=START&&x.date<=END).map(x=>x.date),flow=await flows(qdates);console.log(`PUTCALL_ROWS ${flow.length}/${qdates.length}`);if(flow.length<qdates.length*.9)throw new Error("Insufficient put/call coverage");const f=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(x=>x.date>=START&&x.date<=END),g=runG(m.histories,us),bt=asset(m.histories.BTAL),db=asset(m.histories.DBMF),mk=(c=.001,l=0)=>apply(f,g,bt,db,m.histories.QQQ,flow,c,l),base=mk(),stress=[mk(.003),mk(.001,1),mk(.001,2),trim(mk(),"2021-01-01")],sc=stress.map(x=>performanceStats(x).cagr),rw=rolling36(base),st=performanceStats(base),proxy=Math.min(median(sc),median(rw));console.log(JSON.stringify({architecture:"Frozen Stage11 + Cboe Total Put/Call Yellow state + frozen M3 Deep state",rule:"1-session lag; 5-observation mean total P/C > 20-observation mean -> Yellow; M3 -> Deep",objective:{planningCAGR:.40,maxDrawdown:-.17},coverage:{rows:flow.length,dates:qdates.length},result:{stats:st,stressMedianCAGR:median(sc),rolling36MedianCAGR:median(rw),rolling36Worst:Math.min(...rw),planningProxy:proxy,pass:proxy>=.40&&st.maxDrawdown>=-.17}},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});