import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import {fetchYahooHistory} from "../src/lib/yahoo";
import type {EquityPoint,PricePoint,UniverseMonth} from "../src/lib/types";
type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};
const START="2020-01-01",END="2026-08-25";const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/(x.length||1);
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function runG(h:Record<string,PricePoint[]>,us:UniverseMonth[]){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date).filter(d=>d>=START&&d<=END),rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))])),idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))])),maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di],nd=dates[di+1]??null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>{const r=(maps[x.s] as Map<string,PricePoint>).get(d);return z+x.sh*(r?.open??r?.close??x.e)},0)*.999;pos=[];pout=null;hold=0;peak=cash}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===5&&os.every(x=>x&&x>0)){const per=cash/5;pos=pin.ss.map((s,i)=>({s,sh:per*.999/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*.88);if(stop||dd<=-.15||hold>=20)pout=nd}if(!pos.length&&!pin&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<99||i<20)continue;const close=r[i].close;if(close<=mean(r.slice(i-99,i+1).map(x=>x.close)))continue;const hi=Math.max(...r.slice(i-20,i).map(x=>x.close));if(close>hi)ca.push({s,v:close/hi-1})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=5)pin={d:nd,ss:ca.slice(0,5).map(x=>x.s)}}}return curve}
function retMap(c:EquityPoint[]){const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m}
function assetCurve(a:PricePoint[]){const r=[...a].sort((x,y)=>x.date.localeCompare(y.date)).filter(x=>x.date>=START&&x.date<=END);let e=1,p=1;const o:EquityPoint[]=[{date:r[0].date,equity:1,drawdown:0}];for(let i=1;i<r.length;i++){e*=r[i].close/r[i-1].close;p=Math.max(p,e);o.push({date:r[i].date,equity:e,drawdown:e/p-1})}return o}
function dynamic(f:EquityPoint[],g:EquityPoint[],bt:EquityPoint[],qqq:PricePoint[],shift=.20){const fm=retMap(f),gm=retMap(g),bm=retMap(bt),q=[...qqq].sort((a,b)=>a.date.localeCompare(b.date)).filter(x=>x.date>=START&&x.date<=END),qi=new Map(q.map((x,i)=>[x.date,i])),dates=f.slice(1).map(x=>x.date).filter(d=>gm.has(d)&&bm.has(d)&&qi.has(d));let e=1,p=1;const out:EquityPoint[]=[{date:f[0].date,equity:1,drawdown:0}];for(const d of dates){const idx=qi.get(d) as number,si=Math.max(0,idx-1);let risk=false;if(si>=99&&si>=20){const ma=mean(q.slice(si-99,si+1).map(x=>x.close)),r20=q[si].close/q[si-20].close-1;risk=q[si].close<ma&&r20<0}const wf=risk?.85-shift:.85,wg=.15,wb=risk?shift:0;const r=wf*(fm.get(d)??0)+wg*(gm.get(d)??0)+wb*(bm.get(d)??0);e*=1+r;p=Math.max(p,e);out.push({date:d,equity:e,drawdown:e/p-1})}return out}
function maxDdWindow(c:EquityPoint[]){let peakI=0,troughI=0,peak= c[0].equity,worst=0,lastPeakI=0;for(let i=0;i<c.length;i++){if(c[i].equity>=peak){peak=c[i].equity;lastPeakI=i}const dd=c[i].equity/peak-1;if(dd<worst){worst=dd;peakI=lastPeakI;troughI=i}}let rec:I|null=null;type I=number;for(let i=troughI+1;i<c.length;i++){if(c[i].equity>=c[peakI].equity){rec=i;break}}return{peakIndex:peakI,troughIndex:troughI,recoveryIndex:rec,peakDate:c[peakI].date,troughDate:c[troughI].date,recoveryDate:rec==null?null:c[rec].date,maxDrawdown:worst}}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));if(!m.histories.BTAL||m.histories.BTAL.length<200)m.histories.BTAL=await fetchYahooHistory("BTAL");const fixed=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(x=>x.date>=START&&x.date<=END),g=runG(m.histories,us),bt=assetCurve(m.histories.BTAL),qqq=[...(m.histories.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)).filter(x=>x.date>=START&&x.date<=END),h20=dynamic(fixed,g,bt,qqq,.20),win=maxDdWindow(h20),qi=new Map(qqq.map((x,i)=>[x.date,i]));const sample:any[]=[];for(let i=Math.max(0,win.peakIndex-10);i<=Math.min(h20.length-1,win.troughIndex+10);i++){const d=h20[i].date,k=qi.get(d);if(k==null)continue;const ma50=k>=49?mean(qqq.slice(k-49,k+1).map(x=>x.close)):NaN,ma100=k>=99?mean(qqq.slice(k-99,k+1).map(x=>x.close)):NaN,ma200=k>=199?mean(qqq.slice(k-199,k+1).map(x=>x.close)):NaN,r5=k>=5?qqq[k].close/qqq[k-5].close-1:NaN,r10=k>=10?qqq[k].close/qqq[k-10].close-1:NaN,r20=k>=20?qqq[k].close/qqq[k-20].close-1:NaN;const riskOff=k>=99&&k>=20&&qqq[k].close<ma100&&r20<0;sample.push({date:d,h20DD:h20[i].drawdown,qqqClose:qqq[k].close,below50:qqq[k].close<ma50,below100:qqq[k].close<ma100,below200:qqq[k].close<ma200,r5,r10,r20,riskOff})}console.log(JSON.stringify({window:win,sample},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});