import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {gunzipSync} from "node:zlib";
import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import {latestPublicFilings} from "../src/lib/universe/sec-nport";
import type {EquityPoint,NportFiling,PricePoint,UniverseMonth} from "../src/lib/types";

type MF={histories:Record<string,PricePoint[]>}; type UF={history:UniverseMonth[]};
const START="2020-01-01", END="2026-08-25", TOP=5;
const med=(x:number[])=>{const a=[...x].sort((p,q)=>p-q),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const prior90=(d:string)=>{const x=new Date(d+"T00:00:00Z");x.setUTCDate(x.getUTCDate()-90);return x.toISOString().slice(0,10)};
function rm(c:EquityPoint[]){const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m}
function monthly(c:EquityPoint[]){const out=new Map<string,number>();let pm="",pe=1;for(const x of c){const m=x.date.slice(0,7);if(pm&&m!==pm){const prev=[...c].reverse().find(y=>y.date.slice(0,7)===pm)!;out.set(pm,prev.equity/pe-1);pe=prev.equity}if(!pm)pe=x.equity;pm=m}if(pm){const last=c[c.length-1];out.set(pm,last.equity/pe-1)}return out}
function corr(a:EquityPoint[],b:EquityPoint[]){const x=monthly(a),y=monthly(b),ks=[...x.keys()].filter(k=>y.has(k));const A=ks.map(k=>x.get(k)!),B=ks.map(k=>y.get(k)!);const ma=A.reduce((s,v)=>s+v,0)/A.length,mb=B.reduce((s,v)=>s+v,0)/B.length;let n=0,da=0,db=0;for(let i=0;i<A.length;i++){const p=A[i]-ma,q=B[i]-mb;n+=p*q;da+=p*p;db+=q*q}return n/Math.sqrt(da*db)}
function rolling36(c:EquityPoint[]){const a:number[]=[];for(let i=0;i<c.length;i++){const ed=new Date(c[i].date+"T00:00:00Z"),t=new Date(ed);t.setUTCFullYear(t.getUTCFullYear()-3);let j=i;while(j>0&&new Date(c[j].date+"T00:00:00Z")>t)j--;const y=(ed.getTime()-new Date(c[j].date+"T00:00:00Z").getTime())/86400000/365.25;if(y>=2.9)a.push((c[i].equity/c[j].equity)**(1/y)-1)}return a}
function trim(c:EquityPoint[],s:string){const z=c.filter(x=>x.date>=s);if(!z.length)return z;const b=z[0].equity;let p=1;return z.map(x=>{const e=x.equity/b;p=Math.max(p,e);return{date:x.date,equity:e,drawdown:e/p-1}})}
function monthEnds(q:PricePoint[]){const a=q.filter(x=>x.date>=START&&x.date<=END),o:string[]=[];for(let i=0;i<a.length;i++)if(i===a.length-1||a[i+1].date.slice(0,7)!==a[i].date.slice(0,7))o.push(a[i].date);return o}
type Snap=Map<string,{owners:Set<string>;weight:number}>;
function snap(f:NportFiling[],d:string):Snap{const s:Snap=new Map();for(const x of latestPublicFilings(f,d))for(const h of x.holdings){let z=s.get(h.symbol);if(!z){z={owners:new Set(),weight:0};s.set(h.symbol,z)}z.owners.add(x.seriesId);z.weight+=h.weight}return s}
function score(cur:Snap,prev:Snap,mode:"breadth"|"weight"|"sponsor",symbol:string){const c=cur.get(symbol),p=prev.get(symbol);if(mode==="breadth")return (c?.owners.size??0)-(p?.owners.size??0);if(mode==="weight")return (c?.weight??0)-(p?.weight??0);let add=0,lost=0;for(const x of c?.owners??[])if(!p?.owners.has(x))add++;for(const x of p?.owners??[])if(!c?.owners.has(x))lost++;return add-lost}
function run(h:Record<string,PricePoint[]>,filings:NportFiling[],mode:"breadth"|"weight"|"sponsor",cost=.001,lag=0){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.filter(x=>x.date>=START&&x.date<=END).map(x=>x.date),di=new Map(dates.map((d,i)=>[d,i])),ends=new Set(monthEnds(q)),maps=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,new Map(a.map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;last:number}>=[],pending:Map<string,string[]>=new Map(),peak=1;const out:EquityPoint[]=[];for(const d of dates){const sel=pending.get(d);if(sel){if(pos.length){cash=pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.open??x.last),0)*(1-cost);pos=[]}if(sel.length){const valid=sel.map(s=>({s,p:(maps[s] as Map<string,PricePoint>).get(d)?.open})).filter(x=>x.p&&x.p>0) as {s:string;p:number}[];if(valid.length){const per=cash/valid.length;pos=valid.map(x=>({s:x.s,sh:per*(1-cost)/x.p,last:x.p}));cash=0}}pending.delete(d)}let e=cash;for(const x of pos){const p=(maps[x.s] as Map<string,PricePoint>).get(d)?.close??x.last;x.last=p;e+=x.sh*p}peak=Math.max(peak,e);out.push({date:d,equity:e,drawdown:e/peak-1});if(!ends.has(d))continue;const i=di.get(d)!+1+lag;if(i>=dates.length)continue;const cur=snap(filings,d),prev=snap(filings,prior90(d)),ca:Array<{s:string;v:number}>=[];for(const s of cur.keys()){const v=score(cur,prev,mode,s);if(v<=0)continue;const arr=h[s];if(!arr||arr.filter(x=>x.date<=d).length<100)continue;const ex=maps[s] as Map<string,PricePoint>;if(!ex.get(dates[i])?.open)continue;ca.push({s,v})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));pending.set(dates[i],ca.slice(0,TOP).map(x=>x.s))}return out}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,b=JSON.parse(gunzipSync(await readFile(resolve("data/sec-nport/bootstrap.json.gz"))).toString("utf8"))as{snapshots:NportFiling[]};const f=runStrategySimulation({histories:m.histories,universeHistory:u.history,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(x=>x.date>=START&&x.date<=END),defs={AL:"breadth",AM:"weight",AN:"sponsor"}as const,res:any={};for(const[k,mode]of Object.entries(defs)){const mk=(c=.001,l=0)=>run(m.histories,b.snapshots,mode,c,l),base=mk(),stress=[mk(.003),mk(.001,1),mk(.001,2),trim(mk(),"2021-01-01")],sc=stress.map(x=>performanceStats(x).cagr),rw=rolling36(base),st=performanceStats(base),proxy=Math.min(med(sc),med(rw)),co=corr(base,f);res[k]={mode,stats:st,stressMedianCAGR:med(sc),rolling36MedianCAGR:med(rw),rolling36Worst:Math.min(...rw),planningProxy:proxy,fixed60MonthlyCorrelation:co,pass:proxy>=.25&&st.maxDrawdown>=-.40&&Math.abs(co)<=.35}}console.log(JSON.stringify({architecture:"Monthly PIT N-PORT flow acceleration; Top5 equal weight; next-open; no price ranking",objective:{planningCAGR:.25,maxDrawdown:-.40,absFixed60Correlation:.35},results:res},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});
