import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import {fetchYahooHistory} from "../src/lib/yahoo";
import type {EquityPoint,PricePoint,UniverseMonth} from "../src/lib/types";
type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};type Cot={date:string;net:number};type State="NORMAL"|"YELLOW"|"DEEP";const START="2020-01-01",END="2026-08-25";
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/(x.length||1);const median=(x:number[])=>{const a=[...x].sort((p,q)=>p-q),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function runG(h:Record<string,PricePoint[]>,us:UniverseMonth[]){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date).filter(d=>d>=START&&d<=END),rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))])),idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))])),maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di],nd=dates[di+1]??null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>{const r=(maps[x.s] as Map<string,PricePoint>).get(d);return z+x.sh*(r?.open??r?.close??x.e)},0)*.999;pos=[];pout=null;hold=0;peak=cash}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===5&&os.every(x=>x&&x>0)){const per=cash/5;pos=pin.ss.map((s,i)=>({s,sh:per*.999/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*.88);if(stop||dd<=-.15||hold>=20)pout=nd}if(!pos.length&&!pin&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<99||i<20)continue;const close=r[i].close;if(close<=mean(r.slice(i-99,i+1).map(x=>x.close)))continue;const hi=Math.max(...r.slice(i-20,i).map(x=>x.close));if(close>hi)ca.push({s,v:close/hi-1})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=5)pin={d:nd,ss:ca.slice(0,5).map(x=>x.s)}}}return curve}
function rm(c:EquityPoint[]){const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m}
function asset(a:PricePoint[]){const r=[...a].sort((x,y)=>x.date.localeCompare(y.date)).filter(x=>x.date>=START&&x.date<=END);let e=1,p=1;const o:EquityPoint[]=[{date:r[0].date,equity:1,drawdown:0}];for(let i=1;i<r.length;i++){e*=r[i].close/r[i-1].close;p=Math.max(p,e);o.push({date:r[i].date,equity:e,drawdown:e/p-1})}return o}
function core(f:EquityPoint[],g:EquityPoint[]){const fm=rm(f),gm=rm(g),dates=f.slice(1).map(x=>x.date).filter(d=>gm.has(d));let e=1,p=1;const o:EquityPoint[]=[{date:f[0].date,equity:1,drawdown:0}];for(const d of dates){e*=1+.85*(fm.get(d)??0)+.15*(gm.get(d)??0);p=Math.max(p,e);o.push({date:d,equity:e,drawdown:e/p-1})}return o}
const N={f:.7225,g:.1275,gold:.075,bond:.075,sh:0,c:0};const Y={f:.425,g:.1275,gold:.1121875,bond:.1121875,sh:.074375,c:.14875};const D={f:.1275,g:.1275,gold:.149375,bond:.149375,sh:.14875,c:.2975};function targets(s:State){return s==="DEEP"?D:s==="YELLOW"?Y:N}
async function cot(){const url="https://publicreporting.cftc.gov/resource/gpe5-46if.json?$limit=5000&$where=cftc_contract_market_code='209742'&$order=report_date_as_yyyy_mm_dd";const r=await fetch(url,{headers:{"user-agent":"momentum-research/1.0"}});if(!r.ok)throw new Error(`CFTC ${r.status}`);const j:any[]=await r.json();const out:Cot[]=[];for(const x of j){const date=String(x.report_date_as_yyyy_mm_dd??"").slice(0,10),l=Number(x.asset_mgr_positions_long),s=Number(x.asset_mgr_positions_short);if(date&&Number.isFinite(l)&&Number.isFinite(s))out.push({date,net:l-s})}return out.sort((a,b)=>a.date.localeCompare(b.date))}
function cotStress(rows:Cot[],date:string){const cut=new Date(date+"T00:00:00Z");cut.setUTCDate(cut.getUTCDate()-7);const ds=rows.filter(x=>x.date<=cut.toISOString().slice(0,10));if(ds.length<5)return false;return ds[ds.length-1].net<ds[ds.length-5].net}
function apply(f:EquityPoint[],g:EquityPoint[],gold:EquityPoint[],bond:EquityPoint[],sh:EquityPoint[],qqq:PricePoint[],cotRows:Cot[],cost=.001,lag=0){const fm=rm(f),gm=rm(g),am=rm(gold),bm=rm(bond),smkt=rm(sh),shadow=core(f,g),sim=new Map(shadow.map((x,i)=>[x.date,i])),q=[...qqq].sort((a,b)=>a.date.localeCompare(b.date)).filter(x=>x.date>=START&&x.date<=END),qm=new Map(q.map((x,i)=>[x.date,i])),dates=f.slice(1).map(x=>x.date).filter(d=>gm.has(d)&&am.has(d)&&bm.has(d)&&smkt.has(d)&&sim.has(d));let m3=false,confirm=0,peak=1,lastMonth="",state:State="NORMAL";let bal={...N};const out:EquityPoint[]=[{date:f[0].date,equity:1,drawdown:0}];for(const d of dates){const ci=sim.get(d) as number,si=Math.max(0,ci-1-lag);let enter=false,exit=false;if(si>=20){const qi=qm.get(shadow[si].date);if(qi!=null&&qi>=20){const cr=shadow[si].equity/shadow[si-20].equity-1,qr=q[qi].close/q[qi-20].close-1,gap=cr-qr;enter=cr<0&&gap<=-.10;if(m3){if(gap>-.03)confirm++;else confirm=0;exit=confirm>=5}}}if(!m3&&enter){m3=true;confirm=0}else if(m3&&exit){m3=false;confirm=0}const cs=cotStress(cotRows,shadow[si]?.date??d),desired:State=m3?"DEEP":cs?"YELLOW":"NORMAL";bal.f*=1+(fm.get(d)??0);bal.g*=1+(gm.get(d)??0);bal.gold*=1+(am.get(d)??0);bal.bond*=1+(bm.get(d)??0);bal.sh*=1+(smkt.get(d)??0);const month=d.slice(0,7),rebalance=month!==lastMonth||desired!==state;if(rebalance){let total=bal.f+bal.g+bal.gold+bal.bond+bal.sh+bal.c;const t=targets(desired),cur={f:bal.f/total,g:bal.g/total,gold:bal.gold/total,bond:bal.bond/total,sh:bal.sh/total,c:bal.c/total},turn=(Math.abs(cur.f-t.f)+Math.abs(cur.g-t.g)+Math.abs(cur.gold-t.gold)+Math.abs(cur.bond-t.bond)+Math.abs(cur.sh-t.sh)+Math.abs(cur.c-t.c))/2;total*=1-cost*turn;bal={f:total*t.f,g:total*t.g,gold:total*t.gold,bond:total*t.bond,sh:total*t.sh,c:total*t.c};lastMonth=month;state=desired}const e=bal.f+bal.g+bal.gold+bal.bond+bal.sh+bal.c;peak=Math.max(peak,e);out.push({date:d,equity:e,drawdown:e/peak-1})}return out}
function rolling36(c:EquityPoint[]){const a:number[]=[];for(let i=0;i<c.length;i++){const ed=new Date(c[i].date+"T00:00:00Z"),t=new Date(ed);t.setUTCFullYear(t.getUTCFullYear()-3);let j=i;while(j>0&&new Date(c[j].date+"T00:00:00Z")>t)j--;const y=(ed.getTime()-new Date(c[j].date+"T00:00:00Z").getTime())/86400000/365.25;if(y>=2.9)a.push((c[i].equity/c[j].equity)**(1/y)-1)}return a}
function trim(c:EquityPoint[],s:string){const z=c.filter(x=>x.date>=s),b=z[0].equity;let p=1;return z.map(x=>{const e=x.equity/b;p=Math.max(p,e);return{date:x.date,equity:e,drawdown:e/p-1}})}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));for(const s of ["GLDM","IEF","SH"]){if(!m.histories[s]||m.histories[s].length<200)m.histories[s]=await fetchYahooHistory(s)}const cr=await cot();const f=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(x=>x.date>=START&&x.date<=END),g=runG(m.histories,us),gold=asset(m.histories.GLDM),bond=asset(m.histories.IEF),sh=asset(m.histories.SH),mk=(c=.001,l=0)=>apply(f,g,gold,bond,sh,m.histories.QQQ,cr,c,l),base=mk(),stress=[mk(.003),mk(.001,1),mk(.001,2),trim(mk(),"2021-01-01")],sc=stress.map(x=>performanceStats(x).cagr),rw=rolling36(base),st=performanceStats(base),proxy=Math.min(median(sc),median(rw));console.log(JSON.stringify({architecture:"SBI Stage18: exact Stage15 role substitution",normal:N,yellow:Y,deep:D,rule:"DBMF->50/50 GLDM+IEF, BTAL->SH; CFTC/M3 frozen",result:{stats:st,stressCAGRs:sc,stressMedianCAGR:median(sc),rolling36MedianCAGR:median(rw),rolling36Worst:Math.min(...rw),planningProxy:proxy,pass:proxy>=.40&&st.maxDrawdown>=-.17}},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});