import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import {fetchYahooHistory} from "../src/lib/yahoo";
import type {EquityPoint,PricePoint,UniverseMonth} from "../src/lib/types";
type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};
const START="2020-01-01",END="2026-08-25";const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/(x.length||1);const med=(x:number[])=>{const a=[...x].sort((p,q)=>p-q),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function runG(h:Record<string,PricePoint[]>,us:UniverseMonth[]){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date).filter(d=>d>=START&&d<=END),rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))])),idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))])),maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di],nd=dates[di+1]??null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>{const r=(maps[x.s] as Map<string,PricePoint>).get(d);return z+x.sh*(r?.open??r?.close??x.e)},0)*.999;pos=[];pout=null;hold=0;peak=cash}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===5&&os.every(x=>x&&x>0)){const per=cash/5;pos=pin.ss.map((s,i)=>({s,sh:per*.999/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*.88);if(stop||dd<=-.15||hold>=20)pout=nd}if(!pos.length&&!pin&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<99||i<20)continue;const close=r[i].close;if(close<=mean(r.slice(i-99,i+1).map(x=>x.close)))continue;const hi=Math.max(...r.slice(i-20,i).map(x=>x.close));if(close>hi)ca.push({s,v:close/hi-1})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=5)pin={d:nd,ss:ca.slice(0,5).map(x=>x.s)}}}return curve}
function rets(c:EquityPoint[]){const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m}
function portfolio(parts:{curve:EquityPoint[],w:number}[]){const rm=parts.map(p=>rets(p.curve)),dates=parts[0].curve.slice(1).map(x=>x.date).filter(d=>rm.every(m=>m.has(d)));let e=1,p=1;const out:EquityPoint[]=[{date:parts[0].curve[0].date,equity:1,drawdown:0}];for(const d of dates){let r=0;for(let i=0;i<parts.length;i++)r+=parts[i].w*(rm[i].get(d)??0);e*=1+r;p=Math.max(p,e);out.push({date:d,equity:e,drawdown:e/p-1})}return out}
function rolling36(c:EquityPoint[]){const out:number[]=[];for(let i=0;i<c.length;i++){const end=new Date(c[i].date+"T00:00:00Z"),target=new Date(end);target.setUTCFullYear(target.getUTCFullYear()-3);let j=i;while(j>0&&new Date(c[j].date+"T00:00:00Z")>target)j--;const yrs=(end.getTime()-new Date(c[j].date+"T00:00:00Z").getTime())/86400000/365.25;if(yrs>=2.9)out.push((c[i].equity/c[j].equity)**(1/yrs)-1)}return out}
function trim(c:EquityPoint[],s:string){const z=c.filter(x=>x.date>=s),b=z[0].equity;let p=1;return z.map(x=>{const e=x.equity/b;p=Math.max(p,e);return{date:x.date,equity:e,drawdown:e/p-1}})}
function tactical(qqq:PricePoint[],assets:Record<string,PricePoint[]>,kind:"Z1"|"Z2"|"Z3",cost=.001,delay=0){const q=[...qqq].sort((a,b)=>a.date.localeCompare(b.date)).filter(x=>x.date>=START&&x.date<=END),dates=q.map(x=>x.date),rows=Object.fromEntries(Object.entries(assets).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date)).filter(x=>x.date>=START&&x.date<=END)])) as Record<string,PricePoint[]>;const idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map(a.map((x,i)=>[x.date,i]))])) as Record<string,Map<string,number>>;let cash=1,hold:string|null=null,sh=0,pending:{i:number,s:string|null}|null=null,prev=1;const rr=new Map<string,number>();for(let i=0;i<dates.length;i++){const d=dates[i];if(pending&&pending.i===i){if(hold){const k=idx[hold].get(d);if(k!=null){cash=sh*rows[hold][k].open*(1-cost);sh=0;hold=null}}if(pending.s){const s=pending.s,k=idx[s].get(d);if(k!=null&&rows[s][k].open>0){sh=cash*(1-cost)/rows[s][k].open;cash=0;hold=s}}pending=null}let eq=cash;if(hold){const k=idx[hold].get(d);if(k!=null)eq+=sh*rows[hold][k].close}rr.set(d,eq/prev-1);prev=eq;if(i<199||i===dates.length-1)continue;const ma100=mean(q.slice(i-99,i+1).map(x=>x.close)),ma200=mean(q.slice(i-199,i+1).map(x=>x.close)),r20=q[i].close/q[i-20].close-1;let want:string|null=null;if(kind==="Z1")want=q[i].close<ma100&&r20<0?"VIXY":null;else if(kind==="Z2")want=q[i].close<ma100&&r20<0?"BTAL":null;else want=q[i].close>ma200&&r20>0?"TQQQ":q[i].close<ma100&&r20<0?"VIXY":null;if(want!==hold&&!pending)pending={i:Math.min(dates.length-1,i+1+delay),s:want}}let e=1,p=1;const out:EquityPoint[]=[{date:dates[0],equity:1,drawdown:0}];for(let i=1;i<dates.length;i++){e*=1+(rr.get(dates[i])??0);p=Math.max(p,e);out.push({date:dates[i],equity:e,drawdown:e/p-1})}return out}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));for(const s of ["TQQQ","VIXY","BTAL","QQQ"])if(!m.histories[s]||m.histories[s].length<200)m.histories[s]=await fetchYahooHistory(s);const fixed=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(p=>p.date>=START&&p.date<=END),g=runG(m.histories,us),qqq=m.histories.QQQ;const results:any={};for(const k of ["Z1","Z2","Z3"] as const){const mk=(cost=.001,delay=0)=>portfolio([{curve:fixed,w:.75},{curve:g,w:.10},{curve:tactical(qqq,{TQQQ:m.histories.TQQQ,VIXY:m.histories.VIXY,BTAL:m.histories.BTAL},k,cost,delay),w:.15}]);const base=mk(),stress=[mk(.003,0),mk(.001,1),mk(.001,2),trim(mk(),"2021-01-01")],sc=stress.map(x=>performanceStats(x).cagr),r=rolling36(base),proxy=Math.min(med(sc),med(r)),s=performanceStats(base);results[k]={stats:s,stressCAGR:sc,stressMedianCAGR:med(sc),rolling36MedianCAGR:med(r),rolling36Worst:Math.min(...r),forwardPlanningCAGRProxy:proxy,pass:proxy>=.40&&s.maxDrawdown>=-.17}}console.log(JSON.stringify({core:{fixed:.75,g:.10,tactical:.15},objective:{planningCAGR:.40,maxDrawdown:-.17},results},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});