import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import {fetchYahooHistory} from "../src/lib/yahoo";
import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import type {EquityPoint,PricePoint,UniverseMonth} from "../src/lib/types";

type MF={histories:Record<string,PricePoint[]>}; type UF={history:UniverseMonth[]};
const START="2020-01-01",END="2026-08-25";
const pairs=[{u:"GLD",bull:"UGL",bear:"GLL"},{u:"TLT",bull:"TMF",bear:"TMV"},{u:"USO",bull:"UCO",bear:"SCO"}] as const;
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/(x.length||1); const med=(x:number[])=>{const a=[...x].sort((p,q)=>p-q),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const rm=(c:EquityPoint[])=>{const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m};
function curveFromDaily(dates:string[],rets:Map<string,number>){let e=1,p=1;const out:EquityPoint[]=[{date:dates[0],equity:1,drawdown:0}];for(let i=1;i<dates.length;i++){e*=1+(rets.get(dates[i])??0);p=Math.max(p,e);out.push({date:dates[i],equity:e,drawdown:e/p-1})}return out}
function monthRet(c:EquityPoint[]){const m=new Map<string,{f:number;l:number}>();for(const x of c){const k=x.date.slice(0,7),v=m.get(k);if(!v)m.set(k,{f:x.equity,l:x.equity});else v.l=x.equity}return new Map([...m].map(([k,v])=>[k,v.l/v.f-1]))}
function corr(a:Map<string,number>,b:Map<string,number>){const ks=[...a.keys()].filter(k=>b.has(k));const x=ks.map(k=>a.get(k)!),y=ks.map(k=>b.get(k)!);const mx=mean(x),my=mean(y);let n=0,dx=0,dy=0;for(let i=0;i<x.length;i++){const A=x[i]-mx,B=y[i]-my;n+=A*B;dx+=A*A;dy+=B*B}return n/Math.sqrt(dx*dy)}
function rolling36(c:EquityPoint[]){const a:number[]=[];for(let i=0;i<c.length;i++){const ed=new Date(c[i].date+"T00:00:00Z"),t=new Date(ed);t.setUTCFullYear(t.getUTCFullYear()-3);let j=i;while(j>0&&new Date(c[j].date+"T00:00:00Z")>t)j--;const y=(ed.getTime()-new Date(c[j].date+"T00:00:00Z").getTime())/86400000/365.25;if(y>=2.9)a.push((c[i].equity/c[j].equity)**(1/y)-1)}return a}
function trim(c:EquityPoint[],s:string){const z=c.filter(x=>x.date>=s),b=z[0].equity;let p=1;return z.map(x=>{const e=x.equity/b;p=Math.max(p,e);return{date:x.date,equity:e,drawdown:e/p-1}})}
function build(hist:Record<string,PricePoint[]>,mode:"dir"|"long"|"winner",cost=.001,lag=0){const rows=Object.fromEntries(Object.entries(hist).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date)).filter(x=>x.date>=START&&x.date<=END)]));const maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));const idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))]));const dates=(rows.GLD as PricePoint[]).map(x=>x.date).filter(d=>pairs.every(p=>(maps[p.u] as Map<string,PricePoint>).has(d)&&(maps[p.bull] as Map<string,PricePoint>).has(d)&&(maps[p.bear] as Map<string,PricePoint>).has(d)));
 let prev:string[]=[];const rets=new Map<string,number>();for(let di=1;di<dates.length;di++){const d=dates[di],sd=dates[Math.max(0,di-1-lag)];let picks:string[]=[];if(mode==="winner"){const cs=pairs.map(p=>{const i=(idx[p.u] as Map<string,number>).get(sd)!;const r=rows[p.u] as PricePoint[];return {p,m:i>=63?r[i].close/r[i-63].close-1:-Infinity}}).sort((a,b)=>b.m-a.m);if(cs[0].m>0)picks=[cs[0].p.bull]}else for(const p of pairs){const i=(idx[p.u] as Map<string,number>).get(sd)!;const r=rows[p.u] as PricePoint[];if(i<199)continue;const on=r[i].close>mean(r.slice(i-199,i+1).map(x=>x.close));if(on)picks.push(p.bull);else if(mode==="dir")picks.push(p.bear)}
 let rr=0;if(picks.length){const w=1/picks.length;for(const s of picks){const a=maps[s] as Map<string,PricePoint>,p0=a.get(dates[di-1]),p1=a.get(d);if(p0&&p1)rr+=w*(p1.close/p0.close-1)}}const turn=new Set([...prev,...picks]).size?([...new Set([...prev,...picks])].reduce((z,s)=>z+Math.abs((picks.includes(s)?1/Math.max(1,picks.length):0)-(prev.includes(s)?1/Math.max(1,prev.length):0)),0)):0;rr-=.5*turn*cost;rets.set(d,rr);prev=picks}return curveFromDaily(dates,rets)}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF;for(const s of [...new Set(pairs.flatMap(p=>[p.u,p.bull,p.bear]))])if(!m.histories[s]||m.histories[s].length<200)m.histories[s]=await fetchYahooHistory(s);const fixed=runStrategySimulation({histories:m.histories,universeHistory:u.history,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(x=>x.date>=START&&x.date<=END),fm=monthRet(fixed);const defs={AA:"dir",AB:"long",AC:"winner"} as const,results:any={};for(const [k,mode] of Object.entries(defs)){const mk=(c=.001,l=0)=>build(m.histories,mode,c,l),base=mk(),stress=[mk(.003,0),mk(.001,1),mk(.001,2),trim(mk(),"2021-01-01")],sc=stress.map(x=>performanceStats(x).cagr),rw=rolling36(base),st=performanceStats(base),proxy=Math.min(med(sc),med(rw)),co=corr(monthRet(base),fm);results[k]={mode,stats:st,stressMedianCAGR:med(sc),rolling36MedianCAGR:med(rw),rolling36Worst:Math.min(...rw),planningProxy:proxy,fixed60MonthlyCorrelation:co,pass:proxy>=.25&&st.maxDrawdown>=-.35&&Math.abs(co)<=.35}}console.log(JSON.stringify({objective:{standalonePlanningCAGR:.25,maxDrawdown:-.35,absFixed60Correlation:.35},results},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});