import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import {fetchYahooHistory} from "../src/lib/yahoo";
import type {EquityPoint,PricePoint,UniverseMonth} from "../src/lib/types";
type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};
const START="2020-01-01",END="2026-08-25";const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/(x.length||1);const med=(x:number[])=>{const a=[...x].sort((p,q)=>p-q),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function runG(h:Record<string,PricePoint[]>,us:UniverseMonth[]){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date).filter(d=>d>=START&&d<=END),rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))])),idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))])),maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di],nd=dates[di+1]??null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>{const r=(maps[x.s] as Map<string,PricePoint>).get(d);return z+x.sh*(r?.open??r?.close??x.e)},0)*.999;pos=[];pout=null;hold=0;peak=cash}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===5&&os.every(x=>x&&x>0)){const per=cash/5;pos=pin.ss.map((s,i)=>({s,sh:per*.999/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*.88);if(stop||dd<=-.15||hold>=20)pout=nd}if(!pos.length&&!pin&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<99||i<20)continue;const close=r[i].close;if(close<=mean(r.slice(i-99,i+1).map(x=>x.close)))continue;const hi=Math.max(...r.slice(i-20,i).map(x=>x.close));if(close>hi)ca.push({s,v:close/hi-1})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=5)pin={d:nd,ss:ca.slice(0,5).map(x=>x.s)}}}return curve}
function rm(c:EquityPoint[]){const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m}
function asset(a:PricePoint[]){const r=[...a].sort((x,y)=>x.date.localeCompare(y.date)).filter(x=>x.date>=START&&x.date<=END);let e=1,p=1;const o:EquityPoint[]=[{date:r[0].date,equity:1,drawdown:0}];for(let i=1;i<r.length;i++){e*=r[i].close/r[i-1].close;p=Math.max(p,e);o.push({date:r[i].date,equity:e,drawdown:e/p-1})}return o}
function core(f:EquityPoint[],g:EquityPoint[]){const fm=rm(f),gm=rm(g),dates=f.slice(1).map(x=>x.date).filter(d=>gm.has(d));let e=1,p=1;const o:EquityPoint[]=[{date:f[0].date,equity:1,drawdown:0}];for(const d of dates){e*=1+.85*(fm.get(d)??0)+.15*(gm.get(d)??0);p=Math.max(p,e);o.push({date:d,equity:e,drawdown:e/p-1})}return o}
function run(f:EquityPoint[],g:EquityPoint[],bt:EquityPoint[],kind:"L1"|"L2"|"L3",cost=.001,lag=0){const fm=rm(f),gm=rm(g),bm=rm(bt),sh=core(f,g),si=new Map(sh.map((x,i)=>[x.date,i])),dates=f.slice(1).map(x=>x.date).filter(d=>gm.has(d)&&bm.has(d)&&si.has(d));let e=1,p=1,state=false;const o:EquityPoint[]=[{date:f[0].date,equity:1,drawdown:0}];for(const d of dates){const ci=si.get(d) as number,k=Math.max(0,ci-1-lag),s=sh[k];let desired=state;if(!state&&s.drawdown<=-.12)desired=true;else if(state&&s.drawdown>-.08&&k>=10&&s.equity/sh[k-10].equity-1>0)desired=false;let wf=.85,wg=.15,wb=0;if(desired){wf=.15;if(kind==="L2")wb=.70;else if(kind==="L3")wb=.35}let r=wf*(fm.get(d)??0)+wg*(gm.get(d)??0)+wb*(bm.get(d)??0);if(desired!==state){const turn=kind==="L1"?.70:kind==="L2"?1.40:1.05;r-=turn*cost}state=desired;e*=1+r;p=Math.max(p,e);o.push({date:d,equity:e,drawdown:e/p-1})}return o}
function rolling36(c:EquityPoint[]){const a:number[]=[];for(let i=0;i<c.length;i++){const ed=new Date(c[i].date+"T00:00:00Z"),t=new Date(ed);t.setUTCFullYear(t.getUTCFullYear()-3);let j=i;while(j>0&&new Date(c[j].date+"T00:00:00Z")>t)j--;const y=(ed.getTime()-new Date(c[j].date+"T00:00:00Z").getTime())/86400000/365.25;if(y>=2.9)a.push((c[i].equity/c[j].equity)**(1/y)-1)}return a}
function trim(c:EquityPoint[],s:string){const z=c.filter(x=>x.date>=s),b=z[0].equity;let p=1;return z.map(x=>{const e=x.equity/b;p=Math.max(p,e);return{date:x.date,equity:e,drawdown:e/p-1}})}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));if(!m.histories.BTAL||m.histories.BTAL.length<200)m.histories.BTAL=await fetchYahooHistory("BTAL");const f=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(x=>x.date>=START&&x.date<=END),g=runG(m.histories,us),bt=asset(m.histories.BTAL),results:any={};for(const k of ["L1","L2","L3"] as const){const mk=(cost=.001,lag=0)=>run(f,g,bt,k,cost,lag),base=mk(),stress=[mk(.003,0),mk(.001,1),mk(.001,2),trim(mk(),"2021-01-01")],sc=stress.map(x=>performanceStats(x).cagr),rw=rolling36(base),proxy=Math.min(med(sc),med(rw)),st=performanceStats(base);results[k]={stats:st,stressCAGR:sc,stressMedianCAGR:med(sc),rolling36MedianCAGR:med(rw),rolling36Worst:Math.min(...rw),forwardPlanningCAGRProxy:proxy,pass:proxy>=.40&&st.maxDrawdown>=-.17}}console.log(JSON.stringify({trigger:"shadow DD <= -12; recover >-8 and 10d>0",objective:{planningCAGR:.40,maxDrawdown:-.17},results},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});