import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import {fetchYahooHistory} from "../src/lib/yahoo";
import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import type {EquityPoint,PricePoint,UniverseMonth} from "../src/lib/types";
type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};const START="2020-01-01",END="2026-08-25";const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/(x.length||1);const med=(x:number[])=>{const a=[...x].sort((p,q)=>p-q),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const specs={AD:{lead:"SMH",bull:"SOXL",bear:"SOXS"},AE:{lead:"IWM",bull:"TNA",bear:"TZA"},AF:{lead:"XLF",bull:"FAS",bear:"FAZ"}} as const;
const rm=(c:EquityPoint[])=>{const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m};function mret(c:EquityPoint[]){const m=new Map<string,{f:number;l:number}>();for(const x of c){const k=x.date.slice(0,7),v=m.get(k);if(!v)m.set(k,{f:x.equity,l:x.equity});else v.l=x.equity}return new Map([...m].map(([k,v])=>[k,v.l/v.f-1]))}function corr(a:Map<string,number>,b:Map<string,number>){const ks=[...a.keys()].filter(k=>b.has(k)),x=ks.map(k=>a.get(k)!),y=ks.map(k=>b.get(k)!),mx=mean(x),my=mean(y);let n=0,dx=0,dy=0;for(let i=0;i<x.length;i++){const A=x[i]-mx,B=y[i]-my;n+=A*B;dx+=A*A;dy+=B*B}return n/Math.sqrt(dx*dy)}
function roll36(c:EquityPoint[]){const a:number[]=[];for(let i=0;i<c.length;i++){const ed=new Date(c[i].date+"T00:00:00Z"),t=new Date(ed);t.setUTCFullYear(t.getUTCFullYear()-3);let j=i;while(j>0&&new Date(c[j].date+"T00:00:00Z")>t)j--;const y=(ed.getTime()-new Date(c[j].date+"T00:00:00Z").getTime())/86400000/365.25;if(y>=2.9)a.push((c[i].equity/c[j].equity)**(1/y)-1)}return a}function trim(c:EquityPoint[],s:string){const z=c.filter(x=>x.date>=s),b=z[0].equity;let p=1;return z.map(x=>{const e=x.equity/b;p=Math.max(p,e);return{date:x.date,equity:e,drawdown:e/p-1}})}
function run(h:Record<string,PricePoint[]>,sp:{lead:string;bull:string;bear:string},cost=.001,lag=0){const sy=[sp.lead,"QQQ",sp.bull,sp.bear,"TQQQ","SQQQ"],rows=Object.fromEntries(sy.map(s=>[s,[...(h[s]??[])].sort((a,b)=>a.date.localeCompare(b.date)).filter(x=>x.date>=START&&x.date<=END)])),maps=Object.fromEntries(sy.map(s=>[s,new Map((rows[s] as PricePoint[]).map(x=>[x.date,x]))])),idx=Object.fromEntries(sy.map(s=>[s,new Map((rows[s] as PricePoint[]).map((x,i)=>[x.date,i]))]));const dates=(rows.QQQ as PricePoint[]).map(x=>x.date).filter(d=>sy.every(s=>(maps[s] as Map<string,PricePoint>).has(d)));let e=1,p=1,prev="";const out:EquityPoint[]=[{date:dates[0],equity:1,drawdown:0}];for(let di=1;di<dates.length;di++){const d=dates[di],si=Math.max(0,di-1-lag),sd=dates[si],li=(idx[sp.lead] as Map<string,number>).get(sd)!,qi=(idx.QQQ as Map<string,number>).get(sd)!;let picks:string[]=[];if(li>=63&&qi>=63){const lr=(rows[sp.lead] as PricePoint[])[li].close/(rows[sp.lead] as PricePoint[])[li-63].close-1,qr=(rows.QQQ as PricePoint[])[qi].close/(rows.QQQ as PricePoint[])[qi-63].close-1;if(lr>qr)picks=[sp.bull,"SQQQ"];else picks=[sp.bear,"TQQQ"]}let r=0;if(picks.length)for(const s of picks){const m=maps[s] as Map<string,PricePoint>,a=m.get(dates[di-1])!,b=m.get(d)!;r+=.5*(b.close/a.close-1)}const key=picks.join("+");if(key!==prev)r-=cost;prev=key;e*=1+r;p=Math.max(p,e);out.push({date:d,equity:e,drawdown:e/p-1})}return out}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF;for(const s of [...new Set(Object.values(specs).flatMap(x=>[x.lead,x.bull,x.bear,"QQQ","TQQQ","SQQQ"]))])if(!m.histories[s]||m.histories[s].length<200)m.histories[s]=await fetchYahooHistory(s);const fixed=runStrategySimulation({histories:m.histories,universeHistory:u.history,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(x=>x.date>=START&&x.date<=END),fm=mret(fixed),results:any={};for(const [k,sp] of Object.entries(specs)){const mk=(c=.001,l=0)=>run(m.histories,sp,c,l),base=mk(),stress=[mk(.003,0),mk(.001,1),mk(.001,2),trim(mk(),"2021-01-01")],sc=stress.map(x=>performanceStats(x).cagr),rw=roll36(base),st=performanceStats(base),proxy=Math.min(med(sc),med(rw)),co=corr(mret(base),fm);results[k]={spec:sp,stats:st,stressMedianCAGR:med(sc),rolling36MedianCAGR:med(rw),rolling36Worst:Math.min(...rw),planningProxy:proxy,fixed60MonthlyCorrelation:co,pass:proxy>=.25&&st.maxDrawdown>=-.35&&Math.abs(co)<=.35}}console.log(JSON.stringify({architecture:"50/50 relative-value pair: leveraged leader direction + inverse Nasdaq hedge",objective:{planningCAGR:.25,maxDrawdown:-.35,absFixed60Correlation:.35},results},null,2))}main().catch(e=>{console.error(e);process.exitCode=1});