import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import {fetchYahooHistory} from "../src/lib/yahoo";
import type {EquityPoint,PricePoint,UniverseMonth} from "../src/lib/types";
type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};
const START="2020-01-01",END="2026-08-25";const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/(x.length||1);const med=(x:number[])=>{const a=[...x].sort((p,q)=>p-q),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function runG(h:Record<string,PricePoint[]>,us:UniverseMonth[]){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date).filter(d=>d>=START&&d<=END),rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))])),idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))])),maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di],nd=dates[di+1]??null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>{const r=(maps[x.s] as Map<string,PricePoint>).get(d);return z+x.sh*(r?.open??r?.close??x.e)},0)*.999;pos=[];pout=null;hold=0;peak=cash}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===5&&os.every(x=>x&&x>0)){const per=cash/5;pos=pin.ss.map((s,i)=>({s,sh:per*.999/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*.88);if(stop||dd<=-.15||hold>=20)pout=nd}if(!pos.length&&!pin&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<99||i<20)continue;const close=r[i].close;if(close<=mean(r.slice(i-99,i+1).map(x=>x.close)))continue;const hi=Math.max(...r.slice(i-20,i).map(x=>x.close));if(close>hi)ca.push({s,v:close/hi-1})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=5)pin={d:nd,ss:ca.slice(0,5).map(x=>x.s)}}}return curve}
function rets(c:EquityPoint[]){const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m}
function buyHold(a:PricePoint[]){const rows=[...a].sort((x,y)=>x.date.localeCompare(y.date)).filter(x=>x.date>=START&&x.date<=END);let e=1,p=1;const out:EquityPoint[]=[{date:rows[0].date,equity:1,drawdown:0}];for(let i=1;i<rows.length;i++){e*=rows[i].close/rows[i-1].close;p=Math.max(p,e);out.push({date:rows[i].date,equity:e,drawdown:e/p-1})}return out}
function portfolio(parts:{curve:EquityPoint[],w:number}[]){const rm=parts.map(p=>rets(p.curve)),dates=parts[0].curve.slice(1).map(x=>x.date).filter(d=>rm.every(m=>m.has(d)));let e=1,p=1;const out:EquityPoint[]=[{date:parts[0].curve[0].date,equity:1,drawdown:0}];for(const d of dates){let r=0;for(let i=0;i<parts.length;i++)r+=parts[i].w*(rm[i].get(d)??0);e*=1+r;p=Math.max(p,e);out.push({date:d,equity:e,drawdown:e/p-1})}return out}
function rolling36(c:EquityPoint[]){const out:number[]=[];for(let i=0;i<c.length;i++){const end=new Date(c[i].date+"T00:00:00Z"),target=new Date(end);target.setUTCFullYear(target.getUTCFullYear()-3);let j=i;while(j>0&&new Date(c[j].date+"T00:00:00Z")>target)j--;const years=(end.getTime()-new Date(c[j].date+"T00:00:00Z").getTime())/86400000/365.25;if(years>=2.9)out.push((c[i].equity/c[j].equity)**(1/years)-1)}return out}
function trim(c:EquityPoint[],s:string){const z=c.filter(x=>x.date>=s);const b=z[0].equity;let p=1;return z.map(x=>{const e=x.equity/b;p=Math.max(p,e);return{date:x.date,equity:e,drawdown:e/p-1}})}
function govern(base:EquityPoint[],qqq:PricePoint[],kind:"Y1"|"Y2"|"Y3",lag=0){const br=base.slice(1).map((p,i)=>p.equity/base[i].equity-1),qm=new Map(qqq.map((x,i)=>[x.date,i]));let e=1,p=1,risk=1;const out:EquityPoint[]=[{date:base[0].date,equity:1,drawdown:0}];const queued:number[]=[];for(let i=0;i<br.length;i++){const si=Math.max(0,i-lag),shadow=base[si],dd=shadow.drawdown;let desired=risk;if(kind==="Y1"){const r10=si>=10?base[si].equity/base[si-10].equity-1:0;if(risk===1&&dd<=-.08)desired=.25;else if(risk<1&&dd>-.03&&r10>0)desired=1}else if(kind==="Y2"){desired=dd<=-.10?.25:dd<=-.05?.60:1}else{const d=base[si].date,qi=qm.get(d);let below=false;if(qi!=null&&qi>=99)below=qqq[qi].close<mean(qqq.slice(qi-99,qi+1).map(x=>x.close));if(risk===1&&dd<=-.08&&below)desired=.25;else if(risk<1&&((dd>-.03)||!below))desired=1}risk=desired;e*=1+risk*br[i];p=Math.max(p,e);out.push({date:base[i+1].date,equity:e,drawdown:e/p-1})}return out}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const fixed=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(p=>p.date>=START&&p.date<=END),g=runG(m.histories,us),dbmf=buyHold(await fetchYahooHistory("DBMF")),base=portfolio([{curve:fixed,w:.60},{curve:g,w:.15},{curve:dbmf,w:.25}]),qqq=[...(m.histories.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)).filter(x=>x.date>=START&&x.date<=END);const results:any={base:performanceStats(base)};for(const k of ["Y1","Y2","Y3"] as const){const c=govern(base,qqq,k,0),stress=[govern(base,qqq,k,1),govern(base,qqq,k,2),trim(govern(base,qqq,k,0),"2021-01-01")],sc=stress.map(x=>performanceStats(x).cagr),r=rolling36(c),proxy=Math.min(med(sc),med(r)),s=performanceStats(c);results[k]={stats:s,stressCAGR:sc,stressMedianCAGR:med(sc),rolling36MedianCAGR:med(r),rolling36Worst:Math.min(...r),forwardPlanningCAGRProxy:proxy,pass:proxy>=.40&&s.maxDrawdown>=-.17}}console.log(JSON.stringify({underlying:{fixed:.60,g:.15,dbmf:.25},objective:{planningCAGR:.40,maxDrawdown:-.17},results},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});