import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import {fetchYahooHistory} from "../src/lib/yahoo";
import type {EquityPoint,PricePoint,UniverseMonth} from "../src/lib/types";

type MF={histories:Record<string,PricePoint[]>}; type UF={history:UniverseMonth[]};
const START="2020-01-01",END="2026-08-25";
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/(x.length||1);
const median=(x:number[])=>{const a=[...x].sort((p,q)=>p-q);if(!a.length)return NaN;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
function sorted(a:PricePoint[]){return [...a].sort((x,y)=>x.date.localeCompare(y.date)).filter(x=>x.date>=START&&x.date<=END)}
function latestUniverse(us:UniverseMonth[],d:string){let z:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)z=u;else break}return z}
function mkCurve(dates:string[],rets:Map<string,number>){let e=1,pk=1;const out:EquityPoint[]=[{date:dates[0],equity:1,drawdown:0}];for(let i=1;i<dates.length;i++){e*=1+(rets.get(dates[i])??0);pk=Math.max(pk,e);out.push({date:dates[i],equity:e,drawdown:e/pk-1})}return out}
function dailyRets(c:EquityPoint[]){const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m}
function monthlyRets(c:EquityPoint[]){const by=new Map<string,{f:number,l:number}>();for(const p of c){const k=p.date.slice(0,7),x=by.get(k);if(!x)by.set(k,{f:p.equity,l:p.equity});else x.l=p.equity}return [...by.entries()].map(([k,v])=>({k,r:v.l/v.f-1}))}
function corr(a:EquityPoint[],b:EquityPoint[]){const x=new Map(monthlyRets(a).map(z=>[z.k,z.r])),y=monthlyRets(b).filter(z=>x.has(z.k));const xs=y.map(z=>x.get(z.k) as number),ys=y.map(z=>z.r),mx=mean(xs),my=mean(ys);let n=0,dx=0,dy=0;for(let i=0;i<xs.length;i++){const ax=xs[i]-mx,ay=ys[i]-my;n+=ax*ay;dx+=ax*ax;dy+=ay*ay}return n/Math.sqrt(dx*dy)}
function rolling36(c:EquityPoint[]){const out:number[]=[];for(let i=0;i<c.length;i++){const end=c[i].date;const ey=+end.slice(0,4),em=+end.slice(5,7),ed=+end.slice(8,10);const target=new Date(Date.UTC(ey-3,em-1,ed));let j=i;while(j>0&&new Date(c[j].date+"T00:00:00Z")>target)j--;if(j===i||j===0&&new Date(c[j].date+"T00:00:00Z")>target)continue;const days=(new Date(end+"T00:00:00Z").getTime()-new Date(c[j].date+"T00:00:00Z").getTime())/86400000;const years=days/365.25;if(years>=2.9)out.push((c[i].equity/c[j].equity)**(1/years)-1)}return out}
function nextIndex(dates:string[],i:number,delay:number){return Math.min(dates.length-1,i+1+delay)}

function runV(raw:Record<string,PricePoint[]>,cost=.001,delay=0,start=START){const syms=["TQQQ","GLD","DBMF"],rows=Object.fromEntries(syms.map(s=>[s,sorted(raw[s]??[])])) as Record<string,PricePoint[]>;const q=sorted(raw.QQQ??[]),dates=q.map(x=>x.date),maps=Object.fromEntries(syms.map(s=>[s,new Map(rows[s].map((x,i)=>[x.date,i]))])) as Record<string,Map<string,number>>;let cash=1,hold:string|null=null,shares=0,pending:{i:number,s:string|null}|null=null;const ret=new Map<string,number>();let prevEq=1;for(let i=0;i<dates.length;i++){const d=dates[i];if(pending&&pending.i===i){const ns=pending.s;if(hold){const r=rows[hold][maps[hold].get(d)??-1];if(r){cash=shares*r.open*(1-cost);shares=0;hold=null}}if(ns){const r=rows[ns][maps[ns].get(d)??-1];if(r&&r.open>0){shares=cash*(1-cost)/r.open;cash=0;hold=ns}}pending=null}let eq=cash;if(hold){const r=rows[hold][maps[hold].get(d)??-1];if(r)eq+=shares*r.close}ret.set(d,eq/prevEq-1);prevEq=eq;if(d<start||i<130||i===dates.length-1)continue;const month=d.slice(0,7),nm=dates[i+1]?.slice(0,7);if(month===nm)continue;let best:string|null=null,bv=-Infinity;for(const s of syms){const k=maps[s].get(d);if(k==null||k<126)continue;const r=rows[s],r3=r[k].close/r[k-63].close-1,r6=r[k].close/r[k-126].close-1;if(r6<=0)continue;const sc=.5*r3+.5*r6;if(sc>bv){bv=sc;best=s}}if(best!==hold){pending={i:nextIndex(dates,i,delay),s:best}}}return mkCurve(dates,ret)}

function breadthSeries(raw:Record<string,PricePoint[]>,us:UniverseMonth[],dates:string[]){const rows=Object.fromEntries(Object.entries(raw).map(([s,a])=>[s,sorted(a)])) as Record<string,PricePoint[]>;const idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map(a.map((x,i)=>[x.date,i]))])) as Record<string,Map<string,number>>;const out=new Map<string,number>();for(const d of dates){const u=latestUniverse(us,d);if(!u)continue;let ok=0,n=0;for(const m of u.symbols){const r=rows[m.symbol],k=idx[m.symbol]?.get(d);if(!r||k==null||k<49)continue;n++;if(r[k].close>mean(r.slice(k-49,k+1).map(x=>x.close)))ok++}if(n>=10)out.set(d,ok/n)}return out}
function runEventTqqq(raw:Record<string,PricePoint[]>,us:UniverseMonth[],kind:"W"|"X",cost=.001,delay=0,start=START){const q=sorted(raw.QQQ??[]),t=sorted(raw.TQQQ??[]),dates=q.map(x=>x.date),qi=new Map(q.map((x,i)=>[x.date,i])),ti=new Map(t.map((x,i)=>[x.date,i])),breadth=kind==="W"?breadthSeries(raw,us,dates):new Map<string,number>();let cash=1,sh=0,entry=0,hold=0,pendingIn:number|null=null,pendingOut:number|null=null;const ret=new Map<string,number>();let prevEq=1;for(let i=0;i<dates.length;i++){const d=dates[i],tk=ti.get(d);if(tk==null){ret.set(d,0);continue}if(pendingOut===i&&sh>0){cash=sh*t[tk].open*(1-cost);sh=0;entry=0;hold=0;pendingOut=null}if(pendingIn===i&&sh===0){sh=cash*(1-cost)/t[tk].open;cash=0;entry=t[tk].open;hold=0;pendingIn=null}const eq=cash+sh*t[tk].close;ret.set(d,eq/prevEq-1);prevEq=eq;const qk=qi.get(d);if(qk==null||d<start)continue;if(sh>0){hold++;let exit=false;if(kind==="W")exit=hold>=20;else if(qk>=49){const ma50=mean(q.slice(qk-49,qk+1).map(x=>x.close));exit=q[qk].close<ma50||hold>=20}if(exit&&pendingOut==null)pendingOut=nextIndex(dates,i,delay)}else if(pendingIn==null&&i<dates.length-2){let trig=false;if(kind==="W"&&qk>=99&&i>=10){const b=breadth.get(d),b10=breadth.get(dates[i-10]);const arm=dates.slice(Math.max(0,i-10),i+1).some(x=>(breadth.get(x)??1)<=.40);const ma100=mean(q.slice(qk-99,qk+1).map(x=>x.close));trig=!!b&&b10!=null&&arm&&b>=.60&&(b-b10)>=.20&&q[qk].close>ma100}else if(kind==="X"&&qk>=199&&qk>=20){const ma200=mean(q.slice(qk-199,qk+1).map(x=>x.close)),hi=Math.max(...q.slice(qk-20,qk).map(x=>x.close));trig=q[qk].close>ma200&&q[qk].close>hi}if(trig)pendingIn=nextIndex(dates,i,delay)}}return mkCurve(dates,ret)}

function trim(c:EquityPoint[],start:string){const z=c.filter(x=>x.date>=start);if(!z.length)return c;const b=z[0].equity;let pk=1;return z.map(x=>{const e=x.equity/b;pk=Math.max(pk,e);return{date:x.date,equity:e,drawdown:e/pk-1}})}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));for(const s of ["TQQQ","GLD","DBMF","QQQ"]){if(!m.histories[s]||m.histories[s].length<200)m.histories[s]=await fetchYahooHistory(s)}const fixed=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(x=>x.date>=START&&x.date<=END);const defs={V:(cost:number,delay:number,start:string)=>runV(m.histories,cost,delay,start),W:(cost:number,delay:number,start:string)=>runEventTqqq(m.histories,us,"W",cost,delay,start),X:(cost:number,delay:number,start:string)=>runEventTqqq(m.histories,us,"X",cost,delay,start)};const results:any={};for(const [name,fn] of Object.entries(defs)){const base=fn(.001,0,START),stress=[fn(.003,0,START),fn(.001,1,START),fn(.001,2,START),trim(fn(.001,0,"2021-01-01"),"2021-01-01")],sC=stress.map(x=>performanceStats(x).cagr),r36=rolling36(base),proxy=Math.min(median(sC),median(r36)),bs=performanceStats(base),c=corr(base,fixed);results[name]={base:bs,monthlyCorrelationFixed60:c,stressCAGR:sC,stressMedianCAGR:median(sC),rolling36MedianCAGR:median(r36),rolling36Worst:Math.min(...r36),forwardPlanningCAGRProxy:proxy,pass:proxy>=.30&&c<=.40&&bs.maxDrawdown>=-.40}}console.log(JSON.stringify({gate:{planningCAGR:.30,maxCorrelation:.40,maxDrawdown:-.40},results},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});