import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import type {EquityPoint,PricePoint,UniverseMonth} from "../src/lib/types";

type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};type Entry={end:string;filed:string;form:string;fp?:string;val:number};type Facts={facts?:Record<string,Record<string,{units?:Record<string,Entry[]>}>>};
const START="2020-01-01",END="2026-08-25",TOP=5,UA="momentum-console research https://github.com/kensuke5704/momentum-console";
const med=(x:number[])=>{const a=[...x].sort((p,q)=>p-q),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function latestU(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function rm(c:EquityPoint[]){const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m}
function monthly(c:EquityPoint[]){const o=new Map<string,number>();let key="",start=1,last=1;for(const x of c){const k=x.date.slice(0,7);if(key&&k!==key){o.set(key,last/start-1);start=last}if(!key)start=x.equity;key=k;last=x.equity}if(key)o.set(key,last/start-1);return o}
function corr(a:EquityPoint[],b:EquityPoint[]){const x=monthly(a),y=monthly(b),ks=[...x.keys()].filter(k=>y.has(k)),A=ks.map(k=>x.get(k)!),B=ks.map(k=>y.get(k)!);const ma=A.reduce((s,v)=>s+v,0)/A.length,mb=B.reduce((s,v)=>s+v,0)/B.length;let n=0,da=0,db=0;for(let i=0;i<A.length;i++){const p=A[i]-ma,q=B[i]-mb;n+=p*q;da+=p*p;db+=q*q}return n/Math.sqrt(da*db)}
function rolling36(c:EquityPoint[]){const a:number[]=[];for(let i=0;i<c.length;i++){const ed=new Date(c[i].date+"T00:00:00Z"),t=new Date(ed);t.setUTCFullYear(t.getUTCFullYear()-3);let j=i;while(j>0&&new Date(c[j].date+"T00:00:00Z")>t)j--;const y=(ed.getTime()-new Date(c[j].date+"T00:00:00Z").getTime())/86400000/365.25;if(y>=2.9)a.push((c[i].equity/c[j].equity)**(1/y)-1)}return a}
function trim(c:EquityPoint[],s:string){const z=c.filter(x=>x.date>=s);if(!z.length)return z;const b=z[0].equity;let p=1;return z.map(x=>{const e=x.equity/b;p=Math.max(p,e);return{date:x.date,equity:e,drawdown:e/p-1}})}
function monthEnds(q:PricePoint[]){const a=q.filter(x=>x.date>=START&&x.date<=END),o:string[]=[];for(let i=0;i<a.length;i++)if(i===a.length-1||a[i+1].date.slice(0,7)!==a[i].date.slice(0,7))o.push(a[i].date);return o}
function tag(f:Facts,name:string,unit:string,d:string){const u=f.facts?.["us-gaap"]?.[name]?.units?.[unit]??[],by=new Map<string,Entry>();for(const x of u){if(x.filed>d||!/^10-K/.test(x.form)||x.fp&&x.fp!=="FY"||!Number.isFinite(x.val))continue;const z=by.get(x.end);if(!z||x.filed>z.filed)by.set(x.end,x)}return [...by.values()].sort((a,b)=>b.end.localeCompare(a.end))}
function pair(f:Facts,name:string,unit:string,d:string){const a=tag(f,name,unit,d);return a.length>=2?[a[0],a[1]] as const:null}
function score(f:Facts,d:string,mode:"fcf"|"shares"|"quality"){if(mode==="shares"){const p=pair(f,"WeightedAverageNumberOfDilutedSharesOutstanding","shares",d);if(!p||p[0].val<=0||p[1].val<=0)return null;const v=p[1].val/p[0].val-1;return v>0?v:null}const c=pair(f,"NetCashProvidedByUsedInOperatingActivities","USD",d),n=pair(f,"NetIncomeLoss","USD",d);if(!c||!n)return null;if(mode==="quality"){if(c[0].val<=0||c[1].val<=0||n[0].val<=0||n[1].val<=0)return null;const v=c[0].val/n[0].val-c[1].val/n[1].val;return v>0?v:null}const cap=pair(f,"PaymentsToAcquirePropertyPlantAndEquipment","USD",d);if(!cap)return null;const now=c[0].val-cap[0].val,prev=c[1].val-cap[1].val;if(now<=0||prev<=0)return null;const v=now/prev-1;return v>0?v:null}
async function fetchJson(url:string){const r=await fetch(url,{headers:{"User-Agent":UA,"Accept-Encoding":"gzip, deflate"}});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json()}
async function loadFacts(symbols:string[]){const tick=await fetchJson("https://www.sec.gov/files/company_tickers.json") as Record<string,{ticker:string;cik_str:number}>,map=new Map(Object.values(tick).map(x=>[x.ticker.toUpperCase(),x.cik_str])),out=new Map<string,Facts>();let ok=0;for(const s of symbols){const cik=map.get(s);if(!cik)continue;try{const f=await fetchJson(`https://data.sec.gov/api/xbrl/companyfacts/CIK${String(cik).padStart(10,"0")}.json`) as Facts;out.set(s,f);ok++}catch{}await sleep(120)}console.error(`SEC_FACTS_COVERAGE ${ok}/${symbols.length}`);return out}
function run(h:Record<string,PricePoint[]>,us:UniverseMonth[],facts:Map<string,Facts>,mode:"fcf"|"shares"|"quality",cost=.001,lag=0){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.filter(x=>x.date>=START&&x.date<=END).map(x=>x.date),di=new Map(dates.map((d,i)=>[d,i])),ends=new Set(monthEnds(q)),maps=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,new Map(a.map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;last:number}>=[],pending=new Map<string,string[]>(),peak=1;const out:EquityPoint[]=[];for(const d of dates){const sel=pending.get(d);if(sel){if(pos.length){cash=pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.open??x.last),0)*(1-cost);pos=[]}const v=sel.map(s=>({s,p:(maps[s] as Map<string,PricePoint>).get(d)?.open})).filter(x=>x.p&&x.p>0) as {s:string;p:number}[];if(v.length){const per=cash/v.length;pos=v.map(x=>({s:x.s,sh:per*(1-cost)/x.p,last:x.p}));cash=0}pending.delete(d)}let e=cash;for(const x of pos){const p=(maps[x.s] as Map<string,PricePoint>).get(d)?.close??x.last;x.last=p;e+=x.sh*p}peak=Math.max(peak,e);out.push({date:d,equity:e,drawdown:e/peak-1});if(!ends.has(d))continue;const i=di.get(d)!+1+lag;if(i>=dates.length)continue;const u=latestU(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const f=facts.get(m.symbol);if(!f)continue;const v=score(f,d,mode);if(v==null)continue;if(!(maps[m.symbol] as Map<string,PricePoint>|undefined)?.get(dates[i])?.open)continue;ca.push({s:m.symbol,v})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));pending.set(dates[i],ca.slice(0,TOP).map(x=>x.s))}return out}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),symbols=[...new Set(us.flatMap(x=>x.symbols.map(y=>y.symbol)))].filter(s=>m.histories[s]);const facts=await loadFacts(symbols),f=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(x=>x.date>=START&&x.date<=END),defs={AO:"fcf",AP:"shares",AQ:"quality"}as const,res:any={};for(const[k,mode]of Object.entries(defs)){const mk=(c=.001,l=0)=>run(m.histories,us,facts,mode,c,l),base=mk(),stress=[mk(.003),mk(.001,1),mk(.001,2),trim(mk(),"2021-01-01")],sc=stress.map(x=>performanceStats(x).cagr),rw=rolling36(base),st=performanceStats(base),proxy=Math.min(med(sc),med(rw)),co=corr(base,f);res[k]={mode,stats:st,stressMedianCAGR:med(sc),rolling36MedianCAGR:med(rw),rolling36Worst:Math.min(...rw),planningProxy:proxy,fixed60MonthlyCorrelation:co,pass:proxy>=.25&&st.maxDrawdown>=-.40&&Math.abs(co)<=.35}}console.log(JSON.stringify({architecture:"PIT annual 10-K fundamental acceleration; PIT N-PORT Universe Top5; next-open; no price ranking",coverage:{facts:facts.size,requested:symbols.length},objective:{planningCAGR:.25,maxDrawdown:-.40,absFixed60Correlation:.35},results:res},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});