import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY as C} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {MonthlySignal,PricePoint,UniverseMonth} from '../src/lib/types';

type Row={date:string;year:number;mode:string;consensus:boolean;top1:string;top2:string;r1:number;r2:number;spread:number;w1:number};
function isConsensus(s:MonthlySignal){const e=s.candidates.filter(c=>c.eligible&&c.threeMonth!==null&&c.sixMonth!==null);if(e.length<2)return false;const r3=[...e].sort((a,b)=>(b.threeMonth??-9)-(a.threeMonth??-9)||a.symbol.localeCompare(b.symbol))[0]?.symbol;const r6=[...e].sort((a,b)=>(b.sixMonth??-9)-(a.sixMonth??-9)||a.symbol.localeCompare(b.symbol))[0]?.symbol;return !!r3&&r3===r6&&s.selectedSymbols[0]===r3;}
function mean(a:number[]){return a.length?a.reduce((x,y)=>x+y,0)/a.length:NaN}function med(a:number[]){if(!a.length)return NaN;const x=[...a].sort((p,q)=>p-q),m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}function trimmed(a:number[],k=1){if(a.length<=2*k)return mean(a);const x=[...a].sort((p,q)=>p-q).slice(k,-k);return mean(x)}
function rng(seed=5704){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return (x>>>0)/4294967296}}
function sampleWithout<T>(a:T[],n:number,r:()=>number){const x=[...a];for(let i=0;i<n;i++){const j=i+Math.floor(r()*(x.length-i));[x[i],x[j]]=[x[j],x[i]]}return x.slice(0,n)}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8')) as {histories:Record<string,PricePoint[]>};const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8')) as {history:UniverseMonth[]};const hist=market.histories,q=[...hist.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date),di=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))]));const rows:Row[]=[];
 for(const u of [...uf.history].filter(x=>x.asOf>=C.backtestStart).sort((a,b)=>a.asOf.localeCompare(b.asOf))){const i=di.get(u.asOf);if(i===undefined||i+22>=dates.length)continue;const next=dates[i+1]??nextUsTradingSession(u.asOf);const s=buildMonthlySignal({universe:u,histories:hist,qqq:q,nextSessionDate:next,config:C});if(!s.marketRiskOn||s.selectedSymbols.length<2)continue;const [a,b]=s.selectedSymbols,pa=pm[a]?.get(next),pb=pm[b]?.get(next);if(!pa||!pb)continue;const exitDate=dates[i+22],ea=pm[a]?.get(exitDate),eb=pm[b]?.get(exitDate);if(!ea||!eb)continue;const entryA=pa.open??pa.close,entryB=pb.open??pb.close;if(!(entryA>0&&entryB>0&&ea.close>0&&eb.close>0))continue;const r1=Math.log(ea.close/entryA),r2=Math.log(eb.close/entryB);const w1=s.zGap!==null&&s.zGap>=C.allocation.concentrationZGap?C.allocation.concentratedTop1Weight:C.allocation.baseTop1Weight;rows.push({date:u.asOf,year:+u.asOf.slice(0,4),mode:w1>=.7?'70/30':'50/50',consensus:isConsensus(s),top1:a,top2:b,r1,r2,spread:r1-r2,w1});}
 const cons=rows.filter(x=>x.consensus),non=rows.filter(x=>!x.consensus);const stats=(x:Row[])=>({n:x.length,meanSpread:mean(x.map(r=>r.spread)),medianSpread:med(x.map(r=>r.spread)),trim1Mean:trimmed(x.map(r=>r.spread),1),top1WinRate:x.length?x.filter(r=>r.spread>0).length/x.length:null,meanTop1:mean(x.map(r=>r.r1)),meanTop2:mean(x.map(r=>r.r2))});
 const strata=new Map<string,{pool:Row[];n:number}>();for(const r of rows){const k=`${r.year}|${r.mode}`;if(!strata.has(k))strata.set(k,{pool:[],n:0});const s=strata.get(k)!;s.pool.push(r);if(r.consensus)s.n++;}
 const obs=mean(cons.map(x=>x.spread)),obsMed=med(cons.map(x=>x.spread)),R=100000,rand=rng(),nullMeans:number[]=[],nullMeds:number[]=[];for(let z=0;z<R;z++){const pick:Row[]=[];for(const s of strata.values())if(s.n>0)pick.push(...sampleWithout(s.pool,s.n,rand));nullMeans.push(mean(pick.map(x=>x.spread)));nullMeds.push(med(pick.map(x=>x.spread)));}
 const geMean=nullMeans.filter(x=>x>=obs).length/R,geMed=nullMeds.filter(x=>x>=obsMed).length/R;const qtile=(a:number[],p:number)=>{const x=[...a].sort((a,b)=>a-b);return x[Math.min(x.length-1,Math.floor(p*(x.length-1)))]};
 const early=cons.filter(x=>x.year<=2023),late=cons.filter(x=>x.year>=2024);const leaveBest=[...cons].sort((a,b)=>b.spread-a.spread).slice(0,3);const withoutTop1=cons.filter(x=>x!==leaveBest[0]),withoutTop3=cons.filter(x=>!leaveBest.includes(x));
 const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,noLeverage:true,trueOOS:false,warning:'Falsification diagnostic, not strategy backtest. Forward label is next-open to 21-trading-day-later close log return. Permutation preserves calendar year and Production base allocation mode counts.'},counts:{riskOnMonths:rows.length,consensus:cons.length,nonConsensus:non.length},consensus:stats(cons),nonConsensus:stats(non),early:stats(early),late:stats(late),outlierRobustness:{withoutBest:stats(withoutTop1),withoutTop3:stats(withoutTop3),best3:leaveBest},permutation:{iterations:R,observedMeanSpread:obs,pValueUpperMean:geMean,observedMedianSpread:obsMed,pValueUpperMedian:geMed,nullMeanP05:qtile(nullMeans,.05),nullMeanP50:qtile(nullMeans,.5),nullMeanP95:qtile(nullMeans,.95)},rows};const d=path.join(process.cwd(),'data/research/consensus75-event-falsification');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({...out,rows:undefined},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});