import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,MonthlySignal,PositionState,PricePoint,UniverseMonth} from '../src/lib/types';
const TAX=.20315;
type Ledger={gain:Record<string,number>;loss:Record<string,number>;taxes:number;sales:number;turnover:number};
function consensus(sig:MonthlySignal){const e=sig.candidates.filter(c=>c.eligible&&c.threeMonth!==null&&c.sixMonth!==null);if(e.length<2)return false;const r3=[...e].sort((a,b)=>(b.threeMonth??-9)-(a.threeMonth??-9)||a.symbol.localeCompare(b.symbol))[0]?.symbol,r6=[...e].sort((a,b)=>(b.sixMonth??-9)-(a.sixMonth??-9)||a.symbol.localeCompare(b.symbol))[0]?.symbol;return !!r3&&r3===r6&&sig.selectedSymbols[0]===r3;}
function sale(l:Ledger,p:PositionState,px:number,date:string){const proceeds=p.shares*px*(1-PRODUCTION_STRATEGY.execution.transactionCost),basis=p.shares*p.entryPrice,pnl=proceeds-basis,y=date.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++;l.turnover+=proceeds;}
function taxCurve(curve:EquityPoint[],l:Ledger){const years=[...new Set(curve.map(p=>p.date.slice(0,4)))],ty:Record<string,number>={};let carry:{y:number,a:number}[]=[];for(const ys of years){const y=+ys;carry=carry.filter(x=>y-x.y<=3);let net=(l.gain[ys]??0)-(l.loss[ys]??0);if(net>0){for(const x of carry){const u=Math.min(net,x.a);net-=u;x.a-=u;if(net<=0)break}carry=carry.filter(x=>x.a>1e-12);ty[ys]=net*TAX}else if(net<0)carry.push({y,a:-net})}l.taxes=Object.values(ty).reduce((a,b)=>a+b,0);let e=curve[0]?.equity??1,pg=e,peak=e;const out:EquityPoint[]=[];for(let i=0;i<curve.length;i++){const p=curve[i];if(i)e*=p.equity/pg;pg=p.equity;const n=curve[i+1];if((!n||n.date.slice(0,4)!==p.date.slice(0,4))&&(ty[p.date.slice(0,4)]??0)>0)e=Math.max(0,e-(ty[p.date.slice(0,4)]??0)*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);out.push({date:p.date,equity:e,drawdown:e/peak-1})}return out;}
function sim(hist:Record<string,PricePoint[]>,universe:UniverseMonth[],c75:boolean){const qqq=[...hist.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),dates=qqq.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(universe.map(u=>[u.asOf,u]));let st=initialEngineState(PRODUCTION_STRATEGY),hits=0;const curve:EquityPoint[]=[],l:Ledger={gain:{},loss:{},taxes:0,sales:0,turnover:0};for(let i=0;i<dates.length;i++){const date=dates[i];if(date<PRODUCTION_STRATEGY.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),u=um.get(date);let sig=u?buildMonthlySignal({universe:u,histories:hist,qqq,nextSessionDate:next,config:PRODUCTION_STRATEGY}):null;if(sig&&c75&&sig.selectedSymbols.length===2&&consensus(sig)){sig={...sig,targetWeights:[.75,.25]};hits++;}const sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));const before=structuredClone(st);st=transitionDay(st,{date,prices,qqqHistoryThroughClose:qqq.slice(0,(idx.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},PRODUCTION_STRATEGY);if(before.currentPositions.length&&((before.nextAction.type==='SELL_ALL_NEXT_OPEN'||before.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN')&&before.nextAction.executionDate===date)){for(const p of before.currentPositions)sale(l,p,prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice,date)}curve.push({date,equity:st.currentEquity,drawdown:st.drawdown})}return{curve,afterTax:taxCurve(curve,l),ledger:l,hits};}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8')) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8')) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),b=sim(market.histories,u,false),c=sim(market.histories,u,true);const pack=(id:string,x:ReturnType<typeof sim>)=>({id,gross:performanceStats(x.curve),afterTax:performanceStats(x.afterTax),taxPaidApprox:x.ledger.taxes,sales:x.ledger.sales,turnover:x.ledger.turnover,hits:x.hits});const years=[2023,2024,2025,2026];const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,noLeverage:true,trueOOS:false,taxRate:TAX,warning:'Historical annual realized-P&L tax approximation with 3-year loss carryforward; not exact Japanese withholding/tax-lot timing.'},full:[pack('PRODUCTION',b),pack('PROD_CONS75',c)],confirmation:{base:performanceStats(sl(b.afterTax,'2023-01-01','2026-08-25')),cons75:performanceStats(sl(c.afterTax,'2023-01-01','2026-08-25'))},annual:years.map(y=>({year:y,base:performanceStats(sl(b.afterTax,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`)),cons75:performanceStats(sl(c.afterTax,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))}))};const d=path.join(process.cwd(),'data/research/consensus75-tax');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});