import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import type { EngineState } from "../src/lib/strategy/state-machine";
import type { MonthlySignal, PricePoint, StrategyConfig, UniverseMonth } from "../src/lib/types";

type Market={histories:Record<string,PricePoint[]>}; type UF={history:UniverseMonth[]}; type Rng=()=>number;
type Mode="baseline"|"relative20"|"triggerLike";
const PATHS=Number(process.env.CPCM_EVENT_AWARE_PATHS??100), YEARS=5, H=YEARS*252, WARM=252, BLOCK=20, RADIUS=126, SEED=20260825;
const cfg=PRODUCTION_STRATEGY as StrategyConfig;
const variants:{label:string;mode:Mode}[]=[{label:"baseline",mode:"baseline"},{label:"relative20",mode:"relative20"},{label:"triggerLike",mode:"triggerLike"}];
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
const sd=(x:number[])=>{const m=avg(x);return x.length?Math.sqrt(avg(x.map(v=>(v-m)**2))):0};
const pct=(x:number[],p:number)=>{if(!x.length)return null;const a=[...x].sort((u,v)=>u-v),q=(a.length-1)*p,l=Math.floor(q),h=Math.ceil(q),w=q-l;return a[l]*(1-w)+a[h]*w};
function rng32(seed:number):Rng{let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function latestU(us:UniverseMonth[],d:string){let a=us[0];for(const u of us){if(u.asOf<=d)a=u;else break}return a}
const score=(r3:number,r6:number)=>cfg.momentum.threeMonth*r3+cfg.momentum.sixMonth*r6;
function makeSignal(date:string,next:string|null,u:UniverseMonth,monthly:Map<string,number[]>):MonthlySignal{
 const q=monthly.get("QQQ")??[],ret=(x:number[],n:number)=>x.length>n?x.at(-1)!/x.at(-(n+1))!-1:null,q1=ret(q,1),q3=ret(q,3),q6=ret(q,6),qs=q1==null||q3==null||q6==null?null:score(q3,q6),ma=q.slice(-cfg.market.qqqMonthlyMaMonths),risk=ma.length===cfg.market.qqqMonthlyMaMonths&&q.at(-1)!>avg(ma),c:any[]=[];
 for(const m of u.symbols){const x=monthly.get(m.symbol)??[],r1=ret(x,1),r3=ret(x,3),r6=ret(x,6);if(r1==null||r3==null||r6==null||qs==null){c.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:null,qqqScore:qs,scoreSpread:null,eligible:false,exclusionReason:"INSUFFICIENT_PRICE_HISTORY",rank:null});continue}const s=score(r3,r6),reason=r1>=cfg.momentum.surgeLimit?"ONE_MONTH_SURGE":cfg.momentum.requireAboveQqqScore&&s<=qs?"NOT_ABOVE_QQQ":null;c.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:s,qqqScore:qs,scoreSpread:s-qs,eligible:!reason,exclusionReason:reason,rank:null})}
 const e=c.filter(x=>x.eligible&&x.score!=null).sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol));e.forEach((x,i)=>x.rank=i+1);const chosen=risk?e.slice(0,cfg.selection.topN):[],valid=chosen.length===cfg.selection.topN,d=sd(e.map(x=>x.score)),zg=valid&&d>0?(chosen[0].score-chosen[1].score)/d:valid?0:null,conc=zg!=null&&zg>=cfg.allocation.concentrationZGap,w=Math.min(cfg.allocation.maxTop1Weight,conc?cfg.allocation.concentratedTop1Weight:cfg.allocation.baseTop1Weight);
 return {strategyId:cfg.strategyId,signalMonth:date.slice(0,7),signalDate:date,executionDate:next,marketRiskOn:risk,qqqClose:q.at(-1)??null,qqqMonthlyMa:ma.length===cfg.market.qqqMonthlyMaMonths?avg(ma):null,qqqScore:qs,universe:u.symbols.map(x=>x.symbol),candidates:c,selectedSymbols:valid?chosen.map(x=>x.symbol):[],targetWeights:valid?[w,1-w]:[],zGap:zg,allocationMode:!valid?"CASH":conc?"70/30":"50/50"} as MonthlySignal;
}
function seriesRet(x:number[],n:number){return x.length>n?x.at(-1)!/x.at(-(n+1))!-1:null}
function srcRet(maps:Map<string,Map<string,PricePoint>>,dates:string[],s:string,k:number,n=20){if(k-n<0)return null;const a=maps.get(s)?.get(dates[k-n])?.close,b=maps.get(s)?.get(dates[k])?.close;return a&&b?b/a-1:null}
function basketSrcRet(maps:Map<string,Map<string,PricePoint>>,dates:string[],symbols:string[],weights:number[],k:number){if(symbols.length!==2||weights.length!==2)return null;const r0=srcRet(maps,dates,symbols[0],k),r1=srcRet(maps,dates,symbols[1],k);return r0==null||r1==null?null:weights[0]*r0+weights[1]*r1}
function ret(prices:Record<string,Record<string,PricePoint>>,target:string[],symbol:string,i0:number,i1:number){if(i0<0||i1>=target.length)return null;const a=prices[target[i0]]?.[symbol]?.close,b=prices[target[i1]]?.[symbol]?.close;return a&&b?b/a-1:null}
function basketRet(prices:Record<string,Record<string,PricePoint>>,target:string[],symbols:string[],weights:number[],i0:number,i1:number){if(symbols.length!==2||weights.length!==2||i0<0||i1>=target.length)return null;const a=ret(prices,target,symbols[0],i0,i1),b=ret(prices,target,symbols[1],i0,i1);return a==null||b==null?null:weights[0]*a+weights[1]*b}
function runEvents(target:string[],prices:Record<string,Record<string,PricePoint>>,signals:Record<string,MonthlySignal>){let st=initialEngineState(cfg),qh:PricePoint[]=[];const events:any[]=[];for(let i=0;i<target.length;i++){const d=target[i],next=target[i+1]??null,pp=prices[d]??{};if(pp.QQQ)qh.push(pp.QQQ);if(i===WARM)st=initialEngineState(cfg);if(i<WARM)continue;const before=structuredClone(st),syms=before.currentPositions.map(p=>p.symbol),ws=before.currentPositions.map(p=>p.targetWeight);st=transitionDay(st,{date:d,prices:pp,qqqHistoryThroughClose:qh,monthlySignal:signals[d]??null,nextSessionDate:next},cfg);let type:string|null=null;if(before.state==="INVESTED"&&st.state==="LOCKED_STOP")type="stop";else if(before.state==="INVESTED"&&st.state==="LOCKED_CIRCUIT")type="circuit";if(type&&syms.length===2)events.push({type,basket:{p1_5:basketRet(prices,target,syms,ws,i,i+5),p1_10:basketRet(prices,target,syms,ws,i,i+10),p11_20:basketRet(prices,target,syms,ws,i+10,i+20)},qqq:{p1_5:ret(prices,target,"QQQ",i,i+5),p1_10:ret(prices,target,"QQQ",i,i+10),p11_20:ret(prices,target,"QQQ",i+10,i+20)}})}return events}
function summarizeEvents(events:any[]){const o:any={};for(const type of ["stop","circuit"]){const e=events.filter(x=>x.type===type),one=(obj:string,key:string)=>{const z=e.map(x=>x[obj]?.[key]).filter((v:any):v is number=>Number.isFinite(v));return{n:z.length,mean:avg(z)}};o[type]={n:e.length,basket:{p1_5:one("basket","p1_5"),p1_10:one("basket","p1_10"),p11_20:one("basket","p11_20")},qqq:{p1_5:one("qqq","p1_5"),p1_10:one("qqq","p1_10"),p11_20:one("qqq","p11_20")}}}return o}
function aggregate(rows:any[]){const o:any={};for(const type of ["stop","circuit"]){o[type]={};for(const obj of ["basket","qqq"]){o[type][obj]={};for(const key of ["p1_5","p1_10","p11_20"]){const z=rows.map(r=>r[type][obj][key].mean).filter((v:any):v is number=>Number.isFinite(v));o[type][obj][key]={median:pct(z,.5),p05:pct(z,.05),p95:pct(z,.95)}}}const n=rows.map(r=>r[type].n);o[type].eventCount={median:pct(n,.5),p05:pct(n,.05),p95:pct(n,.95)}}return o}
function marketStats(prices:Record<string,Record<string,PricePoint>>,target:string[]){const q=target.slice(WARM).map(d=>prices[d]?.QQQ?.close).filter((v):v is number=>!!v),r:number[]=[];for(let i=1;i<q.length;i++)r.push(q[i]/q[i-1]-1);const r20:number[]=[];for(let i=20;i<q.length;i++)r20.push(q[i]/q[i-20]-1);let peak=q[0]??1,dd=0;for(const v of q){peak=Math.max(peak,v);dd=Math.min(dd,v/peak-1)}return{dailySd:sd(r),r20p05:pct(r20,.05),r20Median:pct(r20,.5),r20p95:pct(r20,.95),maxDD:dd}}
async function main(){
 const market=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8")) as Market,uf=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8")) as UF,us=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),hist=market.histories,dates=(hist.QQQ??[]).filter(p=>p.date>=us[0].asOf).map(p=>p.date),target=dates.slice(-(WARM+H)),symbols=[...new Set(["QQQ",...us.flatMap(u=>u.symbols.map(x=>x.symbol))])],maps=new Map(symbols.map(s=>[s,new Map((hist[s]??[]).map(p=>[p.date,p]))])),idx=new Map(dates.map((d,i)=>[d,i]));
 const qMap=new Map((hist.QQQ??[]).map(p=>[p.date,p]));const feats=dates.map((_,i)=>{if(i<60)return null;const closes=dates.slice(i-60,i+1).map(d=>qMap.get(d)?.close).filter((x):x is number=>x!=null),rr:number[]=[];for(let j=i-19;j<=i;j++){const a=qMap.get(dates[j])?.close,b=qMap.get(dates[j-1])?.close;if(a&&b)rr.push(a/b-1)}return closes.length===61&&rr.length===20?{trend:closes.at(-1)!/closes[0]-1,vol:sd(rr)}:null});
 const histPrices:Record<string,Record<string,PricePoint>>={};for(const d of target){const day:Record<string,PricePoint>={};for(const s of symbols){const p=maps.get(s)?.get(d);if(p)day[s]=p}histPrices[d]=day}
 const buildSignalsFull=(prices:Record<string,Record<string,PricePoint>>)=>{const monthly=new Map<string,number[]>(symbols.map(s=>[s,[]])),sig:Record<string,MonthlySignal>={};for(let i=0;i<target.length;i++){const d=target[i],next=target[i+1]??null,me=!next||next.slice(0,7)!==d.slice(0,7);if(me){for(const s of symbols){const c=prices[d]?.[s]?.close;if(c)monthly.get(s)!.push(c)}sig[d]=makeSignal(d,next,latestU(us,d),monthly)}}return sig};
 const historical={events:summarizeEvents(runEvents(target,histPrices,buildSignalsFull(histPrices))),market:marketStats(histPrices,target)};
 const out:any={generatedAt:new Date().toISOString(),paths:PATHS,seed:SEED,definitions:{relative20:"baseline QQQ distance + |synthetic Top2 20d relative return - donor same-Top2 20d relative return|/0.10",triggerLike:"if portfolio DD<=-10% or any position loss<=-12%, require donor same-Top2 20d return<=-5%; otherwise baseline"},historical,variants:{}};
 for(let vi=0;vi<variants.length;vi++){const variant=variants[vi],rng=rng32(SEED+vi*100003),summaries:any[]=[],mstats:any[]=[];
  for(let p=0;p<PATHS;p++){const syn=new Map(symbols.map(s=>[s,100])),synHist=new Map(symbols.map(s=>[s,[] as number[]])),prices:Record<string,Record<string,PricePoint>>={},monthly=new Map<string,number[]>(symbols.map(s=>[s,[]])),signals:Record<string,MonthlySignal>={},qh:PricePoint[]=[];let st:EngineState=initialEngineState(cfg);
   for(let ti=0;ti<target.length;){const base=idx.get(target[ti])!,f=feats[base];let donor=base;const pos=st.currentPositions,ps=pos.map(x=>x.symbol),pw=pos.map(x=>x.targetWeight),q20=seriesRet(synHist.get("QQQ")!,20);let curBasket20:number|null=null;if(ps.length===2){const a=seriesRet(synHist.get(ps[0])!,20),b=seriesRet(synHist.get(ps[1])!,20);if(a!=null&&b!=null)curBasket20=pw[0]*a+pw[1]*b}
    if(f){let cand:{k:number;dist:number}[]=[];for(let k=Math.max(61,base-RADIUS);k<=Math.min(dates.length-BLOCK-1,base+RADIUS);k++){const g=feats[k];if(!g)continue;if(Math.sign(g.trend)!==Math.sign(f.trend)&&Math.abs(f.trend)>.03)continue;let dist=Math.abs(g.trend-f.trend)/.10+Math.abs(g.vol-f.vol)/.01;const db=ps.length===2?basketSrcRet(maps,dates,ps,pw,k):null;const dq=srcRet(maps,dates,"QQQ",k);if(variant.mode==="relative20"&&curBasket20!=null&&q20!=null&&db!=null&&dq!=null)dist+=Math.abs((db-dq)-(curBasket20-q20))/.10;if(variant.mode==="triggerLike"&&ps.length===2){const near=st.drawdown<=-.10||pos.some(x=>(x.currentPrice??x.entryPrice)/x.entryPrice-1<=-.12);if(near&&(db==null||db>-.05))continue}cand.push({k,dist})}cand.sort((a,b)=>a.dist-b.dist||a.k-b.k);const pool=cand.slice(0,20);if(pool.length)donor=pool[Math.floor(rng()*pool.length)].k}
    for(let j=0;j<BLOCK&&ti<target.length;j++,ti++){const d=target[ti],next=target[ti+1]??null,src=dates[Math.min(donor+j,dates.length-1)],srcPrev=dates[Math.max(0,donor+j-1)],targetPrev=ti>0?target[ti-1]:null,day:Record<string,PricePoint>={};for(const s of symbols){let a=maps.get(s)?.get(src),b=maps.get(s)?.get(srcPrev);if(!a||!b||a.open<=0||b.close<=0){const ta=maps.get(s)?.get(d),tb=targetPrev?maps.get(s)?.get(targetPrev):undefined;if(ta&&tb&&ta.open>0&&tb.close>0){a=ta;b=tb}else continue}const pc=syn.get(s)!,o=pc*(a.open/b.close),c=o*(a.close/a.open);syn.set(s,c);synHist.get(s)!.push(c);day[s]={date:d,open:o,high:Math.max(o,c),low:Math.min(o,c),close:c} as PricePoint}prices[d]=day;if(day.QQQ)qh.push(day.QQQ);const me=!next||next.slice(0,7)!==d.slice(0,7);let ms:MonthlySignal|null=null;if(me){for(const s of symbols){const c=day[s]?.close;if(c)monthly.get(s)!.push(c)}ms=makeSignal(d,next,latestU(us,d),monthly);signals[d]=ms}if(ti===WARM)st=initialEngineState(cfg);if(ti>=WARM)st=transitionDay(st,{date:d,prices:day,qqqHistoryThroughClose:qh,monthlySignal:ms,nextSessionDate:next},cfg)}}
   summaries.push(summarizeEvents(runEvents(target,prices,signals)));mstats.push(marketStats(prices,target));if((p+1)%25===0)console.log(`${variant.label} ${p+1}/${PATHS}`)}
  const ms=(key:string)=>{const z=mstats.map(x=>x[key]).filter((v:any):v is number=>Number.isFinite(v));return{median:pct(z,.5),p05:pct(z,.05),p95:pct(z,.95)}};out.variants[variant.label]={events:aggregate(summaries),market:{dailySd:ms("dailySd"),r20p05:ms("r20p05"),r20Median:ms("r20Median"),r20p95:ms("r20p95"),maxDD:ms("maxDD")}};
 }
 await mkdir(resolve("data/research/cpcm-validity"),{recursive:true});await writeFile(resolve("data/research/cpcm-validity/event-aware-variants.json"),JSON.stringify(out,null,2));console.log("EVENT_AWARE_JSON="+JSON.stringify(out));
}
main().catch(e=>{console.error(e);process.exit(1)});