import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import type { MonthlySignal, PricePoint, StrategyConfig, UniverseMonth } from "../src/lib/types";

type Market = { histories: Record<string, PricePoint[]> };
type UF = { history: UniverseMonth[] };
type Rng = () => number;
const PATHS = Number(process.env.CPCM_ATTR_PATHS ?? 200);
const YEARS = 5, H = YEARS * 252, WARM = 252, BLOCK = 20, RADIUS = 126, SEED = 20260825;
const prod = PRODUCTION_STRATEGY as StrategyConfig;
const r5 = { ...PRODUCTION_STRATEGY, recovery: { ...PRODUCTION_STRATEGY.recovery, confirmationDays: 5 } } as StrategyConfig;
const avg = (x:number[]) => x.length ? x.reduce((a,b)=>a+b,0)/x.length : 0;
const sd = (x:number[]) => { const m=avg(x); return x.length ? Math.sqrt(avg(x.map(v=>(v-m)**2))) : 0; };
const pct = (x:number[],p:number) => { if(!x.length) return null; const a=[...x].sort((u,v)=>u-v),q=(a.length-1)*p,l=Math.floor(q),h=Math.ceil(q),w=q-l; return a[l]*(1-w)+a[h]*w; };
function rng32(seed:number):Rng { let a=seed>>>0; return()=>{ a|=0; a=a+0x6D2B79F5|0; let t=Math.imul(a^a>>>15,1|a); t=t+Math.imul(t^t>>>7,61|t)^t; return((t^t>>>14)>>>0)/4294967296; }; }
function latestU(us:UniverseMonth[],d:string){ let a=us[0]; for(const u of us){ if(u.asOf<=d)a=u; else break; } return a; }
const score=(r3:number,r6:number,cfg:StrategyConfig)=>cfg.momentum.threeMonth*r3+cfg.momentum.sixMonth*r6;
function makeSignal(date:string,next:string|null,u:UniverseMonth,monthly:Map<string,number[]>,cfg:StrategyConfig):MonthlySignal{
  const q=monthly.get("QQQ")??[], ret=(x:number[],n:number)=>x.length>n?x.at(-1)!/x.at(-(n+1))!-1:null;
  const q1=ret(q,1),q3=ret(q,3),q6=ret(q,6),qs=q1==null||q3==null||q6==null?null:score(q3,q6,cfg);
  const ma=q.slice(-cfg.market.qqqMonthlyMaMonths),risk=ma.length===cfg.market.qqqMonthlyMaMonths&&q.at(-1)!>avg(ma),c:any[]=[];
  for(const m of u.symbols){ const x=monthly.get(m.symbol)??[],r1=ret(x,1),r3=ret(x,3),r6=ret(x,6); if(r1==null||r3==null||r6==null||qs==null){c.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:null,qqqScore:qs,scoreSpread:null,eligible:false,exclusionReason:"INSUFFICIENT_PRICE_HISTORY",rank:null});continue;} const s=score(r3,r6,cfg),reason=r1>=cfg.momentum.surgeLimit?"ONE_MONTH_SURGE":cfg.momentum.requireAboveQqqScore&&s<=qs?"NOT_ABOVE_QQQ":null; c.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:s,qqqScore:qs,scoreSpread:s-qs,eligible:!reason,exclusionReason:reason,rank:null}); }
  const e=c.filter(x=>x.eligible&&x.score!=null).sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol)); e.forEach((x,i)=>x.rank=i+1); const chosen=risk?e.slice(0,cfg.selection.topN):[],valid=chosen.length===cfg.selection.topN,d=sd(e.map(x=>x.score)),zg=valid&&d>0?(chosen[0].score-chosen[1].score)/d:valid?0:null,conc=zg!=null&&zg>=cfg.allocation.concentrationZGap,w=Math.min(cfg.allocation.maxTop1Weight,conc?cfg.allocation.concentratedTop1Weight:cfg.allocation.baseTop1Weight);
  return {strategyId:cfg.strategyId,signalMonth:date.slice(0,7),signalDate:date,executionDate:next,marketRiskOn:risk,qqqClose:q.at(-1)??null,qqqMonthlyMa:ma.length===cfg.market.qqqMonthlyMaMonths?avg(ma):null,qqqScore:qs,universe:u.symbols.map(x=>x.symbol),candidates:c,selectedSymbols:valid?chosen.map(x=>x.symbol):[],targetWeights:valid?[w,1-w]:[],zGap:zg,allocationMode:!valid?"CASH":conc?"70/30":"50/50"} as MonthlySignal;
}
function triggerClass(s:string|null){ if(!s)return"unknown"; const z=s.toLowerCase(); if(z.includes("10m ma")||z.includes("riskoff"))return"market"; if(z.includes("stop"))return"stop"; if(z.includes("circuit"))return"circuit"; return"other"; }
function summarizeExclusive(rows:any[]){
  const ex=rows.filter(x=>x.r5Invested&&!x.prodInvested),r=ex.map(x=>x.r5Ret),by:any={};
  for(const k of ["market","stop","circuit","other","unknown"]){ const z=ex.filter(x=>x.trigger===k).map(x=>x.r5Ret); by[k]={days:z.length,meanDaily:avg(z),logContribution:z.reduce((s,v)=>s+Math.log1p(v),0)}; }
  const boundary=ex.filter(x=>x.blockAge!=null&&x.blockAge<5).map(x=>x.r5Ret),interior=ex.filter(x=>x.blockAge==null||x.blockAge>=5).map(x=>x.r5Ret);
  return {exclusiveDays:ex.length,meanDaily:avg(r),medianDaily:pct(r,.5),positiveRate:r.length?r.filter(x=>x>0).length/r.length:null,logContribution:r.reduce((s,v)=>s+Math.log1p(v),0),byTrigger:by,boundaryFirst5:{days:boundary.length,meanDaily:avg(boundary),logContribution:boundary.reduce((s,v)=>s+Math.log1p(v),0)},interior:{days:interior.length,meanDaily:avg(interior),logContribution:interior.reduce((s,v)=>s+Math.log1p(v),0)}};
}
function runPair(target:string[],prices:Record<string,Record<string,PricePoint>>,signals:Record<string,MonthlySignal>,ages:(number|null)[]){
  let ps=initialEngineState(prod),rs=initialEngineState(r5),pq:PricePoint[]=[],rq:PricePoint[]=[],pPrev=1,rPrev=1; const rows:any[]=[];
  for(let i=0;i<target.length;i++){ const d=target[i],next=target[i+1]??null,pp=prices[d]??{}; if(pp.QQQ){pq.push(pp.QQQ);rq.push(pp.QQQ);} if(i===WARM){ps=initialEngineState(prod);rs=initialEngineState(r5);pPrev=1;rPrev=1;} if(i>=WARM){ ps=transitionDay(ps,{date:d,prices:pp,qqqHistoryThroughClose:pq,monthlySignal:signals[d]??null,nextSessionDate:next},prod); rs=transitionDay(rs,{date:d,prices:pp,qqqHistoryThroughClose:rq,monthlySignal:signals[d]??null,nextSessionDate:next},r5); const pRet=ps.currentEquity/(pPrev||1)-1,rRet=rs.currentEquity/(rPrev||1)-1; rows.push({prodInvested:ps.currentPositions.length>0,r5Invested:rs.currentPositions.length>0,pRet,r5Ret:rRet,trigger:triggerClass(ps.lastTrigger),blockAge:ages[i]}); pPrev=ps.currentEquity;rPrev=rs.currentEquity; } }
  return {rows,prodFinal:ps.currentEquity,r5Final:rs.currentEquity,pairedCagr:rs.currentEquity**(1/YEARS)-ps.currentEquity**(1/YEARS)};
}
async function main(){
  const market=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8")) as Market,uf=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8")) as UF,us=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),hist=market.histories,dates=(hist.QQQ??[]).filter(p=>p.date>=us[0].asOf).map(p=>p.date),target=dates.slice(-(WARM+H)),symbols=[...new Set(["QQQ",...us.flatMap(u=>u.symbols.map(x=>x.symbol))])],maps=new Map(symbols.map(s=>[s,new Map((hist[s]??[]).map(p=>[p.date,p]))])),idx=new Map(dates.map((d,i)=>[d,i]));
  const buildSignals=(prices:Record<string,Record<string,PricePoint>>)=>{ const monthly=new Map<string,number[]>(symbols.map(s=>[s,[]])),signals:Record<string,MonthlySignal>={}; for(let i=0;i<target.length;i++){ const d=target[i],next=target[i+1]??null,day=prices[d]??{},me=!next||next.slice(0,7)!==d.slice(0,7); if(me){ for(const s of symbols)if(day[s])monthly.get(s)!.push(day[s].close); signals[d]=makeSignal(d,next,latestU(us,d),monthly,prod); } } return signals; };
  const histPrices:Record<string,Record<string,PricePoint>>={}; for(const d of target){ const day:Record<string,PricePoint>={}; for(const s of symbols){const p=maps.get(s)?.get(d);if(p)day[s]=p;} histPrices[d]=day; } const histRun=runPair(target,histPrices,buildSignals(histPrices),target.map(()=>null));
  const qMap=new Map((hist.QQQ??[]).map(p=>[p.date,p])); const feats=dates.map((_,i)=>{ if(i<60)return null; const closes=dates.slice(i-60,i+1).map(d=>qMap.get(d)?.close).filter((x):x is number=>x!=null),rr:number[]=[]; for(let j=i-19;j<=i;j++){const a=qMap.get(dates[j])?.close,b=qMap.get(dates[j-1])?.close;if(a&&b)rr.push(a/b-1);} return closes.length===61&&rr.length===20?{trend:closes.at(-1)!/closes[0]-1,vol:sd(rr)}:null; });
  const rng=rng32(SEED),paths:any[]=[];
  for(let p=0;p<PATHS;p++){ const syn=new Map(symbols.map(s=>[s,100])),prices:Record<string,Record<string,PricePoint>>={},ages:(number|null)[]=Array(target.length).fill(null); for(let ti=0;ti<target.length;){ const base=idx.get(target[ti])!,f=feats[base]; let donor=base; if(f){ const cand:{k:number;dist:number}[]=[]; for(let k=Math.max(61,base-RADIUS);k<=Math.min(dates.length-BLOCK-1,base+RADIUS);k++){const g=feats[k];if(!g)continue;if(Math.sign(g.trend)!==Math.sign(f.trend)&&Math.abs(f.trend)>.03)continue;cand.push({k,dist:Math.abs(g.trend-f.trend)/.10+Math.abs(g.vol-f.vol)/.01});} cand.sort((a,b)=>a.dist-b.dist||a.k-b.k); const pool=cand.slice(0,20); if(pool.length)donor=pool[Math.floor(rng()*pool.length)].k; } for(let j=0;j<BLOCK&&ti<target.length;j++,ti++){ const d=target[ti],src=dates[Math.min(donor+j,dates.length-1)],srcPrev=dates[Math.max(0,donor+j-1)],targetPrev=ti>0?target[ti-1]:null,day:Record<string,PricePoint>={}; ages[ti]=j; for(const s of symbols){ let a=maps.get(s)?.get(src),b=maps.get(s)?.get(srcPrev); if(!a||!b||a.open<=0||b.close<=0){const ta=maps.get(s)?.get(d),tb=targetPrev?maps.get(s)?.get(targetPrev):undefined;if(ta&&tb&&ta.open>0&&tb.close>0){a=ta;b=tb}else continue;} const pc=syn.get(s)!,o=pc*(a.open/b.close),c=o*(a.close/a.open); syn.set(s,c); day[s]={date:d,open:o,high:Math.max(o,c),low:Math.min(o,c),close:c} as PricePoint; } prices[d]=day; } } const run=runPair(target,prices,buildSignals(prices),ages); paths.push({exclusive:summarizeExclusive(run.rows),pairedCagr:run.pairedCagr}); if((p+1)%25===0)console.log(`completed ${p+1}/${PATHS}`); }
  const h=summarizeExclusive(histRun.rows),exDays=paths.map(x=>x.exclusive.exclusiveDays),meanD=paths.map(x=>x.exclusive.meanDaily),logC=paths.map(x=>x.exclusive.logContribution),pair=paths.map(x=>x.pairedCagr),boundaryShare=paths.map(x=>x.exclusive.exclusiveDays?x.exclusive.boundaryFirst5.days/x.exclusive.exclusiveDays:0),trig:any={};
  for(const k of ["market","stop","circuit","other","unknown"]){ const days=paths.map(x=>x.exclusive.byTrigger[k].days),logs=paths.map(x=>x.exclusive.byTrigger[k].logContribution); trig[k]={medianDays:pct(days,.5),medianLogContribution:pct(logs,.5)}; }
  const out={generatedAt:new Date().toISOString(),paths:PATHS,baselineGenerator:{block:BLOCK,radius:RADIUS,mode:"actual-target",seed:SEED},historical:{exclusive:h,productionFinalWealth:histRun.prodFinal,recovery5FinalWealth:histRun.r5Final,pairedCagr:histRun.pairedCagr},cpcm:{exclusiveDays:{p05:pct(exDays,.05),median:pct(exDays,.5),p95:pct(exDays,.95)},exclusiveMeanDaily:{p05:pct(meanD,.05),median:pct(meanD,.5),p95:pct(meanD,.95)},exclusiveLogContribution:{p05:pct(logC,.05),median:pct(logC,.5),p95:pct(logC,.95)},pairedCagr:{p05:pct(pair,.05),median:pct(pair,.5),p95:pct(pair,.95),winRate:pair.filter(x=>x>0).length/PATHS},boundaryFirst5Share:{p05:pct(boundaryShare,.05),median:pct(boundaryShare,.5),p95:pct(boundaryShare,.95)},byTrigger:trig}};
  await mkdir(resolve("data/research/cpcm-validity"),{recursive:true}); await writeFile(resolve("data/research/cpcm-validity/recovery-gap-attribution.json"),JSON.stringify(out,null,2)); console.log("ATTRIBUTION_JSON="+JSON.stringify(out));
}
main().catch(e=>{console.error(e);process.exit(1)});