import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { PricePoint } from "../src/lib/types";

type Market={histories:Record<string,PricePoint[]>};
type Feature={trend:number,vol:number};
type Mode="actual-target"|"synthetic-state"|"unconditional-local";
const PATHS=Number(process.env.CPCM_AUDIT_PATHS??500), BLOCK=20, RADIUS=126, WARM=252, H=5*252, SEED=20260825;
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:NaN;
const sd=(x:number[])=>{const m=avg(x);return x.length?Math.sqrt(avg(x.map(v=>(v-m)**2))):NaN};
const pct=(x:number[],p:number)=>{const a=[...x].filter(Number.isFinite).sort((u,v)=>u-v);if(!a.length)return NaN;const q=(a.length-1)*p,l=Math.floor(q),h=Math.ceil(q),w=q-l;return a[l]*(1-w)+a[h]*w};
function rng32(seed:number){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function ac1(x:number[]){if(x.length<3)return NaN;const a=x.slice(1),b=x.slice(0,-1),ma=avg(a),mb=avg(b);const num=avg(a.map((v,i)=>(v-ma)*(b[i]-mb))),den=Math.sqrt(avg(a.map(v=>(v-ma)**2))*avg(b.map(v=>(v-mb)**2)));return den?num/den:0}
function maxDd(closes:number[]){let peak=closes[0]??1,dd=0;for(const v of closes){peak=Math.max(peak,v);dd=Math.min(dd,v/peak-1)}return dd}
function featureFromCloses(xs:number[]):Feature|null{if(xs.length<61)return null;const z=xs.slice(-61),rets=[];for(let i=z.length-20;i<z.length;i++)rets.push(z[i]/z[i-1]-1);return{trend:z.at(-1)!/z[0]-1,vol:sd(rets)}}
function metrics(closes:number[]){const lr:number[]=[];for(let i=1;i<closes.length;i++)lr.push(Math.log(closes[i]/closes[i-1]));const r20:number[]=[];for(let i=20;i<closes.length;i++)r20.push(closes[i]/closes[i-20]-1);const t60:number[]=[];for(let i=60;i<closes.length;i++)t60.push(closes[i]/closes[i-60]-1);let flips=0;for(let i=1;i<t60.length;i++)if(Math.sign(t60[i])!==Math.sign(t60[i-1]))flips++;return{dailyLogMean:avg(lr),dailyLogSd:sd(lr),dailyLag1:ac1(lr),r20p05:pct(r20,.05),r20p50:pct(r20,.5),r20p95:pct(r20,.95),trend60p05:pct(t60,.05),trend60p50:pct(t60,.5),trend60p95:pct(t60,.95),trend60Positive:t60.filter(x=>x>0).length/Math.max(1,t60.length),trendSignFlipsPerYear:flips/(closes.length/252),maxDd:maxDd(closes)} }
function medObj(rows:any[]){const keys=Object.keys(rows[0]??{});return Object.fromEntries(keys.map(k=>[k,pct(rows.map(r=>r[k]).filter(Number.isFinite),.5)]))}
async function main(){const market=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8")) as Market;const q=(market.histories.QQQ??[]).filter(p=>p.close>0);if(q.length<WARM+H+RADIUS+61)throw new Error("Insufficient QQQ history");const dates=q.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i])),target=q.slice(-(WARM+H)),targetStart=idx.get(target[0].date)!;
 const actualFeatures=q.map((_,i)=>i<60?null:featureFromCloses(q.slice(0,i+1).map(p=>p.close)));
 const historicalEval=target.slice(WARM).map(p=>p.close);const historical=metrics(historicalEval);
 const modes:Mode[]=["actual-target","synthetic-state","unconditional-local"];const out:any={generatedAt:new Date().toISOString(),paths:PATHS,block:BLOCK,radius:RADIUS,seed:SEED,historical,methodNotes:{"actual-target":"Current CPCM: donor similarity is measured against actual historical QQQ state at the target calendar date.","synthetic-state":"Audit variant: donor similarity is measured against the synthetic QQQ path's own trailing 60d trend and 20d volatility.","unconditional-local":"Audit variant: donor is sampled locally within +/-126 trading days without trend/vol conditioning."},modes:{}};
 for(const mode of modes){const rng=rng32(SEED);const rows:any[]=[];let selfEligible=0,selfChosen=0,poolObs=0,dist1:number[]=[],dist20:number[]=[],uniqueDonors:number[]=[];
  for(let path=0;path<PATHS;path++){let syn=100;const closes:number[]=[syn];const donors:number[]=[];for(let ti=1;ti<target.length;){const baseIdx=targetStart+ti;let f:Feature|null=null;if(mode==="actual-target")f=actualFeatures[baseIdx];else if(mode==="synthetic-state")f=featureFromCloses(closes);let pool:number[]=[];let ranked:{k:number,dist:number}[]=[];
    for(let k=Math.max(61,baseIdx-RADIUS);k<=Math.min(q.length-BLOCK-1,baseIdx+RADIUS);k++){if(mode==="unconditional-local"){ranked.push({k,dist:0});continue}const g=actualFeatures[k];if(!f||!g)continue;if(Math.sign(g.trend)!==Math.sign(f.trend)&&Math.abs(f.trend)>.03)continue;const dist=Math.abs(g.trend-f.trend)/.10+Math.abs(g.vol-f.vol)/.01;ranked.push({k,dist})}
    if(mode==="unconditional-local")pool=ranked.map(x=>x.k);else{ranked.sort((a,b)=>a.dist-b.dist);pool=ranked.slice(0,Math.min(20,ranked.length)).map(x=>x.k);if(ranked.length){dist1.push(ranked[0].dist);dist20.push(ranked[Math.min(19,ranked.length-1)].dist)}}
    if(!pool.length)pool=[baseIdx];poolObs++;if(pool.includes(baseIdx))selfEligible++;const donor=pool[Math.floor(rng()*pool.length)];if(donor===baseIdx)selfChosen++;donors.push(donor);
    for(let j=0;j<BLOCK&&ti<target.length;j++,ti++){const si=Math.min(donor+j,q.length-1),sp=Math.max(0,si-1);syn*=q[si].close/q[sp].close;closes.push(syn)} }
   uniqueDonors.push(new Set(donors).size);rows.push(metrics(closes.slice(WARM)))}
  out.modes[mode]={median:medObj(rows),p05MaxDd:pct(rows.map(r=>r.maxDd),.05),p95MaxDd:pct(rows.map(r=>r.maxDd),.95),donorDiagnostics:{selfInPoolRate:selfEligible/Math.max(1,poolObs),selfChosenRate:selfChosen/Math.max(1,poolObs),medianNearestDistance:pct(dist1,.5),median20thDistance:pct(dist20,.5),medianUniqueDonorBlocks:pct(uniqueDonors,.5)}} }
 await mkdir(resolve("data/research/cpcm-validity"),{recursive:true});await writeFile(resolve("data/research/cpcm-validity/audit.json"),JSON.stringify(out,null,2));const a=out.modes["actual-target"].median,s=out.modes["synthetic-state"].median,u=out.modes["unconditional-local"].median;const md=`# CPCM Generator Validity Audit\n\nPaths: ${PATHS}, block=${BLOCK}, radius=${RADIUS}, seed=${SEED}.\n\n## Structural finding\nCurrent CPCM conditions each donor search on the **actual historical QQQ state at the target calendar date**, not on the synthetic path's own state. It is therefore a local perturbation around realized regime chronology, not a free-running forward market generator.\n\n## QQQ posterior-predictive diagnostics (median path)\n\n| Metric | Historical | Current CPCM | Synthetic-state conditioning | Unconditional local |\n|---|---:|---:|---:|---:|\n| Daily log-return sd | ${historical.dailyLogSd.toFixed(5)} | ${a.dailyLogSd.toFixed(5)} | ${s.dailyLogSd.toFixed(5)} | ${u.dailyLogSd.toFixed(5)} |\n| Lag-1 autocorr | ${historical.dailyLag1.toFixed(3)} | ${a.dailyLag1.toFixed(3)} | ${s.dailyLag1.toFixed(3)} | ${u.dailyLag1.toFixed(3)} |\n| 20d return p05 | ${(historical.r20p05*100).toFixed(2)}% | ${(a.r20p05*100).toFixed(2)}% | ${(s.r20p05*100).toFixed(2)}% | ${(u.r20p05*100).toFixed(2)}% |\n| 20d return p95 | ${(historical.r20p95*100).toFixed(2)}% | ${(a.r20p95*100).toFixed(2)}% | ${(s.r20p95*100).toFixed(2)}% | ${(u.r20p95*100).toFixed(2)}% |\n| 60d trend positive share | ${(historical.trend60Positive*100).toFixed(1)}% | ${(a.trend60Positive*100).toFixed(1)}% | ${(s.trend60Positive*100).toFixed(1)}% | ${(u.trend60Positive*100).toFixed(1)}% |\n| 60d sign flips/year | ${historical.trendSignFlipsPerYear.toFixed(2)} | ${a.trendSignFlipsPerYear.toFixed(2)} | ${s.trendSignFlipsPerYear.toFixed(2)} | ${u.trendSignFlipsPerYear.toFixed(2)} |\n| MaxDD | ${(historical.maxDd*100).toFixed(2)}% | ${(a.maxDd*100).toFixed(2)}% | ${(s.maxDd*100).toFixed(2)}% | ${(u.maxDd*100).toFixed(2)}% |\n\n## Donor diagnostics\n- Current CPCM self-date present in Top20 pool: ${(out.modes["actual-target"].donorDiagnostics.selfInPoolRate*100).toFixed(1)}%\n- Current CPCM exact self-block chosen: ${(out.modes["actual-target"].donorDiagnostics.selfChosenRate*100).toFixed(1)}%\n- Median nearest standardized distance: ${out.modes["actual-target"].donorDiagnostics.medianNearestDistance.toFixed(3)}\n- Median 20th standardized distance: ${out.modes["actual-target"].donorDiagnostics.median20thDistance.toFixed(3)}\n\n## Interpretation rule\nCPCM should be treated as meaningful for **local robustness comparison** only if it reproduces key QQQ stylized facts reasonably and candidate-strategy deltas remain directionally stable under generator variants. It should not be interpreted as an unconditional forecast distribution.\n`;await writeFile(resolve("data/research/cpcm-validity/README.md"),md);console.log("AUDIT_JSON="+JSON.stringify(out))}
main().catch(e=>{console.error(e);process.exit(1)});