import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay, type EngineState } from "../src/lib/strategy/state-machine";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import { performanceStats } from "../src/lib/backtest";
import type { EquityPoint, PositionState, PricePoint, UniverseMonth } from "../src/lib/types";

const TAX=0.20315;
type Variant={id:string; financing:number; exposure:(z:number|null)=>number};
const VARIANTS:Variant[]=[
 {id:"PRODUCTION",financing:0,exposure:()=>1},
 {id:"STRONG125_F5",financing:0.05,exposure:z=>z!=null&&z>=0.50?1.25:1},
 {id:"STRONG125_F8",financing:0.08,exposure:z=>z!=null&&z>=0.50?1.25:1},
 {id:"TIERED_F5",financing:0.05,exposure:z=>z==null?1:z<0.25?0.75:z>=0.50?1.25:1},
];
type Ledger={gain:Record<string,number>;loss:Record<string,number>;taxes:number;sales:number};
const clone=<T>(x:T):T=>structuredClone(x);
function recordSale(l:Ledger,p:PositionState,px:number,date:string){const proceeds=p.shares*px*(1-PRODUCTION_STRATEGY.execution.transactionCost);const pnl=proceeds-p.shares*p.entryPrice;const y=date.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++;}
function afterTax(curve:EquityPoint[],l:Ledger){if(!curve.length)return[];const ys=[...new Set(curve.map(p=>p.date.slice(0,4)))];const ty:Record<string,number>={};let carry:{y:number,a:number}[]=[];for(const s of ys){const y=+s;carry=carry.filter(x=>y-x.y<=3);let net=(l.gain[s]??0)-(l.loss[s]??0);if(net>0){for(const x of carry){const u=Math.min(net,x.a);net-=u;x.a-=u;if(net<=0)break}carry=carry.filter(x=>x.a>1e-12);ty[s]=net*TAX}else if(net<0)carry.push({y,a:-net})}l.taxes=Object.values(ty).reduce((a,b)=>a+b,0);let e=curve[0].equity,prev=curve[0].equity,peak=e;const out:EquityPoint[]=[];for(let i=0;i<curve.length;i++){const p=curve[i];if(i)e*=p.equity/prev;prev=p.equity;const n=curve[i+1];const t=ty[p.date.slice(0,4)]??0;if((!n||n.date.slice(0,4)!==p.date.slice(0,4))&&t>0)e=Math.max(0,e-t*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);out.push({date:p.date,equity:e,drawdown:e/peak-1})}return out}
function applyExposure(state:EngineState,prices:Record<string,PricePoint|undefined>,x:number,resetPeak:boolean){if(state.currentPositions.length!==2)return;const eq=state.cash+state.currentPositions.reduce((s,p)=>s+p.shares*(prices[p.symbol]?.open??p.currentPrice??p.entryPrice),0);if(eq<=0)return;for(const p of state.currentPositions)p.shares*=x;state.cash=eq*(1-x);state.currentEquity=state.cash+state.currentPositions.reduce((s,p)=>s+p.shares*(prices[p.symbol]?.open??p.currentPrice??p.entryPrice),0);if(resetPeak)state.portfolioPeak=state.currentEquity;else state.portfolioPeak=Math.max(state.portfolioPeak,state.currentEquity);state.drawdown=state.portfolioPeak>0?state.currentEquity/state.portfolioPeak-1:0;}
function sim(hist:Record<string,PricePoint[]>,universe:UniverseMonth[],v:Variant){const qqq=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date));const dates=qqq.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i]));const pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))]));const um=new Map(universe.map(u=>[u.asOf,u]));let state=initialEngineState(PRODUCTION_STRATEGY);const curve:EquityPoint[]=[];const ledger:Ledger={gain:{},loss:{},taxes:0,sales:0};let levDays=0,financingPaid=0;
 for(let i=0;i<dates.length;i++){const date=dates[i];if(date<PRODUCTION_STRATEGY.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date);if(state.cash<0&&v.financing>0){const c=(-state.cash)*v.financing/252;state.cash-=c;financingPaid+=c;levDays++;}
 const u=um.get(date),sig=u?buildMonthlySignal({universe:u,histories:hist,qqq,nextSessionDate:next,config:PRODUCTION_STRATEGY}):null;const sy=new Set(["QQQ",...state.currentPositions.map(p=>p.symbol),...(state.pendingSignal?.selectedSymbols??[]),...state.nextAction.symbols,...(sig?.selectedSymbols??[])]);const prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));const before=clone(state);const execBuy=(before.nextAction.type==="BUY_NEXT_OPEN"||before.nextAction.type==="MONTH_END_REBALANCE_NEXT_OPEN")&&before.nextAction.executionDate===date;const execExit=before.currentPositions.length>0&&(before.nextAction.type==="SELL_ALL_NEXT_OPEN"||before.nextAction.type==="MONTH_END_REBALANCE_NEXT_OPEN")&&before.nextAction.executionDate===date;if(execExit){for(const p of before.currentPositions){const px=prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice;recordSale(ledger,p,px,date)}}state=transitionDay(state,{date,prices,qqqHistoryThroughClose:qqq.slice(0,(idx.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},PRODUCTION_STRATEGY);if(execBuy&&state.currentPositions.length===2){const z=before.pendingSignal?.zGap??null;const x=v.exposure(z);applyExposure(state,prices,x,before.nextAction.type==="BUY_NEXT_OPEN");}
 curve.push({date,equity:state.currentEquity,drawdown:state.drawdown});}
 return{variant:v.id,curve,afterTax:afterTax(curve,ledger),tax:ledger.taxes,sales:ledger.sales,levDays,financingPaid};}
function slice(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(!x.length)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>};const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]};const universe=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const sims=VARIANTS.map(v=>sim(market.histories,universe,v));const years=[2022,2023,2024,2025,2026];const full=sims.map(s=>({variant:s.variant,gross:performanceStats(s.curve),afterTax:performanceStats(s.afterTax),taxPaidApprox:s.tax,sales:s.sales,leveragedDays:s.levDays,financingPaid:s.financingPaid}));const oos=years.map(y=>({year:y,rows:sims.map(s=>({variant:s.variant,gross:performanceStats(slice(s.curve,`${y}-01-01`,y===2026?"2026-08-25":`${y}-12-31`)),afterTax:performanceStats(slice(s.afterTax,`${y}-01-01`,y===2026?"2026-08-25":`${y}-12-31`))}))}));const output={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,stateMachineRerun:true,architectureHindsightRemains:true,warning:"Full historical state-machine rerun with negative cash financing approximation and annual realized-P&L tax approximation. Financing is charged daily on negative cash at stated annual rate. No margin calls or broker-specific maintenance requirements modeled."},rules:{STRONG125_F5:"125% gross exposure when monthly zGap>=0.50, otherwise 100%; 5% annual financing on negative cash",STRONG125_F8:"same, 8% financing sensitivity",TIERED_F5:"75% exposure when zGap<0.25, 100% for 0.25<=zGap<0.50, 125% for zGap>=0.50; 5% financing",unchanged:"Production signals, universe, Top2, stop, circuit, recovery, transaction cost"},full,oos};const dir=path.join(process.cwd(),"data/research/dynamic-exposure-full");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
