import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { performanceStats } from "../src/lib/backtest";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import type { EquityPoint, PricePoint, UniverseMonth, StrategyConfig } from "../src/lib/types";

type V={id:string,lookback:number,nearHigh:number,accelMin:number};
const VARS:V[]=[
 {id:"EL63_2",lookback:63,nearHigh:0.02,accelMin:0},
 {id:"EL126_5",lookback:126,nearHigh:0.05,accelMin:0},
 {id:"EL126_10",lookback:126,nearHigh:0.10,accelMin:0},
];
const cost=PRODUCTION_STRATEGY.execution.transactionCost;
const cfg:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,threeMonth:0.25,sixMonth:0.75},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:0.6,concentratedTop1Weight:0.7}};
const ret=(a:number,b:number)=>b/a-1;
function monthlyRiskOn(qqq:PricePoint[],date:string){const through=qqq.filter(p=>p.date<=date);const by=new Map<string,PricePoint>();for(const p of through)by.set(p.date.slice(0,7),p);const arr=[...by.values()].sort((a,b)=>a.date.localeCompare(b.date));if(arr.length<10)return false;const cur=arr[arr.length-1].close, ma=arr.slice(-10).reduce((s,p)=>s+p.close,0)/10;return cur>ma;}
function features(ps:PricePoint[],date:string,v:V,qqq:PricePoint[]){const x=ps.filter(p=>p.date<=date);if(x.length<Math.max(v.lookback,64))return null;const c=x[x.length-1].close,p20=x[x.length-21]?.close,p60=x[x.length-61]?.close;if(!p20||!p60)return null;const r20=ret(p20,c),r60=ret(p60,c),acc=r20-r60/3;const hi=Math.max(...x.slice(-v.lookback).map(p=>p.close));const prox=c/hi-1;const q=qqq.filter(p=>p.date<=date);if(q.length<21)return null;const qr20=ret(q[q.length-21].close,q[q.length-1].close);return{r20,r60,acc,prox,qr20,score:(r20-qr20)+acc};}
function engine(hist:Record<string,PricePoint[]>,u:UniverseMonth[],v:V){const q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date));const dates=q.map(p=>p.date).filter(d=>d>=PRODUCTION_STRATEGY.backtestStart);const pmap=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))]));const sigByExec=new Map<string,{symbols:string[],weights:number[]}>();for(const um of u){if(um.asOf<PRODUCTION_STRATEGY.backtestStart||!monthlyRiskOn(q,um.asOf))continue;const rows=um.symbols.map(m=>{const f=features(hist[m.symbol]??[],um.asOf,v,q);return f?{s:m.symbol,...f}:null}).filter(Boolean) as any[];const eligible=rows.filter(r=>r.prox>=-v.nearHigh&&r.acc>=v.accelMin&&r.r20>r.qr20).sort((a,b)=>b.score-a.score).slice(0,2);if(eligible.length<2)continue;sigByExec.set(nextUsTradingSession(um.asOf),{symbols:eligible.map(x=>x.s),weights:[0.5,0.5]});}
 let cash=1, pos:{s:string,sh:number}[]=[];const curve:EquityPoint[]=[];let peak=1;for(const d of dates){const sig=sigByExec.get(d);if(sig){for(const p of pos){const px=pmap[p.s]?.get(d)?.open;if(px)cash+=p.sh*px*(1-cost)}pos=[];if(sig.symbols.length===2){const total=cash;cash=0;for(let i=0;i<2;i++){const px=pmap[sig.symbols[i]]?.get(d)?.open;if(px)pos.push({s:sig.symbols[i],sh:total*sig.weights[i]*(1-cost)/px});else cash+=total*sig.weights[i];}}}let e=cash;for(const p of pos){const px=pmap[p.s]?.get(d)?.close;if(px)e+=p.sh*px;}peak=Math.max(peak,e);curve.push({date:d,equity:e,drawdown:e/peak-1});}return curve;}
function core(hist:Record<string,PricePoint[]>,u:UniverseMonth[]){const q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg);const curve:EquityPoint[]=[];for(let i=0;i<dates.length;i++){const date=dates[i];if(date<cfg.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),uu=um.get(date),sig=uu?buildMonthlySignal({universe:uu,histories:hist,qqq:q,nextSessionDate:next,config:cfg}):null;if(sig&&sig.selectedSymbols.length===2){sig.targetWeights=sig.zGap!==null&&sig.zGap>=0.25?[0.7,0.3]:[0.6,0.4];sig.allocationMode=sig.targetWeights[0]===0.7?"70/30":"50/50";}const sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));st=transitionDay(st,{date,prices,qqqHistoryThroughClose:q.slice(0,(idx.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},cfg);curve.push({date,equity:st.currentEquity,drawdown:st.drawdown});}return curve;}
function blend(a:EquityPoint[],b:EquityPoint[],wb:number){const bm=new Map(b.map(p=>[p.date,p.equity]));let ea=1,eb=1,prevA=a[0]?.equity??1,prevB=bm.get(a[0]?.date)??1,peak=1;const out:EquityPoint[]=[];for(const p of a){const bv=bm.get(p.date);if(bv==null)continue;ea*=p.equity/prevA;eb*=bv/prevB;prevA=p.equity;prevB=bv;const e=(1-wb)*ea+wb*eb;peak=Math.max(peak,e);out.push({date:p.date,equity:e,drawdown:e/peak-1});}return out;}
function slice(c:EquityPoint[],y:number){const x=c.filter(p=>p.date>=`${y}-01-01`&&p.date<=(y===2026?"2026-08-25":`${y}-12-31`));if(!x.length)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}));}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>};const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]};const u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),c=core(market.histories,u);const rows=[] as any[];for(const v of VARS){const e=engine(market.histories,u,v);rows.push({variant:v,standalone:performanceStats(e),blend25:performanceStats(blend(c,e,0.25)),blend50:performanceStats(blend(c,e,0.5)),annual:[2020,2021,2022,2023,2024,2025,2026].map(y=>({y,standalone:performanceStats(slice(e,y)),blend25:performanceStats(slice(blend(c,e,0.25),y))}))});}const output={generatedAt:new Date().toISOString(),validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,warning:"Independent-engine historical screen; architecture hindsight remains. Three predeclared breakout variants only."},core:performanceStats(c),rows};const dir=path.join(process.cwd(),"data/research/early-leader-engine-screen");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});