import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { performanceStats } from "../src/lib/backtest";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import type { EquityPoint, MonthlySignal, PositionState, PricePoint, UniverseMonth } from "../src/lib/types";
const TAX=0.20315;
const sameSet=(a:string[],b:string[])=>[...a].sort().join(",")===[...b].sort().join(",");
const exactSame=(state:any,s:MonthlySignal)=>{if(!sameSet(state.currentPositions.map((p:any)=>p.symbol),s.selectedSymbols))return false;const wm=new Map(s.selectedSymbols.map((x,i)=>[x,s.targetWeights[i]]));return state.currentPositions.every((p:any)=>Math.abs((wm.get(p.symbol)??-9)-p.targetWeight)<1e-12)};
type Ledger={gain:Record<string,number>;loss:Record<string,number>;taxes:number;sales:number;turnover:number};
function sale(l:Ledger,p:PositionState,px:number,date:string){const proceeds=p.shares*px*(1-PRODUCTION_STRATEGY.execution.transactionCost),basis=p.shares*p.entryPrice,pnl=proceeds-basis,y=date.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++;l.turnover+=proceeds;}
function taxCurve(curve:EquityPoint[],l:Ledger){const years=[...new Set(curve.map(p=>p.date.slice(0,4)))],ty:Record<string,number>={};let carry:{y:number,a:number}[]=[];for(const ys of years){const y=+ys;carry=carry.filter(x=>y-x.y<=3);let net=(l.gain[ys]??0)-(l.loss[ys]??0);if(net>0){for(const x of carry){const u=Math.min(net,x.a);net-=u;x.a-=u;if(net<=0)break}carry=carry.filter(x=>x.a>1e-12);ty[ys]=net*TAX}else if(net<0)carry.push({y,a:-net})}l.taxes=Object.values(ty).reduce((a,b)=>a+b,0);let e=curve[0]?.equity??1,pg=e,peak=e;const out:EquityPoint[]=[];for(let i=0;i<curve.length;i++){const p=curve[i];if(i)e*=p.equity/pg;pg=p.equity;const n=curve[i+1];if((!n||n.date.slice(0,4)!==p.date.slice(0,4))&&(ty[p.date.slice(0,4)]??0)>0)e=Math.max(0,e-(ty[p.date.slice(0,4)]??0)*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);out.push({date:p.date,equity:e,drawdown:e/peak-1})}return out;}
function slice(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(!x.length)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function sim(hist:Record<string,PricePoint[]>,universe:UniverseMonth[],exact:boolean){const qqq=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=qqq.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(universe.map(u=>[u.asOf,u]));let st=initialEngineState(PRODUCTION_STRATEGY),skips=0;const curve:EquityPoint[]=[],l:Ledger={gain:{},loss:{},taxes:0,sales:0,turnover:0};for(let i=0;i<dates.length;i++){const date=dates[i];if(date<PRODUCTION_STRATEGY.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),u=um.get(date),sig=u?buildMonthlySignal({universe:u,histories:hist,qqq,nextSessionDate:next,config:PRODUCTION_STRATEGY}):null,sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));if(exact&&st.nextAction.type==="MONTH_END_REBALANCE_NEXT_OPEN"&&st.nextAction.executionDate===date&&st.pendingSignal&&exactSame(st,st.pendingSignal)){st.nextAction={type:"HOLD",executionDate:null,symbols:st.currentPositions.map(p=>p.symbol),targetWeights:st.currentPositions.map(p=>p.targetWeight),reason:"Research exact no-churn"};skips++;}const before=structuredClone(st);st=transitionDay(st,{date,prices,qqqHistoryThroughClose:qqq.slice(0,(idx.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},PRODUCTION_STRATEGY);if(before.currentPositions.length&&((before.nextAction.type==="SELL_ALL_NEXT_OPEN"||before.nextAction.type==="MONTH_END_REBALANCE_NEXT_OPEN")&&before.nextAction.executionDate===date)){for(const p of before.currentPositions)sale(l,p,prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice,date)}curve.push({date,equity:st.currentEquity,drawdown:st.drawdown})}return{curve,afterTax:taxCurve(curve,l),ledger:l,skips};}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),p=sim(market.histories,u,false),e=sim(market.histories,u,true),years=[2022,2023,2024,2025,2026],output={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,noLeverage:true,warning:"Historical annual realized-P&L tax approximation with 3-year loss carryforward; not exact Japanese withholding/tax-lot timing."},full:[{variant:"PRODUCTION",gross:performanceStats(p.curve),afterTax:performanceStats(p.afterTax),taxPaidApprox:p.ledger.taxes,sales:p.ledger.sales,turnover:p.ledger.turnover},{variant:"EXACT_NO_CHURN",gross:performanceStats(e.curve),afterTax:performanceStats(e.afterTax),taxPaidApprox:e.ledger.taxes,sales:e.ledger.sales,turnover:e.ledger.turnover,skips:e.skips}],oos:years.map(y=>({year:y,production:performanceStats(slice(p.afterTax,`${y}-01-01`,y===2026?"2026-08-25":`${y}-12-31`)),exactNoChurn:performanceStats(slice(e.afterTax,`${y}-01-01`,y===2026?"2026-08-25":`${y}-12-31`))}))};const dir=path.join(process.cwd(),"data/research/exact-no-churn-tax");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});