import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import type { MonthlySignal, PricePoint, UniverseMonth } from "../src/lib/types";

type Market={histories:Record<string,PricePoint[]>}; type UF={history:UniverseMonth[]};
const PATHS=1000,H=5*252,WARM=252,BLOCK=20,RADIUS=126,SEED=20260825;
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
const sd=(x:number[])=>{const m=avg(x);return x.length?Math.sqrt(avg(x.map(v=>(v-m)**2))):0};
const pct=(x:number[],p:number)=>{const a=[...x].sort((u,v)=>u-v),q=(a.length-1)*p,l=Math.floor(q),h=Math.ceil(q),w=q-l;return a[l]*(1-w)+a[h]*w};
function rng32(seed:number){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function latestU(us:UniverseMonth[],d:string){let a=us[0];for(const u of us){if(u.asOf<=d)a=u;else break}return a}
const score=(r3:number,r6:number)=>.2*r3+.8*r6;
function makeSignal(date:string,next:string|null,u:UniverseMonth,monthly:Map<string,number[]>):MonthlySignal{
 const q=monthly.get("QQQ")??[],ret=(x:number[],n:number)=>x.length>n?x.at(-1)!/x.at(-(n+1))!-1:null;
 const q1=ret(q,1),q3=ret(q,3),q6=ret(q,6),qs=q1==null||q3==null||q6==null?null:score(q3,q6),ma=q.slice(-10),risk=ma.length===10&&q.at(-1)!>avg(ma),c:any[]=[];
 for(const m of u.symbols){const x=monthly.get(m.symbol)??[],r1=ret(x,1),r3=ret(x,3),r6=ret(x,6);if(r1==null||r3==null||r6==null||qs==null){c.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:null,qqqScore:qs,scoreSpread:null,eligible:false,exclusionReason:"INSUFFICIENT_PRICE_HISTORY",rank:null});continue}const s=score(r3,r6),reason=r1>=.8?"ONE_MONTH_SURGE":s<=qs?"NOT_ABOVE_QQQ":null;c.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:s,qqqScore:qs,scoreSpread:s-qs,eligible:!reason,exclusionReason:reason,rank:null})}
 const e=c.filter(x=>x.eligible&&x.score!=null).sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol));e.forEach((x,i)=>x.rank=i+1);const chosen=e.slice(0,2),valid=chosen.length===2,d=sd(e.map(x=>x.score)),zg=valid&&d>0?(chosen[0].score-chosen[1].score)/d:valid?0:null,conc=zg!=null&&zg>=.25,w=conc?.7:.5;
 return {strategyId:PRODUCTION_STRATEGY.strategyId,signalMonth:date.slice(0,7),signalDate:date,executionDate:next,marketRiskOn:risk,qqqClose:q.at(-1)??null,qqqMonthlyMa:ma.length===10?avg(ma):null,qqqScore:qs,universe:u.symbols.map(x=>x.symbol),candidates:c,selectedSymbols:valid?chosen.map(x=>x.symbol):[],targetWeights:valid?[w,1-w]:[],zGap:zg,allocationMode:!valid?"CASH":conc?"70/30":"50/50"} as MonthlySignal;
}
function monthlyReturns(dates:string[],curve:number[]){const last=new Map<string,{date:string,e:number}>();for(let i=0;i<dates.length;i++)last.set(dates[i].slice(0,7),{date:dates[i],e:curve[i]});const a=[...last.entries()].sort((x,y)=>x[0].localeCompare(y[0]));const out:{month:string,r:number}[]=[];for(let i=1;i<a.length;i++)out.push({month:a[i][0],r:a[i][1].e/a[i-1][1].e-1});return out}
function zeroTopKCagr(ms:{month:string,r:number}[],k:number){const idx=new Set(ms.map((x,i)=>({i,r:x.r})).sort((a,b)=>b.r-a.r).slice(0,k).map(x=>x.i));const wealth=ms.reduce((w,x,i)=>w*(1+(idx.has(i)?0:x.r)),1);return wealth**(12/Math.max(1,ms.length))-1}
function attribution(dates:string[],curve:number[],exposed:boolean[],actualCalendar:boolean){const daily:number[]=[],expLog:number[]=[];for(let i=1;i<curve.length;i++){const r=curve[i]/curve[i-1]-1;daily.push(r);if(exposed[i]||exposed[i-1])expLog.push(Math.log1p(r))}const ms=monthlyReturns(dates,curve),mrs=ms.map(x=>x.r),posLogs=ms.filter(x=>x.r>0).map(x=>Math.log1p(x.r)).sort((a,b)=>b-a),nTop=Math.max(1,Math.ceil(ms.length*.1)),topShare=posLogs.length?posLogs.slice(0,nTop).reduce((a,b)=>a+b,0)/posLogs.reduce((a,b)=>a+b,0):0;const years=actualCalendar?((new Date(dates.at(-1)!).getTime()-new Date(dates[0]).getTime())/(365.25*864e5)):5;return {portfolioCagr:(curve.at(-1)!/curve[0])**(1/years)-1,investedShare:exposed.filter(Boolean).length/exposed.length,exposedAnnualized:Math.exp(avg(expLog)*252)-1,exposedDailyLogMean:avg(expLog),monthly:{count:ms.length,mean:avg(mrs),median:pct(mrs,.5),p90:pct(mrs,.9),p95:pct(mrs,.95),max:Math.max(...mrs),top10pctPositiveLogShare:topShare,zeroTop1Cagr:zeroTopKCagr(ms,1),zeroTop3Cagr:zeroTopKCagr(ms,3),zeroTop5Cagr:zeroTopKCagr(ms,5)},topMonths:ms.sort((a,b)=>b.r-a.r).slice(0,10)} }
function runActual(hist:Record<string,PricePoint[]>,us:UniverseMonth[]){const dates=(hist.QQQ??[]).map(p=>p.date),symbols=[...new Set(["QQQ",...us.flatMap(u=>u.symbols.map(x=>x.symbol))])],maps=new Map(symbols.map(s=>[s,new Map((hist[s]??[]).map(p=>[p.date,p]))])),monthly=new Map<string,number[]>(symbols.map(s=>[s,[]])),signals:Record<string,MonthlySignal>={};for(let i=0;i<dates.length;i++){const d=dates[i],next=dates[i+1]??null,me=!next||next.slice(0,7)!==d.slice(0,7);if(me){for(const s of symbols){const p=maps.get(s)?.get(d);if(p)monthly.get(s)!.push(p.close)}if(d>=us[0].asOf)signals[d]=makeSignal(d,next,latestU(us,d),monthly)}}let st=initialEngineState(PRODUCTION_STRATEGY);const qh:PricePoint[]=[],curve:number[]=[],odates:string[]=[],exposed:boolean[]=[];for(let i=0;i<dates.length;i++){const d=dates[i],next=dates[i+1]??null,pq=maps.get("QQQ")?.get(d);if(pq)qh.push(pq);if(d<PRODUCTION_STRATEGY.backtestStart)continue;const pp:Record<string,PricePoint|undefined>={};for(const s of symbols){const p=maps.get(s)?.get(d);if(p)pp[s]=p}const was=st.currentPositions.length>0;st=transitionDay(st,{date:d,prices:pp,qqqHistoryThroughClose:qh,monthlySignal:signals[d]??null,nextSessionDate:next},PRODUCTION_STRATEGY);curve.push(st.currentEquity);odates.push(d);exposed.push(was||st.currentPositions.length>0)}return attribution(odates,curve,exposed,true)}
function summarize(rows:any[],path:string){const vals=rows.map(r=>path.split('.').reduce((o,k)=>o[k],r) as number);return{p05:pct(vals,.05),median:pct(vals,.5),p95:pct(vals,.95)}}
async function main(){const market=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8")) as Market,uf=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8")) as UF,us=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),hist=market.histories,actual=runActual(hist,us);const dates=(hist.QQQ??[]).filter(p=>p.date>=us[0].asOf).map(p=>p.date),target=dates.slice(-(WARM+H)),symbols=[...new Set(["QQQ",...us.flatMap(u=>u.symbols.map(x=>x.symbol))])],maps=new Map(symbols.map(s=>[s,new Map((hist[s]??[]).map(p=>[p.date,p]))])),dateIndex=new Map(dates.map((d,i)=>[d,i])),qMap=new Map((hist.QQQ??[]).map(p=>[p.date,p]));const feature=(i:number)=>{if(i<60)return null;const closes=dates.slice(i-60,i+1).map(x=>qMap.get(x)?.close).filter((x):x is number=>x!=null),r20=[] as number[];for(let j=i-19;j<=i;j++){const a=qMap.get(dates[j])?.close,b=qMap.get(dates[j-1])?.close;if(a&&b)r20.push(a/b-1)}if(closes.length<61||r20.length<20)return null;return{trend:closes.at(-1)!/closes[0]-1,vol:sd(r20)}};const feats=dates.map((_,i)=>feature(i)),r=rng32(SEED),rows:any[]=[];let fallback=0,obs=0;
 for(let pno=0;pno<PATHS;pno++){const syn=new Map(symbols.map(s=>[s,100])),monthly=new Map<string,number[]>(symbols.map(s=>[s,[]])),prices:Record<string,Record<string,PricePoint>>={},signals:Record<string,MonthlySignal>={};for(let ti=0;ti<target.length;){const td=target[ti],bi=dateIndex.get(td)!,f=feats[bi];let donor=bi;if(f){const cand:number[]=[];for(let k=Math.max(61,bi-RADIUS);k<=Math.min(dates.length-BLOCK-1,bi+RADIUS);k++){const g=feats[k];if(!g)continue;if(Math.sign(g.trend)!==Math.sign(f.trend)&&Math.abs(f.trend)>.03)continue;const dist=Math.abs(g.trend-f.trend)/.10+Math.abs(g.vol-f.vol)/.01;cand.push(k+dist*1e-6)}cand.sort((a,b)=>(a-Math.floor(a))-(b-Math.floor(b)));const pool=cand.slice(0,Math.min(20,cand.length)).map(x=>Math.floor(x));if(pool.length)donor=pool[Math.floor(r()*pool.length)]}for(let j=0;j<BLOCK&&ti<target.length;j++,ti++){const d=target[ti],next=target[ti+1]??null,src=dates[Math.min(donor+j,dates.length-1)],srcPrev=dates[Math.max(0,Math.min(donor+j-1,dates.length-1))],tp=ti>0?target[ti-1]:null,day:Record<string,PricePoint>={};for(const s of symbols){let a=maps.get(s)?.get(src),b=maps.get(s)?.get(srcPrev);if(!a||!b||a.open<=0||b.close<=0){const ta=maps.get(s)?.get(d),tb=tp?maps.get(s)?.get(tp):undefined;if(ta&&tb&&ta.open>0&&tb.close>0){a=ta;b=tb;fallback++}else continue}obs++;const pc=syn.get(s)!,o=pc*(a.open/b.close),c=o*(a.close/a.open);syn.set(s,c);day[s]={date:d,open:o,high:Math.max(o,c),low:Math.min(o,c),close:c}}prices[d]=day;const me=!next||next.slice(0,7)!==d.slice(0,7);if(me){for(const s of symbols)if(day[s])monthly.get(s)!.push(syn.get(s)!);signals[d]=makeSignal(d,next,latestU(us,d),monthly)}}}let st=initialEngineState(PRODUCTION_STRATEGY);const qh:PricePoint[]=[],curve:number[]=[],od:string[]=[],exposed:boolean[]=[];for(let i=0;i<target.length;i++){const d=target[i],next=target[i+1]??null,pp=prices[d]??{};if(pp.QQQ)qh.push(pp.QQQ);if(i===WARM)st=initialEngineState(PRODUCTION_STRATEGY);if(i>=WARM){const was=st.currentPositions.length>0;st=transitionDay(st,{date:d,prices:pp,qqqHistoryThroughClose:qh,monthlySignal:signals[d]??null,nextSessionDate:next},PRODUCTION_STRATEGY);curve.push(st.currentEquity);od.push(d);exposed.push(was||st.currentPositions.length>0)}}rows.push(attribution(od,curve,exposed,false));if((pno+1)%50===0)console.log(`completed ${pno+1}/${PATHS}`)}
 const fields=["portfolioCagr","investedShare","exposedAnnualized","monthly.mean","monthly.median","monthly.p90","monthly.p95","monthly.max","monthly.top10pctPositiveLogShare","monthly.zeroTop1Cagr","monthly.zeroTop3Cagr","monthly.zeroTop5Cagr"];const summary:any={};for(const f of fields)summary[f]=summarize(rows,f);const out={generatedAt:new Date().toISOString(),strategyId:PRODUCTION_STRATEGY.strategyId,method:{name:"exposure-quality attribution",exposedDay:"previous or current close has positions; includes entry/exit days",tailConcentration:"share of positive monthly log gains contributed by top 10% winning months",counterfactual:"set top 1/3/5 monthly portfolio returns to zero; all other monthly returns unchanged",cpcm:"audited chronology-preserving 20d block / +/-126d donor",fallbackRate:fallback/Math.max(1,obs)},actual,mc:{paths:PATHS,seed:SEED,summary}};await mkdir(resolve("data/research/exposure-quality"),{recursive:true});await writeFile(resolve("data/research/exposure-quality/attribution.json"),JSON.stringify(out,null,2));console.log("RESULT_JSON="+JSON.stringify(out))}
main().catch(e=>{console.error(e);process.exit(1)});
