import fs from 'node:fs/promises';
import path from 'node:path';
import { PRODUCTION_STRATEGY } from '../src/lib/config';
import { buildMonthlySignal } from '../src/lib/strategy/momentum';
import type { PricePoint, UniverseMonth } from '../src/lib/types';

type SI={symbolCode:string;settlementDate:string;daysToCoverQuantity:number;currentShortPositionQuantity:number;previousShortPositionQuantity:number;changePercent:number;stockSplitFlag:string|null};
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:null;
function corr(a:number[],b:number[]){if(a.length<5||a.length!==b.length)return null;const ma=mean(a)!,mb=mean(b)!;let n=0,da=0,db=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;n+=x*y;da+=x*x;db+=y*y}return da&&db?n/Math.sqrt(da*db):null;}
function future(ps:PricePoint[],date:string,n:number){const x=ps.filter(p=>p.date>date&&p.open>0&&p.close>0);return x.length>=n?x[n-1].close/x[0].open-1:null;}
function spread(rows:any[],field:'r21'|'r63'){if(rows.length<12)return null;const s=[...rows].sort((a,b)=>a.dtc-b.dtc),k=Math.max(1,Math.floor(s.length*.25));return mean(s.slice(-k).map(x=>x[field]))!-mean(s.slice(0,k).map(x=>x[field]))!;}
async function post(body:any){const r=await fetch('https://api.finra.org/data/group/otcMarket/name/consolidatedShortInterest',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','User-Agent':'momentum-console research'},body:JSON.stringify(body)});if(!r.ok)throw Error(`FINRA ${r.status}: ${await r.text()}`);return await r.json() as SI[];}
function eighthSessionAfter(settle:string,qqqDates:string[]){const x=qqqDates.filter(d=>d>settle);return x[7]??null;}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8')) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8')) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),qqq=market.histories.QQQ??[],qqqDates=qqq.map(p=>p.date),months=u.filter(x=>x.asOf>=PRODUCTION_STRATEGY.backtestStart&&x.asOf<='2026-08-25');const need=new Set<string>(),topByDate=new Map<string,string[]>();for(const m of months){const sg=buildMonthlySignal({universe:m,histories:market.histories,qqq,nextSessionDate:null,config:PRODUCTION_STRATEGY});const top=sg.candidates.filter(c=>c.eligible&&c.score!=null).sort((a,b)=>(b.score??-Infinity)-(a.score??-Infinity)).slice(0,10).map(c=>c.symbol);topByDate.set(m.asOf,top);top.forEach(s=>need.add(s));}
 const symbols=[...need];const all:SI[]=[];for(let y=2020;y<=2026;y++){const rows=await post({fields:['symbolCode','settlementDate','daysToCoverQuantity','currentShortPositionQuantity','previousShortPositionQuantity','changePercent','stockSplitFlag'],dateRangeFilters:[{fieldName:'settlementDate',startDate:`${y}-01-01`,endDate:y===2026?'2026-08-25':`${y}-12-31`}],domainFilters:[{fieldName:'symbolCode',values:symbols}],limit:5000});all.push(...rows);await new Promise(r=>setTimeout(r,250));}
 const bySym=new Map<string,(SI&{available:string})[]>();for(const r of all){const available=eighthSessionAfter(r.settlementDate,qqqDates);const dtc=Number(r.daysToCoverQuantity);if(!available||!Number.isFinite(dtc)||dtc<=0||dtc>=999||r.stockSplitFlag==='S')continue;const s=String(r.symbolCode).toUpperCase();if(!bySym.has(s))bySym.set(s,[]);bySym.get(s)!.push({...r,available});}for(const x of bySym.values())x.sort((a,b)=>a.available.localeCompare(b.available));
 const obs:any[]=[];for(const m of months){for(const s of topByDate.get(m.asOf)??[]){const rows=(bySym.get(s)??[]).filter(r=>r.available<=m.asOf);const r=rows.at(-1);if(!r)continue;const r21=future(market.histories[s]??[],m.asOf,21),r63=future(market.histories[s]??[],m.asOf,63);if(r21==null||r63==null)continue;obs.push({date:m.asOf,symbol:s,settlementDate:r.settlementDate,availableDate:r.available,dtc:Number(r.daysToCoverQuantity),r21,r63});}}
 const summ=(a:string,b:string)=>{const x=obs.filter(o=>o.date>=a&&o.date<=b);return{n:x.length,months:new Set(x.map(o=>o.date)).size,ic21:corr(x.map(o=>o.dtc),x.map(o=>o.r21)),ic63:corr(x.map(o=>o.dtc),x.map(o=>o.r63)),topBottom21:spread(x,'r21'),topBottom63:spread(x,'r63')};};const early=summ('2020-01-01','2023-12-31'),late=summ('2024-01-01','2026-08-25');const pass=[early.ic21,early.ic63,early.topBottom21,early.topBottom63,late.ic21,late.ic63,late.topBottom21,late.topBottom63].every(x=>x!=null&&x<0);const out={validity:{researchOnly:true,trueOOS:false,pit:true,parameterSearch:false,source:'FINRA consolidatedShortInterest Query API',hypothesis:'Within PIT monthly Momentum Top10, higher published days-to-cover predicts lower subsequent 21/63-session return.',availabilityRule:'Conservative proxy: record becomes usable on the 8th QQQ trading session strictly after FINRA settlementDate; only records with availableDate <= signal close are used.',filters:'Exclude nonpositive/999-style days-to-cover and stockSplitFlag=S.',gate:'Proceed only if IC21, IC63, high-minus-low 21D, and high-minus-low 63D are all negative in both 2020-2023 and 2024-2026. No sign/window change after observing results.'},coverage:{requestedSymbols:symbols.length,finraRows:all.length,usableSymbols:bySym.size,observations:obs.length},early2020_2023:early,late2024_2026:late,pass};console.log(JSON.stringify(out,null,2));const d=path.join(process.cwd(),'data/research/finra-short-interest-top10-diagnostic');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify({...out,observations:obs},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
