// research rerun 2026-08-30: fixed predeclared carry scales; no parameter change
import fs from 'node:fs/promises';
import path from 'node:path';
import { PRODUCTION_STRATEGY } from '../src/lib/config';
import { buildMonthlySignal } from '../src/lib/strategy/momentum';
import { initialEngineState, transitionDay } from '../src/lib/strategy/state-machine';
import { performanceStats } from '../src/lib/backtest';
import { nextUsTradingSession } from '../src/lib/trading-calendar';
import type { EquityPoint, PositionState, PricePoint, StrategyConfig, UniverseMonth } from '../src/lib/types';

const TAX=.20315;
const SCALES=[0,.5,1] as const;
const cfg:StrategyConfig={...PRODUCTION_STRATEGY,allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,concentrationZGap:999,maxTop1Weight:.6}};
type Ledger={gain:Record<string,number>;loss:Record<string,number>;cashIncome:Record<string,number>;taxes:number;sales:number};
async function yh(s:string,start='2007-01-01'){const a=Math.floor(Date.parse(start+'T00:00:00Z')/1000),b=Math.floor(Date.parse('2026-09-01T00:00:00Z')/1000),r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${s}?period1=${a}&period2=${b}&interval=1d&events=div%2Csplits&includeAdjustedClose=true`,{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error(`${s}:${r.status}`);const j:any=await r.json(),x=j.chart.result[0],q=x.indicators.quote[0],ad=x.indicators.adjclose[0].adjclose;return x.timestamp.map((t:number,i:number)=>q.close[i]!=null&&ad[i]!=null?{date:new Date(t*1000).toISOString().slice(0,10),open:q.open[i]??q.close[i],close:ad[i]}as PricePoint:null).filter(Boolean)as PricePoint[];}
function salePnl(p:PositionState,px:number){const proceeds=p.shares*px*(1-cfg.execution.transactionCost),basis=p.shares*p.entryPrice;return proceeds-basis;}
function addPnl(l:Ledger,pnl:number,d:string){const y=d.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++;}
function taxed(curve:EquityPoint[],l:Ledger){const ys=[...new Set(curve.map(p=>p.date.slice(0,4)))],tax:Record<string,number>={};let carry:{y:number,a:number}[]=[];for(const s of ys){const y=+s;carry=carry.filter(x=>y-x.y<=3);let n=(l.gain[s]??0)-(l.loss[s]??0);if(n>0){for(const x of carry){const u=Math.min(n,x.a);n-=u;x.a-=u;if(n<=0)break;}carry=carry.filter(x=>x.a>1e-12);}else if(n<0)carry.push({y,a:-n});const stockTax=Math.max(0,n)*TAX;const cashTax=(l.cashIncome[s]??0)*TAX;tax[s]=stockTax+cashTax;}l.taxes=Object.values(tax).reduce((a,b)=>a+b,0);let e=curve[0]?.equity??1,prev=e,peak=e;const out:EquityPoint[]=[];for(let i=0;i<curve.length;i++){const p=curve[i];if(i)e*=p.equity/prev;prev=p.equity;const n=curve[i+1],y=p.date.slice(0,4);if((!n||n.date.slice(0,4)!==y)&&(tax[y]??0)>0)e=Math.max(0,e-(tax[y]??0)*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);out.push({date:p.date,equity:e,drawdown:e/peak-1});}return out;}
function slice(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const prev=[...c].reverse().find(p=>p.date<s);const rows=prev?[prev,...x]:x,b=rows[0].equity;return rows.map(p=>({...p,equity:p.equity/b}));}
function sim(hist:Record<string,PricePoint[]>,u:UniverseMonth[],bil:PricePoint[],scale:number){const q=[...hist.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(p=>p.date),ix=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x])),bm=new Map(bil.map(x=>[x.date,x.close]));let st=initialEngineState(cfg),peak=1,prevBil:number|null=null;const curve:EquityPoint[]=[],l:Ledger={gain:{},loss:{},cashIncome:{},taxes:0,sales:0};for(let i=0;i<dates.length;i++){const d=dates[i];if(d<cfg.backtestStart)continue;const b=bm.get(d);if(scale>0&&b&&prevBil&&st.cash>0){const r=b/prevBil-1,inc=st.cash*(scale*r);st.cash+=inc;st.currentEquity=st.cash+st.currentPositions.reduce((sum,p)=>sum+p.shares*(p.currentPrice??p.entryPrice),0);if(inc>0){const y=d.slice(0,4);l.cashIncome[y]=(l.cashIncome[y]??0)+inc;}}if(b)prevBil=b;const n=dates[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?buildMonthlySignal({universe:uu,histories:hist,qqq:q,nextSessionDate:n,config:cfg}):null;if(sg&&sg.selectedSymbols.length===2)sg.targetWeights=[.6,.4];const sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices:any=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));const before=structuredClone(st);if(before.currentPositions.length&&((before.nextAction.type==='SELL_ALL_NEXT_OPEN'||before.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN')&&before.nextAction.executionDate===d)){for(const p of before.currentPositions){const px=prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice;addPnl(l,salePnl(p,px),d);}}st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},cfg);peak=Math.max(peak,st.currentEquity);curve.push({date:d,equity:st.currentEquity,drawdown:st.currentEquity/peak-1});}const after=taxed(curve,l);return{scale,gross:curve,after,l};}
async function main(){const mk=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),bil=await yh('BIL'),runs=SCALES.map(s=>sim(mk.histories,u,bil,s)),years=[2022,2023,2024,2025,2026];const base=runs[0];const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,noLeverage:true,parameterSearch:false,scenarios:'Predeclared structural rate stress only: 0%, 50%, 100% of historical BIL daily total return applied to strategy cash.',taxApproximation:'20.315% annual realized stock P&L with 3-year loss carry plus 20.315% tax on positive modeled cash-carry income. Cash-carry tax treatment is intentionally simplified and does not model US withholding, Japanese account type, tax lots, broker MMF mechanics, or distribution timing.'},scenarios:runs.map(r=>({carryScale:r.scale,gross:performanceStats(r.gross),afterTax:performanceStats(r.after),taxPaidApprox:r.l.taxes,cashIncomeApprox:Object.values(r.l.cashIncome).reduce((a,b)=>a+b,0),sales:r.l.sales,grossCagrDeltaVsNoCarry:performanceStats(r.gross).cagr-performanceStats(base.gross).cagr,afterTaxCagrDeltaVsNoCarry:performanceStats(r.after).cagr-performanceStats(base.after).cagr,annual:years.map(y=>({year:y,gross:performanceStats(slice(r.gross,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`)),afterTax:performanceStats(slice(r.after,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))}))}))};const d=path.join(process.cwd(),'data/research/fixed60-cash-carry-tax-stress');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
