import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { performanceStats, runStrategySimulation } from "../src/lib/backtest";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { fetchYahooHistory } from "../src/lib/yahoo";
import type { EquityPoint, PricePoint, UniverseMonth } from "../src/lib/types";

type MF={histories:Record<string,PricePoint[]>}; type UF={history:UniverseMonth[]};
const END="2026-08-25", START="2020-01-01", mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function runG(h:Record<string,PricePoint[]>,us:UniverseMonth[]){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date).filter(d=>d>=START&&d<=END),rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))])),idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))])),maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??(maps[x.s] as Map<string,PricePoint>).get(d)?.close??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di],nd=dates[di+1]??null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>{const r=(maps[x.s] as Map<string,PricePoint>).get(d);return z+x.sh*(r?.open??r?.close??x.e)},0)*.999;pos=[];pout=null;hold=0;peak=cash}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===5&&os.every(x=>x&&x>0)){const per=cash/5;pos=pin.ss.map((s,i)=>({s,sh:per*.999/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*.88);if(stop||dd<=-.15||hold>=20)pout=nd}if(!pos.length&&!pin&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<99||i<20)continue;const c=r[i].close;if(c<=mean(r.slice(i-99,i+1).map(x=>x.close)))continue;const hi=Math.max(...r.slice(i-20,i).map(x=>x.close));if(c>hi)ca.push({s,v:c/hi-1})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=5)pin={d:nd,ss:ca.slice(0,5).map(x=>x.s)}}}return curve}
type Vec=[number,number,number,number];
function runU(under:PricePoint[][],inst:PricePoint[][]){const um=under.map(a=>new Map(a.map((x,i)=>[x.date,i]))),ip=inst.map(a=>new Map(a.map(x=>[x.date,x])));const clock=under[0].map(x=>x.date).filter(d=>d>=START&&d<=END&&under.every((_a,k)=>um[k].has(d))&&inst.every((_a,k)=>ip[k].has(d)));const pending=new Map<string,Vec>();let cash=1,shares=[0,0,0,0],peak=1;const curve:EquityPoint[]=[];for(let di=0;di<clock.length;di++){const d=clock[di],exec=pending.get(d);if(exec){const opens=ip.map(m=>m.get(d)!.open),current=shares.map((sh,k)=>sh*opens[k]),eq=cash+current.reduce((z,v)=>z+v,0);let desired=exec.map(w=>eq*w),cost=0,net=eq;for(let it=0;it<3;it++){cost=desired.reduce((z,v,k)=>z+Math.abs(v-current[k])*.001,0);net=Math.max(0,eq-cost);desired=exec.map(w=>net*w)}shares=desired.map((v,k)=>v/opens[k]);cash=Math.max(0,net-desired.reduce((z,v)=>z+v,0))}const e=cash+shares.reduce((z,sh,k)=>z+sh*ip[k].get(d)!.close,0);peak=Math.max(peak,e);curve.push({date:d,equity:e,drawdown:e/peak-1});const vec:Vec=[0,0,0,0];for(let k=0;k<4;k++){const ix=um[k].get(d)!;if(ix>=199){const a=under[k];vec[k]=a[ix].close>mean(a.slice(ix-199,ix+1).map(x=>x.close))?.25:0}}const target=clock[di+1];if(target)pending.set(target,vec)}return curve}
function monthly(c:EquityPoint[]){const last=new Map<string,EquityPoint>();for(const p of c)last.set(p.date.slice(0,7),p);const a=[...last.entries()].sort(([a],[b])=>a.localeCompare(b)),r=new Map<string,number>();for(let i=1;i<a.length;i++)r.set(a[i][0],a[i][1].equity/a[i-1][1].equity-1);return r}
function corr(a:Map<string,number>,b:Map<string,number>){const k=[...a.keys()].filter(x=>b.has(x)),x=k.map(z=>a.get(z)!),y=k.map(z=>b.get(z)!);const mx=mean(x),my=mean(y);let n=0,vx=0,vy=0;for(let i=0;i<x.length;i++){const dx=x[i]-mx,dy=y[i]-my;n+=dx*dy;vx+=dx*dx;vy+=dy*dy}return n/Math.sqrt(vx*vy)}
function common(...cs:EquityPoint[][]){const maps=cs.map(c=>new Map(c.map(x=>[x.date,x.equity]))),dates=cs[0].map(x=>x.date).filter(d=>maps.every(m=>m.has(d)));return {maps,dates}}
function blend(cs:EquityPoint[][],w:number[]){const {maps,dates}=common(...cs);let e=1,peak=1;const prev=maps.map(m=>m.get(dates[0])!);const out:EquityPoint[]=[];for(let i=1;i<dates.length;i++){const d=dates[i];let r=0;for(let k=0;k<maps.length;k++){const v=maps[k].get(d)!;r+=w[k]*(v/prev[k]-1);prev[k]=v}e*=1+r;peak=Math.max(peak,e);out.push({date:d,equity:e,drawdown:e/peak-1})}return out}
function complement(base:Map<string,number>,other:Map<string,number>){const neg=[...base.keys()].filter(k=>(base.get(k)??0)<0&&other.has(k)),hit=neg.filter(k=>(other.get(k)??0)>0).length;return {negativeMonths:neg.length,positiveInNegativeMonths:hit,positiveShare:neg.length?hit/neg.length:null}}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const [iwm,xlf,xle,tna,fas,erx]=await Promise.all(["IWM","XLF","XLE","TNA","FAS","ERX"].map(fetchYahooHistory));const fixed=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(p=>p.date>=START&&p.date<=END),g=runG(m.histories,us),uu=runU([m.histories.QQQ??[],iwm,xlf,xle],[m.histories.TQQQ??[],tna,fas,erx]);const fm=monthly(fixed),gm=monthly(g),um=monthly(uu);const portfolios={g_u_50_50:blend([g,uu],[.5,.5]),fixed_g_50_50:blend([fixed,g],[.5,.5]),fixed_u_50_50:blend([fixed,uu],[.5,.5]),all_equal:blend([fixed,g,uu],[1/3,1/3,1/3]),fixed80_g10_u10:blend([fixed,g,uu],[.8,.1,.1]),fixed70_g15_u15:blend([fixed,g,uu],[.7,.15,.15]),fixed60_g20_u20:blend([fixed,g,uu],[.6,.2,.2]),fixed50_g25_u25:blend([fixed,g,uu],[.5,.25,.25])};const pm=Object.fromEntries(Object.entries(portfolios).map(([k,c])=>[k,monthly(c)]));console.log(JSON.stringify({period:{start:START,end:END},standalone:{fixed60:performanceStats(fixed),g:performanceStats(g),u:performanceStats(uu)},correlations:{fixed60_g:corr(fm,gm),fixed60_u:corr(fm,um),g_u:corr(gm,um)},complement:{g_when_fixed60_negative:complement(fm,gm),u_when_fixed60_negative:complement(fm,um),u_when_g_negative:complement(gm,um),g_when_u_negative:complement(um,gm)},portfolios:Object.fromEntries(Object.entries(portfolios).map(([k,c])=>[k,{stats:performanceStats(c),correlationWithFixed60:corr(pm[k],fm),complementWhenFixed60Negative:complement(fm,pm[k])}]))},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});