import fs from 'node:fs/promises';
import path from 'node:path';
import { PRODUCTION_STRATEGY as P } from '../src/lib/config';
import { buildMonthlySignal } from '../src/lib/strategy/momentum';
import type { PricePoint, StrategyConfig, UniverseMonth } from '../src/lib/types';
const C:StrategyConfig={...P,allocation:{...P.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,maxTop1Weight:.6}} as StrategyConfig;
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]};const u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));let futureFilings=0,dupMembers=0,rankErrors=0,oversize=0,nonMonotoneUniverse=0,priceDup=0,priceNonMonotone=0,selectedMissingSignalClose=0,selectedMissingNextOpen=0,signals=0;const examples:any={futureFilings:[],duplicateMembers:[],rankErrors:[],missingPrices:[]};for(let i=0;i<u.length;i++){const x=u[i];if(i&&x.asOf<=u[i-1].asOf)nonMonotoneUniverse++;const sy=x.symbols.map(s=>s.symbol),set=new Set(sy);if(set.size!==sy.length){dupMembers++;if(examples.duplicateMembers.length<10)examples.duplicateMembers.push(x.asOf)}if(x.symbols.length>C.universe.size)oversize++;const ranks=x.symbols.map(s=>s.universeRank),rs=new Set(ranks);if(rs.size!==ranks.length||ranks.some(r=>r<1)){rankErrors++;if(examples.rankErrors.length<10)examples.rankErrors.push(x.asOf)}for(const f of x.sourceFilings??[]){if(f.filingDate>x.asOf){futureFilings++;if(examples.futureFilings.length<10)examples.futureFilings.push({asOf:x.asOf,filingDate:f.filingDate,accession:f.accession})}}}
 for(const [s,ps0] of Object.entries(m.histories)){const ps=[...ps0];const seen=new Set<string>();let prev='';for(const p of ps){if(seen.has(p.date))priceDup++;seen.add(p.date);if(prev&&p.date<=prev)priceNonMonotone++;prev=p.date}}
 const q=[...(m.histories.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),qdates=q.map(x=>x.date),qi=new Map(qdates.map((d,i)=>[d,i]));for(const x of u){const i=qi.get(x.asOf);if(i==null)continue;const next=qdates[i+1]??null;const sig=buildMonthlySignal({universe:x,histories:m.histories,qqq:q,nextSessionDate:next,config:C});signals++;for(const s of sig.selectedSymbols){const ps=m.histories[s]??[];const sm=ps.find(p=>p.date===x.asOf),nx=next?ps.find(p=>p.date===next):null;if(!sm){selectedMissingSignalClose++;if(examples.missingPrices.length<10)examples.missingPrices.push({date:x.asOf,symbol:s,type:'signal-close'})}if(next&&!nx){selectedMissingNextOpen++;if(examples.missingPrices.length<10)examples.missingPrices.push({date:next,symbol:s,type:'next-open'})}}}
 const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,checksPITInputs:true,doesNotValidateEconomicAlpha:true},sample:{universeMonths:u.length,firstUniverseAsOf:u[0]?.asOf??null,lastUniverseAsOf:u.at(-1)?.asOf??null,priceSymbols:Object.keys(m.histories).length,signals},checks:{futureDatedSourceFilings:{count:futureFilings,pass:futureFilings===0},duplicateUniverseMembers:{count:dupMembers,pass:dupMembers===0},invalidOrDuplicateUniverseRanks:{count:rankErrors,pass:rankErrors===0},universeOversize:{count:oversize,pass:oversize===0},nonMonotoneUniverseDates:{count:nonMonotoneUniverse,pass:nonMonotoneUniverse===0},duplicatePriceDates:{count:priceDup,pass:priceDup===0},nonMonotonePriceDates:{count:priceNonMonotone,pass:priceNonMonotone===0},selectedMissingSignalClose:{count:selectedMissingSignalClose,pass:selectedMissingSignalClose===0},selectedMissingNextOpen:{count:selectedMissingNextOpen,pass:selectedMissingNextOpen===0}},examples};const d=path.join(process.cwd(),'data/research/fixed60-data-integrity-audit');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));if(Object.values(out.checks).some((x:any)=>!x.pass))process.exitCode=2}
main().catch(e=>{console.error(e);process.exit(1)});
