import fs from 'node:fs/promises';
import path from 'node:path';
import { PRODUCTION_STRATEGY } from '../src/lib/config';
import { buildMonthlySignal } from '../src/lib/strategy/momentum';
import { initialEngineState, transitionDay } from '../src/lib/strategy/state-machine';
import { performanceStats } from '../src/lib/backtest';
import { nextUsTradingSession } from '../src/lib/trading-calendar';
import type { EquityPoint, MonthlySignal, PositionState, PricePoint, StrategyConfig, UniverseMonth } from '../src/lib/types';

const TAX=.20315;
const cfg:StrategyConfig={...PRODUCTION_STRATEGY,allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,concentrationZGap:999,maxTop1Weight:.6}};
type Ledger={gain:Record<string,number>;loss:Record<string,number>;taxes:number;sales:number;turnover:number};
const sameSet=(a:string[],b:string[])=>[...a].sort().join(',')===[...b].sort().join(',');
function exactSame(state:any,s:MonthlySignal){if(!sameSet(state.currentPositions.map((p:any)=>p.symbol),s.selectedSymbols))return false;const wm=new Map(s.selectedSymbols.map((x,i)=>[x,s.targetWeights[i]]));return state.currentPositions.every((p:any)=>Math.abs((wm.get(p.symbol)??-9)-p.targetWeight)<1e-12);}
function sale(l:Ledger,p:PositionState,px:number,d:string){const proceeds=p.shares*px*(1-cfg.execution.transactionCost),basis=p.shares*p.entryPrice,pnl=proceeds-basis,y=d.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++;l.turnover+=proceeds;}
function taxed(c:EquityPoint[],l:Ledger){const ys=[...new Set(c.map(p=>p.date.slice(0,4)))],tax:Record<string,number>={};let carry:{y:number,a:number}[]=[];for(const s of ys){const y=+s;carry=carry.filter(x=>y-x.y<=3);let n=(l.gain[s]??0)-(l.loss[s]??0);if(n>0){for(const x of carry){const u=Math.min(n,x.a);n-=u;x.a-=u;if(n<=0)break;}carry=carry.filter(x=>x.a>1e-12);}else if(n<0)carry.push({y,a:-n});tax[s]=Math.max(0,n)*TAX;}l.taxes=Object.values(tax).reduce((a,b)=>a+b,0);let e=c[0]?.equity??1,prev=e,peak=e;return c.map((p,i)=>{if(i)e*=p.equity/prev;prev=p.equity;const nx=c[i+1],y=p.date.slice(0,4);if((!nx||nx.date.slice(0,4)!==y)&&(tax[y]??0)>0)e=Math.max(0,e-(tax[y]??0)*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);return{date:p.date,equity:e,drawdown:e/peak-1};});}
function slice(c:EquityPoint[],s:string,e:string){const xs=c.filter(p=>p.date>=s&&p.date<=e);if(xs.length<2)return[];const prev=[...c].reverse().find(p=>p.date<s),z=prev?[prev,...xs]:xs,b=z[0].equity;return z.map(p=>({...p,equity:p.equity/b}));}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],noChurn:boolean){const q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),ix=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg),skips=0;const c:EquityPoint[]=[],l:Ledger={gain:{},loss:{},taxes:0,sales:0,turnover:0};for(let i=0;i<ds.length;i++){const d=ds[i];if(d<cfg.backtestStart)continue;const n=ds[i+1]??nextUsTradingSession(d),uu=um.get(d);let sg=uu?buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:n,config:cfg}):null;if(sg&&sg.selectedSymbols.length===2)sg.targetWeights=[.6,.4];const sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),pr:any=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));if(noChurn&&st.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN'&&st.nextAction.executionDate===d&&st.pendingSignal&&exactSame(st,st.pendingSignal)){st.nextAction={type:'HOLD',executionDate:null,symbols:st.currentPositions.map(p=>p.symbol),targetWeights:st.currentPositions.map(p=>p.targetWeight),reason:'Research exact no-churn'};st.pendingSignal=null;skips++;}
 const before=structuredClone(st);if(before.currentPositions.length&&((before.nextAction.type==='SELL_ALL_NEXT_OPEN'||before.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN')&&before.nextAction.executionDate===d)){for(const p of before.currentPositions){const px=pr[p.symbol]?.open??pr[p.symbol]?.close??p.currentPrice??p.entryPrice;sale(l,p,px,d);}}
 st=transitionDay(st,{date:d,prices:pr,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},cfg);c.push({date:d,equity:st.currentEquity,drawdown:st.drawdown});}return{gross:c,after:taxed(c,l),l,skips};}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),base=sim(m.histories,u,false),nc=sim(m.histories,u,true),years=[2022,2023,2024,2025,2026],pack=(r:ReturnType<typeof sim>)=>({gross:performanceStats(r.gross),afterTax:performanceStats(r.after),taxPaidApprox:r.l.taxes,sales:r.l.sales,turnover:r.l.turnover,skips:r.skips,annual:years.map(y=>({year:y,gross:performanceStats(slice(r.gross,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`)),afterTax:performanceStats(slice(r.after,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))}))});const b=pack(base),x=pack(nc),out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,noLeverage:true,parameterSearch:false,rule:'Skip a scheduled month-end sell/rebuy only when current symbol set and target weights exactly equal the pending Fixed60 signal. No tolerance, no partial matching, no signal/weight/timing change.',taxApproximation:'20.315% annual realized stock P&L with 3-year loss carry; historical approximation.'},base:b,exactNoChurn:x,delta:{grossCagr:x.gross.cagr-b.gross.cagr,afterTaxCagr:x.afterTax.cagr-b.afterTax.cagr,maxDrawdown:x.gross.maxDrawdown-b.gross.maxDrawdown,sales:x.sales-b.sales,turnover:x.turnover-b.turnover}};console.log(JSON.stringify(out,null,2));const d=path.join(process.cwd(),'data/research/fixed60-exact-no-churn-tax');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
