// research rerun trigger: fixed structural stress, no parameter change
import fs from "node:fs/promises";
import path from "node:path";
import { runBacktest } from "../src/lib/backtest";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import type { EquityPoint, PricePoint, StrategyConfig, UniverseMonth } from "../src/lib/types";
type Day={date:string;logReturn:number;good:boolean};
const F60:StrategyConfig={...PRODUCTION_STRATEGY,allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,maxTop1Weight:.6}};
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
const sd=(x:number[])=>{if(x.length<2)return 0;const m=mean(x);return Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/(x.length-1));};
function stats(rs:number[],dates:string[]){let e=1,p=1,dd=0;for(const r of rs){e*=Math.exp(r);p=Math.max(p,e);dd=Math.min(dd,e/p-1)}const y=(Date.parse(dates.at(-1)!)-Date.parse(dates[0]))/(365.25*86400000);return{cagr:e**(1/y)-1,maxDD:dd,terminal:e};}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>};const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]};const u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const bt=runBacktest({histories:m.histories,universeHistory:u,config:F60});const c=bt.equityCurve,q=[...(m.histories.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),qi=new Map(q.map((p,i)=>[p.date,i]));const days:Day[]=[];for(let i=1;i<c.length;i++){const j=qi.get(c[i-1].date);if(j===undefined||j<199)continue;const qq=q[j],sma=mean(q.slice(j-199,j+1).map(x=>x.close)),rr=q.slice(j-19,j+1).map((x,k,a)=>k?Math.log(x.close/a[k-1].close):null).filter((x):x is number=>x!==null),rv=sd(rr)*Math.sqrt(252);days.push({date:c[i].date,logReturn:Math.log(c[i].equity/c[i-1].equity),good:qq.close>sma&&rv<.30})}const dates=days.map(x=>x.date),base=stats(days.map(x=>x.logReturn),dates),g=days.filter(x=>x.good).map(x=>x.logReturn),mu=mean(g);const retentions=[1,.9,.85,.8,.75,.7,.5,.25,0].map(r=>({edgeRetention:r,...stats(days.map(x=>x.good?x.logReturn-(1-r)*mu:x.logReturn),dates)}));const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,stateMachineRerun:false,descriptiveCounterfactual:true,parameterSearch:false,allocation:'fixed 60/40',warning:'Sensitivity only. Good-regime mean-return haircut preserves historical residual path and is not a calibrated probability model.'},sample:{start:dates[0],end:dates.at(-1),days:days.length,goodRegimeDayShare:g.length/days.length,goodRegimeMeanDailyLogReturn:mu},baseline:base,edgeRetentionStress:retentions,target40:{historicalGrossCagr:base.cagr,minRetentionGridMeeting40:retentions.filter(x=>x.cagr>=.40).at(-1)?.edgeRetention??null,simpleAfterTaxRetentionNeeded:0.40/0.5064691697564643}};const d=path.join(process.cwd(),"data/research/fixed60-structural-stress");await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,"result.json"),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});