// research rerun 2026-08-30: trigger single predeclared semimonthly architecture test
import fs from 'node:fs/promises';
import path from 'node:path';
import { PRODUCTION_STRATEGY } from '../src/lib/config';
import { buildMonthlySignal } from '../src/lib/strategy/momentum';
import { initialEngineState, transitionDay } from '../src/lib/strategy/state-machine';
import { performanceStats } from '../src/lib/backtest';
import { nextUsTradingSession } from '../src/lib/trading-calendar';
import type { EquityPoint, MonthlySignal, PricePoint, StrategyConfig, UniverseMonth } from '../src/lib/types';

const cfg:StrategyConfig={...PRODUCTION_STRATEGY,allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,concentrationZGap:999,maxTop1Weight:.6}};
function slice(c:EquityPoint[],s:string,e:string){const xs=c.filter(p=>p.date>=s&&p.date<=e);if(xs.length<2)return[];const prev=[...c].reverse().find(p=>p.date<s),rows=prev?[prev,...xs]:xs,b=rows[0].equity;return rows.map(p=>({...p,equity:p.equity/b}));}
function fixed60(sig:MonthlySignal){if(sig.selectedSymbols.length===2)return{...sig,targetWeights:[.6,.4],allocationMode:'60/40',zGap:null};return sig;}
function refreshSignal(snapshot:UniverseMonth,date:string,hist:Record<string,PricePoint[]>,qqq:PricePoint[],next:string|null,monthEnd:MonthlySignal){const raw=buildMonthlySignal({universe:{...snapshot,asOf:date},histories:hist,qqq,nextSessionDate:next,config:cfg});const eligible=raw.candidates.filter(c=>c.eligible&&c.score!=null).sort((a,b)=>(b.score??-Infinity)-(a.score??-Infinity)||a.symbol.localeCompare(b.symbol));const picks=monthEnd.marketRiskOn&&eligible.length>=2?eligible.slice(0,2):[];return{...raw,marketRiskOn:monthEnd.marketRiskOn,qqqClose:monthEnd.qqqClose,qqqMonthlyMa:monthEnd.qqqMonthlyMa,selectedSymbols:picks.map(x=>x.symbol),targetWeights:picks.length===2?[.6,.4]:[],allocationMode:picks.length===2?'60/40':'CASH',zGap:null} as MonthlySignal;}
function sim(hist:Record<string,PricePoint[]>,universe:UniverseMonth[],semi:boolean){const q=[...hist.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(universe.map(x=>[x.asOf,x]));const refresh=new Map<string,UniverseMonth>();if(semi){for(const u of universe){const after=dates.filter(d=>d>u.asOf);const d=after[9];if(d&&d<='2026-08-25')refresh.set(d,u);}}let st=initialEngineState(cfg),refreshSignals=0,refreshChanged=0;let lastMonthEnd:MonthlySignal|null=null;const curve:EquityPoint[]=[];for(let i=0;i<dates.length;i++){const d=dates[i];if(d<cfg.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(d);let sig:MonthlySignal|null=null;const u=um.get(d);if(u){sig=fixed60(buildMonthlySignal({universe:u,histories:hist,qqq:q,nextSessionDate:next,config:cfg}));lastMonthEnd=sig;}else if(semi){const ru=refresh.get(d);if(ru&&lastMonthEnd&&lastMonthEnd.signalDate===ru.asOf){const before=lastMonthEnd.selectedSymbols.join(',');sig=refreshSignal(ru,d,hist,q,next,lastMonthEnd);refreshSignals++;if(sig.selectedSymbols.join(',')!==before)refreshChanged++;}}
 const sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(idx.get(d)??i)+1),monthlySignal:sig,nextSessionDate:next},cfg);curve.push({date:d,equity:st.currentEquity,drawdown:st.drawdown});}return{curve,refreshSignals,refreshChanged,events:st.events.length};}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},universe=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),base=sim(market.histories,universe,false),semi=sim(market.histories,universe,true),years=[2022,2023,2024,2025,2026];const pack=(r:ReturnType<typeof sim>)=>({full:performanceStats(r.curve),early2020_2023:performanceStats(slice(r.curve,'2020-01-01','2023-12-31')),late2024_2026:performanceStats(slice(r.curve,'2024-01-01','2026-08-25')),annual:years.map(y=>({year:y,stats:performanceStats(slice(r.curve,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))})),refreshSignals:r.refreshSignals,refreshChanged:r.refreshChanged,events:r.events});const b=pack(base),x=pack(semi),out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,noLeverage:true,parameterSearch:false,architectureTest:true,rule:'Fixed60 baseline plus exactly one mid-month Top2 refresh on the 10th US trading session strictly after each PIT universe snapshot. Same snapshot symbols, same 0/20/80 momentum, same eligibility, Fixed60 60/40. Month-end QQQ 10M gate state is held fixed through the refresh; no weekly/grid alternatives tested.',execution:'Refresh signal confirmed at close, state-machine next-session-open execution; existing Stop/Circuit/Recovery unchanged.'},baseline:b,semiMonthly:x,delta:{fullCagr:x.full.cagr-b.full.cagr,earlyCagr:x.early2020_2023.cagr-b.early2020_2023.cagr,lateCagr:x.late2024_2026.cagr-b.late2024_2026.cagr,maxDd:x.full.maxDrawdown-b.full.maxDrawdown}};console.log(JSON.stringify(out,null,2));const d=path.join(process.cwd(),'data/research/fixed60-semimonthly-refresh');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
