import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY as P} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,PositionState,PricePoint,StrategyConfig,UniverseMonth} from '../src/lib/types';
const TAX=.20315,CARRY_SCALES=[0,.5,1] as const,KS=[1,3,5] as const;
type L={gain:Record<string,number>;loss:Record<string,number>;cashIncome:Record<string,number>;taxes:number;sales:number};
function cfg():StrategyConfig{return {...P,allocation:{...P.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,concentrationZGap:999,maxTop1Weight:.6}} as StrategyConfig;}
async function yh(s:string,start='2007-01-01'){const a=Math.floor(Date.parse(start+'T00:00:00Z')/1000),b=Math.floor(Date.parse('2026-09-01T00:00:00Z')/1000),r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${s}?period1=${a}&period2=${b}&interval=1d&events=div%2Csplits&includeAdjustedClose=true`,{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error(`${s}:${r.status}`);const j:any=await r.json(),x=j.chart.result[0],q=x.indicators.quote[0],ad=x.indicators.adjclose[0].adjclose;return x.timestamp.map((t:number,i:number)=>q.close[i]!=null&&ad[i]!=null?{date:new Date(t*1000).toISOString().slice(0,10),open:q.open[i]??q.close[i],close:ad[i]}as PricePoint:null).filter(Boolean)as PricePoint[];}
function addPnl(l:L,pnl:number,d:string){const y=d.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++;}
function salePnl(p:PositionState,px:number,c:StrategyConfig){return p.shares*px*(1-c.execution.transactionCost)-p.shares*p.entryPrice;}
function addCashIncome(l:L,inc:number,d:string){if(inc<=0)return;const y=d.slice(0,4);l.cashIncome[y]=(l.cashIncome[y]??0)+inc;}
function taxed(curve:EquityPoint[],l:L){const ys=[...new Set(curve.map(p=>p.date.slice(0,4)))],tax:Record<string,number>={};let carry:{y:number,a:number}[]=[];for(const s of ys){const y=+s;carry=carry.filter(x=>y-x.y<=3);let n=(l.gain[s]??0)-(l.loss[s]??0);if(n>0){for(const x of carry){const u=Math.min(n,x.a);n-=u;x.a-=u;if(n<=0)break;}carry=carry.filter(x=>x.a>1e-12);}else if(n<0)carry.push({y,a:-n});tax[s]=Math.max(0,n)*TAX+(l.cashIncome[s]??0)*TAX;}l.taxes=Object.values(tax).reduce((a,b)=>a+b,0);let e=curve[0]?.equity??1,prev=e,peak=e;return curve.map((p,i)=>{if(i)e*=p.equity/prev;prev=p.equity;const n=curve[i+1],y=p.date.slice(0,4);if((!n||n.date.slice(0,4)!==y)&&(tax[y]??0)>0)e=Math.max(0,e-(tax[y]??0)*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);return{date:p.date,equity:e,drawdown:e/peak-1};});}
function slice(c:EquityPoint[],s:string,e:string){const xs=c.filter(p=>p.date>=s&&p.date<=e);if(xs.length<2)return[];const prev=[...c].reverse().find(p=>p.date<s),z=prev?[prev,...xs]:xs,b=z[0].equity;return z.map(p=>({...p,equity:p.equity/b}));}
function sim(hist:Record<string,PricePoint[]>,universe:UniverseMonth[],bil:PricePoint[],k:number,carryScale:number,bridge:boolean){const c=cfg(),q=[...hist.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date),di=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(universe.map(x=>[x.asOf,x])),bm=new Map(bil.map(x=>[x.date,x.close]));let st=initialEngineState(c),prevBase=1,equity=1,peak=1,enterNext=false,exitNext=false,bridgeOn=false,bridgeCash=0,bridgeShares=0,bridgeBasis=0,prevBil:number|null=null;const curve:EquityPoint[]=[],l:L={gain:{},loss:{},cashIncome:{},taxes:0,sales:0};for(let i=0;i<dates.length;i++){const date=dates[i];if(date<c.backtestStart)continue;const b=bm.get(date),br=b&&prevBil?b/prevBil-1:0;if(b)prevBil=b;const next=dates[i+1]??nextUsTradingSession(date),u=um.get(date),sig=u?buildMonthlySignal({universe:u,histories:hist,qqq:q,nextSessionDate:next,config:c}):null,sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices:any=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)])),before=structuredClone(st),beforeEq=st.currentEquity,wasInvested=before.currentPositions.length>0,qr=pm.QQQ?.get(date),qo=qr?.open??qr?.close,qc=qr?.close;
 // Realized base P&L, scaled to overlay equity; bridge never feeds the state machine.
 if(before.currentPositions.length&&((before.nextAction.type==='SELL_ALL_NEXT_OPEN'||before.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN')&&before.nextAction.executionDate===date)){const scale=!bridgeOn&&beforeEq>0?equity/beforeEq:1;for(const p of before.currentPositions){const op=prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice;addPnl(l,salePnl(p,op,c)*scale,date);}}
 st=transitionDay(st,{date,prices,qqqHistoryThroughClose:q.slice(0,(di.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},c);const nowInvested=st.currentPositions.length>0,enteredTop2=!wasInvested&&nowInvested,bf=prevBase>0?st.currentEquity/prevBase:1;
 if(!bridge){if(wasInvested||nowInvested)equity*=bf;else if(carryScale>0&&br!==0){const inc=equity*carryScale*br;equity+=inc;addCashIncome(l,inc,date);}}
 else {
  // Existing bridge position: cash half earns carry; QQQ half follows QQQ. Carry does not affect Stop/Circuit state.
  if(bridgeOn&&carryScale>0&&br!==0){const inc=bridgeCash*carryScale*br;bridgeCash+=inc;addCashIncome(l,inc,date);}
  if(exitNext&&bridgeOn&&qo){const proceeds=bridgeShares*qo*(1-c.execution.transactionCost);addPnl(l,proceeds-bridgeBasis,date);equity=bridgeCash+proceeds;bridgeOn=false;bridgeCash=bridgeShares=bridgeBasis=0;exitNext=false;}
  if(enterNext&&!bridgeOn&&!nowInvested&&qo){bridgeCash=equity*.5;const notional=equity*.5;bridgeBasis=notional;bridgeShares=notional*(1-c.execution.transactionCost)/qo;bridgeOn=true;enterNext=false;}
  if(enteredTop2&&bridgeOn&&qo){const proceeds=bridgeShares*qo*(1-c.execution.transactionCost);addPnl(l,proceeds-bridgeBasis,date);equity=bridgeCash+proceeds;bridgeOn=false;bridgeCash=bridgeShares=bridgeBasis=0;const top2Day=beforeEq>0?st.currentEquity/beforeEq:1;equity*=top2Day;}
  else if(bridgeOn&&qc)equity=bridgeCash+bridgeShares*qc;
  else if(wasInvested||nowInvested)equity*=bf;
  else if(!bridgeOn&&carryScale>0&&br!==0){const inc=equity*carryScale*br;equity+=inc;addCashIncome(l,inc,date);}
  if(bridgeOn&&sig&&sig.marketRiskOn===false)exitNext=true;
  if(!bridgeOn&&!enterNext&&!exitNext&&!nowInvested&&st.state==='WAITING_RECOVERY'&&st.marketRiskOn&&st.recoveryConsecutiveDays===k)enterNext=true;
  if(nowInvested){enterNext=false;exitNext=false;}
 }
 peak=Math.max(peak,equity);curve.push({date,equity,drawdown:equity/peak-1});prevBase=st.currentEquity;}
 return{gross:curve,after:taxed(curve,l),l};}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),bil=await yh('BIL'),years=[2022,2023,2024,2025,2026];const baseRuns=Object.fromEntries(CARRY_SCALES.map(s=>[s,sim(m.histories,u,bil,99,s,false)])),bridgeRuns=Object.fromEntries(KS.flatMap(k=>CARRY_SCALES.map(s=>[`${k}_${s}`,sim(m.histories,u,bil,k,s,true)])));const pack=(r:ReturnType<typeof sim>)=>({gross:performanceStats(r.gross),afterTax:performanceStats(r.after),taxPaidApprox:r.l.taxes,cashIncomeApprox:Object.values(r.l.cashIncome).reduce((a,b)=>a+b,0),sales:r.l.sales,annual:years.map(y=>({year:y,gross:performanceStats(slice(r.gross,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`)),afterTax:performanceStats(slice(r.after,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))}))});const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,noLeverage:true,parameterSearch:false,bridge:'Exact K-close recovery bridge lifecycle; QQQ 50%, other 50% remains cash. K1/K3/K5 all retained for timing-sensitivity falsification. Bridge P&L and carry do not feed Production Stop/Circuit state.',carry:'0/50/100% of historical BIL daily total return applied only to economically idle cash, including the unused 50% while bridge is active.',taxApproximation:'20.315% annual realized security P&L with 3-year loss carry plus 20.315% on positive modeled cash income; simplified research approximation.'},Fixed60:Object.fromEntries(CARRY_SCALES.map(s=>[String(s),pack(baseRuns[s])])),Fixed60Bridge:Object.fromEntries(KS.map(k=>[String(k),Object.fromEntries(CARRY_SCALES.map(s=>[String(s),pack(bridgeRuns[`${k}_${s}`])]))]))};const d=path.join(process.cwd(),'data/research/fixed60-bridge-cash-carry-tax');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
