import fs from 'node:fs/promises';
import path from 'node:path';
import { PRODUCTION_STRATEGY as P } from '../src/lib/config';
import { buildMonthlySignal } from '../src/lib/strategy/momentum';
import { initialEngineState, transitionDay } from '../src/lib/strategy/state-machine';
import { performanceStats, runBacktest } from '../src/lib/backtest';
import type { EquityPoint, MonthlySignal, PositionState, PricePoint, StrategyConfig, UniverseMonth } from '../src/lib/types';

const TAX=0.20315;
const BASE:StrategyConfig={...P,strategyId:'fixed60-comprehensive-falsification-20260830',allocation:{...P.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,maxTop1Weight:.6}} as StrategyConfig;
type Ledger={gain:Record<string,number>;loss:Record<string,number>;taxes:number;sales:number};
type SimSpec={label:string;config?:StrategyConfig;executionDelay?:number;signalShift?:number;dropFraction?:number;seed?:number;rank2SwapProbability?:number;remove?:Set<string>;start?:string};
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
function quant(x:number[],p:number){if(!x.length)return null;const a=[...x].sort((a,b)=>a-b),h=(a.length-1)*p,i=Math.floor(h),f=h-i;return a[i]*(1-f)+a[Math.min(i+1,a.length-1)]*f}
function h32(s:string){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function cfg(cost?:number,start?:string):StrategyConfig{return {...BASE,execution:{...BASE.execution,transactionCost:cost??BASE.execution.transactionCost},backtestStart:start??BASE.backtestStart} as StrategyConfig}
function add(l:Ledger,p:number,d:string){const y=d.slice(0,4);if(p>=0)l.gain[y]=(l.gain[y]??0)+p;else l.loss[y]=(l.loss[y]??0)-p;l.sales++}
function pnl(p:PositionState,px:number,c:StrategyConfig){return p.shares*px*(1-c.execution.transactionCost)-p.shares*p.entryPrice}
function taxCurve(curve:EquityPoint[],l:Ledger){if(!curve.length)return[];const ys=[...new Set(curve.map(p=>p.date.slice(0,4)))],tax:Record<string,number>={};let carry:{y:number,a:number}[]=[];for(const s of ys){const y=+s;carry=carry.filter(x=>y-x.y<=3);let n=(l.gain[s]??0)-(l.loss[s]??0);if(n>0){for(const x of carry){const u=Math.min(n,x.a);n-=u;x.a-=u;if(n<=0)break}carry=carry.filter(x=>x.a>1e-12);tax[s]=n*TAX}else if(n<0)carry.push({y,a:-n})}l.taxes=Object.values(tax).reduce((a,b)=>a+b,0);let e=curve[0].equity,prev=curve[0].equity,peak=e;return curve.map((p,i)=>{if(i)e*=p.equity/prev;prev=p.equity;const n=curve[i+1],y=p.date.slice(0,4);if((!n||n.date.slice(0,4)!==y)&&(tax[y]??0)>0)e=Math.max(0,e-(tax[y]??0)*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);return{date:p.date,equity:e,drawdown:e/peak-1}})}
function shiftUniverse(u:UniverseMonth[],dates:string[],shift:number){if(!shift)return u;const di=new Map(dates.map((d,i)=>[d,i]));return u.flatMap(x=>{const i=di.get(x.asOf);const d=i==null?null:dates[i+shift];return d?[{...x,asOf:d}]:[]})}
function transformUniverse(raw:UniverseMonth[],spec:SimSpec){return raw.map(u=>({...u,symbols:u.symbols.filter(r=>{if(spec.remove?.has(r.symbol))return false;if(!spec.dropFraction)return true;return h32(`${spec.seed??0}|${u.signalMonth}|${r.symbol}`)/2**32>=spec.dropFraction})}))}
function maybeSwap(sig:MonthlySignal|null,spec:SimSpec){if(!sig||!spec.rank2SwapProbability||sig.selectedSymbols.length<2)return sig;const z=h32(`${spec.seed??0}|${sig.signalMonth}|rank2swap`)/2**32;if(z>=spec.rank2SwapProbability)return sig;const ranked=sig.candidates.filter(c=>c.eligible&&c.score!=null).sort((a,b)=>(b.score??-Infinity)-(a.score??-Infinity));const third=ranked[2]?.symbol;if(!third||sig.selectedSymbols.includes(third))return sig;return {...sig,selectedSymbols:[sig.selectedSymbols[0],third]}}
function simulate(hist:Record<string,PricePoint[]>,raw:UniverseMonth[],spec:SimSpec){const c=spec.config??cfg(undefined,spec.start),q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date),di=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))]));let u=transformUniverse(raw,spec);u=shiftUniverse(u,dates,spec.signalShift??0);const um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(c);const curve:EquityPoint[]=[],l:Ledger={gain:{},loss:{},taxes:0,sales:0};for(let i=0;i<dates.length;i++){const date=dates[i];if(date<c.backtestStart)continue;const next=dates[i+1+(spec.executionDelay??0)]??null;const m=um.get(date);let sig=m?buildMonthlySignal({universe:m,histories:hist,qqq:q,nextSessionDate:next,config:c}):null;sig=maybeSwap(sig,spec);const sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]);const prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));const before=structuredClone(st);if(before.currentPositions.length&&before.nextAction.executionDate===date&&(before.nextAction.type==='SELL_ALL_NEXT_OPEN'||before.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN'))for(const p of before.currentPositions){const px=prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice;add(l,pnl(p,px,c),date)}st=transitionDay(st,{date,prices,qqqHistoryThroughClose:q.slice(0,(di.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},c);curve.push({date,equity:st.currentEquity,drawdown:st.drawdown})}const after=taxCurve(curve,l);return{gross:performanceStats(curve),afterTax:performanceStats(after),grossCurve:curve,afterTaxCurve:after,taxPaidApprox:l.taxes,sales:l.sales}}
function rolling(curve:EquityPoint[],sessions:number){const xs:number[]=[];for(let i=sessions;i<curve.length;i++){const a=curve[i-sessions],b=curve[i];if(a.equity<=0||b.equity<=0)continue;xs.push((b.equity/a.equity)**(252/sessions)-1)}return{sessions,n:xs.length,min:quant(xs,0),p10:quant(xs,.1),p25:quant(xs,.25),median:quant(xs,.5),p75:quant(xs,.75),shareAbove40:xs.filter(x=>x>=.4).length/Math.max(1,xs.length),shareAbove30:xs.filter(x=>x>=.3).length/Math.max(1,xs.length)}}
function annual(curve:EquityPoint[]){const by=new Map<string,EquityPoint[]>();for(const p of curve){const y=p.date.slice(0,4);(by.get(y)??by.set(y,[]).get(y)!).push(p)}return Object.fromEntries([...by].map(([y,x])=>[y,x.length>1?x.at(-1)!.equity/x[0].equity-1:null]))}
function regime(curve:EquityPoint[],q:PricePoint[]){const qm=new Map(q.map((p,i)=>[p.date,i])),rs:{good:number[];bad:number[]}={good:[],bad:[]};for(let i=1;i<curve.length;i++){const j=qm.get(curve[i].date);if(j==null||j<199)continue;const sma=mean(q.slice(j-199,j+1).map(x=>x.close));const rr=q.slice(Math.max(0,j-19),j+1).slice(1).map((x,k,a)=>Math.log(x.close/(k===0?q[j-19].close:a[k-1].close)));const m=mean(rr),sd=Math.sqrt(rr.reduce((s,x)=>s+(x-m)**2,0)/Math.max(1,rr.length-1))*Math.sqrt(252);const r=Math.log(curve[i].equity/curve[i-1].equity);(q[j].close>sma&&sd<.30?rs.good:rs.bad).push(r)}const f=(x:number[])=>({days:x.length,share:x.length/(rs.good.length+rs.bad.length),annualizedLogReturn:mean(x)*252,cagrEquivalent:Math.exp(mean(x)*252)-1});return{good:f(rs.good),bad:f(rs.bad)}}
function rng(seed:number){let x=seed>>>0;return()=>{x=(Math.imul(1664525,x)+1013904223)>>>0;return x/2**32}}
function blockBootstrap(curve:EquityPoint[],block:number,years:number,reps:number,seed:number){const r=[] as number[];for(let i=1;i<curve.length;i++)r.push(Math.log(curve[i].equity/curve[i-1].equity));const n=years*252,out:number[]=[],R=rng(seed);for(let k=0;k<reps;k++){let s=0,c=0;while(c<n){const st=Math.floor(R()*Math.max(1,r.length-block));for(let j=0;j<block&&c<n;j++,c++)s+=r[st+j]??0}out.push(Math.exp(s/years)-1)}return{blockSessions:block,years,reps,p05:quant(out,.05),p10:quant(out,.1),p25:quant(out,.25),median:quant(out,.5),p75:quant(out,.75),p90:quant(out,.9),shareAbove40:out.filter(x=>x>=.4).length/reps,shareBelow20:out.filter(x=>x<.2).length/reps}}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const baseline=simulate(m.histories,u,{label:'BASE'});const selected=[...new Set(runBacktest({histories:m.histories,universeHistory:u,config:BASE}).events.flatMap(e=>e.symbols).filter(s=>s&&s!=='QQQ'))].sort();
 const costs=[.001,.002,.003,.005,.01].map(x=>({bp:x*10000,r:simulate(m.histories,u,{label:`COST_${x}`,config:cfg(x)})}));
 const exec=[0,1,2].map(x=>({delay:x,r:simulate(m.histories,u,{label:`EXEC_${x}`,executionDelay:x})}));
 const signal=[-2,-1,0,1].map(x=>({shift:x,r:simulate(m.histories,u,{label:`SIGNAL_${x}`,signalShift:x})}));
 const starts=['2020-01-01','2020-04-01','2020-07-01','2021-01-01'].map(x=>({start:x,r:simulate(m.histories,u,{label:`START_${x}`,start:x})}));
 const dropout:any[]=[];for(const f of [.05,.10])for(let s=1;s<=10;s++)dropout.push({fraction:f,seed:s,r:simulate(m.histories,u,{label:`DROP_${f}_${s}`,dropFraction:f,seed:s})});
 const rankNoise:any[]=[];for(const p of [.05,.10])for(let s=1;s<=10;s++)rankNoise.push({probability:p,seed:s,r:simulate(m.histories,u,{label:`RANK_${p}_${s}`,rank2SwapProbability:p,seed:s})});
 const pairs:any[]=[];for(let i=0;i<selected.length;i++)for(let j=i+1;j<selected.length;j++){const a=selected[i],b=selected[j],r=simulate(m.histories,u,{label:`PAIR_${a}_${b}`,remove:new Set([a,b])});pairs.push({symbols:[a,b],afterTaxCagr:r.afterTax.cagr,grossCagr:r.gross.cagr,afterTaxMaxDD:r.afterTax.maxDrawdown})}
 pairs.sort((a,b)=>a.afterTaxCagr-b.afterTaxCagr);const pairC=pairs.map(x=>x.afterTaxCagr);
 const qqq=[...(m.histories.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date));
 const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,fixedCandidate:'Fixed60',parameterSearch:false,taxApproximation:'20.315% annual realized P&L with 3-year loss carry; not exact broker withholding/tax lots.',bootstrap:'secondary cautionary diagnostic only; moving blocks preserve local dependence but not full regime chronology.',decisionUse:'Falsification only. Do not select a better perturbation as a new strategy.'},baseline:{gross:baseline.gross,afterTax:baseline.afterTax,taxPaidApprox:baseline.taxPaidApprox,sales:baseline.sales},rollingAfterTax:[rolling(baseline.afterTaxCurve,252),rolling(baseline.afterTaxCurve,504),rolling(baseline.afterTaxCurve,756)],annualAfterTax:annual(baseline.afterTaxCurve),regimeAfterTax:regime(baseline.afterTaxCurve,qqq),costStress:costs.map(x=>({bpPerSide:x.bp,gross:x.r.gross,afterTax:x.r.afterTax})),executionDelayStress:exec.map(x=>({delaySessions:x.delay,gross:x.r.gross,afterTax:x.r.afterTax})),signalDateStress:signal.map(x=>({shiftSessions:x.shift,gross:x.r.gross,afterTax:x.r.afterTax})),startDateStress:starts.map(x=>({start:x.start,gross:x.r.gross,afterTax:x.r.afterTax})),universeDropout:{runs:dropout.map(x=>({fraction:x.fraction,seed:x.seed,afterTaxCagr:x.r.afterTax.cagr,grossCagr:x.r.gross.cagr})),summary:Object.fromEntries([.05,.10].map(f=>{const a=dropout.filter(x=>x.fraction===f).map(x=>x.r.afterTax.cagr);return[String(f),{n:a.length,min:quant(a,0),p10:quant(a,.1),median:quant(a,.5),shareAbove40:a.filter(x=>x>=.4).length/a.length}]}))},rankingNoise:{runs:rankNoise.map(x=>({probability:x.probability,seed:x.seed,afterTaxCagr:x.r.afterTax.cagr,grossCagr:x.r.gross.cagr})),summary:Object.fromEntries([.05,.10].map(p=>{const a=rankNoise.filter(x=>x.probability===p).map(x=>x.r.afterTax.cagr);return[String(p),{n:a.length,min:quant(a,0),p10:quant(a,.1),median:quant(a,.5),shareAbove40:a.filter(x=>x>=.4).length/a.length}]}))},twoWinnerRemoval:{selectedCount:selected.length,pairCount:pairs.length,distribution:{min:quant(pairC,0),p10:quant(pairC,.1),p25:quant(pairC,.25),median:quant(pairC,.5),shareAbove40:pairC.filter(x=>x>=.4).length/Math.max(1,pairC.length),countBelow40:pairC.filter(x=>x<.4).length},worst10:pairs.slice(0,10)},movingBlockBootstrapAfterTax:[blockBootstrap(baseline.afterTaxCurve,21,5,3000,20260830),blockBootstrap(baseline.afterTaxCurve,63,5,3000,20260831),blockBootstrap(baseline.afterTaxCurve,21,10,3000,20260832),blockBootstrap(baseline.afterTaxCurve,63,10,3000,20260833)]};
 const dir=path.join(process.cwd(),'data/research/fixed60-comprehensive-falsification');await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}
main().catch(e=>{console.error(e);process.exit(1)});
