import fs from 'node:fs/promises';
import path from 'node:path';
import {FIXED60_STRATEGY as cfg} from './lib/fixed60-config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,PricePoint,UniverseMonth} from '../src/lib/types';

const ASSETS=['GLD','IEF','UUP','DBC']; const COST=.001;
async function yahoo(s:string,start='2007-01-01'){const p1=Math.floor(Date.parse(start+'T00:00:00Z')/1000),p2=Math.floor(Date.parse('2026-09-01T00:00:00Z')/1000);const r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${s}?period1=${p1}&period2=${p2}&interval=1d&events=div%2Csplits&includeAdjustedClose=true`,{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error(`${s}:${r.status}`);const j:any=await r.json(),x=j.chart.result?.[0],q=x?.indicators?.quote?.[0],ad=x?.indicators?.adjclose?.[0]?.adjclose??[];const out:PricePoint[]=[];for(let i=0;i<(x?.timestamp?.length??0);i++){if(q.open[i]==null||q.close[i]==null||ad[i]==null)continue;const k=ad[i]/q.close[i];out.push({date:new Date(x.timestamp[i]*1000).toISOString().slice(0,10),open:q.open[i]*k,close:ad[i]});}return out;}
function core(hist:Record<string,PricePoint[]>,u:UniverseMonth[]){const q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(p=>p.date),di=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg);const curve:EquityPoint[]=[],risk=new Map<string,boolean>();for(let i=0;i<ds.length;i++){const d=ds[i];if(d<cfg.backtestStart)continue;const nx=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?buildMonthlySignal({universe:uu,histories:hist,qqq:q,nextSessionDate:nx,config:cfg}):null,sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(di.get(d)??i)+1),monthlySignal:sg,nextSessionDate:nx},cfg);curve.push({date:d,equity:st.currentEquity,drawdown:st.drawdown});risk.set(d,st.state==='INVESTED');}return{curve,risk,q,ds};}
function plans(hist:Record<string,PricePoint[]>,u:UniverseMonth[],a:Record<string,PricePoint[]>){const q=[...hist.QQQ].sort((x,y)=>x.date.localeCompare(y.date)),m=new Map<string,{risk:boolean,s:string|null}>();for(const um of u){if(um.asOf<cfg.backtestStart)continue;const ex=nextUsTradingSession(um.asOf),sg=buildMonthlySignal({universe:um,histories:hist,qqq:q,nextSessionDate:ex,config:cfg});const rows=ASSETS.map(s=>{const x=a[s].filter(p=>p.date<=um.asOf);return x.length>63?{s,r:x.at(-1)!.close/x.at(-64)!.close-1}:null}).filter(Boolean) as {s:string,r:number}[];rows.sort((x,y)=>y.r-x.r||x.s.localeCompare(y.s));m.set(ex,{risk:sg.marketRiskOn,s:!sg.marketRiskOn&&rows[0]?.r>0?rows[0].s:null});}return m;}
function sleeve(ds:string[],a:Record<string,PricePoint[]>,pl:Map<string,{risk:boolean,s:string|null}>){const pm=Object.fromEntries(Object.entries(a).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))]));let cash=1,pos:{s:string,sh:number}|null=null,risk=true,peak=1;const c:EquityPoint[]=[],rm=new Map<string,boolean>();for(const d of ds){const p=pl.get(d);if(p){if(pos){const px=pm[pos.s]?.get(d)?.open;if(px)cash=pos.sh*px*(1-COST);pos=null;}risk=p.risk;if(!risk&&p.s){const px=pm[p.s]?.get(d)?.open;if(px){pos={s:p.s,sh:cash*(1-COST)/px};cash=0;}}}rm.set(d,risk);let e=cash;if(pos){const px=pm[pos.s]?.get(d)?.close;if(px)e=pos.sh*px;}peak=Math.max(peak,e);c.push({date:d,equity:e,drawdown:e/peak-1});}return{curve:c,risk:rm};}
function combine(coreC:EquityPoint[],macroC:EquityPoint[],risk:Map<string,boolean>,retention=1){const mm=new Map(macroC.map(x=>[x.date,x.equity]));let e=1,peak=1,pc=coreC[0]?.equity??1,pm=mm.get(coreC[0]?.date)??1,pr=risk.get(coreC[0]?.date)??true;const z:EquityPoint[]=[];for(let i=0;i<coreC.length;i++){const d=coreC[i].date,mv=mm.get(d);if(mv==null)continue;const rc=i?coreC[i].equity/pc-1:0;let mr=i?mv/pm-1:0;if(mr>0)mr*=retention;pc=coreC[i].equity;pm=mv;const cr=risk.get(d)??pr;let f=1;if(i)f=cr===pr?1+(cr?rc:mr):(1+rc)*(1+mr);e*=f;pr=cr;peak=Math.max(peak,e);z.push({date:d,equity:e,drawdown:e/peak-1});}return z;}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
async function main(){const mk=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8')) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8')) as {history:UniverseMonth[]},u=[...uf.history].sort((x,y)=>x.asOf.localeCompare(y.asOf)),a:Record<string,PricePoint[]>={};for(const s of ASSETS)a[s]=await yahoo(s);const c=core(mk.histories,u),m=sleeve(c.curve.map(x=>x.date),a,plans(mk.histories,u,a)),combo=combine(c.curve,m.curve,m.risk),years=[2020,2021,2022,2023,2024,2025,2026];const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,pit:true,nextOpen:true,freeDataOnly:true,noLeverage:true,fixed60StrategyId:cfg.strategyId,rule:'During Fixed60 Risk-Off, hold the strongest positive 63-session return among GLD/IEF/UUP/DBC; otherwise cash.',warning:'Historical diagnostic. Macro sleeve concept predates this Fixed60 transfer, but was selected after observing recent historical data.'},fixed60:performanceStats(c.curve),macro3:performanceStats(combo),annual:years.map(y=>({y,fixed60:performanceStats(sl(c.curve,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`)),macro3:performanceStats(sl(combo,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))})),edgeRetention:[1,.75,.5,.25,0].map(r=>({retention:r,stats:performanceStats(combine(c.curve,m.curve,m.risk,r))}))};const d=path.join(process.cwd(),'data/research/forward40-riskoff-macro-fixed60');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});