import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,MonthlySignal,PricePoint,UniverseMonth,StrategyConfig} from '../src/lib/types';

const TAX=.20315;
const F60:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,oneMonth:0,threeMonth:.2,sixMonth:.8},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,maxTop1Weight:.6}} as StrategyConfig;
function consensus(s:MonthlySignal){const e=s.candidates.filter(c=>c.eligible&&c.threeMonth!==null&&c.sixMonth!==null);if(e.length<2)return false;const r3=[...e].sort((a,b)=>(b.threeMonth??-9)-(a.threeMonth??-9)||a.symbol.localeCompare(b.symbol))[0]?.symbol,r6=[...e].sort((a,b)=>(b.sixMonth??-9)-(a.sixMonth??-9)||a.symbol.localeCompare(b.symbol))[0]?.symbol;return !!r3&&r3===r6&&s.selectedSymbols[0]===r3;}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],on:boolean){const q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),ix=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(F60),hits=0;const z:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<F60.backtestStart)continue;const n=ds[i+1]??nextUsTradingSession(d),uu=um.get(d);let sg=uu?buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:n,config:F60}):null;if(sg&&sg.selectedSymbols.length===2){let w=.6;if(on&&consensus(sg)){w=.75;hits++;}sg={...sg,targetWeights:[w,1-w],allocationMode:w===.6?'60/40':'70/30'};}const ss=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),pr=Object.fromEntries([...ss].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices:pr,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},F60);z.push({date:d,equity:st.currentEquity,drawdown:st.drawdown});}return{curve:z,hits};}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}));}
function taxProxy(c:EquityPoint[]){if(!c.length)return[];let carry:{year:number;amt:number}[]=[],wealth=1,peak=1,prev=c[0].equity,ystart=c[0].equity;const out:EquityPoint[]=[];for(let i=0;i<c.length;i++){const p=c[i];if(i){wealth*=p.equity/prev;prev=p.equity}const n=c[i+1],end=!n||n.date.slice(0,4)!==p.date.slice(0,4);if(end){const y=+p.date.slice(0,4),net=p.equity/ystart-1;carry=carry.filter(x=>y-x.year<=3);if(net>0){let taxable=net;for(const x of carry){const q=Math.min(taxable,x.amt);taxable-=q;x.amt-=q;if(taxable<=0)break}carry=carry.filter(x=>x.amt>1e-12);wealth*=Math.max(0,1-taxable*TAX)}else if(net<0)carry.push({year:y,amt:-net});if(n)ystart=n.equity}peak=Math.max(peak,wealth);out.push({date:p.date,equity:wealth,drawdown:wealth/peak-1});}return out;}
function stressed(b:EquityPoint[],c:EquityPoint[],f:number){let e=1,pk=1;const z:EquityPoint[]=[{date:b[0].date,equity:1,drawdown:0}];for(let i=1;i<Math.min(b.length,c.length);i++){const rb=b[i].equity/b[i-1].equity,rc=c[i].equity/c[i-1].equity;e*=Math.exp(Math.log(Math.max(rb,1e-12))+f*(Math.log(Math.max(rc,1e-12))-Math.log(Math.max(rb,1e-12))));pk=Math.max(pk,e);z.push({date:b[i].date,equity:e,drawdown:e/pk-1});}return z;}
async function main(){const mk=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),b=sim(mk.histories,u,false),c=sim(mk.histories,u,true);const years=[2020,2021,2022,2023,2024,2025,2026];const pack=(x:EquityPoint[])=>({full:performanceStats(x),early:performanceStats(sl(x,'2020-01-01','2023-12-31')),late:performanceStats(sl(x,'2024-01-01','2026-08-25')),annual:years.map(y=>({year:y,stats:performanceStats(sl(x,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))}))});const edge=[0,.25,.5,.75,1].map(f=>{const x=stressed(b.curve,c.curve,f);return{retention:f,gross:performanceStats(x),late:performanceStats(sl(x,'2024-01-01','2026-08-25')),afterTaxProxy:performanceStats(taxProxy(x))}});const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,noLeverage:true,pit:true,nextOpen:true,fixed60Core:true,parameterSearch:false,rule:'Fixed60 remains 60/40 except when the selected Top1 is independently rank #1 on both 3M and 6M; then use 75/25. One predeclared conditional weight only.',taxProxy:'20.315% annual positive calendar-year net return with 3-year loss carry; screening proxy only.',edgeRetention:'Sensitivity scaling of candidate-vs-base daily log-return difference; not a probability forecast.'},hits:c.hits,base:pack(b.curve),consensus75:pack(c.curve),afterTaxProxy:{base:pack(taxProxy(b.curve)),consensus75:pack(taxProxy(c.curve))},edgeRetention:edge};const d=path.join(process.cwd(),'data/research/forward40-consensus-fixed60');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
