import fs from 'node:fs/promises';
import path from 'node:path';
import {FIXED60_STRATEGY as cfg} from './lib/fixed60-config';
import {buildMonthlySignal,monthlyCloses,qqqMonthlyGate} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,MomentumCandidate,MonthlySignal,PricePoint,UniverseMonth} from '../src/lib/types';

function avg(a:number[]){return a.length?a.reduce((s,x)=>s+x,0)/a.length:0}function sd(a:number[]){const m=avg(a);return a.length?Math.sqrt(avg(a.map(x=>(x-m)**2))):0}
function retMonth(p:PricePoint[],d:string,m:number){const x=monthlyCloses(p).filter(q=>q.date<=d);if(x.length<=m)return null;const a=x.at(-1)!.close,b=x.at(-(m+1))!.close;return a/b-1}
function betaAndResidual(h:PricePoint[],q:PricePoint[],d:string,look=126){const hm=new Map(h.filter(x=>x.date<=d).map(x=>[x.date,x.close])),qm=new Map(q.filter(x=>x.date<=d).map(x=>[x.date,x.close]));const dates=[...qm.keys()].filter(x=>hm.has(x)).sort().slice(-(look+1));if(dates.length<100)return null;const ar:number[]=[],mr:number[]=[];for(let i=1;i<dates.length;i++){const a0=hm.get(dates[i-1])!,a1=hm.get(dates[i])!,m0=qm.get(dates[i-1])!,m1=qm.get(dates[i])!;if(a0>0&&a1>0&&m0>0&&m1>0){ar.push(Math.log(a1/a0));mr.push(Math.log(m1/m0))}}if(ar.length<90)return null;const ma=avg(ar),mm=avg(mr),v=avg(mr.map(x=>(x-mm)**2));if(v<=0)return null;const b=avg(ar.map((x,i)=>(x-ma)*(mr[i]-mm)))/v;const residual=ar.map((x,i)=>x-b*mr[i]);const s3=residual.slice(-63).reduce((s,x)=>s+x,0),s6=residual.reduce((s,x)=>s+x,0);return{beta:b,r3:Math.exp(s3)-1,r6:Math.exp(s6)-1}}
function residualSignal(u:UniverseMonth,h:Record<string,PricePoint[]>,q:PricePoint[],next:string|null,w3:number,w6:number):MonthlySignal{const d=u.asOf,g=qqqMonthlyGate(q,d,cfg);const rows:MomentumCandidate[]=u.symbols.map(({symbol})=>{const hp=h[symbol]??[],r1=retMonth(hp,d,1),r3=retMonth(hp,d,3),r6=retMonth(hp,d,6),z=betaAndResidual(hp,q,d);if(r1==null||r3==null||r6==null||!z)return{symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:null,qqqScore:0,scoreSpread:null,eligible:false,exclusionReason:'INSUFFICIENT_PRICE_HISTORY',rank:null};const score=w3*z.r3+w6*z.r6,reason=r1>=cfg.momentum.surgeLimit?'ONE_MONTH_SURGE':score<=0?'NOT_ABOVE_QQQ':null;return{symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score,qqqScore:0,scoreSpread:score,eligible:reason===null,exclusionReason:reason,rank:null}});const e=rows.filter((x):x is MomentumCandidate&{score:number}=>x.eligible&&x.score!=null).sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol));e.forEach((x,i)=>x.rank=i+1);const s=g.riskOn?e.slice(0,2):[],ok=s.length===2,disp=sd(e.map(x=>x.score)),zg=ok&&disp>0?(s[0].score-s[1].score)/disp:ok?0:null;return{strategyId:cfg.strategyId,signalMonth:u.signalMonth,signalDate:d,executionDate:next,marketRiskOn:g.riskOn,qqqClose:g.close,qqqMonthlyMa:g.ma,qqqScore:0,universe:u.symbols.map(x=>x.symbol),candidates:rows.sort((a,b)=>(a.rank??9999)-(b.rank??9999)||(b.score??-Infinity)-(a.score??-Infinity)),selectedSymbols:ok?s.map(x=>x.symbol):[],targetWeights:ok?[.6,.4]:[],zGap:zg,allocationMode:ok?'50/50':'CASH'} }
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],mode:'BASE'|'R25'|'R50'){const q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),ix=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg);const z:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<cfg.backtestStart)continue;const n=ds[i+1]??nextUsTradingSession(d),uu=um.get(d);let sg:MonthlySignal|null=null;if(uu)sg=mode==='BASE'?buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:n,config:cfg}):residualSignal(uu,h,q,n,mode==='R25'?.25:.5,mode==='R25'?.75:.5);const ss=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),pr=Object.fromEntries([...ss].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices:pr,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},cfg);z.push({date:d,equity:st.currentEquity,drawdown:st.drawdown})}return z}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function corr(a:EquityPoint[],b:EquityPoint[]){const bm=new Map(b.map(p=>[p.date,p.equity]));const x:number[]=[],y:number[]=[];let pa:number|null=null,pb:number|null=null;for(const p of a){const bv=bm.get(p.date);if(bv==null)continue;if(pa!==null&&pb!==null&&pa>0&&pb>0){x.push(p.equity/pa-1);y.push(bv/pb-1)}pa=p.equity;pb=bv;}if(x.length<2)return null;const mx=avg(x),my=avg(y);let n=0,dx=0,dy=0;for(let i=0;i<x.length;i++){const u=x[i]-mx,v=y[i]-my;n+=u*v;dx+=u*u;dy+=v*v}return dx&&dy?n/Math.sqrt(dx*dy):null;}
async function main(){const mk=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const curves={BASE:sim(mk.histories,u,'BASE'),R25:sim(mk.histories,u,'R25'),R50:sim(mk.histories,u,'R50')};const modes=['BASE','R25','R50'] as const,annual=modes.map(m=>({mode:m,full:performanceStats(curves[m]),correlationToFixed60:m==='BASE'?1:corr(curves.BASE,curves[m]),years:[2020,2021,2022,2023,2024,2025,2026].map(y=>({y,stats:performanceStats(sl(curves[m],`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))}))})),splits=[{tr:'2021-12-31',y:2022},{tr:'2022-12-31',y:2023},{tr:'2023-12-31',y:2024},{tr:'2024-12-31',y:2025},{tr:'2025-12-31',y:2026}],wf=splits.map(s=>{const ranked=modes.map(m=>({m,train:performanceStats(sl(curves[m],'2020-01-01',s.tr))})).sort((a,b)=>(b.train.calmar??-99)-(a.train.calmar??-99)),pick=ranked[0].m,e=s.y===2026?'2026-08-25':`${s.y}-12-31`;return{trainThrough:s.tr,oosYear:s.y,pick,oos:performanceStats(sl(curves[pick],`${s.y}-01-01`,e)),base:performanceStats(sl(curves.BASE,`${s.y}-01-01`,e)),train:ranked}}),o={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,pit:true,nextOpen:true,freeDataOnly:true,noLeverage:true,fixed60StrategyId:cfg.strategyId,variantsPredeclared:['R25','R50'],warning:'Residual momentum retrospective screen. Beta estimated from trailing 126 daily log returns; only two pre-existing residual weight variants.'},annual,wf};const d=path.join(process.cwd(),'data/research/forward40-residual-momentum-fixed60');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(o,null,2));console.log(JSON.stringify(o,null,2))}main().catch(e=>{console.error(e);process.exit(1)});