import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay,type EngineState} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,MonthlySignal,PositionState,PricePoint,UniverseMonth,StrategyConfig} from '../src/lib/types';

const TAX=.20315;
const F60:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,oneMonth:0,threeMonth:.2,sixMonth:.8},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,maxTop1Weight:.6}} as StrategyConfig;
type Ledger={gain:Record<string,number>;loss:Record<string,number>;taxes:number;sales:number;turnover:number;fullRebalances:number;skippedSameSet:number};
const sameSet=(a:string[],b:string[])=>[...a].sort().join(',')===[...b].sort().join(',');
function normalize(sig:MonthlySignal){if(sig.selectedSymbols.length===2)return{...sig,targetWeights:[.6,.4],allocationMode:'60/40' as any,zGap:null};return sig;}
function recordSale(l:Ledger,p:PositionState,px:number,date:string){const proceeds=p.shares*px*(1-F60.execution.transactionCost),basis=p.shares*p.entryPrice,pnl=proceeds-basis,y=date.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++;l.turnover+=proceeds;}
function taxCurve(curve:EquityPoint[],l:Ledger){if(!curve.length)return[];const years=[...new Set(curve.map(p=>p.date.slice(0,4)))],ty:Record<string,number>={};let carry:{y:number;a:number}[]=[];for(const ys of years){const y=+ys;carry=carry.filter(x=>y-x.y<=3);let net=(l.gain[ys]??0)-(l.loss[ys]??0);if(net>0){for(const x of carry){const u=Math.min(net,x.a);net-=u;x.a-=u;if(net<=0)break}carry=carry.filter(x=>x.a>1e-12);ty[ys]=net*TAX}else if(net<0)carry.push({y,a:-net})}l.taxes=Object.values(ty).reduce((a,b)=>a+b,0);let e=curve[0].equity,pg=e,peak=e;const out:EquityPoint[]=[];for(let i=0;i<curve.length;i++){const p=curve[i];if(i)e*=p.equity/pg;pg=p.equity;const n=curve[i+1];if((!n||n.date.slice(0,4)!==p.date.slice(0,4))&&(ty[p.date.slice(0,4)]??0)>0)e=Math.max(0,e-(ty[p.date.slice(0,4)]??0)*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);out.push({date:p.date,equity:e,drawdown:e/peak-1})}return out;}
function sim(hist:Record<string,PricePoint[]>,universe:UniverseMonth[],noChurn:boolean){const q=[...hist.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(universe.map(u=>[u.asOf,u]));let state:EngineState=initialEngineState(F60);const curve:EquityPoint[]=[],l:Ledger={gain:{},loss:{},taxes:0,sales:0,turnover:0,fullRebalances:0,skippedSameSet:0};for(let i=0;i<dates.length;i++){const date=dates[i];if(date<F60.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),u=um.get(date);let sig=u?normalize(buildMonthlySignal({universe:u,histories:hist,qqq:q,nextSessionDate:next,config:F60})):null;const sy=new Set(['QQQ',...state.currentPositions.map(p=>p.symbol),...(state.pendingSignal?.selectedSymbols??[]),...state.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));if(noChurn&&state.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN'&&state.nextAction.executionDate===date&&state.pendingSignal&&state.currentPositions.length===2&&sameSet(state.currentPositions.map(p=>p.symbol),state.pendingSignal.selectedSymbols)){l.skippedSameSet++;state.nextAction={type:'HOLD',executionDate:null,symbols:state.currentPositions.map(p=>p.symbol),targetWeights:state.currentPositions.map(p=>p.targetWeight),reason:'Research Fixed60 no-churn same-set hold'};}const before=structuredClone(state);state=transitionDay(state,{date,prices,qqqHistoryThroughClose:q.slice(0,(idx.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},F60);const hadExit=before.currentPositions.length>0&&before.nextAction.type==='SELL_ALL_NEXT_OPEN'&&before.nextAction.executionDate===date;const hadRebal=before.currentPositions.length>0&&before.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN'&&before.nextAction.executionDate===date;if(hadExit||hadRebal){for(const p of before.currentPositions)recordSale(l,p,prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice,date);if(hadRebal)l.fullRebalances++;}curve.push({date,equity:state.currentEquity,drawdown:state.drawdown})}return{curve,afterTax:taxCurve(curve,l),ledger:l};}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function pack(x:ReturnType<typeof sim>){return{gross:performanceStats(x.curve),afterTax:performanceStats(x.afterTax),sales:x.ledger.sales,turnover:x.ledger.turnover,taxPaidApprox:x.ledger.taxes,fullRebalances:x.ledger.fullRebalances,skippedSameSet:x.ledger.skippedSameSet};}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8')) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8')) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),b=sim(market.histories,u,false),n=sim(market.histories,u,true),years=[2020,2021,2022,2023,2024,2025,2026];const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,pit:true,noLeverage:true,nextOpen:true,parameterSearch:false,rule:'Fixed60 0/20/80, 60/40. If next month selects the same Top2 set, skip the full month-end sell/rebuy and continue holding current shares. All other gate/Stop/Circuit/Recovery logic unchanged.',taxApprox:'20.315% annual realized P&L with 3-year loss carry; not exact broker tax lots/withholding.'},baseline:pack(b),noChurn:pack(n),early:{baseline:performanceStats(sl(b.afterTax,'2020-01-01','2023-12-31')),noChurn:performanceStats(sl(n.afterTax,'2020-01-01','2023-12-31'))},late:{baseline:performanceStats(sl(b.afterTax,'2024-01-01','2026-08-25')),noChurn:performanceStats(sl(n.afterTax,'2024-01-01','2026-08-25'))},annual:years.map(y=>({year:y,baseline:performanceStats(sl(b.afterTax,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`)),noChurn:performanceStats(sl(n.afterTax,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))}))};const d=path.join(process.cwd(),'data/research/forward40-nochurn-fixed60');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
