import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,MonthlySignal,PositionState,PricePoint,UniverseMonth,StrategyConfig} from '../src/lib/types';

const TAX=.20315;
const F60:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,oneMonth:0,threeMonth:.2,sixMonth:.8},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,maxTop1Weight:.6}} as StrategyConfig;
type Ledger={gain:Record<string,number>;loss:Record<string,number>;taxes:number;sales:number;turnover:number};
function consensus(sig:MonthlySignal){const e=sig.candidates.filter(c=>c.eligible&&c.threeMonth!==null&&c.sixMonth!==null);if(e.length<2)return false;const r3=[...e].sort((a,b)=>(b.threeMonth??-9)-(a.threeMonth??-9)||a.symbol.localeCompare(b.symbol))[0]?.symbol,r6=[...e].sort((a,b)=>(b.sixMonth??-9)-(a.sixMonth??-9)||a.symbol.localeCompare(b.symbol))[0]?.symbol;return !!r3&&r3===r6&&sig.selectedSymbols[0]===r3;}
function sale(l:Ledger,p:PositionState,px:number,date:string){const proceeds=p.shares*px*(1-F60.execution.transactionCost),basis=p.shares*p.entryPrice,pnl=proceeds-basis,y=date.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++;l.turnover+=proceeds;}
function taxCurve(curve:EquityPoint[],l:Ledger){if(!curve.length)return[];const years=[...new Set(curve.map(p=>p.date.slice(0,4)))],ty:Record<string,number>={};let carry:{y:number;a:number}[]=[];for(const ys of years){const y=+ys;carry=carry.filter(x=>y-x.y<=3);let net=(l.gain[ys]??0)-(l.loss[ys]??0);if(net>0){for(const x of carry){const u=Math.min(net,x.a);net-=u;x.a-=u;if(net<=0)break}carry=carry.filter(x=>x.a>1e-12);ty[ys]=net*TAX}else if(net<0)carry.push({y,a:-net})}l.taxes=Object.values(ty).reduce((a,b)=>a+b,0);let e=curve[0].equity,pg=e,peak=e;const out:EquityPoint[]=[];for(let i=0;i<curve.length;i++){const p=curve[i];if(i)e*=p.equity/pg;pg=p.equity;const n=curve[i+1];if((!n||n.date.slice(0,4)!==p.date.slice(0,4))&&(ty[p.date.slice(0,4)]??0)>0)e=Math.max(0,e-(ty[p.date.slice(0,4)]??0)*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);out.push({date:p.date,equity:e,drawdown:e/peak-1})}return out;}
function sim(hist:Record<string,PricePoint[]>,universe:UniverseMonth[],on:boolean,disableYear:number|null=null){const q=[...hist.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(universe.map(u=>[u.asOf,u]));let st=initialEngineState(F60),hits=0;const curve:EquityPoint[]=[],hitMonths:string[]=[],l:Ledger={gain:{},loss:{},taxes:0,sales:0,turnover:0};for(let i=0;i<dates.length;i++){const date=dates[i];if(date<F60.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),u=um.get(date);let sig=u?buildMonthlySignal({universe:u,histories:hist,qqq:q,nextSessionDate:next,config:F60}):null;if(sig&&sig.selectedSymbols.length===2){let w=.6;if(on&&consensus(sig)&&Number(date.slice(0,4))!==disableYear){w=.75;hits++;hitMonths.push(date)}sig={...sig,targetWeights:[w,1-w],allocationMode:w===.75?'75/25' as any:'60/40'};}const sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));const before=structuredClone(st);st=transitionDay(st,{date,prices,qqqHistoryThroughClose:q.slice(0,(idx.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},F60);if(before.currentPositions.length&&((before.nextAction.type==='SELL_ALL_NEXT_OPEN'||before.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN')&&before.nextAction.executionDate===date)){for(const p of before.currentPositions)sale(l,p,prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice,date)}curve.push({date,equity:st.currentEquity,drawdown:st.drawdown})}return{curve,afterTax:taxCurve(curve,l),ledger:l,hits,hitMonths};}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8')) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8')) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),b=sim(market.histories,u,false),c=sim(market.histories,u,true);const years=[2020,2021,2022,2023,2024,2025,2026];const loo=years.map(y=>{const x=sim(market.histories,u,true,y);return{disabledYear:y,gross:performanceStats(x.curve),afterTax:performanceStats(x.afterTax)}});const pack=(id:string,x:ReturnType<typeof sim>)=>({id,gross:performanceStats(x.curve),afterTax:performanceStats(x.afterTax),taxPaidApprox:x.ledger.taxes,sales:x.ledger.sales,turnover:x.ledger.turnover,hits:x.hits});const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,noLeverage:true,pit:true,nextOpen:true,parameterSearch:false,rule:'Fixed60 0/20/80 and normal 60/40. Only when selected Top1 independently ranks #1 on both 3M and 6M, use 75/25 for that monthly signal.',taxApprox:'20.315% annual realized P&L with 3-year loss carry; not exact broker tax lots.'},full:[pack('FIXED60',b),pack('FIXED60_CONS75',c)],early:{base:performanceStats(sl(b.afterTax,'2020-01-01','2023-12-31')),candidate:performanceStats(sl(c.afterTax,'2020-01-01','2023-12-31'))},late:{base:performanceStats(sl(b.afterTax,'2024-01-01','2026-08-25')),candidate:performanceStats(sl(c.afterTax,'2024-01-01','2026-08-25'))},annual:years.map(y=>({year:y,base:performanceStats(sl(b.afterTax,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`)),candidate:performanceStats(sl(c.afterTax,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))})),leaveOneYearOut:loo,hitMonths:c.hitMonths};const d=path.join(process.cwd(),'data/research/forward40-consensus75-fixed60');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
