import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,PricePoint,UniverseMonth,StrategyConfig} from '../src/lib/types';

const TAX=.20315;
const F60:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,oneMonth:0,threeMonth:.2,sixMonth:.8},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,maxTop1Weight:.6}} as StrategyConfig;
function cfg(cost:number):StrategyConfig{return {...F60,execution:{...F60.execution,transactionCost:cost}} as StrategyConfig}
async function yahoo(s:string,start='2007-01-01'){const p1=Math.floor(Date.parse(start+'T00:00:00Z')/1000),p2=Math.floor(Date.parse('2026-09-01T00:00:00Z')/1000);const r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${s}?period1=${p1}&period2=${p2}&interval=1d&events=div%2Csplits&includeAdjustedClose=true`,{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error(`${s}:${r.status}`);const j:any=await r.json(),x=j.chart.result?.[0],q=x?.indicators?.quote?.[0],ad=x?.indicators?.adjclose?.[0]?.adjclose??[];const out:PricePoint[]=[];for(let i=0;i<(x?.timestamp?.length??0);i++){if(q.open[i]==null||q.close[i]==null||ad[i]==null)continue;const k=ad[i]/q.close[i];out.push({date:new Date(x.timestamp[i]*1000).toISOString().slice(0,10),open:q.open[i]*k,close:ad[i]});}return out}
function slice(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function core(hist:Record<string,PricePoint[]>,u:UniverseMonth[],c:StrategyConfig){const q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(p=>p.date),di=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(c);const z:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<c.backtestStart)continue;const nx=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?buildMonthlySignal({universe:uu,histories:hist,qqq:q,nextSessionDate:nx,config:c}):null;if(sg&&sg.selectedSymbols.length===2){sg.targetWeights=[.6,.4];sg.allocationMode='60/40'}const sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),pr=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices:pr,qqqHistoryThroughClose:q.slice(0,(di.get(d)??i)+1),monthlySignal:sg,nextSessionDate:nx},c);z.push({date:d,equity:st.currentEquity,drawdown:st.drawdown})}return z}
function gate(hist:Record<string,PricePoint[]>,u:UniverseMonth[],c:StrategyConfig,delay:number){const q=[...hist.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(p=>p.date),di=new Map(ds.map((d,i)=>[d,i])),events=new Map<string,boolean>();for(const um of u){if(um.asOf<c.backtestStart)continue;const i=di.get(um.asOf),ex=i==null?nextUsTradingSession(um.asOf):(ds[i+1+delay]??null);if(!ex)continue;const sg=buildMonthlySignal({universe:um,histories:hist,qqq:q,nextSessionDate:ex,config:c});events.set(ex,sg.marketRiskOn)}let on=true;const out=new Map<string,boolean>();for(const d of ds.filter(d=>d>=c.backtestStart)){if(events.has(d))on=events.get(d)!;out.set(d,on)}return out}
function goldCurve(ds:string[],gld:PricePoint[],g:Map<string,boolean>,cost:number){const pm=new Map(gld.map(p=>[p.date,p]));let cash=1,sh=0,peak=1,prevOn=true;const out:EquityPoint[]=[];for(const d of ds){const on=g.get(d)??prevOn;if(on!==prevOn){const p=pm.get(d);if(p){if(on&&sh>0){cash=sh*p.open*(1-cost);sh=0}else if(!on&&cash>0){sh=cash*(1-cost)/p.open;cash=0}}}prevOn=on;let e=cash;if(sh>0){const p=pm.get(d);if(p)e=sh*p.close}peak=Math.max(peak,e);out.push({date:d,equity:e,drawdown:e/peak-1})}return out}
function combine(c:EquityPoint[],gld:EquityPoint[],g:Map<string,boolean>){const gm=new Map(gld.map(p=>[p.date,p.equity]));let e=1,peak=1,pc=c[0]?.equity??1,pg=gm.get(c[0]?.date)??1;const z:EquityPoint[]=[];for(let i=0;i<c.length;i++){const d=c[i].date,gv=gm.get(d);if(gv==null)continue;const rc=i?c[i].equity/pc-1:0,rg=i?gv/pg-1:0;pc=c[i].equity;pg=gv;e*=1+(g.get(d)?rc:rg);peak=Math.max(peak,e);z.push({date:d,equity:e,drawdown:e/peak-1})}return z}
function taxProxy(c:EquityPoint[]){if(!c.length)return[];let carry:{y:number,a:number}[]=[],wealth=1,peak=1,prev=c[0].equity,ys=c[0].equity;const out:EquityPoint[]=[];for(let i=0;i<c.length;i++){const p=c[i];if(i){wealth*=p.equity/prev;prev=p.equity}const n=c[i+1],end=!n||n.date.slice(0,4)!==p.date.slice(0,4);if(end){const y=+p.date.slice(0,4),net=p.equity/ys-1;carry=carry.filter(x=>y-x.y<=3);if(net>0){let t=net;for(const x of carry){const u=Math.min(t,x.a);t-=u;x.a-=u;if(t<=0)break}carry=carry.filter(x=>x.a>1e-12);wealth*=Math.max(0,1-t*TAX)}else if(net<0)carry.push({y,a:-net});if(n)ys=n.equity}peak=Math.max(peak,wealth);out.push({date:p.date,equity:wealth,drawdown:wealth/peak-1})}return out}
function report(c:EquityPoint[]){return{full:performanceStats(c),early:performanceStats(slice(c,'2020-01-01','2023-12-31')),late:performanceStats(slice(c,'2024-01-01','2026-08-25')),annual:[2020,2021,2022,2023,2024,2025,2026].map(y=>({y,...performanceStats(slice(c,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))}))}}
function monthEnd(p:PricePoint[]){const m=new Map<string,PricePoint>();for(const x of p)m.set(x.date.slice(0,7),x);return[...m.values()].sort((a,b)=>a.date.localeCompare(b.date))}
function longGold(q:PricePoint[],gld:PricePoint[],cost:number){const qm=monthEnd(q),pm=new Map(gld.map(p=>[p.date,p]));let cash=1,sh=0,peak=1;const z:EquityPoint[]=[];for(let i=9;i<qm.length;i++){const sig=qm[i],ma=qm.slice(i-9,i+1).reduce((a,b)=>a+b.close,0)/10,on=sig.close>ma,ex=nextUsTradingSession(sig.date);const px=pm.get(ex);if(px){if(sh>0){cash=sh*px.open*(1-cost);sh=0}if(!on){sh=cash*(1-cost)/px.open;cash=0}}const end=qm[i+1]?.date??'2026-08-25';for(const d of q.filter(x=>x.date>=ex&&x.date<=end).map(x=>x.date)){let e=cash;if(sh>0){const p=pm.get(d);if(p)e=sh*p.close}peak=Math.max(peak,e);z.push({date:d,equity:e,drawdown:e/peak-1})}}return z}
async function main(){const mk=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8')) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8')) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),gld=await yahoo('GLD'),qLong=await yahoo('QQQ');const scenarios=[] as any[];for(const bp of [10,30]){const c=cfg(bp/10000),b=core(mk.histories,u,c);for(const delay of [0,1]){if(bp===30&&delay===1)continue;const gt=gate(mk.histories,u,c,delay),gc=goldCurve(b.map(x=>x.date),gld,gt,c.execution.transactionCost),x=combine(b,gc,gt);scenarios.push({bpPerSide:bp,delaySessions:delay,gross:report(x),afterTaxProxy:report(taxProxy(x))})}if(bp===10)scenarios.push({role:'FIXED60_CASH_CORE',bpPerSide:bp,delaySessions:0,gross:report(b),afterTaxProxy:report(taxProxy(b))})}const lg=longGold(qLong,gld,.001),out={generatedAt:new Date().toISOString(),rule:'Fixed60 unchanged in Risk-On; 100% GLD in monthly QQQ 10M-MA Risk-Off; signal close -> next open; no GLD momentum filter.',validity:{researchOnly:true,trueOOS:false,noLeverage:true,pitGate:true,architectureHindsightRemains:true,taxProxy:'20.315% positive calendar-year net return with 3y loss carry; screening proxy, not exact tax lots.'},scenarios,longGoldOnly:{p0812:performanceStats(slice(lg,'2008-01-01','2012-12-31')),p1319:performanceStats(slice(lg,'2013-01-01','2019-12-31')),p2026:performanceStats(slice(lg,'2020-01-01','2026-08-25')),full:performanceStats(lg)}};const d=path.join(process.cwd(),'data/research/forward40-riskoff-gold-fixed60');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}
main().catch(e=>{console.error(e);process.exit(1)});