import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {PricePoint,UniverseMonth,StrategyConfig} from '../src/lib/types';

const F60:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,oneMonth:0,threeMonth:.2,sixMonth:.8},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,maxTop1Weight:.6}} as StrategyConfig;
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:null;
function ranks(a:number[]){const o=a.map((v,i)=>({v,i})).sort((x,y)=>x.v-y.v),r=Array(a.length).fill(0);for(let i=0;i<o.length;){let j=i;while(j+1<o.length&&o[j+1].v===o[i].v)j++;const q=(i+j)/2+1;for(let k=i;k<=j;k++)r[o[k].i]=q;i=j+1}return r}
function corr(x:number[],y:number[]){if(x.length<4)return null;const mx=x.reduce((a,b)=>a+b,0)/x.length,my=y.reduce((a,b)=>a+b,0)/y.length;let n=0,dx=0,dy=0;for(let i=0;i<x.length;i++){const a=x[i]-mx,b=y[i]-my;n+=a*b;dx+=a*a;dy+=b*b}return dx>0&&dy>0?n/Math.sqrt(dx*dy):null}
const spear=(x:number[],y:number[])=>corr(ranks(x),ranks(y));
function proximity(ps:PricePoint[],d:string){const x=ps.filter(p=>p.date<=d).slice(-252);if(x.length<200)return null;const c=x.at(-1)!.close,h=Math.max(...x.map(p=>p.close));return h>0?c/h:null}
function future(ps:PricePoint[],d:string,n:number){const i=ps.findIndex(p=>p.date===d);if(i<0||i+1>=ps.length||i+n>=ps.length)return null;const s=ps[i+1].open??ps[i+1].close,e=ps[i+n].close;return s&&e&&s>0?e/s-1:null}
function summary(rows:any[],a:string,b:string){const x=rows.filter(r=>r.date>=a&&r.date<=b),m=x.filter(r=>r.ic21!=null&&r.ic63!=null);return{months:m.length,meanIC21:mean(m.map(r=>r.ic21)),meanIC63:mean(m.map(r=>r.ic63)),positiveIC21Share:m.length?m.filter(r=>r.ic21>0).length/m.length:null,positiveIC63Share:m.length?m.filter(r=>r.ic63>0).length/m.length:null,meanCoverage:mean(m.map(r=>r.n/10))}}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8')) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8')) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),q=[...market.histories.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),rows:any[]=[];for(const um of u){if(um.asOf<'2020-01-01'||um.asOf>'2026-08-25')continue;const sig=buildMonthlySignal({universe:um,histories:market.histories,qqq:q,nextSessionDate:nextUsTradingSession(um.asOf),config:F60});if(!sig.marketRiskOn)continue;const top=sig.candidates.filter(c=>c.eligible&&c.score!=null).sort((a,b)=>(b.score??-Infinity)-(a.score??-Infinity)||a.symbol.localeCompare(b.symbol)).slice(0,10),z:{p:number;r21:number;r63:number}[]=[];for(const c of top){const ps=market.histories[c.symbol]??[],p=proximity(ps,um.asOf),r21=future(ps,um.asOf,21),r63=future(ps,um.asOf,63);if(p!=null&&r21!=null&&r63!=null)z.push({p,r21,r63})}rows.push({date:um.asOf,n:z.length,ic21:z.length>=4?spear(z.map(v=>v.p),z.map(v=>v.r21)):null,ic63:z.length>=4?spear(z.map(v=>v.p),z.map(v=>v.r63)):null})}const early=summary(rows,'2020-01-01','2023-12-31'),late=summary(rows,'2024-01-01','2026-08-25');const pass=early.months>=18&&late.months>=12&&(early.meanIC21??-1)>0&&(early.meanIC63??-1)>0&&(late.meanIC21??-1)>0&&(late.meanIC63??-1)>0&&(early.positiveIC21Share??0)>.5&&(early.positiveIC63Share??0)>.5&&(late.positiveIC21Share??0)>.5&&(late.positiveIC63Share??0)>.5;const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,pit:true,parameterSearch:false,hypothesis:'Within Fixed60 0/20/80 eligible Momentum Top10, greater closeness to the trailing 252-session high predicts higher next-21 and next-63-session return.',measure:'signal-close / maximum close over up to trailing 252 sessions, requiring >=200 observations; only data <= signal close.',future:'next US session open to 21st/63rd session close.',passGate:'Positive mean monthly Spearman IC and >50% positive-IC month share for both 21d and 63d horizons in both 2020-23 and 2024-26; minimum 18/12 valid months.'},early2020_2023:early,late2024_2026:late,passGate:pass,monthly:rows};const d=path.join(process.cwd(),'data/research/forward40-52week-high-diagnostic');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({...out,monthly:undefined},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
