import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,PricePoint,UniverseMonth,StrategyConfig} from '../src/lib/types';

const TAX=0.20315;
const F60:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,oneMonth:0,threeMonth:.2,sixMonth:.8},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,maxTop1Weight:.6}} as StrategyConfig;
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
function cfg(cost:number):StrategyConfig{return {...F60,execution:{...F60.execution,transactionCost:cost}} as StrategyConfig}
function slice(c:EquityPoint[],start:string,end:string){const x=c.filter(p=>p.date>=start&&p.date<=end);if(!x.length)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function core(hist:Record<string,PricePoint[]>,u:UniverseMonth[],c:StrategyConfig){const q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(c);const curve:EquityPoint[]=[];for(let i=0;i<dates.length;i++){const d=dates[i];if(d<c.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(d),uu=um.get(d),sig=uu?buildMonthlySignal({universe:uu,histories:hist,qqq:q,nextSessionDate:next,config:c}):null;if(sig&&sig.selectedSymbols.length===2){sig.targetWeights=[.6,.4];sig.allocationMode='60/40'}const sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(idx.get(d)??i)+1),monthlySignal:sig,nextSessionDate:next},c);curve.push({date:d,equity:st.currentEquity,drawdown:st.drawdown})}return curve}
function score(ps:PricePoint[],d:string){const x=ps.filter(p=>p.date<=d);if(x.length<201)return null;const close=x.at(-1)!.close,r6=close/x.at(-127)!.close-1,ma=mean(x.slice(-200).map(p=>p.close)),z=x.slice(-61),lr=z.slice(1).map((p,i)=>Math.log(p.close/z[i].close)),mu=mean(lr),vol=Math.sqrt(mean(lr.map(v=>(v-mu)**2))*252);return{r6,close,ma,score:vol>0?r6/vol:-Infinity}}
function schedule(hist:Record<string,PricePoint[]>,u:UniverseMonth[],c:StrategyConfig,delay:number){const q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(p=>p.date),di=new Map(dates.map((d,i)=>[d,i])),m=new Map<string,{risk:boolean,syms:string[]}>();for(const um of u){if(um.asOf<c.backtestStart)continue;const i=di.get(um.asOf);const exec=i==null?nextUsTradingSession(um.asOf):(dates[i+1+delay]??null);if(!exec)continue;const sig=buildMonthlySignal({universe:um,histories:hist,qqq:q,nextSessionDate:exec,config:c});let syms:string[]=[];if(!sig.marketRiskOn)syms=um.symbols.map(x=>{const z=score(hist[x.symbol]??[],um.asOf);return z&&z.r6>0&&z.close>z.ma?{s:x.symbol,v:z.score}:null}).filter((x):x is {s:string;v:number}=>x!==null).sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s)).slice(0,2).map(x=>x.s);m.set(exec,{risk:sig.marketRiskOn,syms})}return m}
function combined(hist:Record<string,PricePoint[]>,u:UniverseMonth[],base:EquityPoint[],expo:number,c:StrategyConfig,delay:number){const dates=base.map(p=>p.date),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),pl=schedule(hist,u,c,delay);let risk=true,cash=1,pos:{s:string;sh:number}[]=[],sleevePrev=1,corePrev=base[0]?.equity??1,total=1,peak=1;const out:EquityPoint[]=[];for(let i=0;i<dates.length;i++){const d=dates[i],p=pl.get(d);if(p){if(pos.length){for(const x of pos){const px=pm[x.s]?.get(d)?.open;if(px)cash+=x.sh*px*(1-c.execution.transactionCost)}pos=[]}risk=p.risk;if(!risk&&p.syms.length===2){const amt=cash*expo;cash-=amt;for(const s of p.syms){const px=pm[s]?.get(d)?.open;if(px)pos.push({s,sh:amt*.5*(1-c.execution.transactionCost)/px});else cash+=amt*.5}}}let sleeve=cash;for(const x of pos){const px=pm[x.s]?.get(d)?.close;if(px)sleeve+=x.sh*px}const rs=i?sleeve/sleevePrev-1:0;sleevePrev=sleeve;const rc=i?base[i].equity/corePrev-1:0;corePrev=base[i].equity;total*=1+(risk?rc:rs);peak=Math.max(peak,total);out.push({date:d,equity:total,drawdown:total/peak-1})}return out}
// Conservative, consistent comparison proxy: tax positive calendar-year net gains at 20.315%, with 3y loss carry.
// This is intentionally not claimed as exact tax-lot accounting; it is used only for candidate-vs-core screening.
function taxProxy(c:EquityPoint[]){if(!c.length)return[];let carry:{year:number;amt:number}[]=[],wealth=1,peak=1;const out:EquityPoint[]=[];let prevGross=c[0].equity,year=c[0].date.slice(0,4),yearStartGross=c[0].equity;for(let i=0;i<c.length;i++){const p=c[i];if(i){wealth*=p.equity/prevGross;prevGross=p.equity}const next=c[i+1],end=!next||next.date.slice(0,4)!==p.date.slice(0,4);if(end){const y=+p.date.slice(0,4),net=p.equity/yearStartGross-1;carry=carry.filter(x=>y-x.year<=3);if(net>0){let taxable=net;for(const x of carry){const z=Math.min(taxable,x.amt);taxable-=z;x.amt-=z;if(taxable<=0)break}carry=carry.filter(x=>x.amt>1e-12);wealth*=Math.max(0,1-taxable*TAX)}else if(net<0)carry.push({year:y,amt:-net});if(next){year=next.date.slice(0,4);yearStartGross=next.equity}}peak=Math.max(peak,wealth);out.push({date:p.date,equity:wealth,drawdown:wealth/peak-1})}return out}
function report(c:EquityPoint[]){return{full:performanceStats(c),early:performanceStats(slice(c,'2020-01-01','2023-12-31')),late:performanceStats(slice(c,'2024-01-01','2026-08-25')),annual:[2020,2021,2022,2023,2024,2025,2026].map(y=>({year:y,stats:performanceStats(slice(c,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))}))}}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8')) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8')) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const scenarios=[] as any[];for(const bp of [10,30]){const c=cfg(bp/10000),b=core(market.histories,u,c);for(const expo of [.5,1])for(const delay of [0,1]){if((bp===30||delay===1)&&expo===1)continue;const x=combined(market.histories,u,b,expo,c,delay);scenarios.push({bpPerSide:bp,expo,delaySessions:delay,gross:report(x),afterTaxProxy:report(taxProxy(x))})}if(bp===10)scenarios.push({bpPerSide:bp,expo:0,delaySessions:0,gross:report(b),afterTaxProxy:report(taxProxy(b)),role:'FIXED60_CORE'})}const output={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,pit:true,noLeverage:true,nextOpen:true,architectureHindsightRemains:true,fixed60Core:true,taxProxy:'20.315% on positive calendar-year net return with 3-year loss carry; conservative screening proxy, not exact realized tax lots.',predeclared:'Risk-off equity sleeve only; 50% and 100% exposure. Stress only 50% sleeve at 30bp and +1 session to avoid post-hoc grid.'},rule:'When Fixed60 monthly QQQ gate is Risk-Off, select up to Top2 PIT-universe equities with positive 6M return and price > 200DMA, ranked by 6M return / 60D realized volatility; equal-weight. Fixed60 is untouched in Risk-On periods.',scenarios};const dir=path.join(process.cwd(),'data/research/forward40-riskoff-equity-fixed60');await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'result.json'),JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2))}
main().catch(e=>{console.error(e);process.exit(1)});