import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay,type EngineState} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,MonthlySignal,PositionState,PricePoint,UniverseMonth,StrategyConfig} from '../src/lib/types';

const TAX=.20315;
const F60:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,oneMonth:0,threeMonth:.2,sixMonth:.8},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.6,maxTop1Weight:.6}} as StrategyConfig;
type Ledger={gain:Record<string,number>;loss:Record<string,number>;taxes:number;sales:number;partialSales:number;turnover:number;partialRebalances:number;fullRebalances:number};
const sameSet=(a:string[],b:string[])=>[...a].sort().join(',')===[...b].sort().join(',');
function normalize(s:MonthlySignal){return s.selectedSymbols.length===2?{...s,targetWeights:[.6,.4],allocationMode:'60/40' as any,zGap:null}:s;}
function targetWeight(s:MonthlySignal,sym:string){const i=s.selectedSymbols.indexOf(sym);return i>=0?s.targetWeights[i]:null;}
function sale(l:Ledger,p:PositionState,shares:number,px:number,d:string,partial:boolean){if(shares<=0)return;const proceeds=shares*px*(1-F60.execution.transactionCost),basis=shares*p.entryPrice,pnl=proceeds-basis,y=d.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++;if(partial)l.partialSales++;l.turnover+=proceeds;}
function taxCurve(c:EquityPoint[],l:Ledger){if(!c.length)return[];const ys=[...new Set(c.map(p=>p.date.slice(0,4)))],ty:Record<string,number>={};let carry:{y:number,a:number}[]=[];for(const s of ys){const y=+s;carry=carry.filter(x=>y-x.y<=3);let n=(l.gain[s]??0)-(l.loss[s]??0);if(n>0){for(const x of carry){const u=Math.min(n,x.a);n-=u;x.a-=u;if(n<=0)break}carry=carry.filter(x=>x.a>1e-12);ty[s]=n*TAX}else if(n<0)carry.push({y,a:-n})}l.taxes=Object.values(ty).reduce((a,b)=>a+b,0);let e=c[0].equity,prev=e,peak=e;const out:EquityPoint[]=[];for(let i=0;i<c.length;i++){const p=c[i];if(i)e*=p.equity/prev;prev=p.equity;const nx=c[i+1],y=p.date.slice(0,4);if((!nx||nx.date.slice(0,4)!==y)&&(ty[y]??0)>0)e=Math.max(0,e-(ty[y]??0)*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);out.push({date:p.date,equity:e,drawdown:e/peak-1})}return out;}
function partial(state:EngineState,sig:MonthlySignal,date:string,prices:Record<string,PricePoint|undefined>,l:Ledger){if(state.currentPositions.length!==2||sig.selectedSymbols.length!==2||!sameSet(state.currentPositions.map(p=>p.symbol),sig.selectedSymbols))return false;const opens=new Map(state.currentPositions.map(p=>[p.symbol,prices[p.symbol]?.open??p.currentPrice??p.entryPrice]));const total=state.cash+state.currentPositions.reduce((a,p)=>a+p.shares*(opens.get(p.symbol)??p.entryPrice),0);if(total<=0)return false;const desired=new Map(sig.selectedSymbols.map((s,i)=>[s,total*sig.targetWeights[i]]));for(const p of state.currentPositions){const px=opens.get(p.symbol)!;const cur=p.shares*px,des=desired.get(p.symbol)??cur;if(cur>des+1e-10){const sh=(cur-des)/px;sale(l,p,sh,px,date,true);p.shares-=sh;state.cash+=(cur-des)*(1-F60.execution.transactionCost);}}
for(const p of state.currentPositions){const px=opens.get(p.symbol)!;const cur=p.shares*px,des=desired.get(p.symbol)??cur;if(cur<des-1e-10&&state.cash>0){const gross=Math.min(des-cur,state.cash);const newShares=gross*(1-F60.execution.transactionCost)/px;const oldCost=p.shares*p.entryPrice;p.shares+=newShares;p.entryPrice=(oldCost+newShares*px)/Math.max(p.shares,1e-12);state.cash-=gross;}}
for(const p of state.currentPositions){p.currentPrice=opens.get(p.symbol)!;p.targetWeight=targetWeight(sig,p.symbol)??p.targetWeight;}state.currentEquity=state.cash+state.currentPositions.reduce((a,p)=>a+p.shares*(p.currentPrice??p.entryPrice),0);l.partialRebalances++;state.nextAction={type:'HOLD',executionDate:null,symbols:state.currentPositions.map(p=>p.symbol),targetWeights:state.currentPositions.map(p=>p.targetWeight),reason:'Research exact partial rebalance'};state.pendingSignal=null;return true;}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],usePartial:boolean){const q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),ix=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(F60);const curve:EquityPoint[]=[],l:Ledger={gain:{},loss:{},taxes:0,sales:0,partialSales:0,turnover:0,partialRebalances:0,fullRebalances:0};for(let i=0;i<ds.length;i++){const d=ds[i];if(d<F60.backtestStart)continue;const n=ds[i+1]??nextUsTradingSession(d),uu=um.get(d);const sg=uu?normalize(buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:n,config:F60})):null;const sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),pr=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));let intercepted=false;if(usePartial&&st.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN'&&st.nextAction.executionDate===d&&st.pendingSignal)intercepted=partial(st,normalize(st.pendingSignal),d,pr,l);const before=structuredClone(st);st=transitionDay(st,{date:d,prices:pr,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},F60);if(!intercepted&&before.currentPositions.length&&((before.nextAction.type==='SELL_ALL_NEXT_OPEN'||before.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN')&&before.nextAction.executionDate===d)){for(const p of before.currentPositions)sale(l,p,p.shares,pr[p.symbol]?.open??pr[p.symbol]?.close??p.currentPrice??p.entryPrice,d,false);if(before.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN')l.fullRebalances++;}curve.push({date:d,equity:st.currentEquity,drawdown:st.drawdown});}return{curve,after:taxCurve(curve,l),l};}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function pack(x:ReturnType<typeof sim>){return{gross:performanceStats(x.curve),afterTaxApprox:performanceStats(x.after),sales:x.l.sales,partialSales:x.l.partialSales,turnover:x.l.turnover,taxPaidApprox:x.l.taxes,partialRebalances:x.l.partialRebalances,fullRebalances:x.l.fullRebalances};}
async function main(){const mk=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),b=sim(mk.histories,u,false),p=sim(mk.histories,u,true),years=[2020,2021,2022,2023,2024,2025,2026];const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,pit:true,noLeverage:true,nextOpen:true,parameterSearch:false,rule:'Fixed60 unchanged. When month-end next-open rebalance keeps the same Top2, trade only the share delta needed to restore exact 60/40 instead of fully selling and rebuying both positions.',taxApprox:'20.315% annual realized P&L with 3-year loss carry; moving-average-like basis approximation for partial buys, not exact broker withholding.'},baseline:pack(b),partial:pack(p),early:{baseline:performanceStats(sl(b.after,'2020-01-01','2023-12-31')),partial:performanceStats(sl(p.after,'2020-01-01','2023-12-31'))},late:{baseline:performanceStats(sl(b.after,'2024-01-01','2026-08-25')),partial:performanceStats(sl(p.after,'2024-01-01','2026-08-25'))},annual:years.map(y=>({year:y,baseline:performanceStats(sl(b.after,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`)),partial:performanceStats(sl(p.after,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))}))};const d=path.join(process.cwd(),'data/research/forward40-exact-partial-rebalance-fixed60');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
