import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY as BASE } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import { performanceStats } from "../src/lib/backtest";
import type { EquityPoint,MonthlySignal,PricePoint,UniverseMonth } from "../src/lib/types";
const CONFIG:any={...BASE,strategyId:"momentum-hybrid-60-70-ranking-frequency",allocation:{...BASE.allocation,baseTop1Weight:.60,concentratedTop1Weight:.70,concentrationZGap:.25,maxTop1Weight:.70}};
type V="MONTHLY"|"BIWEEKLY"|"WEEKLY";
const sameSet=(a:string[],b:string[])=>[...a].sort().join(",")===[...b].sort().join(",");
function exactSame(st:any,s:MonthlySignal){if(!sameSet(st.currentPositions.map((p:any)=>p.symbol),s.selectedSymbols))return false;const w=new Map(s.selectedSymbols.map((x,i)=>[x,s.targetWeights[i]]));return st.currentPositions.every((p:any)=>Math.abs((w.get(p.symbol)??-9)-p.targetWeight)<1e-12)}
function weekKey(d:string){const x=new Date(d+"T00:00:00Z"),day=(x.getUTCDay()+6)%7;x.setUTCDate(x.getUTCDate()-day);return x.toISOString().slice(0,10)}
function weeklyDates(ds:string[]){const out:string[]=[];for(let i=0;i<ds.length;i++)if(!ds[i+1]||weekKey(ds[i+1])!==weekKey(ds[i]))out.push(ds[i]);return out}
function latestUniverse(us:UniverseMonth[],d:string){let lo=0,hi=us.length-1,best:UniverseMonth|null=null;while(lo<=hi){const m=(lo+hi)>>1;if(us[m].asOf<=d){best=us[m];lo=m+1}else hi=m-1}return best}
function hybridSignal(base:MonthlySignal){if(!base.marketRiskOn||base.selectedSymbols.length<2)return base;const top=base.zGap!==null&&base.zGap>=.25?.70:.60;return{...base,targetWeights:[top,1-top],allocationMode:(top===.70?"70/30":"60/40") as any}}
function makeSignal(u:UniverseMonth,d:string,h:Record<string,PricePoint[]>,q:PricePoint[],next:string,monthlyGate:boolean){const x:any={...u,asOf:d,signalMonth:d.slice(0,7)};const s=hybridSignal(buildMonthlySignal({universe:x,histories:h,qqq:q,nextSessionDate:next,config:CONFIG}));return{...s,marketRiskOn:monthlyGate}}
function norm(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function sim(h:Record<string,PricePoint[]>,us:UniverseMonth[],v:V){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(p=>p.date),di=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),actual=new Map(us.map(u=>[u.asOf,u])),weeks=weeklyDates(ds.filter(d=>d>=CONFIG.backtestStart)),wset=new Set(v==="WEEKLY"?weeks:v==="BIWEEKLY"?weeks.filter((_,i)=>i%2===0):[]);let st=initialEngineState(CONFIG),gate=false,skips=0,signals=0;const c:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<CONFIG.backtestStart)continue;const nx=ds[i+1]??nextUsTradingSession(d),au=actual.get(d);if(au){const ms=hybridSignal(buildMonthlySignal({universe:au,histories:h,qqq:q,nextSessionDate:nx,config:CONFIG}));gate=ms.marketRiskOn}let sg:MonthlySignal|null=null;if(v==="MONTHLY"&&au){sg=hybridSignal(buildMonthlySignal({universe:au,histories:h,qqq:q,nextSessionDate:nx,config:CONFIG}));signals++}else if(v!=="MONTHLY"&&wset.has(d)){const lu=latestUniverse(us,d);if(lu){sg=makeSignal(lu,d,h,q,nx,gate);signals++}}const sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));if(v!=="MONTHLY"&&st.nextAction.type==="MONTH_END_REBALANCE_NEXT_OPEN"&&st.nextAction.executionDate===d&&st.pendingSignal&&exactSame(st,st.pendingSignal)){st.nextAction={type:"HOLD",executionDate:null,symbols:st.currentPositions.map(p=>p.symbol),targetWeights:st.currentPositions.map(p=>p.targetWeight),reason:"Research unchanged ranking refresh"};skips++}st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(di.get(d)??i)+1),monthlySignal:sg,nextSessionDate:nx},CONFIG);c.push({date:d,equity:st.currentEquity,drawdown:st.drawdown})}return{curve:c,signals,skips}}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]},us=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),vs:V[]=["MONTHLY","BIWEEKLY","WEEKLY"],runs=new Map<V,ReturnType<typeof sim>>();for(const v of vs){console.log("run",v);runs.set(v,sim(m.histories,us,v))}const full=vs.map(v=>({variant:v,...performanceStats(runs.get(v)!.curve),signals:runs.get(v)!.signals,skips:runs.get(v)!.skips})),splits=[] as any[];for(const y of [2022,2023,2024,2025,2026]){const te=`${y-1}-12-31`,oe=y===2026?"2026-08-25":`${y}-12-31`,tr=vs.map(v=>({v,s:performanceStats(norm(runs.get(v)!.curve,"2020-01-01",te))})).sort((a,b)=>(b.s.calmar??-Infinity)-(a.s.calmar??-Infinity)),ch=tr[0].v,base=performanceStats(norm(runs.get("MONTHLY")!.curve,`${y}-01-01`,oe)),oos=performanceStats(norm(runs.get(ch)!.curve,`${y}-01-01`,oe));splits.push({trainThrough:y-1,oosYear:y,chosen:ch,oos,monthlyBase:base,cagrDiff:oos.cagr-base.cagr})}const out={generatedAt:new Date().toISOString(),method:{baseline:"Hybrid 60/40->70/30 monthly",variants:"Biweekly or weekly Top2 ranking refresh using latest PIT monthly universe",marketGate:"QQQ 10M MA remains frozen to actual monthly signal dates",noChurn:"for higher-frequency variants, skip scheduled full rebalance when selected set and target weights are unchanged",cost:"same 10bp per side on executed trades"},validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,architectureHindsightRemains:true,warning:"Retrospective pseudo-OOS. Higher refresh frequency increases model responsiveness and potentially turnover/tax; tax is not included in this screen."},full,splits};const d=path.join(process.cwd(),"data/research/hybrid-ranking-frequency-screen");await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,"result.json"),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});