import fs from "node:fs/promises";
import path from "node:path";
import { gunzipSync } from "node:zlib";
import { PRODUCTION_STRATEGY as BASE } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import { performanceStats } from "../src/lib/backtest";
import type { EquityPoint,NportFiling,PricePoint,UniverseMonth } from "../src/lib/types";
const CONFIG:any={...BASE,strategyId:"momentum-hybrid-60-70-nport-initiation",allocation:{...BASE.allocation,baseTop1Weight:.60,concentratedTop1Weight:.70,concentrationZGap:.25,maxTop1Weight:.70}};
type F="BASE"|"NET_INITIATION"|"CONVICTION_DELTA";type V={id:string;factor:F;lambda:number};
const VARIANTS:V[]=[{id:"HYBRID_BASE",factor:"BASE",lambda:0},{id:"NET_INIT_25",factor:"NET_INITIATION",lambda:.25},{id:"NET_INIT_50",factor:"NET_INITIATION",lambda:.5},{id:"CONVICTION_25",factor:"CONVICTION_DELTA",lambda:.25},{id:"CONVICTION_50",factor:"CONVICTION_DELTA",lambda:.5}];
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0,sd=(x:number[])=>{if(x.length<2)return 0;const m=mean(x);return Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/x.length)},z=(v:number,m:number,s:number)=>s>1e-12?(v-m)/s:0;
type RG={reportDate:string;versions:NportFiling[]};type SR={reports:RG[]};type Row={netInitiation:number;convictionDelta:number;events:number;involved:number};
function seriesReports(fs:NportFiling[]):SR[]{const b=new Map<string,Map<string,NportFiling[]>>();for(const f of fs){if(!b.has(f.seriesId))b.set(f.seriesId,new Map());const m=b.get(f.seriesId)!;if(!m.has(f.reportDate))m.set(f.reportDate,[]);m.get(f.reportDate)!.push(f)}return[...b.values()].map(m=>({reports:[...m.entries()].map(([reportDate,versions])=>({reportDate,versions:versions.sort((a,b)=>a.filingDate.localeCompare(b.filingDate))})).sort((a,b)=>a.reportDate.localeCompare(b.reportDate))}))}
function two(sr:SR,d:string){const xs:NportFiling[]=[];for(const g of sr.reports){if(g.reportDate>d)break;const f=g.versions.filter(x=>x.filingDate<=d).at(-1);if(f)xs.push(f)}return xs.length>=2?[xs.at(-1)!,xs.at(-2)!] as const:null}
function wm(f:NportFiling,sy:Set<string>){const m=new Map<string,number>();for(const h of f.holdings??[])if(sy.has(h.symbol))m.set(h.symbol,Number(h.weight)||0);return m}
function maps(us:UniverseMonth[],fs:NportFiling[]){const sr=seriesReports(fs),res=new Map<string,Map<string,Row>>();for(const u of us){const sy=new Set(u.symbols.map(x=>x.symbol)),a=new Map<string,{en:number;ex:number;inv:number;cc:number;pc:number}>();for(const s of sy)a.set(s,{en:0,ex:0,inv:0,cc:0,pc:0});for(const r of sr){const p=two(r,u.asOf);if(!p)continue;const [c,pr]=p,cm=wm(c,sy),pm=wm(pr,sy),un=new Set([...cm.keys(),...pm.keys()]);for(const s of un){const x=a.get(s)!;x.inv++;const cw=cm.get(s)??0,pw=pm.get(s)??0;if(pw<=0&&cw>0)x.en++;if(pw>0&&cw<=0)x.ex++;if(cw>=1)x.cc++;if(pw>=1)x.pc++;}}const m=new Map<string,Row>();for(const [s,x]of a){const ev=x.en+x.ex;m.set(s,{netInitiation:x.inv?(x.en-x.ex)/x.inv:0,convictionDelta:(x.cc-x.pc)/Math.max(1,x.pc),events:ev,involved:x.inv})}res.set(u.asOf,m)}return res}
function signal(u:UniverseMonth,h:Record<string,PricePoint[]>,q:PricePoint[],next:string,v:V,fm:Map<string,Map<string,Row>>){const b:any=buildMonthlySignal({universe:u,histories:h,qqq:q,nextSessionDate:next,config:CONFIG});if(v.factor==="BASE"||!b.marketRiskOn)return b;const e=b.candidates.filter((c:any)=>c.eligible&&c.score!==null),m=fm.get(u.asOf);if(e.length<2||!m)return b;const rs=e.map((c:any)=>{const r=m.get(c.symbol);return{c,r,fv:v.factor==="NET_INITIATION"?r?.netInitiation:r?.convictionDelta}}).filter((x:any)=>x.r&&x.r.involved>=2&&x.fv!==undefined);if(rs.length<2)return b;const sm=mean(rs.map((x:any)=>x.c.score)),ss=sd(rs.map((x:any)=>x.c.score)),xm=mean(rs.map((x:any)=>x.fv)),xs=sd(rs.map((x:any)=>x.fv));if(xs<=1e-12)return b;const rr=rs.map((x:any)=>({...x,combo:z(x.c.score,sm,ss)+v.lambda*z(x.fv,xm,xs)})).sort((a:any,b:any)=>b.combo-a.combo||a.c.symbol.localeCompare(b.c.symbol)),sel=rr.slice(0,2),disp=sd(rr.map((x:any)=>x.combo)),zg=disp>0?(sel[0].combo-sel[1].combo)/disp:0,top=zg>=.25?.70:.60;return{...b,selectedSymbols:sel.map((x:any)=>x.c.symbol),targetWeights:[top,1-top],zGap:zg,allocationMode:top===.70?"70/30":"60/40"}}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],v:V,fm:Map<string,Map<string,Row>>){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),di=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(CONFIG);const c:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<CONFIG.backtestStart)continue;const nx=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?signal(uu,h,q,nx,v,fm):null,sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),p=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices:p,qqqHistoryThroughClose:q.slice(0,(di.get(d)??i)+1),monthlySignal:sg,nextSessionDate:nx},CONFIG);c.push({date:d,equity:st.currentEquity,drawdown:st.drawdown})}return c}
function ns(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),raw=JSON.parse(gunzipSync(await fs.readFile(path.join(process.cwd(),"data/sec-nport/bootstrap.json.gz"))).toString("utf8")) as {snapshots:NportFiling[]},fm=maps(u,raw.snapshots),curves=new Map<string,EquityPoint[]>();for(const v of VARIANTS){console.log("run",v.id);curves.set(v.id,sim(market.histories,u,v,fm))}const full=VARIANTS.map(v=>({variant:v,...performanceStats(curves.get(v.id)!)})),splits=[] as any[];for(const y of [2022,2023,2024,2025,2026]){const te=`${y-1}-12-31`,oe=y===2026?"2026-08-25":`${y}-12-31`,tr=VARIANTS.map(v=>({v,s:performanceStats(ns(curves.get(v.id)!,"2020-01-01",te))})).sort((a,b)=>(b.s.calmar??-Infinity)-(a.s.calmar??-Infinity)),ch=tr[0].v,base=performanceStats(ns(curves.get("HYBRID_BASE")!,`${y}-01-01`,oe)),oos=performanceStats(ns(curves.get(ch.id)!,`${y}-01-01`,oe));splits.push({trainThrough:y-1,oosYear:y,chosen:ch.id,oos,hybridBase:base,cagrDiff:oos.cagr-base.cagr})}const out={generatedAt:new Date().toISOString(),method:{pit:"filingDate<=signal close; latest two report dates per series",NET_INITIATION:"(new-holder series - exiting-holder series)/series holding symbol in either report",CONVICTION_DELTA:"change in count of series with portfolio weight >=1%, normalized by prior count",blend:"z(momentum)+lambda*z(factor), lambda .25/.50",baseline:"Hybrid 60/40 -> 70/30 at zGap .25"},validity:{freeDataOnly:true,trueOOS:false,noLeverage:true,warning:"Retrospective pseudo-OOS; N-PORT reporting is delayed and fund coverage is not the whole institutional market."},full,splits};const d=path.join(process.cwd(),"data/research/hybrid-nport-initiation-screen");await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,"result.json"),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});