import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY as BASE } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import { performanceStats } from "../src/lib/backtest";
import type { EquityPoint,PricePoint,UniverseMonth } from "../src/lib/types";
const ROOT:any={...BASE,allocation:{...BASE.allocation,baseTop1Weight:.60,concentratedTop1Weight:.70,concentrationZGap:.25,maxTop1Weight:.70}};
type V={id:string,w3:number,w6:number};const VS:V[]=[{id:"HYBRID_W20_80",w3:.20,w6:.80},{id:"HYBRID_W25_75",w3:.25,w6:.75}];
function hybrid(s:any){if(!s.marketRiskOn||s.selectedSymbols.length<2)return s;const top=s.zGap!==null&&s.zGap>=.25?.70:.60;return{...s,targetWeights:[top,1-top],allocationMode:top===.70?"70/30":"60/40"}}
function ns(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],v:V){const cfg:any={...ROOT,strategyId:v.id,momentum:{...ROOT.momentum,oneMonth:0,threeMonth:v.w3,sixMonth:v.w6}},q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(p=>p.date),di=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg);const c:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<cfg.backtestStart)continue;const nx=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?hybrid(buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:nx,config:cfg})):null,sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(di.get(d)??i)+1),monthlySignal:sg,nextSessionDate:nx},cfg);c.push({date:d,equity:st.currentEquity,drawdown:st.drawdown})}return c}
function logReturns(c:EquityPoint[]){return c.slice(1).map((p,i)=>({date:p.date,r:Math.log(p.equity/c[i].equity)}))}
function stress(c:EquityPoint[],retention:number){const lr=logReturns(c),out:EquityPoint[]=[];let e=c[0]?.equity??1,peak=e;out.push({date:c[0].date,equity:e,drawdown:0});for(const x of lr){const r=x.r>0?x.r*retention:x.r;e*=Math.exp(r);peak=Math.max(peak,e);out.push({date:x.date,equity:e,drawdown:e/peak-1})}return performanceStats(out)}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),curves=new Map<string,EquityPoint[]>();for(const v of VS)curves.set(v.id,sim(m.histories,u,v));const full=VS.map(v=>({variant:v,...performanceStats(curves.get(v.id)!)}));const annual=[] as any[];for(const y of [2020,2021,2022,2023,2024,2025,2026]){const e=y===2026?"2026-08-25":`${y}-12-31`;annual.push({year:y,baseline:performanceStats(ns(curves.get(VS[0].id)!,`${y}-01-01`,e)),candidate:performanceStats(ns(curves.get(VS[1].id)!,`${y}-01-01`,e))})}const stressRows=[.75,.50,.25].map(r=>({retention:r,baseline:stress(curves.get(VS[0].id)!,r),candidate:stress(curves.get(VS[1].id)!,r)}));const out={generatedAt:new Date().toISOString(),method:{candidate:"Hybrid allocation + 0/25/75 momentum",baseline:"Hybrid allocation + 0/20/80 momentum",stress:"simple deterministic positive daily log-return retention, negative daily log returns unchanged; sensitivity check only"},validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,architectureHindsightRemains:true,warning:"Annual slices and stress are historical diagnostics. Candidate was motivated by prior anchored parameter-region transfer, but this sample was already seen."},full,annual,stressRows};const d=path.join(process.cwd(),"data/research/hybrid-w25-validation");await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,"result.json"),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});