import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY as BASE } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import { performanceStats } from "../src/lib/backtest";
import type { EquityPoint, PricePoint, UniverseMonth } from "../src/lib/types";

const CONFIG:any={...BASE,strategyId:"momentum-hybrid-60-70-alpha-screen",allocation:{...BASE.allocation,baseTop1Weight:.60,concentratedTop1Weight:.70,concentrationZGap:.25,maxTop1Weight:.70}};
type Factor="BASE"|"ACCEL20"|"HIGH52"|"VOL_ADJ";
type Variant={id:string;factor:Factor;lambda:number};
const VARIANTS:Variant[]=[
 {id:"HYBRID_BASE",factor:"BASE",lambda:0},
 {id:"ACCEL20_25",factor:"ACCEL20",lambda:.25},{id:"ACCEL20_50",factor:"ACCEL20",lambda:.50},
 {id:"HIGH52_25",factor:"HIGH52",lambda:.25},{id:"HIGH52_50",factor:"HIGH52",lambda:.50},
 {id:"VOL_ADJ_25",factor:"VOL_ADJ",lambda:.25},{id:"VOL_ADJ_50",factor:"VOL_ADJ",lambda:.50},
];
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
const sd=(x:number[])=>{if(x.length<2)return 0;const m=mean(x);return Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/x.length)};
const z=(v:number,m:number,s:number)=>s>1e-12?(v-m)/s:0;
function closesThrough(ps:PricePoint[],date:string){return ps.filter(p=>p.date<=date).sort((a,b)=>a.date.localeCompare(b.date));}
function retN(ps:PricePoint[],n:number){if(ps.length<=n)return null;const a=ps.at(-(n+1))!.close,b=ps.at(-1)!.close;return b/a-1;}
function factorValue(f:Factor,ps:PricePoint[],prodScore:number){if(f==="BASE")return 0;const h=closesThrough(ps,ps.at(-1)?.date??"");if(f==="ACCEL20"){const r20=retN(h,20),r60=retN(h,60);return r20===null||r60===null?null:r20-r60/3;}if(f==="HIGH52"){if(h.length<60)return null;const w=h.slice(-252),mx=Math.max(...w.map(p=>p.close)),c=w.at(-1)!.close;return c/mx-1;}const rs=h.slice(-21);if(rs.length<21)return null;const logs=rs.slice(1).map((p,i)=>Math.log(p.close/rs[i].close)),rv=sd(logs)*Math.sqrt(252);return prodScore/Math.max(rv,.10);}
function customSignal(u:UniverseMonth,hist:Record<string,PricePoint[]>,qqq:PricePoint[],next:string,v:Variant){const base:any=buildMonthlySignal({universe:u,histories:hist,qqq,nextSessionDate:next,config:CONFIG});if(v.factor==="BASE"||!base.marketRiskOn)return base;const eligible=base.candidates.filter((c:any)=>c.eligible&&c.score!==null);if(eligible.length<2)return base;const rows=eligible.map((c:any)=>{const ps=closesThrough(hist[c.symbol]??[],u.asOf);const fv=factorValue(v.factor,ps,c.score);return{c,fv}}).filter((x:any)=>x.fv!==null);if(rows.length<2)return base;const sm=mean(rows.map((x:any)=>x.c.score)),ss=sd(rows.map((x:any)=>x.c.score)),fm=mean(rows.map((x:any)=>x.fv)),fs=sd(rows.map((x:any)=>x.fv));const ranked=rows.map((x:any)=>({...x,combo:z(x.c.score,sm,ss)+v.lambda*z(x.fv,fm,fs)})).sort((a:any,b:any)=>b.combo-a.combo||a.c.symbol.localeCompare(b.c.symbol));const sel=ranked.slice(0,2);if(sel.length<2)return base;const combos=ranked.map((x:any)=>x.combo),disp=sd(combos),zg=disp>0?(sel[0].combo-sel[1].combo)/disp:0,conc=zg>=CONFIG.allocation.concentrationZGap,top1=conc?.70:.60;return{...base,selectedSymbols:sel.map((x:any)=>x.c.symbol),targetWeights:[top1,1-top1],zGap:zg,allocationMode:conc?"70/30":"60/40"};}
function sim(hist:Record<string,PricePoint[]>,universe:UniverseMonth[],v:Variant){const qqq=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=qqq.map(p=>p.date),di=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(universe.map(x=>[x.asOf,x]));let st=initialEngineState(CONFIG);const curve:EquityPoint[]=[];for(let i=0;i<dates.length;i++){const date=dates[i];if(date<CONFIG.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),u=um.get(date),sig=u?customSignal(u,hist,qqq,next,v):null,sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));st=transitionDay(st,{date,prices,qqqHistoryThroughClose:qqq.slice(0,(di.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},CONFIG);curve.push({date,equity:st.currentEquity,drawdown:st.drawdown});}return curve;}
function normSlice(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}));}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>};const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]};const universe=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const curves=new Map<string,EquityPoint[]>();for(const v of VARIANTS){console.log("run",v.id);curves.set(v.id,sim(market.histories,universe,v));}
 const full=VARIANTS.map(v=>({variant:v,...performanceStats(curves.get(v.id)!)}));const splits=[] as any[];for(const y of [2022,2023,2024,2025,2026]){const trainEnd=`${y-1}-12-31`,oosEnd=y===2026?"2026-08-25":`${y}-12-31`;const train=VARIANTS.map(v=>({v,stats:performanceStats(normSlice(curves.get(v.id)!,"2020-01-01",trainEnd))})).sort((a,b)=>(b.stats.calmar??-Infinity)-(a.stats.calmar??-Infinity));const chosen=train[0].v;const base=performanceStats(normSlice(curves.get("HYBRID_BASE")!,`${y}-01-01`,oosEnd)),oos=performanceStats(normSlice(curves.get(chosen.id)!,`${y}-01-01`,oosEnd));splits.push({trainThrough:y-1,oosYear:y,chosen:chosen.id,trainCalmar:train[0].stats.calmar,oos,hybridBase:base,cagrDiff:oos.cagr-base.cagr});}
 const out={generatedAt:new Date().toISOString(),method:{baseline:"Hybrid allocation 60/40; 70/30 when zGap>=0.25",eligibility:"Production eligibility and market gate unchanged",factors:{ACCEL20:"20-trading-day return minus one-third of 60-trading-day return",HIGH52:"current close / trailing-252-session max close - 1",VOL_ADJ:"Production momentum score divided by 20-session annualized realized volatility (floor 10%)"},blend:"cross-sectional z(Production momentum)+lambda*z(factor)",lambdas:[.25,.50],selection:"training-only Calmar; next-calendar-year OOS"},validity:{trueOOS:false,architectureHindsightRemains:true,factorsPredeclaredFromPriorMissedWinnerDiagnosis:true,smallCandidateSet:true,warning:"The factor families were proposed after inspecting historical missed-winner patterns, so this is not independent discovery. OOS is anchored pseudo-OOS within the already-seen 2020-2026 sample."},full,splits};const dir=path.join(process.cwd(),"data/research/hybrid-alpha-factor-screen");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});