import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY as BASE } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import { performanceStats } from "../src/lib/backtest";
import type { EquityPoint, PricePoint, UniverseMonth } from "../src/lib/types";

const CONFIG:any={...BASE,strategyId:"momentum-hybrid-60-70-nport-screen",allocation:{...BASE.allocation,baseTop1Weight:.60,concentratedTop1Weight:.70,concentrationZGap:.25,maxTop1Weight:.70}};
type URow={symbol:string;breadthCount:number;seriesCount:number;universeRank:number};
type UMonth=Omit<UniverseMonth,"symbols">&{symbols:URow[]};
type Factor="BASE"|"BREADTH_DELTA"|"SERIES_DELTA"|"BREADTH_LEVEL";
type Variant={id:string;factor:Factor;lambda:number};
const VARIANTS:Variant[]=[
 {id:"HYBRID_BASE",factor:"BASE",lambda:0},
 {id:"BREADTH_DELTA_25",factor:"BREADTH_DELTA",lambda:.25},{id:"BREADTH_DELTA_50",factor:"BREADTH_DELTA",lambda:.50},
 {id:"SERIES_DELTA_25",factor:"SERIES_DELTA",lambda:.25},{id:"SERIES_DELTA_50",factor:"SERIES_DELTA",lambda:.50},
 {id:"BREADTH_LEVEL_25",factor:"BREADTH_LEVEL",lambda:.25},{id:"BREADTH_LEVEL_50",factor:"BREADTH_LEVEL",lambda:.50},
];
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
const sd=(x:number[])=>{if(x.length<2)return 0;const m=mean(x);return Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/x.length)};
const z=(v:number,m:number,s:number)=>s>1e-12?(v-m)/s:0;
function prevMap(universe:UMonth[]){const out=new Map<string,Map<string,URow>>();for(let i=1;i<universe.length;i++)out.set(universe[i].asOf,new Map(universe[i-1].symbols.map(x=>[x.symbol,x])));return out;}
function fv(f:Factor,row:URow,prev?:URow){if(f==="BASE")return 0;if(f==="BREADTH_LEVEL")return Math.log1p(Math.max(0,row.breadthCount));if(!prev)return null;if(f==="BREADTH_DELTA")return Math.log1p(Math.max(0,row.breadthCount))-Math.log1p(Math.max(0,prev.breadthCount));return Math.log1p(Math.max(0,row.seriesCount))-Math.log1p(Math.max(0,prev.seriesCount));}
function customSignal(u:UMonth,hist:Record<string,PricePoint[]>,qqq:PricePoint[],next:string,v:Variant,prevs:Map<string,Map<string,URow>>){const base:any=buildMonthlySignal({universe:u as any,histories:hist,qqq,nextSessionDate:next,config:CONFIG});if(v.factor==="BASE"||!base.marketRiskOn)return base;const umap=new Map(u.symbols.map(x=>[x.symbol,x])),pmap=prevs.get(u.asOf);const eligible=base.candidates.filter((c:any)=>c.eligible&&c.score!==null);const rows=eligible.map((c:any)=>{const row=umap.get(c.symbol);if(!row)return null;const val=fv(v.factor,row,pmap?.get(c.symbol));return val===null?null:{c,val};}).filter(Boolean) as any[];if(rows.length<2)return base;const sm=mean(rows.map(x=>x.c.score)),ss=sd(rows.map(x=>x.c.score)),fm=mean(rows.map(x=>x.val)),fs=sd(rows.map(x=>x.val));if(fs<=1e-12)return base;const ranked=rows.map(x=>({...x,combo:z(x.c.score,sm,ss)+v.lambda*z(x.val,fm,fs)})).sort((a,b)=>b.combo-a.combo||a.c.symbol.localeCompare(b.c.symbol));const sel=ranked.slice(0,2);if(sel.length<2)return base;const disp=sd(ranked.map(x=>x.combo)),zg=disp>0?(sel[0].combo-sel[1].combo)/disp:0,conc=zg>=CONFIG.allocation.concentrationZGap,top1=conc?.70:.60;return{...base,selectedSymbols:sel.map(x=>x.c.symbol),targetWeights:[top1,1-top1],zGap:zg,allocationMode:conc?"70/30":"60/40"};}
function sim(hist:Record<string,PricePoint[]>,universe:UMonth[],v:Variant,prevs:Map<string,Map<string,URow>>){const qqq=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=qqq.map(p=>p.date),di=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(universe.map(x=>[x.asOf,x]));let st=initialEngineState(CONFIG);const curve:EquityPoint[]=[];for(let i=0;i<dates.length;i++){const date=dates[i];if(date<CONFIG.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),u=um.get(date),sig=u?customSignal(u,hist,qqq,next,v,prevs):null,sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));st=transitionDay(st,{date,prices,qqqHistoryThroughClose:qqq.slice(0,(di.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},CONFIG);curve.push({date,equity:st.currentEquity,drawdown:st.drawdown});}return curve;}
function normSlice(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}));}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>};const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UMonth[]};const universe=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),prevs=prevMap(universe),curves=new Map<string,EquityPoint[]>();for(const v of VARIANTS){console.log("run",v.id);curves.set(v.id,sim(market.histories,universe,v,prevs));}
 const full=VARIANTS.map(v=>({variant:v,...performanceStats(curves.get(v.id)!)}));const splits=[] as any[];for(const y of [2022,2023,2024,2025,2026]){const trainEnd=`${y-1}-12-31`,oosEnd=y===2026?"2026-08-25":`${y}-12-31`;const train=VARIANTS.map(v=>({v,stats:performanceStats(normSlice(curves.get(v.id)!,"2020-01-01",trainEnd))})).sort((a,b)=>(b.stats.calmar??-Infinity)-(a.stats.calmar??-Infinity));const chosen=train[0].v,base=performanceStats(normSlice(curves.get("HYBRID_BASE")!,`${y}-01-01`,oosEnd)),oos=performanceStats(normSlice(curves.get(chosen.id)!,`${y}-01-01`,oosEnd));splits.push({trainThrough:y-1,oosYear:y,chosen:chosen.id,trainCalmar:train[0].stats.calmar,oos,hybridBase:base,cagrDiff:oos.cagr-base.cagr});}
 const out={generatedAt:new Date().toISOString(),method:{baseline:"Hybrid 60/40; 70/30 when zGap>=0.25",eligibility:"Production eligibility and market gate unchanged",pitSource:"Existing universe-history monthly N-PORT breadthCount/seriesCount only",factors:{BREADTH_DELTA:"month-over-month delta log1p(breadthCount)",SERIES_DELTA:"month-over-month delta log1p(seriesCount)",BREADTH_LEVEL:"log1p(current breadthCount), included as control because level is partly embedded in universe rank"},blend:"cross-sectional z(Production momentum)+lambda*z(N-PORT factor)",lambdas:[.25,.50],selection:"training-only Calmar; next-calendar-year anchored pseudo-OOS"},validity:{trueOOS:false,architectureHindsightRemains:true,smallCandidateSet:true,warning:"N-PORT factor families were chosen after prior strategy diagnostics. Existing universe-history is assumed to preserve the Production PIT construction; this screen does not alter filing eligibility. Results remain retrospective pseudo-OOS."},full,splits};const dir=path.join(process.cwd(),"data/research/hybrid-nport-factor-screen");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});