import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY as BASE } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import { performanceStats } from "../src/lib/backtest";
import type { EquityPoint,PricePoint,UniverseMonth } from "../src/lib/types";
const CONFIG:any={...BASE,strategyId:"momentum-hybrid-60-70-trailing-stop",allocation:{...BASE.allocation,baseTop1Weight:.60,concentratedTop1Weight:.70,concentrationZGap:.25,maxTop1Weight:.70}};
type V={id:string,trail:number|null};const VS:V[]=[{id:"HYBRID_BASE",trail:null},{id:"TRAIL15",trail:.15},{id:"TRAIL17_5",trail:.175},{id:"TRAIL20",trail:.20}];
function hybrid(s:any){if(!s.marketRiskOn||s.selectedSymbols.length<2)return s;const top=s.zGap!==null&&s.zGap>=.25?.70:.60;return{...s,targetWeights:[top,1-top],allocationMode:top===.70?"70/30":"60/40"}}
function ns(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],v:V){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(p=>p.date),di=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st:any=initialEngineState(CONFIG),peaks=new Map<string,number>(),triggers=0;const triggerEvents:any[]=[],c:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<CONFIG.backtestStart)continue;const nx=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?hybrid(buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:nx,config:CONFIG})):null,sy=new Set(["QQQ",...st.currentPositions.map((p:any)=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));const eventCount=st.events.length;st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(di.get(d)??i)+1),monthlySignal:sg,nextSessionDate:nx},CONFIG);
 const newEvents=st.events.slice(eventCount);const reentered=newEvents.some((e:any)=>e.date===d&&e.type==="ENTRY_OPEN");if(reentered)peaks.clear();
 const held=new Set(st.currentPositions.map((p:any)=>p.symbol));for(const s of [...peaks.keys()])if(!held.has(s))peaks.delete(s);for(const p of st.currentPositions){const cl=prices[p.symbol]?.close??p.currentPrice??p.entryPrice;peaks.set(p.symbol,reentered?Math.max(p.entryPrice,cl):Math.max(peaks.get(p.symbol)??p.entryPrice,cl));}
 if(v.trail!==null&&st.state==="INVESTED"&&st.nextAction.type!=="SELL_ALL_NEXT_OPEN"){const hit=st.currentPositions.find((p:any)=>{const cl=prices[p.symbol]?.close??p.currentPrice??Infinity,pk=peaks.get(p.symbol)??p.entryPrice;return cl<=pk*(1-v.trail!)});if(hit){const pk=peaks.get(hit.symbol)!;st.state="LOCKED_STOP";st.lastTrigger=`${d}: ${hit.symbol} close breached -${v.trail*100}% trailing stop from peak ${pk}`;st.recoveryConsecutiveDays=0;st.nextAction={type:"SELL_ALL_NEXT_OPEN",executionDate:nx,symbols:st.currentPositions.map((p:any)=>p.symbol),targetWeights:[],reason:`${hit.symbol} trailing stop -${v.trail*100}% from peak close`};triggers++;triggerEvents.push({date:d,symbol:hit.symbol,close:prices[hit.symbol]?.close,peak:pk,trail:v.trail,nextOpen:nx});}}
 c.push({date:d,equity:st.currentEquity,drawdown:st.drawdown});}return{curve:c,triggers,triggerEvents}}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),runs=new Map<string,ReturnType<typeof sim>>();for(const v of VS){console.log("run",v.id);runs.set(v.id,sim(m.histories,u,v))}const full=VS.map(v=>({variant:v,...performanceStats(runs.get(v.id)!.curve),triggers:runs.get(v.id)!.triggers,triggerEvents:runs.get(v.id)!.triggerEvents})),splits=[] as any[];for(const y of [2022,2023,2024,2025,2026]){const te=`${y-1}-12-31`,oe=y===2026?"2026-08-25":`${y}-12-31`,tr=VS.map(v=>({v,s:performanceStats(ns(runs.get(v.id)!.curve,"2020-01-01",te))})).sort((a,b)=>(b.s.calmar??-Infinity)-(a.s.calmar??-Infinity)),ch=tr[0].v,base=performanceStats(ns(runs.get("HYBRID_BASE")!.curve,`${y}-01-01`,oe)),oos=performanceStats(ns(runs.get(ch.id)!.curve,`${y}-01-01`,oe));splits.push({trainThrough:y-1,oosYear:y,chosen:ch.id,oos,hybridBase:base,cagrDiff:oos.cagr-base.cagr})}const out={generatedAt:new Date().toISOString(),method:{baseline:"Hybrid 60/40->70/30 with Production fixed -17.5% entry stop",variants:"Additional close-based trailing stop from each position's highest close since the latest entry/rebalance; whole portfolio exits next open, then existing Recovery10 applies",peakReset:"Reset every time ENTRY_OPEN occurs, including month-end sell/rebuy",trails:[.15,.175,.20]},validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,architectureHindsightRemains:true,warning:"Retrospective pseudo-OOS. Trailing exit changes state path and recovery timing; tax not included in this screen."},full,splits};const d=path.join(process.cwd(),"data/research/hybrid-trailing-stop-screen");await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,"result.json"),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});