import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY as BASE } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay, type EngineState } from "../src/lib/strategy/state-machine";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import { performanceStats } from "../src/lib/backtest";
import type { EquityPoint,PricePoint,UniverseMonth } from "../src/lib/types";

const HYBRID:any={...BASE,strategyId:"momentum-hybrid-60-70-single-position-stop",allocation:{...BASE.allocation,baseTop1Weight:.60,concentratedTop1Weight:.70,concentrationZGap:.25,maxTop1Weight:.70}};
const NO_NATIVE_STOP:any={...HYBRID,risk:{...HYBRID.risk,individualStop:99}};
type V="ALL_EXIT"|"SINGLE_CASH";
function hybrid(s:any){if(!s.marketRiskOn||s.selectedSymbols.length<2)return s;const top=s.zGap!==null&&s.zGap>=.25?.70:.60;return{...s,targetWeights:[top,1-top],allocationMode:top===.70?"70/30":"60/40"}}
function ns(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function eq(st:EngineState,prices:Record<string,PricePoint|undefined>,field:"open"|"close"){return st.cash+st.currentPositions.reduce((sum,p)=>sum+p.shares*(prices[p.symbol]?.[field]??prices[p.symbol]?.close??p.currentPrice??p.entryPrice),0)}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],v:V){
 const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(p=>p.date),di=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));
 let st:EngineState=initialEngineState(v==="ALL_EXIT"?HYBRID:NO_NATIVE_STOP),pendingPartial:{symbol:string,date:string,reason:string}|null=null,partialStops=0;const stopEvents:any[]=[],curve:EquityPoint[]=[];
 for(let i=0;i<ds.length;i++){
  const d=ds[i];if(d<HYBRID.backtestStart)continue;const nx=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?hybrid(buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:nx,config:HYBRID})):null;
  const sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[]),...(pendingPartial?[pendingPartial.symbol]:[])]);const prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));
  if(v==="SINGLE_CASH"&&pendingPartial?.date===d){const p=st.currentPositions.find(x=>x.symbol===pendingPartial!.symbol);if(p){const px=prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice;const proceeds=p.shares*px*(1-HYBRID.execution.transactionCost);st.cash+=proceeds;st.currentPositions=st.currentPositions.filter(x=>x.symbol!==p.symbol);st.events.push({date:d,type:"PARTIAL_STOP_EXIT_OPEN",symbols:[p.symbol],reason:pendingPartial.reason});if(!st.currentPositions.length){st.state="CASH";st.nextAction={type:"CASH",executionDate:null,symbols:[],targetWeights:[],reason:"All positions individually stopped; wait for next monthly signal"};}st.currentEquity=eq(st,prices,"open");}pendingPartial=null;}
  st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(di.get(d)??i)+1),monthlySignal:sg,nextSessionDate:nx},v==="ALL_EXIT"?HYBRID:NO_NATIVE_STOP);
  if(v==="SINGLE_CASH"&&st.state==="INVESTED"&&st.nextAction.type!=="SELL_ALL_NEXT_OPEN"&&!pendingPartial){const hit=st.currentPositions.find(p=>(p.currentPrice??Infinity)<=p.entryPrice*(1-HYBRID.risk.individualStop));if(hit){pendingPartial={symbol:hit.symbol,date:nx,reason:`${hit.symbol} close breached -${HYBRID.risk.individualStop*100}% individual-only stop`};partialStops++;stopEvents.push({signalDate:d,exitDate:nx,symbol:hit.symbol,close:hit.currentPrice,entryPrice:hit.entryPrice,otherSymbols:st.currentPositions.filter(p=>p.symbol!==hit.symbol).map(p=>p.symbol)});}}
  curve.push({date:d,equity:st.currentEquity,drawdown:st.drawdown});
 }
 return{curve,partialStops,stopEvents};
}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),vs:V[]=["ALL_EXIT","SINGLE_CASH"],runs=new Map<V,ReturnType<typeof sim>>();for(const v of vs){console.log("run",v);runs.set(v,sim(m.histories,u,v))}const full=vs.map(v=>({variant:v,...performanceStats(runs.get(v)!.curve),partialStops:runs.get(v)!.partialStops,stopEvents:runs.get(v)!.stopEvents})),years=[2021,2022,2023,2024,2025,2026],annual=years.map(y=>{const e=y===2026?"2026-08-25":`${y}-12-31`;return{year:y,allExit:performanceStats(ns(runs.get("ALL_EXIT")!.curve,`${y}-01-01`,e)),singleCash:performanceStats(ns(runs.get("SINGLE_CASH")!.curve,`${y}-01-01`,e))}}),splits=[] as any[];for(const y of [2022,2023,2024,2025,2026]){const te=`${y-1}-12-31`,oe=y===2026?"2026-08-25":`${y}-12-31`,tr=vs.map(v=>({v,s:performanceStats(ns(runs.get(v)!.curve,"2020-01-01",te))})).sort((a,b)=>(b.s.calmar??-Infinity)-(a.s.calmar??-Infinity)),ch=tr[0].v,base=performanceStats(ns(runs.get("ALL_EXIT")!.curve,`${y}-01-01`,oe)),oos=performanceStats(ns(runs.get(ch)!.curve,`${y}-01-01`,oe));splits.push({trainThrough:y-1,oosYear:y,chosen:ch,oos,allExitBase:base,cagrDiff:oos.cagr-base.cagr})}const out={generatedAt:new Date().toISOString(),method:{baseline:"Hybrid 60/40->70/30; Production behavior: any -17.5% individual stop sells all and enters Recovery10",candidate:"On -17.5% individual stop, sell only breached position next open, retain other position and cash proceeds; no Recovery lock from single-name stop",unchanged:"QQQ monthly gate and -15% portfolio circuit still sell all; monthly rebalance remains full sell/rebuy",cost:"10bp on partial stop sale and normal trades"},validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,architectureHindsightRemains:true,warning:"Retrospective pseudo-OOS. Candidate changes risk-state semantics and can hold one stock plus cash until next monthly rebalance."},full,annual,splits};const d=path.join(process.cwd(),"data/research/hybrid-single-position-stop-screen");await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,"result.json"),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});