import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY as P} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,PositionState,PricePoint,StrategyConfig,UniverseMonth} from '../src/lib/types';
const TAX=.20315;
type L={gain:Record<string,number>;loss:Record<string,number>;tax:number;sales:number;turnover:number};
type V={id:string;base:number};
const VS:V[]=[{id:'PROD50',base:.5},{id:'B55',base:.55},{id:'B60',base:.6},{id:'B65',base:.65},{id:'B70',base:.7}];
function cfg(v:V):StrategyConfig{return {...P,allocation:{...P.allocation,baseTop1Weight:v.base,concentratedTop1Weight:.7,maxTop1Weight:.7}} as StrategyConfig}
function sale(l:L,p:PositionState,px:number,d:string,c:StrategyConfig){const proceeds=p.shares*px*(1-c.execution.transactionCost),basis=p.shares*p.entryPrice,pnl=proceeds-basis,y=d.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++;l.turnover+=proceeds}
function taxCurve(curve:EquityPoint[],l:L){const yrs=[...new Set(curve.map(x=>x.date.slice(0,4)))],ty:Record<string,number>={};let carry:{y:number,a:number}[]=[];for(const ys of yrs){const y=+ys;carry=carry.filter(x=>y-x.y<=3);let n=(l.gain[ys]??0)-(l.loss[ys]??0);if(n>0){for(const x of carry){const u=Math.min(n,x.a);n-=u;x.a-=u;if(n<=0)break}carry=carry.filter(x=>x.a>1e-12);ty[ys]=n*TAX}else if(n<0)carry.push({y,a:-n})}l.tax=Object.values(ty).reduce((a,b)=>a+b,0);let e=curve[0]?.equity??1,prev=e,pk=e;const out:EquityPoint[]=[];for(let i=0;i<curve.length;i++){const p=curve[i];if(i)e*=p.equity/prev;prev=p.equity;const nx=curve[i+1];if((!nx||nx.date.slice(0,4)!==p.date.slice(0,4))&&(ty[p.date.slice(0,4)]??0)>0)e=Math.max(0,e-(ty[p.date.slice(0,4)]??0)*(e/Math.max(p.equity,1e-12)));pk=Math.max(pk,e);out.push({date:p.date,equity:e,drawdown:e/pk-1})}return out}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],v:V,disableDates:Set<string>=new Set()){const c=cfg(v),q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),ix=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(c);const curve:EquityPoint[]=[],lowGapDates:string[]=[],l:L={gain:{},loss:{},tax:0,sales:0,turnover:0};for(let i=0;i<ds.length;i++){const d=ds[i];if(d<c.backtestStart)continue;const n=ds[i+1]??nextUsTradingSession(d),uu=um.get(d);let sg=uu?buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:n,config:c}):null;if(sg?.marketRiskOn&&sg.selectedSymbols.length===2&&sg.zGap!==null&&sg.zGap<P.allocation.concentrationZGap){lowGapDates.push(d);if(disableDates.has(d)){const top=P.allocation.baseTop1Weight;sg={...sg,targetWeights:[top,1-top]};}}
 const sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),pr=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));const before=structuredClone(st);st=transitionDay(st,{date:d,prices:pr,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},c);if(before.currentPositions.length&&(before.nextAction.executionDate===d&&(before.nextAction.type==='SELL_ALL_NEXT_OPEN'||before.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN')))for(const p of before.currentPositions)sale(l,p,pr[p.symbol]?.open??pr[p.symbol]?.close??p.entryPrice,d,c);curve.push({date:d,equity:st.currentEquity,drawdown:st.drawdown})}return{curve,tax:taxCurve(curve,l),ledger:l,lowGapDates:[...new Set(lowGapDates)]}}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const prev=[...c].reverse().find(p=>p.date<s),z=prev?[prev,...x]:x,b=z[0].equity;return z.map(p=>({...p,equity:p.equity/b}))}
function stressed(b:EquityPoint[],c:EquityPoint[],f:number){let e=1,pk=1;const out:EquityPoint[]=[{date:b[0].date,equity:1,drawdown:0}];for(let i=1;i<Math.min(b.length,c.length);i++){const rb=b[i].equity/b[i-1].equity,rc=c[i].equity/c[i-1].equity;const lr=Math.log(Math.max(rb,1e-12))+f*(Math.log(Math.max(rc,1e-12))-Math.log(Math.max(rb,1e-12)));e*=Math.exp(lr);pk=Math.max(pk,e);out.push({date:b[i].date,equity:e,drawdown:e/pk-1})}return out}
async function main(){const mk=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const runs=new Map<string,ReturnType<typeof sim>>();for(const v of VS)runs.set(v.id,sim(mk.histories,u,v));const full=VS.map(v=>{const r=runs.get(v.id)!;return{id:v.id,base:v.base,gross:performanceStats(r.curve),afterTax:performanceStats(r.tax),taxPaidApprox:r.ledger.tax,sales:r.ledger.sales,turnover:r.ledger.turnover}});const years=[2020,2021,2022,2023,2024,2025,2026],annual=years.map(y=>({year:y,...Object.fromEntries(VS.map(v=>[v.id,performanceStats(sl(runs.get(v.id)!.curve,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))]))}));const b=runs.get('PROD50')!,h=runs.get('B65')!,z70=runs.get('B70')!;const edge=[0,.25,.5,.75,1].map(f=>({retention:f,stats:performanceStats(stressed(b.curve,h.curve,f)),confirmation:performanceStats(sl(stressed(b.curve,h.curve,f),'2023-01-01','2026-08-25'))}));const leaveEvent=h.lowGapDates.map(d=>{const r=sim(mk.histories,u,{id:'B65',base:.65},new Set([d]));return{disabledDate:d,gross:performanceStats(r.curve),deltaVsProd:performanceStats(r.curve).cagr-performanceStats(b.curve).cagr,lossOfH65Edge:performanceStats(h.curve).cagr-performanceStats(r.curve).cagr}});const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,noLeverage:true,warning:'Boundary stress is predeclared 50/55/60/65/70 base-weight path. 70 means always 70/30 whenever invested with two names. Edge-retention is sensitivity, not probability. Leave-event disables H65 only at one low-zGap monthly signal date.'},full,annual,boundary:{h65Vs70GrossDelta:performanceStats(h.curve).cagr-performanceStats(z70.curve).cagr,h65Vs70AfterTaxDelta:performanceStats(h.tax).cagr-performanceStats(z70.tax).cagr},edgeRetention:edge,leaveEvent,lowGapDates:h.lowGapDates};const d=path.join(process.cwd(),'data/research/hybrid65-boundary-stress');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}
main().catch(e=>{console.error(e);process.exit(1)});