import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY as BASE } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import { performanceStats } from "../src/lib/backtest";
import type { EquityPoint,PricePoint,UniverseMonth } from "../src/lib/types";
const H:any={...BASE,strategyId:"momentum-hybrid-60-70-circuit-neighborhood",allocation:{...BASE.allocation,baseTop1Weight:.60,concentratedTop1Weight:.70,concentrationZGap:.25,maxTop1Weight:.70}};
type V={id:string,circuit:number};const VS:V[]=[{id:"CIRCUIT12_5",circuit:.125},{id:"CIRCUIT15",circuit:.15},{id:"CIRCUIT17_5",circuit:.175},{id:"CIRCUIT20",circuit:.20}];
function hybrid(s:any){if(!s.marketRiskOn||s.selectedSymbols.length<2)return s;const top=s.zGap!==null&&s.zGap>=.25?.70:.60;return{...s,targetWeights:[top,1-top],allocationMode:top===.70?"70/30":"60/40"}}
function ns(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],v:V){const cfg:any={...H,risk:{...H.risk,portfolioCircuit:v.circuit}},q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(p=>p.date),di=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg);const c:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<cfg.backtestStart)continue;const nx=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?hybrid(buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:nx,config:cfg})):null,sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(di.get(d)??i)+1),monthlySignal:sg,nextSessionDate:nx},cfg);c.push({date:d,equity:st.currentEquity,drawdown:st.drawdown})}return c}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),curves=new Map<string,EquityPoint[]>();for(const v of VS){console.log("run",v.id);curves.set(v.id,sim(m.histories,u,v))}const full=VS.map(v=>({variant:v,...performanceStats(curves.get(v.id)!)})),splits=[] as any[];for(const y of [2022,2023,2024,2025,2026]){const te=`${y-1}-12-31`,oe=y===2026?"2026-08-25":`${y}-12-31`,tr=VS.map(v=>({v,s:performanceStats(ns(curves.get(v.id)!,"2020-01-01",te))})).sort((a,b)=>(b.s.calmar??-Infinity)-(a.s.calmar??-Infinity)),ch=tr[0].v,base=performanceStats(ns(curves.get("CIRCUIT15")!,`${y}-01-01`,oe)),oos=performanceStats(ns(curves.get(ch.id)!,`${y}-01-01`,oe));splits.push({trainThrough:y-1,oosYear:y,chosen:ch.id,trainCalmar:tr[0].s.calmar,oos,baseline:base,cagrDiff:oos.cagr-base.cagr})}const out={generatedAt:new Date().toISOString(),method:{baseline:"Hybrid 60/40->70/30, Stop17.5, Circuit15, Recovery10",variants:"Only portfolio circuit varies: 12.5/15/17.5/20%; all else fixed",selection:"training-only Calmar then next-year pseudo-OOS",priorRationale:"Earlier 972-candidate anchored parameter-region analysis showed Circuit17.5 dominating top10 across splits, so 17.5 is independently motivated rather than selected from this run."},validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,architectureHindsightRemains:true},full,splits};const d=path.join(process.cwd(),"data/research/hybrid-circuit-neighborhood");await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,"result.json"),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});