import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY as BASE } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { performanceStats } from "../src/lib/backtest";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import type { EquityPoint,PositionState,PricePoint,UniverseMonth } from "../src/lib/types";
const TAX=.20315,ROOT:any={...BASE,allocation:{...BASE.allocation,baseTop1Weight:.60,concentratedTop1Weight:.70,concentrationZGap:.25,maxTop1Weight:.70}};
type V={id:string,w3:number,w6:number};const VS:V[]=[{id:"HYBRID_W20_80",w3:.20,w6:.80},{id:"HYBRID_W25_75",w3:.25,w6:.75}];
type L={gain:Record<string,number>;loss:Record<string,number>;taxes:number;sales:number;turnover:number};
function hybrid(s:any){if(!s.marketRiskOn||s.selectedSymbols.length<2)return s;const t=s.zGap!==null&&s.zGap>=.25?.70:.60;return{...s,targetWeights:[t,1-t],allocationMode:t===.70?"70/30":"60/40"}}
function sale(l:L,p:PositionState,px:number,d:string,cfg:any){const pr=p.shares*px*(1-cfg.execution.transactionCost),basis=p.shares*p.entryPrice,pnl=pr-basis,y=d.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++;l.turnover+=pr}
function taxed(c:EquityPoint[],l:L){const ys=[...new Set(c.map(p=>p.date.slice(0,4)))],ty:Record<string,number>={};let carry:{y:number,a:number}[]=[];for(const s of ys){const y=+s;carry=carry.filter(x=>y-x.y<=3);let n=(l.gain[s]??0)-(l.loss[s]??0);if(n>0){for(const x of carry){const u=Math.min(n,x.a);n-=u;x.a-=u;if(n<=0)break}carry=carry.filter(x=>x.a>1e-12);ty[s]=n*TAX}else if(n<0)carry.push({y,a:-n})}l.taxes=Object.values(ty).reduce((a,b)=>a+b,0);let e=c[0]?.equity??1,prev=e,peak=e;return c.map((p,i)=>{if(i)e*=p.equity/prev;prev=p.equity;const n=c[i+1],y=p.date.slice(0,4);if((!n||n.date.slice(0,4)!==y)&&(ty[y]??0)>0)e=Math.max(0,e-(ty[y]??0)*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);return{date:p.date,equity:e,drawdown:e/peak-1}})}
function slice(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],v:V){const cfg:any={...ROOT,strategyId:v.id,momentum:{...ROOT.momentum,oneMonth:0,threeMonth:v.w3,sixMonth:v.w6}},q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(p=>p.date),di=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg);const c:EquityPoint[]=[],l:L={gain:{},loss:{},taxes:0,sales:0,turnover:0};for(let i=0;i<ds.length;i++){const d=ds[i];if(d<cfg.backtestStart)continue;const nx=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?hybrid(buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:nx,config:cfg})):null,sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)])),before=structuredClone(st);st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(di.get(d)??i)+1),monthlySignal:sg,nextSessionDate:nx},cfg);if(before.currentPositions.length&&((before.nextAction.type==="SELL_ALL_NEXT_OPEN"||before.nextAction.type==="MONTH_END_REBALANCE_NEXT_OPEN")&&before.nextAction.executionDate===d))for(const p of before.currentPositions)sale(l,p,prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice,d,cfg);c.push({date:d,equity:st.currentEquity,drawdown:st.drawdown})}return{gross:c,after:taxed(c,l),l}}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),r=VS.map(v=>({v,x:sim(m.histories,u,v)})),years=[2022,2023,2024,2025,2026],out={generatedAt:new Date().toISOString(),validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,warning:"Historical annual realized-P&L tax approximation, 20.315%, 3-year loss carry; not exact tax-lot/withholding timing."},full:r.map(({v,x})=>({variant:v,gross:performanceStats(x.gross),afterTax:performanceStats(x.after),taxPaidApprox:x.l.taxes,sales:x.l.sales,turnover:x.l.turnover})),annual:years.map(y=>Object.fromEntries([['year',y],...r.map(({v,x})=>[v.id,performanceStats(slice(x.after,`${y}-01-01`,y===2026?"2026-08-25":`${y}-12-31`))])]))};const d=path.join(process.cwd(),"data/research/hybrid-w25-tax-compare");await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,"result.json"),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});