import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { performanceStats } from "../src/lib/backtest";
import type { EquityPoint, PricePoint, UniverseMonth } from "../src/lib/types";
type MarketFile={histories:Record<string,PricePoint[]>};type UniverseFile={history:UniverseMonth[]};type FrozenFile={backtest?:{equityCurve:EquityPoint[]}};
type P={qqqSma:number;stockSma:number;breakout:number;shortVol:number;longVol:number;compression:number;hold:number;stop:number;circuit:number;topN:number;cost:number;delay:number;start:string;ignore?:string};
const BASE:P={qqqSma:200,stockSma:100,breakout:20,shortVol:10,longVol:60,compression:.75,hold:20,stop:.12,circuit:.15,topN:2,cost:.001,delay:0,start:"2020-01-01"};
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;const sd=(x:number[])=>{const m=mean(x);return Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/(x.length-1));};const q=(x:number[],p:number)=>{const a=[...x].sort((a,b)=>a-b),i=(a.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return a.length?(l===h?a[l]:a[l]*(h-i)+a[h]*(i-l)):NaN;};
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break;}return x;}
function run(h:Record<string,PricePoint[]>,us:UniverseMonth[],p:P){const qr=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date));const dates=qr.map(x=>x.date).filter(d=>d>=p.start);const rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))]));const idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))]));const maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1,trades=0;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??(maps[x.s] as Map<string,PricePoint>).get(d)?.close??x.e),0);
for(let di=0;di<dates.length;di++){const d=dates[di],nd=dates[di+1]??null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>{const r=(maps[x.s] as Map<string,PricePoint>).get(d);return z+x.sh*(r?.open??r?.close??x.e);},0)*(1-p.cost);pos=[];pout=null;hold=0;peak=cash;trades++;}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.every(x=>x&&x>0)){const per=cash/p.topN;pos=pin.ss.map((s,i)=>({s,sh:per*(1-p.cost)/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0;}pin=null;}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*(1-p.stop));if(stop||dd<=-p.circuit||hold>=p.hold)pout=nd;}if(!pos.length&&!pin&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<p.qqqSma-1)continue;const qrows=rows.QQQ as PricePoint[];if(qrows[qi].close<=mean(qrows.slice(qi-p.qqqSma+1,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const c:Array<{s:string;b:number}>=[];for(const m of u.symbols){const s=m.symbol;if(s===p.ignore)continue;const i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;const need=Math.max(p.stockSma-1,p.breakout,p.longVol);if(i==null||!r||i<need)continue;const close=r[i].close;if(close<=mean(r.slice(i-p.stockSma+1,i+1).map(x=>x.close)))continue;const hi=Math.max(...r.slice(i-p.breakout,i).map(x=>x.close));if(close<=hi)continue;const rets=(n:number)=>r.slice(i-n,i+1).map((x,j,a)=>j?x.close/a[j-1].close-1:0).slice(1);if(!(sd(rets(p.shortVol))<p.compression*sd(rets(p.longVol))))continue;c.push({s,b:close/hi-1});}c.sort((a,b)=>b.b-a.b||a.s.localeCompare(b.s));if(c.length>=p.topN){let ei=di+1+p.delay;if(ei<dates.length)pin={d:dates[ei],ss:c.slice(0,p.topN).map(x=>x.s)};}}}return{curve,trades};}
function monthly(c:EquityPoint[]){const m=new Map<string,EquityPoint>();for(const x of c)m.set(x.date.slice(0,7),x);const a=[...m.entries()].sort(([a],[b])=>a.localeCompare(b)),o=new Map<string,number>();for(let i=1;i<a.length;i++)o.set(a[i][0],a[i][1].equity/a[i-1][1].equity-1);return o;}
function corrMaps(a:Map<string,number>,b:Map<string,number>){const k=[...a.keys()].filter(x=>b.has(x));const x=k.map(z=>a.get(z)!),y=k.map(z=>b.get(z)!);const mx=mean(x),my=mean(y);let n=0,vx=0,vy=0;for(let i=0;i<x.length;i++){const dx=x[i]-mx,dy=y[i]-my;n+=dx*dy;vx+=dx*dx;vy+=dy*dy;}return n/Math.sqrt(vx*vy);}
function blendStats(a:Map<string,number>,b:Map<string,number>,wa:number){const k=[...a.keys()].filter(x=>b.has(x)).sort();let eq=1,peak=1;const c:EquityPoint[]=[];for(const m of k){eq*=1+wa*a.get(m)!+(1-wa)*b.get(m)!;peak=Math.max(peak,eq);c.push({date:m+"-28",equity:eq,drawdown:eq/peak-1});}return performanceStats(c);}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8")) as MarketFile;const u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8")) as UniverseFile;const f=JSON.parse(await readFile(resolve("public/data/backtest-frozen.json"),"utf8")) as FrozenFile;const us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const fixed=f.backtest?.equityCurve??[];const base=run(m.histories,us,BASE);const baseStats=performanceStats(base.curve);const scenarios:{name:string;p:P}[]=[{name:"cost30bp",p:{...BASE,cost:.003}},{name:"delay1",p:{...BASE,delay:1}},{name:"start2021",p:{...BASE,start:"2021-01-01"}},{name:"breakout15",p:{...BASE,breakout:15}},{name:"breakout30",p:{...BASE,breakout:30}},{name:"compression60",p:{...BASE,compression:.60}},{name:"compression90",p:{...BASE,compression:.90}},{name:"hold10",p:{...BASE,hold:10}},{name:"hold30",p:{...BASE,hold:30}}];const stress=scenarios.map(s=>{const r=run(m.histories,us,s.p);return{name:s.name,stats:performanceStats(r.curve),trades:r.trades};});const syms=[...new Set(us.flatMap(x=>x.symbols.map(y=>y.symbol)))];const loo=syms.map(s=>{const r=run(m.histories,us,{...BASE,ignore:s});return{symbol:s,cagr:performanceStats(r.curve).cagr};}).sort((a,b)=>a.cagr-b.cagr);const vm=monthly(base.curve),fm=monthly(fixed);const blend80=blendStats(fm,vm,.8),blend70=blendStats(fm,vm,.7);const stressCagrs=stress.map(x=>x.stats.cagr);console.log(JSON.stringify({baseline:{stats:baseStats,trades:base.trades,correlation:corrMaps(vm,fm)},stress,stressSummary:{medianCagr:q(stressCagrs,.5),p10Cagr:q(stressCagrs,.1),worstCagr:Math.min(...stressCagrs)},loo:{worst:loo[0],p10:q(loo.map(x=>x.cagr),.1),median:q(loo.map(x=>x.cagr),.5),worstRetention:loo[0].cagr/baseStats.cagr,bottom10:loo.slice(0,10)},blends:{fixed80_vcb20:blend80,fixed70_vcb30:blend70}},null,2));}
main().catch(e=>{console.error(e);process.exitCode=1;});
