import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import type {EquityPoint,PricePoint,UniverseMonth} from "../src/lib/types";

type MF={histories:Record<string,PricePoint[]>}; type UF={history:UniverseMonth[]};
const SPEC={strategyId:"independent-top5-breakout-v1",qqqSma:200,stockSma:100,breakout:20,hold:20,topN:5,stop:.12,circuit:.15,cost:.001,start:"2020-01-01"};
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function runG(h:Record<string,PricePoint[]>,us:UniverseMonth[]){const qqq=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=qqq.map(x=>x.date).filter(d=>d>=SPEC.start),rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))])),idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))])),maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??(maps[x.s] as Map<string,PricePoint>).get(d)?.close??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di],nd=di+1<dates.length?dates[di+1]:null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>{const r=(maps[x.s] as Map<string,PricePoint>).get(d);return z+x.sh*(r?.open??r?.close??x.e)},0)*(1-SPEC.cost);pos=[];pout=null;hold=0;peak=cash}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===SPEC.topN&&os.every(x=>x&&x>0)){const per=cash/SPEC.topN;pos=pin.ss.map((s,i)=>({s,sh:per*(1-SPEC.cost)/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*(1-SPEC.stop));if(stop||dd<=-SPEC.circuit||hold>=SPEC.hold)pout=nd}if(!pos.length&&!pin&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<SPEC.qqqSma-1)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-SPEC.qqqSma+1,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<Math.max(SPEC.stockSma-1,SPEC.breakout))continue;const close=r[i].close;if(close<=mean(r.slice(i-SPEC.stockSma+1,i+1).map(x=>x.close)))continue;const hi=Math.max(...r.slice(i-SPEC.breakout,i).map(x=>x.close));if(close>hi)ca.push({s,v:close/hi-1})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=SPEC.topN)pin={d:nd,ss:ca.slice(0,SPEC.topN).map(x=>x.s)}}}return curve}
function monthly(c:EquityPoint[]){const last=new Map<string,EquityPoint>();for(const p of c)last.set(p.date.slice(0,7),p);const a=[...last.entries()].sort(([a],[b])=>a.localeCompare(b)),r=new Map<string,number>();for(let i=1;i<a.length;i++)r.set(a[i][0],a[i][1].equity/a[i-1][1].equity-1);return r}
function corr(a:Map<string,number>,b:Map<string,number>){const k=[...a.keys()].filter(x=>b.has(x)),x=k.map(z=>a.get(z)!),y=k.map(z=>b.get(z)!);const mx=mean(x),my=mean(y);let n=0,vx=0,vy=0;for(let i=0;i<x.length;i++){const dx=x[i]-mx,dy=y[i]-my;n+=dx*dy;vx+=dx*dx;vy+=dy*dy}return n/Math.sqrt(vx*vy)}
function blend(a:EquityPoint[],b:EquityPoint[],wa:number){const bm=new Map(b.map(x=>[x.date,x.equity]));let ap=a[0]?.equity??1,bp=bm.get(a[0]?.date??"")??1,e=1,peak=1;const c:EquityPoint[]=[];for(const p of a){const bv=bm.get(p.date);if(bv==null)continue;const ra=p.equity/ap-1,rb=bv/bp-1;e*=1+wa*ra+(1-wa)*rb;peak=Math.max(peak,e);c.push({date:p.date,equity:e,drawdown:e/peak-1});ap=p.equity;bp=bv}return performanceStats(c)}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const fixed=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve,g=runG(m.histories,us),fm=monthly(fixed),gm=monthly(g),neg=[...fm.keys()].filter(k=>(fm.get(k)??0)<0),pos=neg.filter(k=>(gm.get(k)??0)>0);console.log(JSON.stringify({productionStrategyId:PRODUCTION_STRATEGY.strategyId,fixed60:performanceStats(fixed),g:performanceStats(g),independence:{monthlyCorrelation:corr(fm,gm),fixedNegativeMonths:neg.length,gPositiveInFixedNegativeMonths:pos.length,positiveShare:neg.length?pos.length/neg.length:null},blends:{fixed90_g10:blend(fixed,g,.9),fixed80_g20:blend(fixed,g,.8),fixed70_g30:blend(fixed,g,.7),fixed60_g40:blend(fixed,g,.6),fixed50_g50:blend(fixed,g,.5)}},null,2))}main().catch(e=>{console.error(e);process.exitCode=1});
