import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { performanceStats, runStrategySimulation } from "../src/lib/backtest";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import type { EquityPoint, PricePoint, UniverseMonth } from "../src/lib/types";

type MF={histories:Record<string,PricePoint[]>}; type UF={history:UniverseMonth[]};
type Candidate={id:string;hold:number;stop:number;circuit:number;selector:(s:string,i:number,r:PricePoint[])=>number|null};
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;
const median=(x:number[])=>{const a=[...x].sort((a,b)=>a-b);const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const stdev=(x:number[])=>{if(x.length<2)return 0;const m=mean(x);return Math.sqrt(x.reduce((z,v)=>z+(v-m)**2,0)/(x.length-1))};
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function monthly(c:EquityPoint[]){const m=new Map<string,EquityPoint>();for(const p of c)m.set(p.date.slice(0,7),p);const a=[...m.entries()].sort(([a],[b])=>a.localeCompare(b));const out=new Map<string,number>();for(let i=1;i<a.length;i++)out.set(a[i][0],a[i][1].equity/a[i-1][1].equity-1);return out}
function corr(a:number[],b:number[]){const ma=mean(a),mb=mean(b);const n=Math.min(a.length,b.length);let xy=0,xa=0,xb=0;for(let i=0;i<n;i++){const x=a[i]-ma,y=b[i]-mb;xy+=x*y;xa+=x*x;xb+=y*y}return xa&&xb?xy/Math.sqrt(xa*xb):0}
function runCandidate(h:Record<string,PricePoint[]>,us:UniverseMonth[],c:Candidate,delay=0){const qqq=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date));const dates=qqq.map(x=>x.date).filter(d=>d>="2020-01-01"&&d<="2026-08-25");const rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))]));const idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))]));const maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di],nd=dates[di+1]??null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.open??x.e),0)*.999;pos=[];pout=null;hold=0;peak=cash}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===5&&os.every(x=>x&&x>0)){const per=cash/5;pos=pin.ss.map((s,i)=>({s,sh:per*.999/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*(1-c.stop));if(stop||dd<=-c.circuit||hold>=c.hold)pout=nd}if(!pos.length&&!pin){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<100)continue;const v=c.selector(s,i,r);if(v!=null&&Number.isFinite(v))ca.push({s,v})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=5){const target=dates[di+1+delay];if(target)pin={d:target,ss:ca.slice(0,5).map(x=>x.s)}}}}return curve}
function mainReport(h:Record<string,PricePoint[]>,us:UniverseMonth[],c:Candidate,fixed:EquityPoint[]){const base=runCandidate(h,us,c,0), delayed=runCandidate(h,us,c,1), bm=monthly(base),fm=monthly(fixed);const months=[...bm.keys()].filter(k=>fm.has(k)),a=months.map(k=>bm.get(k)!),b=months.map(k=>fm.get(k)!);const neg=months.filter(k=>fm.get(k)!<0),posNeg=neg.filter(k=>bm.get(k)!>0).length;const bs=performanceStats(base),ds=performanceStats(delayed);return{id:c.id,baseline:bs,delay1:ds,independence:{monthlyCorrelation:corr(a,b),fixedNegativeMonths:neg.length,positiveInFixedNegativeMonths:posNeg,positiveShare:neg.length?posNeg/neg.length:0},screen:{cagr:bs.cagr>=.15,maxDD:bs.maxDrawdown>-.40,correlation:Math.abs(corr(a,b))<=.60,negativeMonthComplement:neg.length?posNeg/neg.length>=.30:false,delay:ds.cagr>=.10,pass:bs.cagr>=.15&&bs.maxDrawdown>-.40&&Math.abs(corr(a,b))<=.60&&(neg.length?posNeg/neg.length>=.30:false)&&ds.cagr>=.10}}}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF;const us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const fixed=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(p=>p.date<="2026-08-25");const I:Candidate={id:"I-shock-continuation",hold:10,stop:.12,circuit:.15,selector:(_s,i,r)=>{if(i<100)return null;const close=r[i].close;if(close<=mean(r.slice(i-99,i+1).map(x=>x.close)))return null;const rets=[];for(let j=i-19;j<=i;j++)if(j>0)rets.push(r[j].close/r[j-1].close-1);const vol=stdev(rets.slice(0,-1));const shock=close/r[i-1].close-1;return vol>0&&shock>2*vol?shock/vol:null}};
const J:Candidate={id:"J-failed-gap-reversal",hold:5,stop:.10,circuit:.12,selector:(_s,i,r)=>{if(i<100)return null;const prior=r[i-1].close,o=r[i].open,c=r[i].close;if(r[i-1].close<=mean(r.slice(i-100,i).map(x=>x.close)))return null;const gap=o/prior-1;if(gap>-.05||c<=o)return null;const rec=(c-o)/(prior-o);return rec>=.5?rec:null}};
const K:Candidate={id:"K-range-expansion-continuation",hold:10,stop:.12,circuit:.15,selector:(_s,i,r)=>{if(i<101)return null;const c=r[i].close;if(c<=mean(r.slice(i-99,i+1).map(x=>x.close)))return null;const ratios=[];for(let j=i-20;j<i;j++){const prev=r[j-1].close;ratios.push((r[j].high-r[j].low)/prev)}const tr=(r[i].high-r[i].low)/r[i-1].close,med=median(ratios),range=r[i].high-r[i].low,pos=range>0?(c-r[i].low)/range:0;return med>0&&tr>2*med&&pos>=.8?tr/med:null}};
console.log(JSON.stringify({fixed60:performanceStats(fixed),candidates:[I,J,K].map(c=>mainReport(m.histories,us,c,fixed))},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});