import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { performanceStats, runStrategySimulation } from "../src/lib/backtest";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import type { EquityPoint, PricePoint, UniverseMonth } from "../src/lib/types";

type MF={histories:Record<string,PricePoint[]>}; type UF={history:UniverseMonth[]};
type TurnoverRow={date:string;turnover:number}; type Turnover=Record<string,Map<string,number>>;
type Candidate={id:string;hold:number;stop:number;circuit:number;selector:(s:string,i:number,r:PricePoint[],turnover:Turnover)=>number|null};
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;
const median=(x:number[])=>{const a=[...x].sort((a,b)=>a-b);const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function monthly(c:EquityPoint[]){const m=new Map<string,EquityPoint>();for(const p of c)m.set(p.date.slice(0,7),p);const a=[...m.entries()].sort(([a],[b])=>a.localeCompare(b)),o=new Map<string,number>();for(let i=1;i<a.length;i++)o.set(a[i][0],a[i][1].equity/a[i-1][1].equity-1);return o}
function corr(a:number[],b:number[]){const ma=mean(a),mb=mean(b);let xy=0,xx=0,yy=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;xy+=x*y;xx+=x*x;yy+=y*y}return xx&&yy?xy/Math.sqrt(xx*yy):0}
async function fetchTurnover(symbol:string):Promise<TurnoverRow[]>{const start=Math.floor(Date.parse("2018-01-01T00:00:00Z")/1000),end=Math.floor(Date.now()/1000)+86400,y=encodeURIComponent(symbol.replace(".","-"));let err="";for(let a=0;a<4;a++){const host=a%2===0?"query1.finance.yahoo.com":"query2.finance.yahoo.com";try{const res=await fetch(`https://${host}/v8/finance/chart/${y}?period1=${start}&period2=${end}&interval=1d&events=history&includeAdjustedClose=true`,{headers:{"User-Agent":"Mozilla/5.0 MomentumResearch/1.0",Accept:"application/json"},signal:AbortSignal.timeout(20000)});if(!res.ok){err=String(res.status);continue}const body=await res.json() as any,result=body?.chart?.result?.[0],q=result?.indicators?.quote?.[0];if(!result?.timestamp||!q)return[];return result.timestamp.map((ts:number,i:number)=>{const c=q.close?.[i],v=q.volume?.[i];return typeof c==="number"&&c>0&&typeof v==="number"&&v>0?{date:new Date(ts*1000).toISOString().slice(0,10),turnover:c*v}:null}).filter((x:any):x is TurnoverRow=>x!==null)}catch(e){err=e instanceof Error?e.message:String(e)}await new Promise(r=>setTimeout(r,250*(a+1)))}console.warn(`${symbol}: volume fetch failed ${err}`);return[]}
async function loadTurnover(symbols:string[]){const out:Turnover={};let cursor=0;async function worker(){while(cursor<symbols.length){const s=symbols[cursor++],rows=await fetchTurnover(s);out[s]=new Map(rows.map(x=>[x.date,x.turnover]))}}await Promise.all(Array.from({length:8},()=>worker()));return out}
function turnoverRatio(s:string,r:PricePoint[],i:number,t:Turnover){const m=t[s];if(!m)return null;const cur=m.get(r[i].date);if(!(cur&&cur>0))return null;const prior:number[]=[];for(let j=i-20;j<i;j++){const v=m.get(r[j].date);if(v&&v>0)prior.push(v)}if(prior.length<15)return null;const med=median(prior);return med>0?cur/med:null}
function run(h:Record<string,PricePoint[]>,us:UniverseMonth[],t:Turnover,c:Candidate,delay=0){const qqq=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=qqq.map(x=>x.date).filter(d=>d>="2020-01-01"&&d<="2026-08-25"),rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))])),idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))])),maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1,trades=0;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di],nd=dates[di+1]??null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.open??x.e),0)*.999;pos=[];pout=null;hold=0;peak=cash;trades++}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===5&&os.every(x=>x&&x>0)){const per=cash/5;pos=pin.ss.map((s,i)=>({s,sh:per*.999/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*(1-c.stop));if(stop||dd<=-c.circuit||hold>=c.hold)pout=nd}if(!pos.length&&!pin){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const mem of u.symbols){const s=mem.symbol,r=rows[s] as PricePoint[]|undefined,i=(idx[s] as Map<string,number>|undefined)?.get(d);if(!r||i==null||i<100)continue;const v=c.selector(s,i,r,t);if(v!=null&&Number.isFinite(v))ca.push({s,v})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=5){const target=dates[di+1+delay];if(target)pin={d:target,ss:ca.slice(0,5).map(x=>x.s)}}}}return{curve,trades}}
function report(h:Record<string,PricePoint[]>,us:UniverseMonth[],t:Turnover,c:Candidate,fixed:EquityPoint[]){const b=run(h,us,t,c),d=run(h,us,t,c,1),bm=monthly(b.curve),fm=monthly(fixed),ks=[...bm.keys()].filter(k=>fm.has(k)),x=ks.map(k=>bm.get(k)!),y=ks.map(k=>fm.get(k)!),neg=ks.filter(k=>fm.get(k)!<0),hit=neg.filter(k=>bm.get(k)!>0).length,bs=performanceStats(b.curve),ds=performanceStats(d.curve),co=corr(x,y),share=neg.length?hit/neg.length:0;return{id:c.id,trades:b.trades,baseline:bs,delay1:ds,independence:{monthlyCorrelation:co,fixedNegativeMonths:neg.length,positiveInFixedNegativeMonths:hit,positiveShare:share},screen:{cagr:bs.cagr>=.15,maxDD:bs.maxDrawdown>-.40,correlation:Math.abs(co)<=.60,negativeMonthComplement:share>=.30,delay:ds.cagr>=.10,pass:bs.cagr>=.15&&bs.maxDrawdown>-.40&&Math.abs(co)<=.60&&share>=.30&&ds.cagr>=.10}}}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const symbols=[...new Set(us.flatMap(x=>x.symbols.map(s=>s.symbol)))].filter(s=>m.histories[s]?.length);console.log(`Fetching research-only volume for ${symbols.length} symbols`);const t=await loadTurnover(symbols);console.log(`Volume series loaded: ${Object.values(t).filter(x=>x.size>0).length}/${symbols.length}`);const fixed=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(p=>p.date<="2026-08-25");const Q:Candidate={id:"Q-abnormal-participation-continuation",hold:10,stop:.12,circuit:.15,selector:(s,i,r,t)=>{const c=r[i].close,prev=r[i-1].close;if(c<=mean(r.slice(i-99,i+1).map(x=>x.close)))return null;const ret=c/prev-1,vr=turnoverRatio(s,r,i,t),range=(r[i].high??c)-(r[i].low??c),loc=range>0?(c-(r[i].low??c))/range:.5;return vr!=null&&ret>.01&&vr>2.5&&loc>=.5?vr*ret:null}};const R:Candidate={id:"R-low-participation-pullback",hold:5,stop:.10,circuit:.12,selector:(s,i,r,t)=>{const c=r[i].close,prev=r[i-1].close;if(c<=mean(r.slice(i-99,i+1).map(x=>x.close)))return null;const ret=c/prev-1,vr=turnoverRatio(s,r,i,t);return vr!=null&&ret<=-.03&&vr<.70?Math.abs(ret)/Math.max(vr,.05):null}};const S:Candidate={id:"S-high-participation-absorption",hold:10,stop:.12,circuit:.15,selector:(s,i,r,t)=>{const c=r[i].close,prev=r[i-1].close;if(c<=mean(r.slice(i-99,i+1).map(x=>x.close)))return null;const ret=c/prev-1,vr=turnoverRatio(s,r,i,t),hi=r[i].high??c,lo=r[i].low??c,range=hi-lo,loc=range>0?(c-lo)/range:.5;return vr!=null&&vr>2.5&&Math.abs(ret)<.01&&loc>=.75?vr*loc:null}};console.log(JSON.stringify({fixed60:performanceStats(fixed),volumeCoverage:Object.values(t).filter(x=>x.size>0).length,candidates:[Q,R,S].map(c=>report(m.histories,us,t,c,fixed))},null,2))}main().catch(e=>{console.error(e);process.exitCode=1});