import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { performanceStats, runStrategySimulation } from "../src/lib/backtest";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import type { EquityPoint, PricePoint, UniverseMonth } from "../src/lib/types";
type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;const sd=(x:number[])=>{if(x.length<2)return 0;const m=mean(x);return Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/(x.length-1))};
function monthly(c:EquityPoint[]){const m=new Map<string,EquityPoint>();for(const p of c)m.set(p.date.slice(0,7),p);const a=[...m.entries()].sort(([a],[b])=>a.localeCompare(b)),o=new Map<string,number>();for(let i=1;i<a.length;i++)o.set(a[i][0],a[i][1].equity/a[i-1][1].equity-1);return o}function corr(a:number[],b:number[]){const ma=mean(a),mb=mean(b);let xy=0,xx=0,yy=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;xy+=x*y;xx+=x*x;yy+=y*y}return xx&&yy?xy/Math.sqrt(xx*yy):0}
function run(h:Record<string,PricePoint[]>,delay:number){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),t=[...(h.TQQQ??[])].sort((a,b)=>a.date.localeCompare(b.date));const qmap=new Map(q.map((x,i)=>[x.date,i])),tmap=new Map(t.map((x,i)=>[x.date,i])),dates=q.map(x=>x.date).filter(d=>d>="2020-01-01"&&d<="2026-08-25"),pending=new Map<string,number>();let cash=1,shares=0,peak=1;const curve:EquityPoint[]=[];for(let di=0;di<dates.length;di++){const d=dates[di],ti=tmap.get(d),qi=qmap.get(d);if(ti==null||qi==null)continue;const tr=t[ti],exec=pending.get(d);if(exec!=null){const openEq=cash+shares*tr.open,current=shares*tr.open,desired=openEq*exec,trade=desired-current,cost=Math.abs(trade)*.001;shares=desired/tr.open;cash=openEq-desired-cost}const eq=cash+shares*tr.close;peak=Math.max(peak,eq);curve.push({date:d,equity:eq,drawdown:eq/peak-1});let w=0;if(qi>=199&&ti>=20){const ma=mean(q.slice(qi-199,qi+1).map(x=>x.close));if(q[qi].close>ma){const rets=[];for(let j=ti-19;j<=ti;j++)rets.push(t[j].close/t[j-1].close-1);const vol=sd(rets)*Math.sqrt(252);w=vol>0?Math.min(1,.30/vol):0}}const target=dates[di+1+delay];if(target)pending.set(target,w)}return curve}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const fixed=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(p=>p.date<="2026-08-25"),base=run(m.histories,0),d1=run(m.histories,1),bm=monthly(base),fm=monthly(fixed),ks=[...bm.keys()].filter(k=>fm.has(k)),x=ks.map(k=>bm.get(k)!),y=ks.map(k=>fm.get(k)!),neg=ks.filter(k=>fm.get(k)!<0),hit=neg.filter(k=>bm.get(k)!>0).length,co=corr(x,y),share=neg.length?hit/neg.length:0,bs=performanceStats(base),ds=performanceStats(d1);console.log(JSON.stringify({fixed60:performanceStats(fixed),candidate:{id:"O-volatility-managed-nasdaq-trend",baseline:bs,delay1:ds,independence:{monthlyCorrelation:co,fixedNegativeMonths:neg.length,positiveInFixedNegativeMonths:hit,positiveShare:share},screen:{cagr:bs.cagr>=.15,maxDD:bs.maxDrawdown>-.40,correlation:Math.abs(co)<=.60,negativeMonthComplement:share>=.30,delay:ds.cagr>=.10,pass:bs.cagr>=.15&&bs.maxDrawdown>-.40&&Math.abs(co)<=.60&&share>=.30&&ds.cagr>=.10}}},null,2))}main().catch(e=>{console.error(e);process.exitCode=1});