import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { performanceStats } from "../src/lib/backtest";
import { fetchYahooHistory } from "../src/lib/yahoo";
import type { EquityPoint, PricePoint } from "../src/lib/types";

type MF={histories:Record<string,PricePoint[]>}; type Vec=[number,number,number,number];
type RunCfg={trendDays?:number;delay?:number;cost?:number;start?:string;active?:[boolean,boolean,boolean,boolean]};
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;
const quantile=(x:number[],p:number)=>{const a=[...x].sort((a,b)=>a-b);if(!a.length)return NaN;const i=(a.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return l===h?a[l]:a[l]*(h-i)+a[h]*(i-l)};
function run(under:PricePoint[][],inst:PricePoint[][],cfg:RunCfg={}){const trend=cfg.trendDays??200,delay=cfg.delay??0,costRate=cfg.cost??.001,start=cfg.start??"2020-01-01",active=cfg.active??[true,true,true,true];const um=under.map(a=>new Map(a.map((x,i)=>[x.date,i]))),ip=inst.map(a=>new Map(a.map(x=>[x.date,x])));const clock=under[0].map(x=>x.date).filter(d=>d>=start&&d<="2026-08-25"&&under.every((_a,k)=>um[k].has(d))&&inst.every((_a,k)=>ip[k].has(d)));const pending=new Map<string,Vec>();let cash=1,shares=[0,0,0,0],peak=1;const curve:EquityPoint[]=[];for(let di=0;di<clock.length;di++){const d=clock[di],exec=pending.get(d);if(exec){const opens=ip.map(m=>m.get(d)!.open),current=shares.map((sh,k)=>sh*opens[k]),eq=cash+current.reduce((z,v)=>z+v,0);let desired=exec.map(w=>eq*w),net=eq;for(let iteration=0;iteration<3;iteration++){const cost=desired.reduce((z,v,k)=>z+Math.abs(v-current[k])*costRate,0);net=Math.max(0,eq-cost);desired=exec.map(w=>net*w)}shares=desired.map((v,k)=>v/opens[k]);cash=Math.max(0,net-desired.reduce((z,v)=>z+v,0))}const equity=cash+shares.reduce((z,sh,k)=>z+sh*ip[k].get(d)!.close,0);peak=Math.max(peak,equity);curve.push({date:d,equity,drawdown:equity/peak-1});const vec:Vec=[0,0,0,0];for(let k=0;k<4;k++){if(!active[k])continue;const ix=um[k].get(d)!;if(ix>=trend-1){const a=under[k];vec[k]=a[ix].close>mean(a.slice(ix-trend+1,ix+1).map(x=>x.close))?.25:0}}const target=clock[di+1+delay];if(target)pending.set(target,vec)}return curve}
function yearly(c:EquityPoint[]){const out:Record<string,number>={},by=new Map<string,EquityPoint[]>();for(const p of c){const y=p.date.slice(0,4);if(!by.has(y))by.set(y,[]);by.get(y)!.push(p)}for(const[y,a]of by)if(a.length>1)out[y]=a.at(-1)!.equity/a[0].equity-1;return out}
function rolling(c:EquityPoint[],days:number){const r:number[]=[];for(let i=days;i<c.length;i++)r.push(Math.pow(c[i].equity/c[i-days].equity,252/days)-1);return{median:quantile(r,.5),p10:quantile(r,.1),worst:r.length?Math.min(...r):NaN,positiveShare:r.length?r.filter(x=>x>0).length/r.length:NaN,count:r.length}}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF;const [iwm,xlf,xle,tna,fas,erx]=await Promise.all(["IWM","XLF","XLE","TNA","FAS","ERX"].map(fetchYahooHistory));const under=[m.histories.QQQ??[],iwm,xlf,xle],inst=[m.histories.TQQQ??[],tna,fas,erx];const base=run(under,inst),baseStats=performanceStats(base);const variants={cost30bp:run(under,inst,{cost:.003}),delay2:run(under,inst,{delay:2}),start2021:run(under,inst,{start:"2021-01-01"}),trend150:run(under,inst,{trendDays:150}),trend250:run(under,inst,{trendDays:250}),removeNasdaq:run(under,inst,{active:[false,true,true,true]}),removeSmallCap:run(under,inst,{active:[true,false,true,true]}),removeFinancials:run(under,inst,{active:[true,true,false,true]}),removeEnergy:run(under,inst,{active:[true,true,true,false]})};const stats=Object.fromEntries(Object.entries(variants).map(([k,c])=>[k,performanceStats(c)]));const cagrs=Object.values(stats).map(s=>s.cagr),removals=[stats.removeNasdaq,stats.removeSmallCap,stats.removeFinancials,stats.removeEnergy],worstRemoval=Math.min(...removals.map(s=>s.cagr));console.log(JSON.stringify({candidate:"U-diversified-leveraged-trend-ensemble",baseline:baseStats,yearly:yearly(base),rolling12M:rolling(base,252),rolling36M:rolling(base,756),stress:stats,stressDistribution:{median:quantile(cagrs,.5),p10:quantile(cagrs,.1),worst:Math.min(...cagrs)},sleeveRemoval:{worstCagr:worstRemoval,worstRetention:baseStats.cagr?worstRemoval/baseStats.cagr:null}},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});