import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { performanceStats, runStrategySimulation } from "../src/lib/backtest";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { fetchYahooHistory } from "../src/lib/yahoo";
import type { EquityPoint, PricePoint, UniverseMonth } from "../src/lib/types";
type MF={histories:Record<string,PricePoint[]>}; type UF={history:UniverseMonth[]};
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;
function monthly(c:EquityPoint[]){const m=new Map<string,EquityPoint>();for(const p of c)m.set(p.date.slice(0,7),p);const a=[...m.entries()].sort(([a],[b])=>a.localeCompare(b)),o=new Map<string,number>();for(let i=1;i<a.length;i++)o.set(a[i][0],a[i][1].equity/a[i-1][1].equity-1);return o}
function corr(a:number[],b:number[]){const ma=mean(a),mb=mean(b);let xy=0,xx=0,yy=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;xy+=x*y;xx+=x*x;yy+=y*y}return xx&&yy?xy/Math.sqrt(xx*yy):0}
function run(qqq:PricePoint[],svxy:PricePoint[],vix:PricePoint[],delay:number){const q=[...qqq].sort((a,b)=>a.date.localeCompare(b.date)),s=[...svxy].sort((a,b)=>a.date.localeCompare(b.date)),v=[...vix].sort((a,b)=>a.date.localeCompare(b.date));const qi=new Map(q.map((x,i)=>[x.date,i])),sm=new Map(s.map(x=>[x.date,x])),vm=new Map(v.map(x=>[x.date,x]));const dates=q.map(x=>x.date).filter(d=>d>="2020-01-01"&&d<="2026-08-25");const pending=new Map<string,0|1>();let cash=1,shares=0,target:0|1=0,peak=1,switches=0;const curve:EquityPoint[]=[];for(let di=0;di<dates.length;di++){const d=dates[di],sp=sm.get(d);if(!sp)continue;const exec=pending.get(d);if(exec!=null&&exec!==target){const openEq=cash+shares*sp.open;if(exec===1){const investable=openEq*(1-.001);shares=investable/sp.open;cash=0}else{cash=shares*sp.open*(1-.001);shares=0}target=exec;switches++}const eq=cash+shares*sp.close;peak=Math.max(peak,eq);curve.push({date:d,equity:eq,drawdown:eq/peak-1});const ix=qi.get(d),vp=vm.get(d);let next:0|1=0;if(ix!=null&&ix>=199&&vp){const sma=mean(q.slice(ix-199,ix+1).map(x=>x.close));next=q[ix].close>sma&&vp.close<25?1:0}const execDate=dates[di+1+delay];if(execDate)pending.set(execDate,next)}return{curve,switches}}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const [svxy,vix]=await Promise.all([fetchYahooHistory("SVXY"),fetchYahooHistory("^VIX")]);const fixed=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(p=>p.date<="2026-08-25"),base=run(m.histories.QQQ??[],svxy,vix,0),d1=run(m.histories.QQQ??[],svxy,vix,1),bm=monthly(base.curve),fm=monthly(fixed),ks=[...bm.keys()].filter(k=>fm.has(k)),x=ks.map(k=>bm.get(k)!),y=ks.map(k=>fm.get(k)!),neg=ks.filter(k=>fm.get(k)!<0),hit=neg.filter(k=>bm.get(k)!>0).length,co=corr(x,y),share=neg.length?hit/neg.length:0,bs=performanceStats(base.curve),ds=performanceStats(d1.curve);console.log(JSON.stringify({fixed60:performanceStats(fixed),data:{svxyRows:svxy.length,vixRows:vix.length},candidate:{id:"T-vix-gated-short-volatility",switches:base.switches,baseline:bs,delay1:ds,independence:{monthlyCorrelation:co,fixedNegativeMonths:neg.length,positiveInFixedNegativeMonths:hit,positiveShare:share},screen:{cagr:bs.cagr>=.15,maxDD:bs.maxDrawdown>-.40,correlation:Math.abs(co)<=.60,negativeMonthComplement:share>=.30,delay:ds.cagr>=.10,pass:bs.cagr>=.15&&bs.maxDrawdown>-.40&&Math.abs(co)<=.60&&share>=.30&&ds.cagr>=.10}}},null,2))}main().catch(e=>{console.error(e);process.exitCode=1});