import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { performanceStats } from "../src/lib/backtest";
import type { EquityPoint, PricePoint, UniverseMonth } from "../src/lib/types";

type MarketFile={histories:Record<string,PricePoint[]>}; type UniverseFile={history:UniverseMonth[]}; type FrozenFile={backtest?:{equityCurve:EquityPoint[]}};
const COST=.001;
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;
const sd=(x:number[])=>{if(x.length<2)return NaN;const m=mean(x);return Math.sqrt(x.reduce((s,v)=>s+(v-m)**2,0)/(x.length-1));};
const mk=(d:string)=>d.slice(0,7);
function monthly(c:EquityPoint[]){const m=new Map<string,EquityPoint>();for(const p of c)m.set(mk(p.date),p);const r=new Map<string,number>();const a=[...m.entries()].sort(([a],[b])=>a.localeCompare(b));for(let i=1;i<a.length;i++)r.set(a[i][0],a[i][1].equity/a[i-1][1].equity-1);return r;}
function corr(a:number[],b:number[]){if(a.length<2)return NaN;const ma=mean(a),mb=mean(b);let n=0,va=0,vb=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;n+=x*y;va+=x*x;vb+=y*y;}return n/Math.sqrt(va*vb);}
function latestUniverse(us:UniverseMonth[],date:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=date)x=u;else break;}return x;}
function summary(name:string,curve:EquityPoint[],fixed:EquityPoint[],trades:number){const s=performanceStats(curve),a=monthly(curve),f=monthly(fixed),keys=[...a.keys()].filter(k=>f.has(k));const cr=corr(keys.map(k=>a.get(k)!),keys.map(k=>f.get(k)!));const neg=keys.filter(k=>f.get(k)!<0),pos=neg.filter(k=>a.get(k)!>0);return{name,stats:s,trades,independence:{monthlyCorrelationWithFixed60:cr,fixed60NegativeMonths:neg.length,positiveShareDuringFixed60NegativeMonths:neg.length?pos.length/neg.length:null},screen:{cagr15:s.cagr>=.15,maxDd40:s.maxDrawdown>-.40,correlation60:Number.isFinite(cr)&&cr<=.60,defensive30:neg.length>0&&pos.length/neg.length>=.30}};}

function runVcb(h:Record<string,PricePoint[]>,us:UniverseMonth[]){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date));const dates=q.map(x=>x.date).filter(d=>d>="2020-01-01");const rows=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,[...p].sort((a,b)=>a.date.localeCompare(b.date))]));const idx=Object.fromEntries(Object.entries(rows).map(([s,p])=>[s,new Map((p as PricePoint[]).map((x,i)=>[x.date,i]))]));const maps=Object.fromEntries(Object.entries(rows).map(([s,p])=>[s,new Map((p as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string,sh:number,e:number}>=[],pendingIn:{d:string,ss:string[]}|null=null,pendingOut:string|null=null,hold=0,peak=1,trades=0;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,p)=>z+p.sh*((maps[p.s] as Map<string,PricePoint>).get(d)?.[f]??(maps[p.s] as Map<string,PricePoint>).get(d)?.close??p.e),0);
for(let di=0;di<dates.length;di++){const d=dates[di],nd=dates[di+1]??null;if(pendingOut===d&&pos.length){cash=pos.reduce((z,p)=>{const x=(maps[p.s] as Map<string,PricePoint>).get(d);return z+p.sh*(x?.open??x?.close??p.e);},0)*(1-COST);pos=[];pendingOut=null;hold=0;peak=cash;trades++;}if(pendingIn?.d===d&&!pos.length){const os=pendingIn.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.every(x=>x&&x>0)){const per=cash/2;pos=pendingIn.ss.map((s,i)=>({s,sh:per*(1-COST)/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0;}pendingIn=null;}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pendingOut&&nd){hold++;const stop=pos.some(p=>((maps[p.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=p.e*.88);if(stop||dd<=-.15||hold>=20)pendingOut=nd;}if(!pos.length&&!pendingIn&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latestUniverse(us,d);if(!u)continue;const cand:Array<{s:string,b:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<100)continue;const close=r[i].close,sma=mean(r.slice(i-99,i+1).map(x=>x.close));if(close<=sma)continue;const prior20=Math.max(...r.slice(i-20,i).map(x=>x.close));if(close<=prior20)continue;const r10=r.slice(i-10,i+1).map((x,j,a)=>j?x.close/a[j-1].close-1:0).slice(1),r60=r.slice(i-60,i+1).map((x,j,a)=>j?x.close/a[j-1].close-1:0).slice(1);if(!(sd(r10)<.75*sd(r60)))continue;cand.push({s,b:close/prior20-1});}cand.sort((a,b)=>b.b-a.b||a.s.localeCompare(b.s));if(cand.length>=2)pendingIn={d:nd,ss:cand.slice(0,2).map(x=>x.s)};}}
return{curve,trades};}

function runCrisis(h:Record<string,PricePoint[]>){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),t=[...(h.TQQQ??[])].sort((a,b)=>a.date.localeCompare(b.date));const tm=new Map(t.map(x=>[x.date,x]));const dates=q.map(x=>x.date).filter(d=>d>="2020-01-01");let cash=1,shares=0,entry=0,pendingIn:string|null=null,pendingOut:string|null=null,hold=0,armed=false,locked=false,peak=1,trades=0;const curve:EquityPoint[]=[];for(let i=0;i<q.length;i++){const d=q[i].date;if(d<"2020-01-01")continue;const ni=i+1<q.length?q[i+1].date:null;if(pendingOut===d&&shares){const x=tm.get(d);if(x){cash=shares*(x.open??x.close)*(1-COST);shares=0;trades++;}pendingOut=null;hold=0;peak=cash;}if(pendingIn===d&&!shares){const x=tm.get(d);if(x?.open){entry=x.open;shares=cash*(1-COST)/x.open;cash=0;hold=0;peak=shares*x.open;locked=true;}pendingIn=null;}const px=tm.get(d)?.close??entry;const e=cash+shares*px;peak=Math.max(peak,e);curve.push({date:d,equity:e,drawdown:e/peak-1});if(i>=59){const hi=Math.max(...q.slice(i-59,i+1).map(x=>x.close));const dd=q[i].close/hi-1;if(dd<=-.12&&!locked)armed=true;if(q[i].close>=hi*.999)locked=false;if(armed&&!shares&&!pendingIn&&ni&&i>=9){const sma10=mean(q.slice(i-9,i+1).map(x=>x.close));const r5=i>=5?q[i].close/q[i-5].close-1:0;if(q[i].close>sma10&&r5>0){pendingIn=ni;armed=false;}}}if(shares&&!pendingOut&&ni){hold++;if(px<=entry*.85||hold>=15)pendingOut=ni;}}
return{curve,trades};}

async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8")) as MarketFile;const u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8")) as UniverseFile;const f=JSON.parse(await readFile(resolve("public/data/backtest-frozen.json"),"utf8")) as FrozenFile;const us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const fixed=f.backtest?.equityCurve??[];const b=runVcb(m.histories,us),c=runCrisis(m.histories);console.log(JSON.stringify({candidateB:summary("VCB",b.curve,fixed,b.trades),candidateC:summary("CRISIS_REBOUND_TQQQ",c.curve,fixed,c.trades),specs:{VCB:{qqqSma:200,stockSma:100,breakout:20,compression:"10d vol < 0.75 * 60d vol",hold:20,stop:.12,circuit:.15,topN:2},CRISIS_REBOUND_TQQQ:{arm:"QQQ 60d drawdown <= -12%",confirm:"QQQ > 10d SMA and 5d return > 0",hold:15,stop:.15,cooldown:"until QQQ retakes 60d high"}}},null,2));}
main().catch(e=>{console.error(e);process.exitCode=1;});
