import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY as P} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import {performanceStats} from '../src/lib/backtest';
import type {EquityPoint,PricePoint,StrategyConfig,UniverseMonth} from '../src/lib/types';
type V='BASE'|'GAP40_25'|'GAP60_25';
const C:StrategyConfig={...P,strategyId:'momentum-info-gap-top10',allocation:{...P.allocation,baseTop1Weight:.7,concentratedTop1Weight:.7,maxTop1Weight:.7}} as StrategyConfig;
const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0, sd=(a:number[])=>{const m=mean(a);return a.length>1?Math.sqrt(mean(a.map(x=>(x-m)**2))):0}, z=(x:number,m:number,s:number)=>s>1e-12?(x-m)/s:0;
function ranks(a:number[]){const q=a.map((v,i)=>({v,i})).sort((x,y)=>x.v-y.v),r=Array(a.length).fill(0);for(let i=0;i<q.length;){let j=i;while(j+1<q.length&&q[j+1].v===q[i].v)j++;for(let k=i;k<=j;k++)r[q[k].i]=(i+j)/2+1;i=j+1}return r}function corr(a:number[],b:number[]){if(a.length<4)return null;const x=ranks(a),y=ranks(b),mx=mean(x),my=mean(y);let n=0,dx=0,dy=0;for(let i=0;i<x.length;i++){const p=x[i]-mx,q=y[i]-my;n+=p*q;dx+=p*p;dy+=q*q}return dx&&dy?n/Math.sqrt(dx*dy):null}
function sorted(h:Record<string,PricePoint[]>){return Object.fromEntries(Object.entries(h).map(([s,p])=>[s,[...p].sort((a,b)=>a.date.localeCompare(b.date))]))}
function gapFactor(a:PricePoint[],d:string,n:number){let i=a.findIndex(x=>x.date===d);if(i<1)return null;const g:number[]=[];for(;i>=1&&g.length<n;i--){if(a[i].open>0&&a[i-1].close>0)g.push(Math.log(a[i].open/a[i-1].close))}if(g.length<20)return null;return Math.max(...g)+Math.min(...g)}
function fwd(a:PricePoint[],d:string,n:number){const i=a.findIndex(x=>x.date===d);if(i<0||i+1>=a.length)return null;const s=a[i+1].open,e=a[Math.min(i+n,a.length-1)].open;return s>0&&e>0?e/s-1:null}
function base(u:UniverseMonth,h:Record<string,PricePoint[]>,q:PricePoint[],n:string){const s:any=buildMonthlySignal({universe:u,histories:h,qqq:q,nextSessionDate:n,config:C});if(s.selectedSymbols.length===2)s.targetWeights=[.7,.3];return s}
function rerank(u:UniverseMonth,h:Record<string,PricePoint[]>,hs:Record<string,PricePoint[]>,q:PricePoint[],n:string,v:V){const b:any=base(u,h,q,n);if(v==='BASE'||!b.marketRiskOn)return b;const w=v==='GAP40_25'?40:60,t=b.candidates.filter((x:any)=>x.eligible&&x.score!=null).slice(0,10),r=t.map((x:any)=>({x,f:hs[x.symbol]?gapFactor(hs[x.symbol],u.asOf,w):null})),fv=r.map(x=>x.f).filter((x):x is number=>x!=null);if(fv.length<4)return b;const sm=mean(t.map((x:any)=>x.score)),ss=sd(t.map((x:any)=>x.score)),fm=mean(fv),fs=sd(fv),rr=r.map(x=>({x:x.x,c:x.f==null?-Infinity:z(x.x.score,sm,ss)+.25*z(x.f,fm,fs)})).sort((a,b)=>b.c-a.c||a.x.symbol.localeCompare(b.x.symbol)),sel=rr.filter(x=>Number.isFinite(x.c)).slice(0,2);return sel.length<2?b:{...b,selectedSymbols:sel.map(x=>x.x.symbol),targetWeights:[.7,.3],allocationMode:'70/30'} }
function sim(h:Record<string,PricePoint[]>,hs:Record<string,PricePoint[]>,u:UniverseMonth[],v:V){const q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),ix=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(C);const c:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<C.backtestStart)continue;const n=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?rerank(uu,h,hs,q,n,v):null,sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},C);c.push({date:d,equity:st.currentEquity,drawdown:st.drawdown})}return c}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const p=[...c].reverse().find(v=>v.date<s),z0=p?[p,...x]:x,b=z0[0].equity;return z0.map(v=>({...v,equity:v.equity/b}))}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].filter(x=>x.asOf>=C.backtestStart).sort((a,b)=>a.asOf.localeCompare(b.asOf)),hs=sorted(m.histories),q=m.histories.QQQ,d:any[]=[];for(const x of u){const t:any=base(x,m.histories,q,nextUsTradingSession(x.asOf));const top=t.candidates.filter((c:any)=>c.eligible&&c.score!=null).slice(0,10);for(const n of [40,60]){const r=top.map((c:any)=>({f:hs[c.symbol]?gapFactor(hs[c.symbol],x.asOf,n):null,r1:hs[c.symbol]?fwd(hs[c.symbol],x.asOf,21):null,r3:hs[c.symbol]?fwd(hs[c.symbol],x.asOf,63):null})).filter((v:any)=>v.f!=null&&v.r1!=null&&v.r3!=null);d.push({date:x.asOf,n,ic1:corr(r.map((v:any)=>v.f),r.map((v:any)=>v.r1)),ic3:corr(r.map((v:any)=>v.f),r.map((v:any)=>v.r3))})}}function dg(a:string,b:string,n:number){const x=d.filter(v=>v.n===n&&v.date>=a&&v.date<=b&&v.ic1!=null);return{months:x.length,meanIC1:mean(x.map(v=>v.ic1)),meanIC3:mean(x.map(v=>v.ic3)),positiveIC1Share:x.filter(v=>v.ic1>0).length/x.length,positiveIC3Share:x.filter(v=>v.ic3>0).length/x.length}}
const variants:V[]=['BASE','GAP40_25','GAP60_25'],cur=Object.fromEntries(variants.map(v=>[v,sim(m.histories,hs,u,v)]))as Record<V,EquityPoint[]>;const years=[2020,2021,2022,2023,2024,2025,2026],annual=years.map(y=>({year:y,...Object.fromEntries(variants.map(v=>[v,performanceStats(sl(cur[v],`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))]))})),anchored=[2022,2023,2024,2025,2026].map(y=>{const tr=`${y-1}-12-31`,rank=variants.map(v=>({v,calmar:performanceStats(sl(cur[v],'2020-01-01',tr)).calmar??-99})).sort((a,b)=>b.calmar-a.calmar),pick=rank[0].v,e=y===2026?'2026-08-25':`${y}-12-31`;return{year:y,pick,rank,oos:performanceStats(sl(cur[pick],`${y}-01-01`,e)),base:performanceStats(sl(cur.BASE,`${y}-01-01`,e))}});const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,freeDataOnly:true,noLeverage:true,pit:true,nextOpen:true,predeclared:'Top10 rerank; max positive overnight gap + min negative overnight gap over 40/60 sessions; lambda=.25; W70'},diagnostic:{early40:dg('2020-01-01','2023-12-31',40),late40:dg('2024-01-01','2026-08-25',40),early60:dg('2020-01-01','2023-12-31',60),late60:dg('2024-01-01','2026-08-25',60)},full:variants.map(v=>({variant:v,...performanceStats(cur[v])})),annual,anchored};const dir=path.join(process.cwd(),'data/research/info-gap-top10');await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});
