import { readFile, mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import type { MonthlySignal, PricePoint, StrategyConfig, UniverseMonth } from "../src/lib/types";

type Market={histories:Record<string,PricePoint[]>}; type UF={history:UniverseMonth[]};
type Variant="production"|"no_gate"|"confirm_2m"|"recovery_5d";
const V:Variant[]=["production","no_gate","confirm_2m","recovery_5d"];
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
const sd=(x:number[])=>{const m=avg(x);return x.length>1?Math.sqrt(x.reduce((a,v)=>a+(v-m)**2,0)/(x.length-1)):0};
const q=(a:number[],p:number)=>{const x=[...a].sort((x,y)=>x-y),i=(x.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return x[l]+(x[h]-x[l])*(i-l)};
function latestU(us:UniverseMonth[],d:string){let a=us[0];for(const u of us){if(u.asOf<=d)a=u;else break}return a}
const score=(r3:number,r6:number)=>.2*r3+.8*r6;
function makeSignal(date:string,next:string|null,u:UniverseMonth,monthly:Map<string,number[]>):MonthlySignal{const qq=monthly.get("QQQ")??[],ret=(x:number[],n:number)=>x.length>n?x.at(-1)!/x.at(-(n+1))!-1:null,q1=ret(qq,1),q3=ret(qq,3),q6=ret(qq,6),qs=q1==null||q3==null||q6==null?null:score(q3,q6),ma=qq.slice(-10),risk=ma.length===10&&qq.at(-1)!>avg(ma),c:any[]=[];for(const m of u.symbols){const x=monthly.get(m.symbol)??[],r1=ret(x,1),r3=ret(x,3),r6=ret(x,6);if(r1==null||r3==null||r6==null||qs==null){c.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:null,qqqScore:qs,scoreSpread:null,eligible:false,exclusionReason:"INSUFFICIENT_PRICE_HISTORY",rank:null});continue}const s=score(r3,r6),reason=r1>=.8?"ONE_MONTH_SURGE":s<=qs?"NOT_ABOVE_QQQ":null;c.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:s,qqqScore:qs,scoreSpread:s-qs,eligible:!reason,exclusionReason:reason,rank:null})}const e=c.filter(x=>x.eligible&&x.score!=null).sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol));e.forEach((x,i)=>x.rank=i+1);const chosen=e.slice(0,2),valid=chosen.length===2,d=sd(e.map(x=>x.score)),zg=valid&&d>0?(chosen[0].score-chosen[1].score)/d:valid?0:null,conc=zg!=null&&zg>=.25,w=conc?.7:.5;return {strategyId:PRODUCTION_STRATEGY.strategyId,signalMonth:date.slice(0,7),signalDate:date,executionDate:next,marketRiskOn:risk,qqqClose:qq.at(-1)??null,qqqMonthlyMa:ma.length===10?avg(ma):null,qqqScore:qs,universe:u.symbols.map(x=>x.symbol),candidates:c,selectedSymbols:valid?chosen.map(x=>x.symbol):[],targetWeights:valid?[w,1-w]:[],zGap:zg,allocationMode:!valid?"CASH":conc?"70/30":"50/50"} as MonthlySignal}
function stats(curve:{date:string,equity:number,drawdown:number}[]){const first=curve[0],last=curve.at(-1)!;const years=(Date.parse(last.date)-Date.parse(first.date))/(365.25*86400000);return{cagr:(last.equity/first.equity)**(1/years)-1,maxDrawdown:Math.min(0,...curve.map(x=>x.drawdown)),finalWealth:last.equity/first.equity}}
function confirmed2(raw:boolean, mem:{state:boolean|null;opposite:number}){if(mem.state==null){mem.state=raw;mem.opposite=0;return raw}if(raw===mem.state){mem.opposite=0;return mem.state}mem.opposite++;if(mem.opposite>=2){mem.state=raw;mem.opposite=0}return mem.state}

async function fullStrategy(hist:Record<string,PricePoint[]>,us:UniverseMonth[]){const allDates=(hist.QQQ??[]).map(p=>p.date),symbols=[...new Set(["QQQ",...us.flatMap(u=>u.symbols.map(x=>x.symbol))])],maps=new Map(symbols.map(s=>[s,new Map((hist[s]??[]).map(p=>[p.date,p]))])),monthly=new Map<string,number[]>(symbols.map(s=>[s,[]])),signals:Record<string,MonthlySignal>={},m2={state:null as boolean|null,opposite:0},risk2:Record<string,boolean>={};for(let i=0;i<allDates.length;i++){const d=allDates[i],next=allDates[i+1]??null,me=!next||next.slice(0,7)!==d.slice(0,7);if(me){for(const s of symbols){const p=maps.get(s)?.get(d);if(p)monthly.get(s)!.push(p.close)}if(d>=us[0].asOf){const sig=makeSignal(d,next,latestU(us,d),monthly);signals[d]=sig;risk2[d]=confirmed2(sig.marketRiskOn,m2)}}}
 const out:any[]=[];for(const v of V){const cfg=(v==="recovery_5d"?{...PRODUCTION_STRATEGY,recovery:{...PRODUCTION_STRATEGY.recovery,confirmationDays:5}}:PRODUCTION_STRATEGY) as StrategyConfig;let st=initialEngineState(cfg),qh:PricePoint[]=[],curve:any[]=[],cash=0,n=0;for(let i=0;i<allDates.length;i++){const d=allDates[i],pqqq=maps.get("QQQ")?.get(d);if(pqqq)qh.push(pqqq);if(d<PRODUCTION_STRATEGY.backtestStart)continue;const next=allDates[i+1]??null,prices:Record<string,PricePoint|undefined>={};for(const s of symbols){const p=maps.get(s)?.get(d);if(p)prices[s]=p}let sig=signals[d]??null;if(sig&&v==="no_gate")sig={...sig,marketRiskOn:true};if(sig&&v==="confirm_2m")sig={...sig,marketRiskOn:risk2[d]};st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:qh,monthlySignal:sig,nextSessionDate:next},cfg);curve.push({date:d,equity:st.currentEquity,drawdown:st.drawdown});n++;if(st.currentPositions.length===0)cash++}out.push({variant:v,...stats(curve),cashRate:cash/n})}return out}

function dailyRecoveryOk(qh:PricePoint[],confirmDays:number){if(qh.length<101)return false;const latest=qh.at(-1)!.close,prior=qh.at(-21)!.close,sma=avg(qh.slice(-100).map(p=>p.close));return latest>sma&&latest/prior-1>0}
function overlay(points:PricePoint[],variant:Variant,start?:string,end?:string){const pp=points.filter(p=>(!start||p.date>=start)&&(!end||p.date<=end));if(pp.length<2)return null;let cash=1,shares=0,peak=1,dd=0,market=true,lock=false,recovery=0,pending:"BUY"|"SELL"|null=null,monthCloses:number[]=[],m2={state:null as boolean|null,opposite:0},qh:PricePoint[]=[],cashDays=0;const curve:number[]=[];for(let i=0;i<pp.length;i++){const p=pp[i];if(pending==="SELL"&&shares){cash=shares*p.open*(1-PRODUCTION_STRATEGY.execution.transactionCost);shares=0}if(pending==="BUY"&&!shares){shares=cash*(1-PRODUCTION_STRATEGY.execution.transactionCost)/p.open;cash=0;lock=false;recovery=0}pending=null;qh.push(p);const eq=cash+shares*p.close;peak=Math.max(peak,eq);dd=Math.min(dd,eq/peak-1);curve.push(eq);if(!shares)cashDays++;const next=pp[i+1],me=!next||next.date.slice(0,7)!==p.date.slice(0,7);if(me){monthCloses.push(p.close);if(monthCloses.length>=10){const raw=p.close>avg(monthCloses.slice(-10));let r=raw;if(variant==="no_gate")r=true;if(variant==="confirm_2m")r=confirmed2(raw,m2);market=r;if(!r){if(shares)pending="SELL";lock=true;recovery=0}else if(!lock&&!shares)pending="BUY"}}if(lock&&!pending&&market){const ok=dailyRecoveryOk(qh,variant==="recovery_5d"?5:10);recovery=ok?recovery+1:0;const need=variant==="recovery_5d"?5:10;if(recovery>=need&&!shares)pending="BUY"}}const years=(Date.parse(pp.at(-1)!.date)-Date.parse(pp[0].date))/(365.25*86400000);return{cagr:(curve.at(-1)!/curve[0])**(1/years)-1,maxDrawdown:dd,finalWealth:curve.at(-1)!/curve[0],cashRate:cashDays/pp.length}}

function rng(seed:number){let x=seed>>>0;return()=>{x=(1664525*x+1013904223)>>>0;return x/4294967296}}
function syntheticQqq(source:PricePoint[],sessions=1512,block=20,seed=1){const r=rng(seed),src=source.filter((_,i)=>i>0),f=src.map((p,i)=>({gap:p.open/source[i].close,intra:p.close/p.open}));const template=source.slice(-sessions).map(p=>p.date);let close=100;const out:PricePoint[]=[];let k=0;while(k<sessions){const st=Math.floor(r()*Math.max(1,f.length-block));for(let j=0;j<block&&k<sessions;j++,k++){const z=f[st+j],open=close*z.gap;close=open*z.intra;out.push({date:template[k],open,high:Math.max(open,close),low:Math.min(open,close),close,volume:0})}}return out}
async function mcGate(qqq:PricePoint[],paths=1000){const rows:Record<Variant,any[]>={production:[],no_gate:[],confirm_2m:[],recovery_5d:[]};for(let i=0;i<paths;i++){const syn=syntheticQqq(qqq,1512,20,20260825+i);const test=syn.slice(252);for(const v of V){const x=overlay(test,v);if(x)rows[v].push(x)}}const out:any={};for(const v of V){const a=rows[v];out[v]={cagr:{p05:q(a.map(x=>x.cagr),.05),median:q(a.map(x=>x.cagr),.5),p95:q(a.map(x=>x.cagr),.95)},maxDrawdown:{adverseP05:q(a.map(x=>x.maxDrawdown),.05),median:q(a.map(x=>x.maxDrawdown),.5)},cashRateMedian:q(a.map(x=>x.cashRate),.5),probLoss:a.filter(x=>x.finalWealth<1).length/a.length,probDd40:a.filter(x=>x.maxDrawdown<=-.4).length/a.length}}return out}

async function main(){const market=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8")) as Market,uf=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8")) as UF,us=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),qqq=market.histories.QQQ??[];const actual=await fullStrategy(market.histories,us);const crises=[{name:"dotcom",start:"2000-03-10",end:"2002-10-09"},{name:"gfc",start:"2007-10-09",end:"2009-03-09"},{name:"covid",start:"2020-02-19",end:"2020-03-23"},{name:"2022",start:"2021-11-19",end:"2022-10-13"}].map(c=>({ ...c,results:Object.fromEntries(V.map(v=>[v,overlay(qqq,v,c.start,c.end)]))}));const mc=await mcGate(qqq,1000);const out={generatedAt:new Date().toISOString(),strategyId:PRODUCTION_STRATEGY.strategyId,method:{actual:"Full Production state machine on chronological PIT Dynamic Universe; only gate/recovery structure changed",crises:"QQQ-only gate overlay because pre-2020 PIT N-PORT universe is unavailable; next-open execution and 10bp/side cost",mc:"QQQ-only structural gate diagnostic; 1000 common 5y paths, 20-session moving blocks, 252-session warmup, seed 20260825+i"},qqqCoverage:{start:qqq[0]?.date,end:qqq.at(-1)?.date,points:qqq.length},actual,crises,mc};await mkdir(resolve("data/research/market-gate"),{recursive:true});await writeFile(resolve("data/research/market-gate/structure.json"),JSON.stringify(out,null,2));console.log("RESULT_JSON="+JSON.stringify(out))}
main().catch(e=>{console.error(e);process.exit(1)});
