import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import type {EquityPoint,PricePoint,UniverseMonth,StrategyConfig} from "../src/lib/types";
type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};
const END="2026-08-25";const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;const median=(x:number[])=>{const a=[...x].sort((a,b)=>a-b),n=a.length;return n%2?a[(n-1)/2]:(a[n/2-1]+a[n/2])/2};
function fromReturns(dates:string[],rs:number[]){let e=1,p=1;const out:EquityPoint[]=[{date:dates[0],equity:1,drawdown:0}];for(let i=1;i<dates.length;i++){e*=1+(rs[i]??0);p=Math.max(p,e);out.push({date:dates[i],equity:e,drawdown:e/p-1})}return out}
function shiftCurve(c:EquityPoint[],n:number){const rs=c.map((p,i)=>i?p.equity/c[i-1].equity-1:0);return fromReturns(c.map(x=>x.date),rs.map((_,i)=>i>=n?rs[i-n]:0))}
function governor(base:EquityPoint[],lag=0){const rs=base.map((p,i)=>i?p.equity/base[i-1].equity-1:0);let e=1,p=1;const out:EquityPoint[]=[{date:base[0].date,equity:1,drawdown:0}];for(let i=1;i<base.length;i++){let x=.5;if(i>=20+lag){const end=i-lag,start=end-20,w=rs.slice(start,end),mu=mean(w),sd=Math.sqrt(w.reduce((z,r)=>z+(r-mu)**2,0)/(w.length-1))*Math.sqrt(252);x=Math.max(.25,Math.min(1,.18/(sd||1)))}e*=1+x*rs[i];p=Math.max(p,e);out.push({date:base[i].date,equity:e,drawdown:e/p-1})}return out}
function startAt(c:EquityPoint[],s:string){const a=c.filter(x=>x.date>=s);const b=a[0].equity;let p=1;return a.map(x=>{const e=x.equity/b;p=Math.max(p,e);return{date:x.date,equity:e,drawdown:e/p-1}})}
function rolling36(c:EquityPoint[]){const out:number[]=[];for(let i=0;i<c.length;i++){const t=new Date(c[i].date+"T00:00:00Z");t.setUTCMonth(t.getUTCMonth()+36);let j=i+1;while(j<c.length&&new Date(c[j].date+"T00:00:00Z")<t)j++;if(j>=c.length)break;const y=(new Date(c[j].date).getTime()-new Date(c[i].date).getTime())/(365.25*86400000);out.push((c[j].equity/c[i].equity)**(1/y)-1)}return out}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const base=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(p=>p.date<=END);const cfg30={...PRODUCTION_STRATEGY,execution:{...PRODUCTION_STRATEGY.execution,transactionCost:.003}} as StrategyConfig;const c30=runStrategySimulation({histories:m.histories,universeHistory:us,config:cfg30}).backtest.equityCurve.filter(p=>p.date<=END);
const main=governor(base),cost=governor(c30),d1=governor(shiftCurve(base,1)),d2=governor(shiftCurve(base,2)),start= startAt(main,"2021-01-01"),lag=governor(base,5);const vals=[performanceStats(main).cagr,performanceStats(cost).cagr,performanceStats(d1).cagr,performanceStats(d2).cagr,performanceStats(start).cagr,performanceStats(lag).cagr],r=rolling36(main),sm=median(vals),rm=median(r),proxy=Math.min(sm,rm);console.log(JSON.stringify({spec:{lookback:20,targetVol:.18,floor:.25,cap:1,warmupExposure:.5,warmupSessions:20},base:performanceStats(main),stresses:{cost30:performanceStats(cost),delay1Proxy:performanceStats(d1),delay2Proxy:performanceStats(d2),start2021:performanceStats(start),volSignalLag5:performanceStats(lag)},stressMedianCAGR:sm,rolling36MedianCAGR:rm,rolling36Worst:Math.min(...r),forwardPlanningCAGRProxy:proxy,pass:proxy>=.40&&performanceStats(main).maxDrawdown>=-.17&&performanceStats(d1).maxDrawdown>=-.20&&performanceStats(d2).maxDrawdown>=-.20},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});