import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { performanceStats, runStrategySimulation } from "../src/lib/backtest";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { fetchYahooHistory } from "../src/lib/yahoo";
import type { EquityPoint, PricePoint, UniverseMonth } from "../src/lib/types";

type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};
const END="2026-08-25",START="2020-01-01";
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;
const stdev=(x:number[])=>{const m=mean(x);return Math.sqrt(x.reduce((s,v)=>s+(v-m)*(v-m),0)/Math.max(1,x.length-1))};
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function runG(h:Record<string,PricePoint[]>,us:UniverseMonth[]){const qqq=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=qqq.map(x=>x.date).filter(d=>d>=START&&d<=END),rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))])),idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))])),maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??(maps[x.s] as Map<string,PricePoint>).get(d)?.close??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di],nd=di+1<dates.length?dates[di+1]:null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>{const r=(maps[x.s] as Map<string,PricePoint>).get(d);return z+x.sh*(r?.open??r?.close??x.e)},0)*.999;pos=[];pout=null;hold=0;peak=cash}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===5&&os.every(x=>x&&x>0)){const per=cash/5;pos=pin.ss.map((s,i)=>({s,sh:per*.999/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*.88);if(stop||dd<=-.15||hold>=20)pout=nd}if(!pos.length&&!pin&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<99||i<20)continue;const close=r[i].close;if(close<=mean(r.slice(i-99,i+1).map(x=>x.close)))continue;const hi=Math.max(...r.slice(i-20,i).map(x=>x.close));if(close>hi)ca.push({s,v:close/hi-1})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=5)pin={d:nd,ss:ca.slice(0,5).map(x=>x.s)}}}return curve}
type Vec=[number,number,number,number];
function runU(under:PricePoint[][],inst:PricePoint[][]){const um=under.map(a=>new Map(a.map((x,i)=>[x.date,i]))),ip=inst.map(a=>new Map(a.map(x=>[x.date,x])));const clock=under[0].map(x=>x.date).filter(d=>d>=START&&d<=END&&under.every((_a,k)=>um[k].has(d))&&inst.every((_a,k)=>ip[k].has(d)));const pending=new Map<string,Vec>();let cash=1,shares=[0,0,0,0],peak=1;const curve:EquityPoint[]=[];for(let di=0;di<clock.length;di++){const d=clock[di],exec=pending.get(d);if(exec){const opens=ip.map(m=>m.get(d)!.open),current=shares.map((sh,k)=>sh*opens[k]),eq=cash+current.reduce((z,v)=>z+v,0);let desired=exec.map(w=>eq*w),cost=0,net=eq;for(let it=0;it<3;it++){cost=desired.reduce((z,v,k)=>z+Math.abs(v-current[k])*.001,0);net=Math.max(0,eq-cost);desired=exec.map(w=>net*w)}shares=desired.map((v,k)=>v/opens[k]);cash=Math.max(0,net-desired.reduce((z,v)=>z+v,0))}const e=cash+shares.reduce((z,sh,k)=>z+sh*ip[k].get(d)!.close,0);peak=Math.max(peak,e);curve.push({date:d,equity:e,drawdown:e/peak-1});const vec:Vec=[0,0,0,0];for(let k=0;k<4;k++){const ix=um[k].get(d)!;if(ix>=199)vec[k]=under[k][ix].close>mean(under[k].slice(ix-199,ix+1).map(x=>x.close))?.25:0}const nd=clock[di+1];if(nd)pending.set(nd,vec)}return curve}
function returns(c:EquityPoint[]){const o=new Map<string,number>();for(let i=1;i<c.length;i++)o.set(c[i].date,c[i].equity/c[i-1].equity-1);return o}
function combine(curves:EquityPoint[],weights:number[]):EquityPoint[]{throw new Error("unused")}
function portfolio(cs:EquityPoint[][],ws:number[]){const rms=cs.map(returns),dates=cs[0].slice(1).map(p=>p.date).filter(d=>rms.every(m=>m.has(d)));let e=1,peak=1;const out:EquityPoint[]=[{date:cs[0][0].date,equity:1,drawdown:0}];for(const d of dates){let r=0;for(let i=0;i<rms.length;i++)r+=ws[i]*(rms[i].get(d)??0);e*=1+r;peak=Math.max(peak,e);out.push({date:d,equity:e,drawdown:e/peak-1})}return out}
function scale(c:EquityPoint[],k:number){return portfolio([c],[k])}
function volTarget(c:EquityPoint[],target:number){const rm=returns(c),dates=c.slice(1).map(p=>p.date);let e=1,peak=1;const hist:number[]=[];const out:EquityPoint[]=[{date:c[0].date,equity:1,drawdown:0}];for(const d of dates){const r=rm.get(d)??0;let exposure=1;if(hist.length>=60){const vol=stdev(hist.slice(-60))*Math.sqrt(252);exposure=vol>0?Math.min(1,target/vol):1}e*=1+exposure*r;peak=Math.max(peak,e);out.push({date:d,equity:e,drawdown:e/peak-1});hist.push(r)}return out}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const [iwm,xlf,xle,tna,fas,erx]=await Promise.all(["IWM","XLF","XLE","TNA","FAS","ERX"].map(fetchYahooHistory));const fixed=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(p=>p.date<=END),g=runG(m.histories,us),uC=runU([m.histories.QQQ??[],iwm,xlf,xle],[m.histories.TQQQ??[],tna,fas,erx]);const gu=portfolio([g,uC],[.5,.5]),all=portfolio([fixed,g,uC],[1/3,1/3,1/3]);const tests:Record<string,EquityPoint[]>={fixed60:fixed,g,u:uC,gu50_50:gu,allEqual:all};for(const k of [.4,.5,.6])tests[`fixed_scaled_${k}`]=scale(fixed,k);for(const k of [.5,.6,.7])tests[`gu_scaled_${k}`]=scale(gu,k);for(const k of [.5,.6,.7])tests[`all_scaled_${k}`]=scale(all,k);for(const v of [.12,.15,.18]){tests[`fixed_vol_${v}`]=volTarget(fixed,v);tests[`all_vol_${v}`]=volTarget(all,v)}const out=Object.fromEntries(Object.entries(tests).map(([k,c])=>[k,performanceStats(c)]));console.log(JSON.stringify({period:{start:START,end:END},objective:{maxDrawdownApprox:-.15},results:out},null,2))}main().catch(e=>{console.error(e);process.exitCode=1});