import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import {fetchYahooHistory} from "../src/lib/yahoo";
import type {EquityPoint,PricePoint,UniverseMonth,StrategyConfig} from "../src/lib/types";

type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};
const START="2020-01-01",END="2026-08-25";
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;
const median=(x:number[])=>{const a=[...x].sort((a,b)=>a-b),n=a.length;return n%2?a[(n-1)/2]:(a[n/2-1]+a[n/2])/2};
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function rets(c:EquityPoint[]){const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m}
function fromReturns(dates:string[],rs:number[]){let e=1,p=1;const out:EquityPoint[]=[{date:dates[0],equity:1,drawdown:0}];for(let i=1;i<dates.length;i++){e*=1+(rs[i]??0);p=Math.max(p,e);out.push({date:dates[i],equity:e,drawdown:e/p-1})}return out}
function shiftCurve(c:EquityPoint[],n:number){const rs=c.map((p,i)=>i? p.equity/c[i-1].equity-1:0);const sh=rs.map((_,i)=>i>=n?rs[i-n]:0);return fromReturns(c.map(x=>x.date),sh)}
function runG(h:Record<string,PricePoint[]>,us:UniverseMonth[],cost=.001,delay=0){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date).filter(d=>d>=START&&d<=END),rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))])),idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))])),maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di];if(pout===d&&pos.length){cash=pos.reduce((z,x)=>{const r=(maps[x.s] as Map<string,PricePoint>).get(d);return z+x.sh*(r?.open??r?.close??x.e)},0)*(1-cost);pos=[];pout=null;hold=0;peak=cash}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===5&&os.every(x=>x&&x>0)){const per=cash/5;pos=pin.ss.map((s,i)=>({s,sh:per*(1-cost)/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});const nd=dates[di+1+delay]??null;if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*.88);if(stop||dd<=-.15||hold>=20)pout=nd}if(!pos.length&&!pin&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<99||i<20)continue;const close=r[i].close;if(close<=mean(r.slice(i-99,i+1).map(x=>x.close)))continue;const hi=Math.max(...r.slice(i-20,i).map(x=>x.close));if(close>hi)ca.push({s,v:close/hi-1})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=5)pin={d:nd,ss:ca.slice(0,5).map(x=>x.s)}}}return curve}
function buyHold(a:PricePoint[]){const rows=[...a].sort((x,y)=>x.date.localeCompare(y.date)).filter(x=>x.date>=START&&x.date<=END);let e=1,p=1;const out:EquityPoint[]=[{date:rows[0].date,equity:1,drawdown:0}];for(let i=1;i<rows.length;i++){e*=rows[i].close/rows[i-1].close;p=Math.max(p,e);out.push({date:rows[i].date,equity:e,drawdown:e/p-1})}return out}
function runTqqq(qqq:PricePoint[],tqqq:PricePoint[],cost=.001,delay=0){const q=[...qqq].sort((a,b)=>a.date.localeCompare(b.date)),t=[...tqqq].sort((a,b)=>a.date.localeCompare(b.date));const tm=new Map(t.map(x=>[x.date,x]));const dates=q.map(x=>x.date).filter(d=>d>=START&&d<=END&&tm.has(d));const qi=new Map(q.map((x,i)=>[x.date,i]));let cash=1,shares=0,pending:{date:string;on:boolean}|null=null,peak=1;const out:EquityPoint[]=[];for(let di=0;di<dates.length;di++){const d=dates[di],tr=tm.get(d)!;if(pending?.date===d){if(pending.on&&!shares){shares=cash*(1-cost)/tr.open;cash=0}else if(!pending.on&&shares){cash=shares*tr.open*(1-cost);shares=0}pending=null}const e=cash+shares*tr.close;peak=Math.max(peak,e);out.push({date:d,equity:e,drawdown:e/peak-1});const i=qi.get(d)!;if(i<199)continue;const on=q[i].close>mean(q.slice(i-199,i+1).map(x=>x.close));const invested=shares>0;if(on!==invested&&!pending){const td=dates[di+1+delay];if(td)pending={date:td,on}}}return out}
function portfolio(parts:{curve:EquityPoint[],w:number}[]){const rm=parts.map(p=>rets(p.curve)),dates=parts[0].curve.map(x=>x.date).filter(d=>rm.every(m=>m.has(d)));let e=1,p=1;const out:EquityPoint[]=[{date:dates[0],equity:1,drawdown:0}];for(let i=1;i<dates.length;i++){const d=dates[i];let r=0;for(let j=0;j<parts.length;j++)r+=parts[j].w*(rm[j].get(d)??0);e*=1+r;p=Math.max(p,e);out.push({date:d,equity:e,drawdown:e/p-1})}return out}
function gov(base:EquityPoint[]){const rs=base.slice(1).map((p,i)=>p.equity/base[i].equity-1);let e=1,p=1;const out:EquityPoint[]=[{date:base[0].date,equity:1,drawdown:0}];for(let i=0;i<rs.length;i++){let x=.70;if(i>=60){const w=rs.slice(i-60,i),mu=mean(w),sd=Math.sqrt(w.reduce((z,r)=>z+(r-mu)**2,0)/(w.length-1))*Math.sqrt(252);x=Math.max(.35,Math.min(1,.18/(sd||1)))}e*=1+x*rs[i];p=Math.max(p,e);out.push({date:base[i+1].date,equity:e,drawdown:e/p-1})}return out}
function rolling36(c:EquityPoint[]){const out:number[]=[];for(let i=0;i<c.length;i++){const target=new Date(c[i].date+"T00:00:00Z");target.setUTCMonth(target.getUTCMonth()+36);let j=i+1;while(j<c.length&&new Date(c[j].date+"T00:00:00Z")<target)j++;if(j>=c.length)break;const yrs=(new Date(c[j].date).getTime()-new Date(c[i].date).getTime())/(365.25*86400000);out.push((c[j].equity/c[i].equity)**(1/yrs)-1)}return out}
function startAt(c:EquityPoint[],start:string){const a=c.filter(x=>x.date>=start);if(!a.length)return c;const b=a[0].equity;let p=1;return a.map(x=>{const e=x.equity/b;p=Math.max(p,e);return{date:x.date,equity:e,drawdown:e/p-1}})}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const tqqq=await fetchYahooHistory("TQQQ"),dbmf=buyHold(await fetchYahooHistory("DBMF"));
 const fixedBase=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(p=>p.date<=END);
 const cfg30={...PRODUCTION_STRATEGY,execution:{...PRODUCTION_STRATEGY.execution,transactionCost:.003}} as StrategyConfig;
 const fixed30=runStrategySimulation({histories:m.histories,universeHistory:us,config:cfg30}).backtest.equityCurve.filter(p=>p.date<=END);
 const qqq=m.histories.QQQ;
 const specs={T1:{f:.40,g:.20,d:.20,t:.20},T2:{f:.35,g:.20,d:.20,t:.25},T3:{f:.30,g:.20,d:.20,t:.30}} as const;
 const evalOne=(sp:{f:number,g:number,d:number,t:number})=>{
  const make=(f:EquityPoint[],g:EquityPoint[],tq:EquityPoint[],tw=sp.t)=>gov(portfolio([{curve:f,w:sp.f},{curve:g,w:sp.g},{curve:dbmf,w:sp.d},{curve:tq,w:tw}]));
  const base=make(fixedBase,runG(m.histories,us,.001,0),runTqqq(qqq,tqqq,.001,0));
  const cost=make(fixed30,runG(m.histories,us,.003,0),runTqqq(qqq,tqqq,.003,0));
  const delay1=make(shiftCurve(fixedBase,1),runG(m.histories,us,.001,1),runTqqq(qqq,tqqq,.001,1));
  const delay2=make(shiftCurve(fixedBase,2),runG(m.histories,us,.001,2),runTqqq(qqq,tqqq,.001,2));
  const noT=gov(portfolio([{curve:fixedBase,w:sp.f},{curve:runG(m.histories,us,.001,0),w:sp.g},{curve:dbmf,w:sp.d}]));
  const vals=[performanceStats(base).cagr,performanceStats(cost).cagr,performanceStats(delay1).cagr,performanceStats(delay2).cagr,performanceStats(startAt(base,"2021-01-01")).cagr,performanceStats(noT).cagr];
  const r36=rolling36(base);const stressMedianCAGR=median(vals),rolling36MedianCAGR=median(r36),proxy=Math.min(stressMedianCAGR,rolling36MedianCAGR);
  return{weights:sp,base:performanceStats(base),stresses:{cost30:performanceStats(cost),delay1:performanceStats(delay1),delay2:performanceStats(delay2),start2021:performanceStats(startAt(base,"2021-01-01")),removeTqqq:performanceStats(noT)},stressMedianCAGR,rolling36MedianCAGR,rolling36Worst:Math.min(...r36),forwardPlanningCAGRProxy:proxy,pass:proxy>=.40&&performanceStats(base).maxDrawdown>=-.17&&performanceStats(delay1).maxDrawdown>=-.20&&performanceStats(delay2).maxDrawdown>=-.20&&performanceStats(noT).cagr>=performanceStats(base).cagr*.5};
 };
 console.log(JSON.stringify({definition:"min(stress median CAGR, rolling36 median CAGR)",results:Object.fromEntries(Object.entries(specs).map(([k,v])=>[k,evalOne(v)]))},null,2));
}
main().catch(e=>{console.error(e);process.exitCode=1});