import {readFile} from "node:fs/promises";
import {resolve} from "node:path";
import {performanceStats,runStrategySimulation} from "../src/lib/backtest";
import {PRODUCTION_STRATEGY} from "../src/lib/config";
import {fetchYahooHistory} from "../src/lib/yahoo";
import type {EquityPoint,PricePoint,UniverseMonth} from "../src/lib/types";

type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};
const START="2020-01-01",END="2026-08-25";const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;
function latest(us:UniverseMonth[],d:string){let x:UniverseMonth|null=null;for(const u of us){if(u.asOf<=d)x=u;else break}return x}
function runG(h:Record<string,PricePoint[]>,us:UniverseMonth[]){const q=[...(h.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date).filter(d=>d>=START&&d<=END),rows=Object.fromEntries(Object.entries(h).map(([s,a])=>[s,[...a].sort((x,y)=>x.date.localeCompare(y.date))])),idx=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map((x,i)=>[x.date,i]))])),maps=Object.fromEntries(Object.entries(rows).map(([s,a])=>[s,new Map((a as PricePoint[]).map(x=>[x.date,x]))]));let cash=1,pos:Array<{s:string;sh:number;e:number}>=[],pin:{d:string;ss:string[]}|null=null,pout:string|null=null,hold=0,peak=1;const curve:EquityPoint[]=[];const eq=(d:string,f:"open"|"close")=>cash+pos.reduce((z,x)=>z+x.sh*((maps[x.s] as Map<string,PricePoint>).get(d)?.[f]??x.e),0);for(let di=0;di<dates.length;di++){const d=dates[di],nd=dates[di+1]??null;if(pout===d&&pos.length){cash=pos.reduce((z,x)=>{const r=(maps[x.s] as Map<string,PricePoint>).get(d);return z+x.sh*(r?.open??r?.close??x.e)},0)*.999;pos=[];pout=null;hold=0;peak=cash}if(pin?.d===d&&!pos.length){const os=pin.ss.map(s=>(maps[s] as Map<string,PricePoint>).get(d)?.open);if(os.length===5&&os.every(x=>x&&x>0)){const per=cash/5;pos=pin.ss.map((s,i)=>({s,sh:per*.999/(os[i] as number),e:os[i] as number}));cash=0;peak=eq(d,"open");hold=0}pin=null}const e=eq(d,"close");peak=Math.max(peak,e);const dd=e/peak-1;curve.push({date:d,equity:e,drawdown:dd});if(pos.length&&!pout&&nd){hold++;const stop=pos.some(x=>((maps[x.s] as Map<string,PricePoint>).get(d)?.close??Infinity)<=x.e*.88);if(stop||dd<=-.15||hold>=20)pout=nd}if(!pos.length&&!pin&&nd){const qi=(idx.QQQ as Map<string,number>).get(d);if(qi==null||qi<199)continue;const qr=rows.QQQ as PricePoint[];if(qr[qi].close<=mean(qr.slice(qi-199,qi+1).map(x=>x.close)))continue;const u=latest(us,d);if(!u)continue;const ca:Array<{s:string;v:number}>=[];for(const m of u.symbols){const s=m.symbol,i=(idx[s] as Map<string,number>|undefined)?.get(d),r=rows[s] as PricePoint[]|undefined;if(i==null||!r||i<99||i<20)continue;const close=r[i].close;if(close<=mean(r.slice(i-99,i+1).map(x=>x.close)))continue;const hi=Math.max(...r.slice(i-20,i).map(x=>x.close));if(close>hi)ca.push({s,v:close/hi-1})}ca.sort((a,b)=>b.v-a.v||a.s.localeCompare(b.s));if(ca.length>=5)pin={d:nd,ss:ca.slice(0,5).map(x=>x.s)}}}return curve}
function rets(c:EquityPoint[]){const m=new Map<string,number>();for(let i=1;i<c.length;i++)m.set(c[i].date,c[i].equity/c[i-1].equity-1);return m}
function buyHold(a:PricePoint[]){const rows=[...a].sort((x,y)=>x.date.localeCompare(y.date)).filter(x=>x.date>=START&&x.date<=END);let e=1,peak=1;const out:EquityPoint[]=[{date:rows[0].date,equity:1,drawdown:0}];for(let i=1;i<rows.length;i++){e*=rows[i].close/rows[i-1].close;peak=Math.max(peak,e);out.push({date:rows[i].date,equity:e,drawdown:e/peak-1})}return out}
function psqRiskOff(psq:PricePoint[],qqq:PricePoint[]){const p=[...psq].sort((a,b)=>a.date.localeCompare(b.date)),q=[...qqq].sort((a,b)=>a.date.localeCompare(b.date)),pm=new Map(p.map((x,i)=>[x.date,i])),qm=new Map(q.map((x,i)=>[x.date,i])),dates=q.map(x=>x.date).filter(d=>d>=START&&d<=END&&pm.has(d));let e=1,peak=1,exp=0;const out:EquityPoint[]=[{date:dates[0],equity:1,drawdown:0}];for(let i=1;i<dates.length;i++){const d=dates[i],pd=dates[i-1],ci=pm.get(d)!,pi=pm.get(pd)!;e*=1+exp*(p[ci].close/p[pi].close-1);peak=Math.max(peak,e);out.push({date:d,equity:e,drawdown:e/peak-1});const qi=qm.get(d)!;exp=qi>=199&&q[qi].close<mean(q.slice(qi-199,qi+1).map(x=>x.close))?1:0}return out}
function portfolio(parts:{curve:EquityPoint[],w:number}[]){const rm=parts.map(p=>rets(p.curve)),dates=parts[0].curve.slice(1).map(x=>x.date).filter(d=>rm.every(m=>m.has(d)));let e=1,peak=1;const out:EquityPoint[]=[{date:parts[0].curve[0].date,equity:1,drawdown:0}];for(const d of dates){let r=0;for(let i=0;i<parts.length;i++)r+=parts[i].w*(rm[i].get(d)??0);e*=1+r;peak=Math.max(peak,e);out.push({date:d,equity:e,drawdown:e/peak-1})}return out}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const fixed=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(p=>p.date<=END),g=runG(m.histories,us);const [dbmf,btal,psq]=await Promise.all(["DBMF","BTAL","PSQ"].map(fetchYahooHistory));const h1=buyHold(dbmf),h2=buyHold(btal),h3=psqRiskOff(psq,m.histories.QQQ??[]),h4=portfolio([{curve:h1,w:.5},{curve:h3,w:.5}]);const hs={H1_DBMF:h1,H2_BTAL:h2,H3_PSQ_RISKOFF:h3,H4_BLEND:h4};const specs={A:[.5,.2,.3],B:[.55,.2,.25],C:[.5,.25,.25]} as const;const results:any={};for(const [name,h] of Object.entries(hs)){results[name]={standalone:performanceStats(h),architectures:{}};for(const [key,[wf,wg,wh]] of Object.entries(specs)){const c=portfolio([{curve:fixed,w:wf},{curve:g,w:wg},{curve:h,w:wh}]);const s=performanceStats(c);results[name].architectures[key]={weights:{fixed60:wf,g:wg,hedge:wh},stats:s,strongPass:s.cagr>=.35&&s.maxDrawdown>=-.17}}}
console.log(JSON.stringify({objective:{cagr:.35,maxDrawdown:-.17},results},null,2))}
main().catch(e=>{console.error(e);process.exitCode=1});