import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { performanceStats, runStrategySimulation } from "../src/lib/backtest";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import type { EquityPoint, PricePoint, UniverseMonth } from "../src/lib/types";
type MF={histories:Record<string,PricePoint[]>};type UF={history:UniverseMonth[]};
const END="2026-08-25";
const mean=(x:number[])=>x.reduce((a,b)=>a+b,0)/x.length;
function overlay(base:EquityPoint[], exposureForNext:(i:number)=>number){let e=1,peak=1;const out:EquityPoint[]=[{date:base[0].date,equity:1,drawdown:0}];for(let i=1;i<base.length;i++){const r=base[i].equity/base[i-1].equity-1;const exp=exposureForNext(i-1);e*=1+exp*r;peak=Math.max(peak,e);out.push({date:base[i].date,equity:e,drawdown:e/peak-1})}return out}
async function main(){const m=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8"))as MF,u=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8"))as UF,us=[...u.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));const fixed=runStrategySimulation({histories:m.histories,universeHistory:us,config:PRODUCTION_STRATEGY}).backtest.equityCurve.filter(p=>p.date<=END);const qqq=(m.histories.QQQ??[]).filter(p=>p.date<=END);const qi=new Map(qqq.map((p,i)=>[p.date,i]));const qqqRegime=overlay(fixed,(i)=>{const d=fixed[i].date,ix=qi.get(d);if(ix==null||ix<199)return .4;const sma=mean(qqq.slice(ix-199,ix+1).map(x=>x.close));return qqq[ix].close>sma?1:.4});const shadowDD=overlay(fixed,(i)=>{const dd=fixed[i].drawdown;return dd>-0.05?1:dd>-0.10?.5:.25});console.log(JSON.stringify({fixed60:performanceStats(fixed),qqq200RegimeScaler:performanceStats(qqqRegime),shadowDdScaler:performanceStats(shadowDD)},null,2))}main().catch(e=>{console.error(e);process.exitCode=1});