import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY as P} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {PricePoint,UniverseMonth} from '../src/lib/types';

const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
function ranks(a:number[]){const q=a.map((v,i)=>({v,i})).sort((x,y)=>x.v-y.v),r=Array(a.length).fill(0);for(let i=0;i<q.length;){let j=i;while(j+1<q.length&&q[j+1].v===q[i].v)j++;for(let k=i;k<=j;k++)r[q[k].i]=(i+j)/2+1;i=j+1}return r}
function corr(a:number[],b:number[]){if(a.length<4||a.length!==b.length)return null;const x=ranks(a),y=ranks(b),mx=mean(x),my=mean(y);let n=0,dx=0,dy=0;for(let i=0;i<x.length;i++){const p=x[i]-mx,q=y[i]-my;n+=p*q;dx+=p*p;dy+=q*q}return dx&&dy?n/Math.sqrt(dx*dy):null}
function futureOpenReturn(rows:PricePoint[],date:string,n:number){const a=[...rows].sort((x,y)=>x.date.localeCompare(y.date));const i=a.findIndex(x=>x.date===date);if(i<0||i+1>=a.length)return null;const s=a[i+1].open??a[i+1].close,e=a[Math.min(i+n,a.length-1)].open??a[Math.min(i+n,a.length-1)].close;return s>0&&e>0?e/s-1:null}
function persistence(history:UniverseMonth[],idx:number,symbol:string,lookback:number){const a=history.slice(Math.max(0,idx-lookback+1),idx+1);return a.length?a.filter(u=>u.symbols.some(x=>x.symbol===symbol)).length/a.length:null}
function consecutive(history:UniverseMonth[],idx:number,symbol:string){let n=0;for(let i=idx;i>=0;i--){if(history[i].symbols.some(x=>x.symbol===symbol))n++;else break}return n}
function summarize(rows:any[],start:string,end:string,key:'p6'|'p12'|'streak'){const x=rows.filter(r=>r.date>=start&&r.date<=end&&r[key]!=null&&r.r1!=null&&r.r3!=null);const months=[...new Set(x.map(r=>r.date))];const monthly=months.map(d=>{const m=x.filter(r=>r.date===d);return{date:d,n:m.length,ic1:corr(m.map(r=>r[key]),m.map(r=>r.r1)),ic3:corr(m.map(r=>r[key]),m.map(r=>r.r3))}}).filter(r=>r.ic1!=null&&r.ic3!=null);return{months:monthly.length,meanIC1:mean(monthly.map(r=>r.ic1 as number)),meanIC3:mean(monthly.map(r=>r.ic3 as number)),positiveIC1Share:monthly.length?monthly.filter(r=>(r.ic1 as number)>0).length/monthly.length:null,positiveIC3Share:monthly.length?monthly.filter(r=>(r.ic3 as number)>0).length/monthly.length:null}}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]};const u=[...uf.history].filter(x=>x.asOf>=P.backtestStart).sort((a,b)=>a.asOf.localeCompare(b.asOf)),q=market.histories.QQQ;const rows:any[]=[];for(let i=0;i<u.length;i++){const x=u[i],sig:any=buildMonthlySignal({universe:x,histories:market.histories,qqq:q,nextSessionDate:nextUsTradingSession(x.asOf),config:P}),top=sig.candidates.filter((c:any)=>c.eligible&&c.score!=null).slice(0,10);for(const c of top){const h=market.histories[c.symbol]??[];rows.push({date:x.asOf,symbol:c.symbol,momentumScore:c.score,p6:persistence(u,i,c.symbol,6),p12:persistence(u,i,c.symbol,12),streak:consecutive(u,i,c.symbol),r1:futureOpenReturn(h,x.asOf,21),r3:futureOpenReturn(h,x.asOf,63)})}}
 const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,pit:true,freeDataOnly:true,diagnosticOnly:true,predeclared:'Momentum Top10 only. N-PORT institutional persistence measured from PIT Top80 universe snapshots. p6 and p12 are 6/12-snapshot presence shares; streak is consecutive Top80 snapshots. No backtest unless direction is stable across 2020-23 and 2024-26.'},diagnostic:{p6:{early:summarize(rows,'2020-01-01','2023-12-31','p6'),late:summarize(rows,'2024-01-01','2026-08-25','p6')},p12:{early:summarize(rows,'2020-01-01','2023-12-31','p12'),late:summarize(rows,'2024-01-01','2026-08-25','p12')},streak:{early:summarize(rows,'2020-01-01','2023-12-31','streak'),late:summarize(rows,'2024-01-01','2026-08-25','streak')}}};const d=path.join(process.cwd(),'data/research/nport-persistence-diagnostic');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}
main().catch(e=>{console.error(e);process.exit(1)});
