import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY as C} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import type {PricePoint,UniverseMember,UniverseMonth} from '../src/lib/types';

type Row={date:string;year:number;symbol:string;selected:boolean;future3m:number;futureTop5:boolean;futureTopDecile:boolean;dScore:number|null;dEtfCount:number|null;dAggWeight:number|null;dMaxWeight:number|null;dRecency:number|null;universeRank:number;score:number|null};
const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:NaN;const med=(a:number[])=>{if(!a.length)return NaN;const x=[...a].sort((a,b)=>a-b),i=Math.floor(x.length/2);return x.length%2?x[i]:(x[i-1]+x[i])/2};
function pctRank(vals:number[],x:number){const s=[...vals].sort((a,b)=>a-b);let n=0;for(const v of s)if(v<=x)n++;return n/s.length}
function feature(rows:Row[],key:keyof Pick<Row,'dScore'|'dEtfCount'|'dAggWeight'|'dMaxWeight'|'dRecency'>){const z=rows.filter(r=>r[key]!==null) as any[];const winners=z.filter(r=>r.futureTopDecile),others=z.filter(r=>!r.futureTopDecile);return{n:z.length,winners:winners.length,winnerMean:mean(winners.map(r=>r[key])),otherMean:mean(others.map(r=>r[key])),winnerMedian:med(winners.map(r=>r[key])),otherMedian:med(others.map(r=>r[key])),winnerPctRankMean:mean(winners.map(r=>pctRank(z.filter(q=>q.date===r.date&&q[key]!==null).map(q=>q[key] as number),r[key] as number)))}}
async function main(){const mk=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]};const us=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),q=[...mk.histories.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date),di=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(mk.histories).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))]));const rows:Row[]=[];for(let mi=1;mi<us.length;mi++){const u=us[mi],prev=us[mi-1];if(u.asOf<C.backtestStart)continue;const i=di.get(u.asOf);if(i===undefined||i+64>=dates.length)continue;const exit=dates[i+64],sig=buildMonthlySignal({universe:u,histories:mk.histories,qqq:q,nextSessionDate:dates[i+1]??u.asOf,config:C}),pmap=new Map(prev.symbols.map(x=>[x.symbol,x]));const tmp:any[]=[];for(const m of u.symbols){const p=pmap.get(m.symbol),a=pm[m.symbol]?.get(u.asOf),b=pm[m.symbol]?.get(exit);if(!a||!b||!(a.close>0&&b.close>0))continue;tmp.push({m,p,r:Math.log(b.close/a.close),score:sig.candidates.find(c=>c.symbol===m.symbol)?.score??null,selected:sig.selectedSymbols.includes(m.symbol)})}const sorted=[...tmp].sort((a,b)=>b.r-a.r),top5=new Set(sorted.slice(0,5).map(x=>x.m.symbol)),nDec=Math.max(1,Math.ceil(sorted.length*.1)),topDec=new Set(sorted.slice(0,nDec).map(x=>x.m.symbol));for(const x of tmp){const p=x.p as UniverseMember|undefined,m=x.m as UniverseMember;rows.push({date:u.asOf,year:+u.asOf.slice(0,4),symbol:m.symbol,selected:x.selected,future3m:x.r,futureTop5:top5.has(m.symbol),futureTopDecile:topDec.has(m.symbol),dScore:p?m.universeScore-p.universeScore:null,dEtfCount:p?m.etfCount-p.etfCount:null,dAggWeight:p?m.aggregateWeight-p.aggregateWeight:null,dMaxWeight:p?m.maxWeight-p.maxWeight:null,dRecency:p?m.recencyWeight-p.recencyWeight:null,universeRank:m.universeRank,score:x.score})}}
 const keys=['dScore','dEtfCount','dAggWeight','dMaxWeight','dRecency'] as const;const pack=(x:Row[])=>Object.fromEntries(keys.map(k=>[k,feature(x,k)]));const missed=rows.filter(r=>r.futureTopDecile&&!r.selected);const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,pit:true,trueOOS:false,warning:'Future 3m return is label only. All features are month-over-month changes in PIT N-PORT universe fields available at signal date. This is diagnostic, not a tradable model.'},counts:{rows:rows.length,months:new Set(rows.map(r=>r.date)).size,futureTopDecile:rows.filter(r=>r.futureTopDecile).length,missedTopDecile:missed.length},all:pack(rows),early:pack(rows.filter(r=>r.year<=2023)),late:pack(rows.filter(r=>r.year>=2024)),missedWinnerFeatures:pack(rows.filter(r=>!r.selected)),selectedVsNot:{selectedMeanFuture3m:mean(rows.filter(r=>r.selected).map(r=>r.future3m)),notSelectedMeanFuture3m:mean(rows.filter(r=>!r.selected).map(r=>r.future3m))}};const d=path.join(process.cwd(),'data/research/nport-breadth-change-diagnostic');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}
main().catch(e=>{console.error(e);process.exit(1)});