import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY as P} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import {performanceStats} from '../src/lib/backtest';
import type {EquityPoint,PricePoint,StrategyConfig,UniverseMonth} from '../src/lib/types';

type F='BASE'|'OVN20_25'|'OVN60_25';
const CONFIG:StrategyConfig={...P,strategyId:'momentum-overnight-top10',allocation:{...P.allocation,baseTop1Weight:.7,concentratedTop1Weight:.7,maxTop1Weight:.7}} as StrategyConfig;
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
const sd=(x:number[])=>{if(x.length<2)return 0;const m=mean(x);return Math.sqrt(mean(x.map(v=>(v-m)**2)))};
const z=(v:number,m:number,s:number)=>s>1e-12?(v-m)/s:0;
function ranks(a:number[]){const ix=a.map((v,i)=>({v,i})).sort((x,y)=>x.v-y.v);const r=Array(a.length).fill(0);for(let i=0;i<ix.length;){let j=i;while(j+1<ix.length&&ix[j+1].v===ix[i].v)j++;const rr=(i+j)/2+1;for(let k=i;k<=j;k++)r[ix[k].i]=rr;i=j+1;}return r}
function corr(a:number[],b:number[]){if(a.length<4||a.length!==b.length)return null;const ra=ranks(a),rb=ranks(b),ma=mean(ra),mb=mean(rb);let n=0,da=0,db=0;for(let i=0;i<ra.length;i++){const x=ra[i]-ma,y=rb[i]-mb;n+=x*y;da+=x*x;db+=y*y}return da>0&&db>0?n/Math.sqrt(da*db):null}
function mapHist(h:Record<string,PricePoint[]>){return Object.fromEntries(Object.entries(h).map(([s,p])=>[s,[...p].sort((a,b)=>a.date.localeCompare(b.date))]))}
function overnight(rows:PricePoint[],date:string,n:number){let i=rows.findIndex(x=>x.date===date);if(i<1)return null;let sum=0,c=0;for(;i>=1&&c<n;i--){const o=rows[i].open,pc=rows[i-1].close;if(o>0&&pc>0){sum+=Math.log(o/pc);c++}}return c>=Math.min(n,15)?sum:null}
function fwd(rows:PricePoint[],date:string,n:number){const i=rows.findIndex(x=>x.date===date);if(i<0||i+1>=rows.length)return null;const a=rows[i+1].open??rows[i+1].close,b=rows[Math.min(i+n,rows.length-1)].open??rows[Math.min(i+n,rows.length-1)].close;return a>0&&b>0?b/a-1:null}
function baseSignal(u:UniverseMonth,h:Record<string,PricePoint[]>,q:PricePoint[],next:string){const s:any=buildMonthlySignal({universe:u,histories:h,qqq:q,nextSessionDate:next,config:CONFIG});if(s.selectedSymbols.length===2)s.targetWeights=[.7,.3];return s}
function rerank(u:UniverseMonth,h:Record<string,PricePoint[]>,hs:Record<string,PricePoint[]>,q:PricePoint[],next:string,f:F){const b:any=baseSignal(u,h,q,next);if(f==='BASE'||!b.marketRiskOn)return b;const n=f==='OVN20_25'?20:60,top10=b.candidates.filter((c:any)=>c.eligible&&c.score!=null).slice(0,10);const rows=top10.map((c:any)=>({c,v:hs[c.symbol]?overnight(hs[c.symbol],u.asOf,n):null})),vals=rows.map(x=>x.v).filter((x):x is number=>x!=null&&Number.isFinite(x));if(vals.length<4)return b;const sm=mean(top10.map((x:any)=>x.score)),ss=sd(top10.map((x:any)=>x.score)),fm=mean(vals),fs=sd(vals);const ranked=rows.map(x=>({c:x.c,combo:x.v==null?-Infinity:z(x.c.score,sm,ss)+.25*z(x.v,fm,fs)})).sort((a,b)=>b.combo-a.combo||a.c.symbol.localeCompare(b.c.symbol));const sel=ranked.filter(x=>Number.isFinite(x.combo)).slice(0,2);if(sel.length<2)return b;return{...b,selectedSymbols:sel.map(x=>x.c.symbol),targetWeights:[.7,.3],allocationMode:'70/30'};}
function sim(h:Record<string,PricePoint[]>,hs:Record<string,PricePoint[]>,u:UniverseMonth[],f:F){const q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),ix=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(CONFIG);const c:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<CONFIG.backtestStart)continue;const n=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?rerank(uu,h,hs,q,n,f):null,sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},CONFIG);c.push({date:d,equity:st.currentEquity,drawdown:st.drawdown});}return c}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const prev=[...c].reverse().find(p=>p.date<s),z0=prev?[prev,...x]:x,b=z0[0].equity;return z0.map(p=>({...p,equity:p.equity/b}))}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].filter(x=>x.asOf>=CONFIG.backtestStart).sort((a,b)=>a.asOf.localeCompare(b.asOf)),hs=mapHist(market.histories),q=market.histories.QQQ;
 const diagnostic:any[]=[];for(const x of u){const b:any=baseSignal(x,market.histories,q,nextUsTradingSession(x.asOf));const top=b.candidates.filter((c:any)=>c.eligible&&c.score!=null).slice(0,10);for(const n of [20,60]){const rows=top.map((c:any)=>({v:hs[c.symbol]?overnight(hs[c.symbol],x.asOf,n):null,r1:hs[c.symbol]?fwd(hs[c.symbol],x.asOf,21):null,r3:hs[c.symbol]?fwd(hs[c.symbol],x.asOf,63):null})).filter((r:any)=>r.v!=null&&r.r1!=null&&r.r3!=null);diagnostic.push({date:x.asOf,n,count:rows.length,ic1:corr(rows.map((r:any)=>r.v),rows.map((r:any)=>r.r1)),ic3:corr(rows.map((r:any)=>r.v),rows.map((r:any)=>r.r3))});}}
 function ds(start:string,end:string,n:number){const a=diagnostic.filter(r=>r.n===n&&r.date>=start&&r.date<=end&&r.ic1!=null);return{months:a.length,meanIC1:mean(a.map(r=>r.ic1)),meanIC3:mean(a.map(r=>r.ic3)),positiveIC1Share:a.length?a.filter(r=>r.ic1>0).length/a.length:null,positiveIC3Share:a.length?a.filter(r=>r.ic3>0).length/a.length:null}}
 const diag={early20:ds('2020-01-01','2023-12-31',20),late20:ds('2024-01-01','2026-08-25',20),early60:ds('2020-01-01','2023-12-31',60),late60:ds('2024-01-01','2026-08-25',60)};
 const fs:F[]=['BASE','OVN20_25','OVN60_25'],cur=Object.fromEntries(fs.map(f=>[f,sim(market.histories,hs,u,f)]))as Record<F,EquityPoint[]>;const full=fs.map(f=>({variant:f,...performanceStats(cur[f])})),years=[2020,2021,2022,2023,2024,2025,2026],annual=years.map(y=>({year:y,...Object.fromEntries(fs.map(f=>[f,performanceStats(sl(cur[f],`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))]))}));const splits=[2022,2023,2024,2025,2026],anchored=splits.map(y=>{const tr=`${y-1}-12-31`,train=fs.map(f=>({f,calmar:performanceStats(sl(cur[f],'2020-01-01',tr)).calmar??-99})).sort((a,b)=>b.calmar-a.calmar),pick=train[0].f,e=y===2026?'2026-08-25':`${y}-12-31`;return{year:y,pick,train,oos:performanceStats(sl(cur[pick],`${y}-01-01`,e)),base:performanceStats(sl(cur.BASE,`${y}-01-01`,e))}});
 const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,freeDataOnly:true,noLeverage:true,pit:true,nextOpen:true,predeclared:'Top10 rerank; overnight close-to-open log return; 20/60 sessions; lambda=.25 only; W70 allocation'},diagnostic:diag,full,annual,anchored};const d=path.join(process.cwd(),'data/research/overnight-momentum-top10');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
