import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY} from '../src/lib/config';
import {buildMonthlySignal,monthlyCloses} from '../src/lib/strategy/momentum';
import {initial,transition} from './lib/cash-residual-state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,PricePoint,UniverseMonth,StrategyConfig} from '../src/lib/types';
const cfg:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,oneMonth:0,threeMonth:.25,sixMonth:.75},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.7}};
type V='BASE'|'R2_LOWVOL30'|'R2_BREADTH50';
function rv20(q:PricePoint[],d:string){const x=q.filter(p=>p.date<=d).slice(-21);if(x.length<21)return null;const r=[] as number[];for(let i=1;i<x.length;i++)r.push(Math.log(x[i].close/x[i-1].close));const m=r.reduce((a,b)=>a+b,0)/r.length;return Math.sqrt(r.reduce((s,v)=>s+(v-m)**2,0)/r.length)*Math.sqrt(252)}
function r6(p:PricePoint[],d:string){const x=monthlyCloses(p).filter(v=>v.date<=d);return x.length>6?x.at(-1)!.close/x.at(-7)!.close-1:null}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],v:V){const q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),ix=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initial(cfg),filters=0;const c:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<cfg.backtestStart)continue;const n=ds[i+1]??nextUsTradingSession(d),uu=um.get(d);let sg=uu?buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:n,config:cfg}):null;if(sg&&sg.selectedSymbols.length===2){const w=sg.zGap!==null&&sg.zGap>=.25?.7:.6;let keep=true;if(v==='R2_LOWVOL30'){const vol=rv20(q,d);keep=vol!=null&&vol<.30;}else if(v==='R2_BREADTH50'){const vals=uu.symbols.map((x:any)=>typeof x==='string'?x:x.symbol).map(s=>r6(h[s]??[],d)).filter((x):x is number=>x!=null);keep=vals.length>0&&vals.filter(x=>x>0).length/vals.length>=.5;}if(v!=='BASE'&&!keep){sg.targetWeights=[w,0];filters++;}else sg.targetWeights=[w,1-w];}const sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));st=transition(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},cfg);c.push({date:d,equity:st.currentEquity,drawdown:st.drawdown})}return{c,filters}}
function sl(c:EquityPoint[],a:string,b:string){const x=c.filter(p=>p.date>=a&&p.date<=b);if(x.length<2)return[];const q=x[0].equity;return x.map(p=>({...p,equity:p.equity/q}))}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),vs:V[]=['BASE','R2_LOWVOL30','R2_BREADTH50'],cur=Object.fromEntries(vs.map(v=>[v,sim(m.histories,u,v)]))as Record<V,ReturnType<typeof sim>>,full=vs.map(v=>({variant:v,...performanceStats(cur[v].c),filters:cur[v].filters})),splits=[{tr:'2021-12-31',y:2022},{tr:'2022-12-31',y:2023},{tr:'2023-12-31',y:2024},{tr:'2024-12-31',y:2025},{tr:'2025-12-31',y:2026}],wf=splits.map(s=>{const ranked=vs.map(v=>({v,stats:performanceStats(sl(cur[v].c,'2020-01-01',s.tr))})).sort((a,b)=>(b.stats.calmar??-99)-(a.stats.calmar??-99)),pick=ranked[0].v,e=s.y===2026?'2026-08-25':`${s.y}-12-31`;return{trainThrough:s.tr,oosYear:s.y,pick,oos:performanceStats(sl(cur[pick].c,`${s.y}-01-01`,e)),base:performanceStats(sl(cur.BASE.c,`${s.y}-01-01`,e)),train:ranked}}),out={generatedAt:new Date().toISOString(),validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,pit:true,nextOpen:true,cashResidualPreserved:true,warning:'Only existing regime thresholds: QQQ 20D realized vol <30%, or PIT Top80 positive-6M breadth >=50%. Rank1 weight unchanged; rejected rank2 allocation remains cash.'},full,wf};const d=path.join(process.cwd(),'data/research/rank2-regime-filter');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});