import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { performanceStats } from "../src/lib/backtest";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import type { EquityPoint, MonthlySignal, PricePoint, UniverseMonth, StrategyConfig } from "../src/lib/types";

type V={id:string,w3:number,w6:number,mode:"BLEND"|"MIN"};
const VARS:V[]=[{id:"RANK25_75",w3:.25,w6:.75,mode:"BLEND"},{id:"RANK50_50",w3:.5,w6:.5,mode:"BLEND"},{id:"RANK_CONSIST",w3:.5,w6:.5,mode:"MIN"}];
const cfg:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,threeMonth:.25,sixMonth:.75},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.7}};
function std(xs:number[]){if(!xs.length)return 0;const m=xs.reduce((a,b)=>a+b,0)/xs.length;return Math.sqrt(xs.reduce((a,b)=>a+(b-m)**2,0)/xs.length);}
function rerank(sig:MonthlySignal,v:V){if(!sig.marketRiskOn)return sig;const e=sig.candidates.filter(c=>c.eligible&&c.score!==null&&c.threeMonth!==null&&c.sixMonth!==null);if(e.length<2)return {...sig,selectedSymbols:[],targetWeights:[],allocationMode:"CASH" as const,zGap:null};const rank=(key:"threeMonth"|"sixMonth")=>{const s=[...e].sort((a,b)=>(b[key]??-Infinity)-(a[key]??-Infinity)||a.symbol.localeCompare(b.symbol));return new Map(s.map((x,i)=>[x.symbol,e.length===1?1:1-i/(e.length-1)]));};const r3=rank("threeMonth"),r6=rank("sixMonth");const rows=e.map(c=>({c,rs:v.mode==="MIN"?Math.min(r3.get(c.symbol)!,r6.get(c.symbol)!):v.w3*r3.get(c.symbol)!+v.w6*r6.get(c.symbol)!})).sort((a,b)=>b.rs-a.rs||a.c.symbol.localeCompare(b.c.symbol));const s=rows.slice(0,2);const disp=std(e.map(x=>x.score!)),zg=disp>0?(s[0].c.score!-s[1].c.score!)/disp:0,top=zg>=.25?.7:.6;return {...sig,selectedSymbols:s.map(x=>x.c.symbol),targetWeights:[top,1-top],zGap:zg,allocationMode:top===.7?"70/30" as const:"50/50" as const};}
function sim(hist:Record<string,PricePoint[]>,u:UniverseMonth[],v:V|null){const q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg);const curve:EquityPoint[]=[];for(let i=0;i<dates.length;i++){const date=dates[i];if(date<cfg.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),uu=um.get(date);let sig=uu?buildMonthlySignal({universe:uu,histories:hist,qqq:q,nextSessionDate:next,config:cfg}):null;if(sig){if(v)sig=rerank(sig,v);else if(sig.selectedSymbols.length===2){sig.targetWeights=sig.zGap!==null&&sig.zGap>=.25?[.7,.3]:[.6,.4];}}const sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));st=transitionDay(st,{date,prices,qqqHistoryThroughClose:q.slice(0,(idx.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},cfg);curve.push({date,equity:st.currentEquity,drawdown:st.drawdown});}return curve;}
function slice(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(!x.length)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}));}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>};const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]};const u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),base=sim(market.histories,u,null),rows=[] as any[];for(const v of VARS){const c=sim(market.histories,u,v);rows.push({variant:v,full:performanceStats(c),annual:[2020,2021,2022,2023,2024,2025,2026].map(y=>({y,candidate:performanceStats(slice(c,`${y}-01-01`,y===2026?"2026-08-25":`${y}-12-31`)),baseline:performanceStats(slice(base,`${y}-01-01`,y===2026?"2026-08-25":`${y}-12-31`))}))});}const output={generatedAt:new Date().toISOString(),validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,warning:"Three predeclared rank-momentum variants. Eligibility/gate/risk controls unchanged; only Top2 ordering changes."},baseline:performanceStats(base),rows};const dir=path.join(process.cwd(),"data/research/rank-momentum-screen");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});