import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY} from '../src/lib/config';
import {buildMonthlySignal,monthlyCloses} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,PricePoint,UniverseMonth,StrategyConfig} from '../src/lib/types';

const cfg:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,oneMonth:0,threeMonth:.25,sixMonth:.75},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.7}};
type V='BASE'|'R2_POS1M'|'R2_3M_GT_QQQ';
function mr(p:PricePoint[],d:string,n:number){const x=monthlyCloses(p).filter(v=>v.date<=d);return x.length>n?x.at(-1)!.close/x.at(-(n+1))!.close-1:null}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],v:V){const q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),ix=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg),filters=0;const z:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<cfg.backtestStart)continue;const n=ds[i+1]??nextUsTradingSession(d),uu=um.get(d);let sg=uu?buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:n,config:cfg}):null;if(sg&&sg.selectedSymbols.length===2){const w=sg.zGap!==null&&sg.zGap>=.25?.7:.6;let keep=true;const r2=sg.candidates.find(c=>c.symbol===sg!.selectedSymbols[1]);if(v==='R2_POS1M')keep=(r2?.oneMonth??-Infinity)>0;else if(v==='R2_3M_GT_QQQ'){const qr=mr(q,d,3);keep=r2?.threeMonth!=null&&qr!=null&&r2.threeMonth>qr}if(!keep&&v!=='BASE'){sg.targetWeights=[w,0];filters++}else sg.targetWeights=[w,1-w]}const ss=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),pr=Object.fromEntries([...ss].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices:pr,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},cfg);z.push({date:d,equity:st.currentEquity,drawdown:st.drawdown})}return{c:z,filters}}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(!x.length)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
async function main(){const mk=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),vs:V[]=['BASE','R2_POS1M','R2_3M_GT_QQQ'],cur=Object.fromEntries(vs.map(v=>[v,sim(mk.histories,u,v)]))as Record<V,ReturnType<typeof sim>>,years=[2020,2021,2022,2023,2024,2025,2026],splits=[{tr:'2021-12-31',y:2022},{tr:'2022-12-31',y:2023},{tr:'2023-12-31',y:2024},{tr:'2024-12-31',y:2025},{tr:'2025-12-31',y:2026}];const full=vs.map(v=>({variant:v,...performanceStats(cur[v].c),filters:cur[v].filters,annual:years.map(y=>({y,...performanceStats(sl(cur[v].c,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))}))})),wf=splits.map(s=>{const train=vs.map(v=>({v,stats:performanceStats(sl(cur[v].c,'2020-01-01',s.tr))})).sort((a,b)=>(b.stats.calmar??-99)-(a.stats.calmar??-99)),pick=train[0].v,e=s.y===2026?'2026-08-25':`${s.y}-12-31`;return{trainThrough:s.tr,oosYear:s.y,pick,oos:performanceStats(sl(cur[pick].c,`${s.y}-01-01`,e)),base:performanceStats(sl(cur.BASE.c,`${s.y}-01-01`,e)),train}}),o={generatedAt:new Date().toISOString(),validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,pit:true,nextOpen:true,warning:'Two predeclared rank2-only filters. Rank1 weight never increases; rejected rank2 sleeve remains cash.'},full,wf};const d=path.join(process.cwd(),'data/research/rank2-quality-screen');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(o,null,2));console.log(JSON.stringify(o,null,2))}main().catch(e=>{console.error(e);process.exit(1)});