import fs from 'node:fs/promises';import path from 'node:path';import {PRODUCTION_STRATEGY as P} from '../src/lib/config';import {buildMonthlySignal} from '../src/lib/strategy/momentum';import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';import {performanceStats} from '../src/lib/backtest';import {nextUsTradingSession} from '../src/lib/trading-calendar';import type {EquityPoint,PricePoint,StrategyConfig,UniverseMonth} from '../src/lib/types';
type V={id:string,top1:number,bridge:number,k:number};const VS:V[]=[{id:'PROD',top1:-1,bridge:0,k:99},{id:'P_B50_K1',top1:-1,bridge:.5,k:1},{id:'P_B50_K3',top1:-1,bridge:.5,k:3},{id:'P_B50_K5',top1:-1,bridge:.5,k:5},{id:'W70',top1:.7,bridge:0,k:99},{id:'W70_B50_K1',top1:.7,bridge:.5,k:1},{id:'W70_B50_K3',top1:.7,bridge:.5,k:3},{id:'W70_B50_K5',top1:.7,bridge:.5,k:5}];
function cfg(v:V):StrategyConfig{return v.top1<0?P:{...P,allocation:{...P.allocation,baseTop1Weight:v.top1,concentratedTop1Weight:v.top1,maxTop1Weight:v.top1}} as StrategyConfig}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],v:V){const c=cfg(v),q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),ix=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(c),prevBaseEq=1,prevQ:number|null=null,e=1,pk=1,on=false,sched=false,trades=0,days=0;const curve:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<c.backtestStart){prevQ=q[i].close;continue}const n=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:n,config:c}):null,sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),pr=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)])),before=structuredClone(st),beforeEq=st.currentEquity;st=transitionDay(st,{date:d,prices:pr,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},c);const qr=pm.QQQ?.get(d),qo=qr?.open??qr?.close,qc=qr?.close,was=before.currentPositions.length>0,now=st.currentPositions.length>0,entered=!was&&now;const bf=prevBaseEq>0?st.currentEquity/prevBaseEq:1;
 if(v.bridge===0)e*=bf;else{
   if(sched&&!on&&qo&&qc){e*=((1-v.bridge)+v.bridge*(1-c.execution.transactionCost)*(qc/qo));on=true;sched=false;trades++;days++;}
   else if(on&&qc&&prevQ){e*=((1-v.bridge)+v.bridge*(qc/prevQ));days++;}
   else if(was||now)e*=bf;
   if(entered&&on&&qo&&qc){const today=((1-v.bridge)+v.bridge*(qc/(prevQ??qc)));if(today>0)e/=today;e*=((1-v.bridge)+v.bridge*(qo/(prevQ??qo))*(1-c.execution.transactionCost));e*=beforeEq>0?st.currentEquity/beforeEq:1;on=false;trades++;sched=false;}
   if(!now&&st.state==='WAITING_RECOVERY'&&st.recoveryConsecutiveDays===v.k&&!on&&!sched)sched=true;
   if(!st.marketRiskOn&&on&&qo&&prevQ){/* exit is intentionally delayed to next open by scheduling via next loop simplification */}
 }
 pk=Math.max(pk,e);curve.push({date:d,equity:e,drawdown:e/pk-1});prevBaseEq=st.currentEquity;prevQ=qc??prevQ}return{curve,trades,days}}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const prev=[...c].reverse().find(p=>p.date<s),z=prev?[prev,...x]:x,b=z[0].equity;return z.map(p=>({...p,equity:p.equity/b}))}
async function main(){const mk=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),runs=new Map<string,ReturnType<typeof sim>>();for(const v of VS)runs.set(v.id,sim(mk.histories,u,v));const full=VS.map(v=>({id:v.id,top1:v.top1,bridge:v.bridge,k:v.k,stats:performanceStats(runs.get(v.id)!.curve),trades:runs.get(v.id)!.trades,bridgeDays:runs.get(v.id)!.days})),years=[2020,2021,2022,2023,2024,2025,2026],annual=years.map(y=>({year:y,...Object.fromEntries(VS.map(v=>[v.id,performanceStats(sl(runs.get(v.id)!.curve,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))]))})),confirmation=VS.map(v=>({id:v.id,stats:performanceStats(sl(runs.get(v.id)!.curve,'2023-01-01','2026-08-25'))}));const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,noLeverage:true,warning:'Shadow-return robustness screen. K is recovery consecutive close at which 50% QQQ bridge is scheduled for next-open entry; sticky bridge holds until Top2 re-entry. Production state machine remains authoritative. Exact engine required before adoption.'},full,annual,confirmation};const d=path.join(process.cwd(),'data/research/recovery-bridge-robustness');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});