import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY as P} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import {performanceStats} from '../src/lib/backtest';
import type {EquityPoint,PricePoint,StrategyConfig,UniverseMonth} from '../src/lib/types';
type V='BASE'|'TREND200'|'LOWVOL30'|'TREND200_LOWVOL30';
const C:StrategyConfig={...P,strategyId:'momentum-w70-regime-entry-gate',allocation:{...P.allocation,baseTop1Weight:.7,concentratedTop1Weight:.7,maxTop1Weight:.7}} as StrategyConfig;
const mean=(a:number[])=>a.reduce((s,x)=>s+x,0)/a.length, sd=(a:number[])=>{const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))};
function regime(q:PricePoint[],i:number){const sma=i>=199?mean(q.slice(i-199,i+1).map(x=>x.close)):NaN;const rs=i>=20?q.slice(i-20,i+1).map((x,j,a)=>j?Math.log(x.close/a[j-1].close):null).filter((x):x is number=>x!=null):[];const rv=rs.length>=20?sd(rs)*Math.sqrt(252):NaN;return{trend:Number.isFinite(sma)&&q[i].close>sma,lowvol:Number.isFinite(rv)&&rv<.30}}
function gated(sig:any,r:{trend:boolean;lowvol:boolean},v:V){if(!sig||!sig.marketRiskOn||v==='BASE')return sig;const ok=v==='TREND200'?r.trend:v==='LOWVOL30'?r.lowvol:r.trend&&r.lowvol;if(ok)return sig;return{...sig,marketRiskOn:false,selectedSymbols:[],targetWeights:[],allocationMode:'CASH',reason:`Research ${v} entry gate blocked Risk-On`}}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],v:V){const q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),ix=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(C);const c:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<C.backtestStart)continue;const n=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),base=uu?buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:n,config:C}):null,sg=uu?gated(base,regime(q,i),v):null,sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},C);c.push({date:d,equity:st.currentEquity,drawdown:st.drawdown})}return c}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const p=[...c].reverse().find(v=>v.date<s),z=p?[p,...x]:x,b=z[0].equity;return z.map(v=>({...v,equity:v.equity/b}))}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),vs:V[]=['BASE','TREND200','LOWVOL30','TREND200_LOWVOL30'],cur=Object.fromEntries(vs.map(v=>[v,sim(m.histories,u,v)]))as Record<V,EquityPoint[]>;const years=[2020,2021,2022,2023,2024,2025,2026],annual=years.map(y=>({year:y,...Object.fromEntries(vs.map(v=>[v,performanceStats(sl(cur[v],`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))]))}));const anchored=[2022,2023,2024,2025,2026].map(y=>{const tr=`${y-1}-12-31`,rank=vs.map(v=>({v,calmar:performanceStats(sl(cur[v],'2020-01-01',tr)).calmar??-99})).sort((a,b)=>b.calmar-a.calmar),pick=rank[0].v,e=y===2026?'2026-08-25':`${y}-12-31`;return{year:y,pick,rank,oos:performanceStats(sl(cur[pick],`${y}-01-01`,e)),base:performanceStats(sl(cur.BASE,`${y}-01-01`,e))}});const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,noLeverage:true,pit:true,nextOpen:true,architectureHindsightRemains:true,predeclared:'W70; monthly new-RiskOn entry only; fixed diagnostic thresholds QQQ>200DMA and/or prior-close 20D realized vol<30%; no threshold grid. Existing holdings remain governed by Production stop/circuit/recovery.'},full:vs.map(v=>({variant:v,...performanceStats(cur[v])})),annual,anchored};const d=path.join(process.cwd(),'data/research/regime-entry-gate-w70');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});
