import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { performanceStats } from "../src/lib/backtest";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import type { EquityPoint, PricePoint, UniverseMonth, StrategyConfig } from "../src/lib/types";

const DEF=["GLD","TLT","IEF","SHY"];
const COST=PRODUCTION_STRATEGY.execution.transactionCost;
const cfg:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,threeMonth:0.25,sixMonth:0.75},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:0.6,concentratedTop1Weight:0.7}};
type Mode="CASH"|"BEST3"|"BEST6";
async function yahoo(sym:string){const p1=Math.floor(Date.parse("2019-01-01T00:00:00Z")/1000),p2=Math.floor(Date.parse("2026-09-01T00:00:00Z")/1000);const r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${sym}?period1=${p1}&period2=${p2}&interval=1d&events=div%2Csplits&includeAdjustedClose=true`,{headers:{"User-Agent":"Mozilla/5.0"}});if(!r.ok)throw new Error(`${sym}: ${r.status}`);const j:any=await r.json(),x=j.chart.result?.[0],ts=x?.timestamp??[],q=x?.indicators?.quote?.[0],adj=x?.indicators?.adjclose?.[0]?.adjclose??[];const out:PricePoint[]=[];for(let i=0;i<ts.length;i++){if(q?.open?.[i]==null||q?.close?.[i]==null||adj?.[i]==null)continue;const ratio=adj[i]/q.close[i];out.push({date:new Date(ts[i]*1000).toISOString().slice(0,10),open:q.open[i]*ratio,close:adj[i]});}return out;}
function core(hist:Record<string,PricePoint[]>,u:UniverseMonth[]){const q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg);const curve:EquityPoint[]=[];for(let i=0;i<dates.length;i++){const date=dates[i];if(date<cfg.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),uu=um.get(date),sig=uu?buildMonthlySignal({universe:uu,histories:hist,qqq:q,nextSessionDate:next,config:cfg}):null;if(sig&&sig.selectedSymbols.length===2){sig.targetWeights=sig.zGap!==null&&sig.zGap>=0.25?[0.7,0.3]:[0.6,0.4];}const sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));st=transitionDay(st,{date,prices,qqqHistoryThroughClose:q.slice(0,(idx.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},cfg);curve.push({date,equity:st.currentEquity,drawdown:st.drawdown});}return curve;}
function choose(daily:Record<string,PricePoint[]>,date:string,months:number){const look=months===3?63:126;const rows=DEF.map(s=>{const x=(daily[s]??[]).filter(p=>p.date<=date);if(x.length<=look)return null;const r=x.at(-1)!.close/x.at(-(look+1))!.close-1;return{s,r};}).filter(Boolean) as {s:string,r:number}[];rows.sort((a,b)=>b.r-a.r||a.s.localeCompare(b.s));return rows[0]?.r>0?rows[0].s:null;}
function schedule(hist:Record<string,PricePoint[]>,u:UniverseMonth[],daily:Record<string,PricePoint[]>,mode:Mode){const q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date));const out=new Map<string,string|null>();for(const um of u){if(um.asOf<cfg.backtestStart)continue;const exec=nextUsTradingSession(um.asOf);const sig=buildMonthlySignal({universe:um,histories:hist,qqq:q,nextSessionDate:exec,config:cfg});const sym=sig.marketRiskOn||mode==="CASH"?null:choose(daily,um.asOf,mode==="BEST3"?3:6);out.set(exec,sym);}return out;}
function sleeve(dates:string[],daily:Record<string,PricePoint[]>,sched:Map<string,string|null>){const pm=Object.fromEntries(Object.entries(daily).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))]));let cash=1,pos:{s:string,sh:number}|null=null,peak=1;const curve:EquityPoint[]=[];for(const d of dates){if(sched.has(d)){const target=sched.get(d)??null;if(pos&&pos.s!==target){const px=pm[pos.s]?.get(d)?.open;if(px){cash=pos.sh*px*(1-COST);pos=null;}}if(target&&!pos){const px=pm[target]?.get(d)?.open;if(px){pos={s:target,sh:cash*(1-COST)/px};cash=0;}}}let e=cash;if(pos){const px=pm[pos.s]?.get(d)?.close;if(px)e=pos.sh*px;}peak=Math.max(peak,e);curve.push({date:d,equity:e,drawdown:e/peak-1});}return curve;}
function gateStatus(hist:Record<string,PricePoint[]>,u:UniverseMonth[]){const q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date));const dates=q.map(p=>p.date).filter(d=>d>=cfg.backtestStart);const events=new Map<string,boolean>();for(const um of u){if(um.asOf<cfg.backtestStart)continue;const exec=nextUsTradingSession(um.asOf);const sig=buildMonthlySignal({universe:um,histories:hist,qqq:q,nextSessionDate:exec,config:cfg});events.set(exec,sig.marketRiskOn);}let status=false;const out=new Map<string,boolean>();for(const d of dates){if(events.has(d))status=events.get(d)!;out.set(d,status);}return out;}
function combine(coreC:EquityPoint[],sleeveC:EquityPoint[],gate:Map<string,boolean>){const sm=new Map(sleeveC.map(p=>[p.date,p.equity]));let e=1,peak=1,pc=coreC[0]?.equity??1,ps=sm.get(coreC[0]?.date)??1;const out:EquityPoint[]=[];for(const p of coreC){const sv=sm.get(p.date);if(sv==null)continue;const rc=p.equity/pc-1,rs=sv/ps-1;pc=p.equity;ps=sv;e*=1+(gate.get(p.date)?rc:rs);peak=Math.max(peak,e);out.push({date:p.date,equity:e,drawdown:e/peak-1});}return out;}
function slice(c:EquityPoint[],y:number){const x=c.filter(p=>p.date>=`${y}-01-01`&&p.date<=(y===2026?"2026-08-25":`${y}-12-31`));if(!x.length)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}));}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>};const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]};const u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),daily:Record<string,PricePoint[]>={};for(const s of DEF)daily[s]=await yahoo(s);const c=core(market.histories,u),dates=c.map(p=>p.date),gate=gateStatus(market.histories,u),rows=[] as any[];for(const mode of ["CASH","BEST3","BEST6"] as Mode[]){const sl=sleeve(dates,daily,schedule(market.histories,u,daily,mode)),x=combine(c,sl,gate);rows.push({mode,sleeve:performanceStats(sl),combined:performanceStats(x),annual:[2020,2021,2022,2023,2024,2025,2026].map(y=>({y,combined:performanceStats(slice(x,y)),core:performanceStats(slice(c,y))}))});}const output={generatedAt:new Date().toISOString(),validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,pitGate:true,nextOpen:true,transactionCostEachWay:COST,warning:"Corrected PIT market gate: signal uses completed asOf close and applies next session. Defensive ranking uses data <= signal close; trades next open; 10bp each way."},core:performanceStats(c),rows};const dir=path.join(process.cwd(),"data/research/riskoff-sleeve-corrected");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});