import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { performanceStats } from "../src/lib/backtest";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import type { EquityPoint, PricePoint, UniverseMonth, StrategyConfig } from "../src/lib/types";

const DEF=["GLD","TLT","IEF","SHY"];
const cfg:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,threeMonth:0.25,sixMonth:0.75},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:0.6,concentratedTop1Weight:0.7}};
const cost=PRODUCTION_STRATEGY.execution.transactionCost;
async function yahoo(sym:string){const p1=Math.floor(new Date("2019-01-01T00:00:00Z").getTime()/1000),p2=Math.floor(new Date("2026-09-01T00:00:00Z").getTime()/1000);const url=`https://query1.finance.yahoo.com/v8/finance/chart/${sym}?period1=${p1}&period2=${p2}&interval=1d&events=div%2Csplits&includeAdjustedClose=true`;const r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0"}});if(!r.ok)throw new Error(`${sym} yahoo ${r.status}`);const j:any=await r.json(),x=j.chart.result?.[0],ts=x?.timestamp??[],q=x?.indicators?.quote?.[0],adj=x?.indicators?.adjclose?.[0]?.adjclose??[];const out:PricePoint[]=[];for(let i=0;i<ts.length;i++){if(q?.open?.[i]==null||adj?.[i]==null)continue;const d=new Date(ts[i]*1000).toISOString().slice(0,10),ratio=adj[i]/q.close[i];out.push({date:d,open:q.open[i]*ratio,close:adj[i]});}return out;}
function riskOnMap(q:PricePoint[]){const dates=q.map(p=>p.date),byMonth=new Map<string,PricePoint>();for(const p of q)byMonth.set(p.date.slice(0,7),p);const months=[...byMonth.entries()].sort((a,b)=>a[0].localeCompare(b[0]));const state=new Map<string,boolean>();for(let i=0;i<months.length;i++){if(i<9){state.set(months[i][0],false);continue;}const ma=months.slice(i-9,i+1).reduce((s,x)=>s+x[1].close,0)/10;state.set(months[i][0],months[i][1].close>ma);}return new Map(dates.map(d=>[d,state.get(d.slice(0,7))??false]));}
function core(hist:Record<string,PricePoint[]>,u:UniverseMonth[]){const q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg);const curve:EquityPoint[]=[];for(let i=0;i<dates.length;i++){const date=dates[i];if(date<cfg.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),uu=um.get(date),sig=uu?buildMonthlySignal({universe:uu,histories:hist,qqq:q,nextSessionDate:next,config:cfg}):null;if(sig&&sig.selectedSymbols.length===2){sig.targetWeights=sig.zGap!==null&&sig.zGap>=0.25?[0.7,0.3]:[0.6,0.4];sig.allocationMode=sig.targetWeights[0]===0.7?"70/30":"50/50";}const sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));st=transitionDay(st,{date,prices,qqqHistoryThroughClose:q.slice(0,(idx.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},cfg);curve.push({date,equity:st.currentEquity,drawdown:st.drawdown});}return curve;}
function defensive(daily:Record<string,PricePoint[]>,qqq:PricePoint[],mode:"BEST3"|"GLD_IEF"){const dates=qqq.map(p=>p.date).filter(d=>d>=cfg.backtestStart),map=Object.fromEntries(Object.entries(daily).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))]));const byMonth=new Map<string,string[]>();for(const d of dates){const m=d.slice(0,7);if(!byMonth.has(m))byMonth.set(m,[]);byMonth.get(m)!.push(d);}const selected=new Map<string,string[]>();for(const [m,ds] of byMonth){const signal=ds[0];const qi=qqq.findIndex(p=>p.date===signal);if(qi<63)continue;if(mode==="GLD_IEF"){selected.set(m,["GLD","IEF"]);continue;}const rows=DEF.map(s=>{const ps=daily[s]??[],i=ps.findIndex(p=>p.date>=signal);const j=i>=0?i-1:ps.length-1;if(j<63)return null;return{s,r3:ps[j].close/ps[j-63].close-1};}).filter(Boolean) as {s:string,r3:number}[];rows.sort((a,b)=>b.r3-a.r3);selected.set(m,rows[0]&&rows[0].r3>0?[rows[0].s]:[]);}let e=1,peak=1;const out:EquityPoint[]=[];let prevPrices:Record<string,number>={};for(const d of dates){const syms=selected.get(d.slice(0,7))??[];let r=0;if(syms.length){for(const s of syms){const px=map[s]?.get(d)?.close,prev=prevPrices[s];if(px&&prev)r+=px/prev-1; if(px)prevPrices[s]=px;}r/=syms.length;}else{for(const s of DEF){const px=map[s]?.get(d)?.close;if(px)prevPrices[s]=px;}}e*=1+r;peak=Math.max(peak,e);out.push({date:d,equity:e,drawdown:e/peak-1});}return out;}
function combine(core:EquityPoint[],def:EquityPoint[],risk:Map<string,boolean>){const dm=new Map(def.map(p=>[p.date,p.equity]));let e=1,peak=1,pc=core[0]?.equity??1,pd=dm.get(core[0]?.date)??1;const out:EquityPoint[]=[];for(const p of core){const de=dm.get(p.date);if(de==null)continue;const rc=p.equity/pc-1,rd=de/pd-1;pc=p.equity;pd=de;e*=1+(risk.get(p.date)?rc:rd);peak=Math.max(peak,e);out.push({date:p.date,equity:e,drawdown:e/peak-1});}return out;}
function slice(c:EquityPoint[],y:number){const x=c.filter(p=>p.date>=`${y}-01-01`&&p.date<=(y===2026?"2026-08-25":`${y}-12-31`));if(!x.length)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}));}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>};const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]};const daily:Record<string,PricePoint[]>={};for(const s of DEF)daily[s]=await yahoo(s);const q=[...(market.histories.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),risk=riskOnMap(q),c=core(market.histories,[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)));const rows=[] as any[];for(const mode of ["BEST3","GLD_IEF"] as const){const d=defensive(daily,q,mode),x=combine(c,d,risk);rows.push({mode,defensive:performanceStats(d),combined:performanceStats(x),annual:[2020,2021,2022,2023,2024,2025,2026].map(y=>({y,combined:performanceStats(slice(x,y)),core:performanceStats(slice(c,y))}))});}const output={generatedAt:new Date().toISOString(),validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,warning:"Risk-off sleeve only replaces QQQ monthly MA RiskOff cash; historical screen, not forward proof."},core:performanceStats(c),rows};const dir=path.join(process.cwd(),"data/research/riskoff-sleeve-screen");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});