import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,PricePoint,UniverseMonth,StrategyConfig} from '../src/lib/types';

const ALL=['GLD','IEF','UUP','DBC'];
const C=PRODUCTION_STRATEGY.execution.transactionCost;
const cfg:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,threeMonth:.25,sixMonth:.75},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.7}};
async function yh(s:string){const a=Math.floor(Date.parse('2019-01-01T00:00:00Z')/1000),b=Math.floor(Date.parse('2026-09-01T00:00:00Z')/1000),r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${s}?period1=${a}&period2=${b}&interval=1d&events=div%2Csplits&includeAdjustedClose=true`,{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error(`${s}:${r.status}`);const j:any=await r.json(),x=j.chart.result[0],q=x.indicators.quote[0],ad=x.indicators.adjclose[0].adjclose;return x.timestamp.map((t:number,i:number)=>{if(q.open[i]==null||q.close[i]==null||ad[i]==null)return null;const k=ad[i]/q.close[i];return{date:new Date(t*1000).toISOString().slice(0,10),open:q.open[i]*k,close:ad[i]} as PricePoint}).filter(Boolean) as PricePoint[];}
function core(h:Record<string,PricePoint[]>,u:UniverseMonth[]){const q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),ix=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg);const z:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<cfg.backtestStart)continue;const n=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?buildMonthlySignal({universe:uu,histories:h,qqq:q,nextSessionDate:n,config:cfg}):null;if(sg&&sg.selectedSymbols.length===2)sg.targetWeights=sg.zGap!==null&&sg.zGap>=.25?[.7,.3]:[.6,.4];const ss=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),pr=Object.fromEntries([...ss].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices:pr,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},cfg);z.push({date:d,equity:st.currentEquity,drawdown:st.drawdown});}return z;}
type Plan={risk:boolean,s:string|null,signalDate:string,ranked:{s:string;r:number}[]};
function plan(h:Record<string,PricePoint[]>,u:UniverseMonth[],a:Record<string,PricePoint[]>,assets:string[],look:number){const q=[...h.QQQ].sort((x,y)=>x.date.localeCompare(y.date)),m=new Map<string,Plan>();for(const um of u){if(um.asOf<cfg.backtestStart)continue;const ex=nextUsTradingSession(um.asOf),sg=buildMonthlySignal({universe:um,histories:h,qqq:q,nextSessionDate:ex,config:cfg});const n=look===3?63:126,ranked=assets.map(s=>{const x=a[s].filter(p=>p.date<=um.asOf);return x.length>n?{s,r:x.at(-1)!.close/x.at(-(n+1))!.close-1}:null}).filter(Boolean) as {s:string;r:number}[];ranked.sort((x,y)=>y.r-x.r||x.s.localeCompare(y.s));m.set(ex,{risk:sg.marketRiskOn,s:!sg.marketRiskOn&&ranked[0]?.r>0?ranked[0].s:null,signalDate:um.asOf,ranked});}return m;}
function sleeve(ds:string[],a:Record<string,PricePoint[]>,pl:Map<string,Plan>,exposure:number){const pm=Object.fromEntries(Object.entries(a).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))]));let cash=1,pos:{s:string,sh:number}|null=null,peak=1,risk=true;const z:EquityPoint[]=[],rm=new Map<string,boolean>(),events:any[]=[];for(const d of ds){const p=pl.get(d);if(p){if(pos){const x=pm[pos.s]?.get(d)?.open;if(x){cash+=pos.sh*x*(1-C);events.push({date:d,type:'SELL',symbol:pos.s,price:x});}pos=null;}risk=p.risk;if(!risk&&p.s){const x=pm[p.s]?.get(d)?.open;if(x){const amt=cash*exposure;cash-=amt;pos={s:p.s,sh:amt*(1-C)/x};events.push({date:d,type:'BUY',symbol:p.s,price:x,signalDate:p.signalDate});}}}rm.set(d,risk);let e=cash;if(pos){const x=pm[pos.s]?.get(d)?.close;if(x)e+=pos.sh*x;}peak=Math.max(peak,e);z.push({date:d,equity:e,drawdown:e/peak-1});}return{z,risk:rm,events};}
function combine(c:EquityPoint[],s:EquityPoint[],risk:Map<string,boolean>){const sm=new Map(s.map(x=>[x.date,x.equity]));let e=1,peak=1,pc=c[0]?.equity??1,ps=sm.get(c[0]?.date)??1,prevRisk=risk.get(c[0]?.date)??true;const z:EquityPoint[]=[];for(let i=0;i<c.length;i++){const d=c[i].date,sv=sm.get(d);if(sv==null)continue;const rc=i?c[i].equity/pc-1:0,rs=i?sv/ps-1:0,cur=risk.get(d)??prevRisk;pc=c[i].equity;ps=sv;const f=i?(cur===prevRisk?1+(cur?rc:rs):(1+rc)*(1+rs)):1;e*=f;prevRisk=cur;peak=Math.max(peak,e);z.push({date:d,equity:e,drawdown:e/peak-1});}return z;}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(!x.length)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}));}
function runVariant(h:Record<string,PricePoint[]>,u:UniverseMonth[],a:Record<string,PricePoint[]>,c:EquityPoint[],assets:string[],look:number,expo:number){const q=sleeve(c.map(x=>x.date),a,plan(h,u,a,assets,look),expo),x=combine(c,q.z,q.risk);return{curve:x,stats:performanceStats(x),events:q.events};}
async function main(){const mk=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8')) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8')) as {history:UniverseMonth[]},u=[...uf.history].sort((x,y)=>x.asOf.localeCompare(y.asOf)),a:Record<string,PricePoint[]>={};for(const s of ALL)a[s]=await yh(s);const c=core(mk.histories,u);const base=runVariant(mk.histories,u,a,c,ALL,3,1);const exposure=[.5,1].map(expo=>({expo,...runVariant(mk.histories,u,a,c,ALL,3,expo).stats}));const leaveOneOut=ALL.map(drop=>{const r=runVariant(mk.histories,u,a,c,ALL.filter(x=>x!==drop),3,1);return{drop,...r.stats};});const lookbacks=[3,6].map(look=>({look,...runVariant(mk.histories,u,a,c,ALL,look,1).stats}));const splits=[{tr:'2021-12-31',y:2022},{tr:'2022-12-31',y:2023},{tr:'2023-12-31',y:2024},{tr:'2024-12-31',y:2025},{tr:'2025-12-31',y:2026}];const curves=new Map<number,EquityPoint[]>([3,6].map(k=>[k,runVariant(mk.histories,u,a,c,ALL,k,1).curve]));const anchored=splits.map(s=>{const scored=[3,6].map(k=>({k,train:performanceStats(sl(curves.get(k)!,'2020-01-01',s.tr))})).sort((x,y)=>(y.train.calmar??-99)-(x.train.calmar??-99));const k=scored[0].k,end=s.y===2026?'2026-08-25':`${s.y}-12-31`;return{trainThrough:s.tr,oosYear:s.y,selectedLookback:k,oos:performanceStats(sl(curves.get(k)!,`${s.y}-01-01`,end)),core:performanceStats(sl(c,`${s.y}-01-01`,end)),training:scored};});const byAsset=Object.fromEntries(ALL.map(s=>[s,0]));for(const e of base.events)if(e.type==='BUY')byAsset[e.symbol]=(byAsset[e.symbol]??0)+1;const output={generatedAt:new Date().toISOString(),validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,pit:true,nextOpen:true,cost:C,warning:'Historical robustness gate; 3M/6M were predeclared before this gate. No new lookback optimization.'},core:performanceStats(c),base3M:base.stats,exposure,lookbacks,leaveOneOut,anchored,macroBuyCounts:byAsset,annual:[2020,2021,2022,2023,2024,2025,2026].map(y=>({y,candidate:performanceStats(sl(base.curve,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`)),core:performanceStats(sl(c,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))}))};const d=path.join(process.cwd(),'data/research/riskoff-macro-robustness');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});