import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,PositionState,PricePoint,UniverseMonth,StrategyConfig} from '../src/lib/types';

const ASSETS=['GLD','IEF','UUP','DBC']; const COST=.001, TAX=.20315;
const cfg:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,oneMonth:0,threeMonth:.25,sixMonth:.75},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.7}};
type Ledger={gain:Record<string,number>;loss:Record<string,number>;taxes:number;sales:number;turnover:number};
async function yahoo(s:string,start='2007-01-01'){const p1=Math.floor(Date.parse(start+'T00:00:00Z')/1000),p2=Math.floor(Date.parse('2026-09-01T00:00:00Z')/1000);const r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${s}?period1=${p1}&period2=${p2}&interval=1d&events=div%2Csplits&includeAdjustedClose=true`,{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)throw Error(`${s}:${r.status}`);const j:any=await r.json(),x=j.chart.result?.[0],q=x?.indicators?.quote?.[0],ad=x?.indicators?.adjclose?.[0]?.adjclose??[];const out:PricePoint[]=[];for(let i=0;i<(x?.timestamp?.length??0);i++){if(q.open[i]==null||q.close[i]==null||ad[i]==null)continue;const k=ad[i]/q.close[i];out.push({date:new Date(x.timestamp[i]*1000).toISOString().slice(0,10),open:q.open[i]*k,close:ad[i]});}return out;}
function sale(l:Ledger,proceeds:number,basis:number,d:string){const pnl=proceeds-basis,y=d.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++;l.turnover+=proceeds;}
function taxCurve(c:EquityPoint[],l:Ledger){const ys=[...new Set(c.map(p=>p.date.slice(0,4)))],ty:Record<string,number>={};let carry:{y:number,a:number}[]=[];for(const s of ys){const y=+s;carry=carry.filter(x=>y-x.y<=3);let n=(l.gain[s]??0)-(l.loss[s]??0);if(n>0){for(const x of carry){const u=Math.min(n,x.a);n-=u;x.a-=u;if(n<=0)break}carry=carry.filter(x=>x.a>1e-12);ty[s]=n*TAX}else if(n<0)carry.push({y,a:-n})}l.taxes=Object.values(ty).reduce((a,b)=>a+b,0);let e=c[0]?.equity??1,prev=e,peak=e;return c.map((p,i)=>{if(i)e*=p.equity/prev;prev=p.equity;const n=c[i+1],y=p.date.slice(0,4);if((!n||n.date.slice(0,4)!==y)&&(ty[y]??0)>0)e=Math.max(0,e-(ty[y]??0)*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);return{date:p.date,equity:e,drawdown:e/peak-1}})}
function core(hist:Record<string,PricePoint[]>,u:UniverseMonth[]){const q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(p=>p.date),di=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg);const curve:EquityPoint[]=[],ledger:Ledger={gain:{},loss:{},taxes:0,sales:0,turnover:0};for(let i=0;i<ds.length;i++){const d=ds[i];if(d<cfg.backtestStart)continue;const nx=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?buildMonthlySignal({universe:uu,histories:hist,qqq:q,nextSessionDate:nx,config:cfg}):null;if(sg&&sg.selectedSymbols.length===2)sg.targetWeights=sg.zGap!==null&&sg.zGap>=.25?[.7,.3]:[.6,.4];const sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)])),before=structuredClone(st);st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(di.get(d)??i)+1),monthlySignal:sg,nextSessionDate:nx},cfg);if(before.currentPositions.length&&((before.nextAction.type==='SELL_ALL_NEXT_OPEN'||before.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN')&&before.nextAction.executionDate===d)){for(const p of before.currentPositions){const px=prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice;const proceeds=p.shares*px*(1-COST),basis=p.shares*p.entryPrice;sale(ledger,proceeds,basis,d)}}curve.push({date:d,equity:st.currentEquity,drawdown:st.drawdown});}return{curve,ledger};}
function plans(hist:Record<string,PricePoint[]>,u:UniverseMonth[],a:Record<string,PricePoint[]>){const q=[...hist.QQQ].sort((x,y)=>x.date.localeCompare(y.date)),m=new Map<string,{risk:boolean,s:string|null}>();for(const um of u){if(um.asOf<cfg.backtestStart)continue;const ex=nextUsTradingSession(um.asOf),sg=buildMonthlySignal({universe:um,histories:hist,qqq:q,nextSessionDate:ex,config:cfg});const rows=ASSETS.map(s=>{const x=a[s].filter(p=>p.date<=um.asOf);return x.length>63?{s,r:x.at(-1)!.close/x.at(-64)!.close-1}:null}).filter(Boolean) as {s:string,r:number}[];rows.sort((x,y)=>y.r-x.r||x.s.localeCompare(y.s));m.set(ex,{risk:sg.marketRiskOn,s:!sg.marketRiskOn&&rows[0]?.r>0?rows[0].s:null});}return m;}
function macroSleeve(ds:string[],a:Record<string,PricePoint[]>,pl:Map<string,{risk:boolean,s:string|null}>){const pm=Object.fromEntries(Object.entries(a).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))]));let cash=1,pos:{s:string,sh:number,entry:number}|null=null,risk=true,peak=1;const c:EquityPoint[]=[],rm=new Map<string,boolean>(),l:Ledger={gain:{},loss:{},taxes:0,sales:0,turnover:0};for(const d of ds){const p=pl.get(d);if(p){if(pos){const px=pm[pos.s]?.get(d)?.open;if(px){const proceeds=pos.sh*px*(1-COST);sale(l,proceeds,pos.sh*pos.entry,d);cash=proceeds}pos=null;}risk=p.risk;if(!risk&&p.s){const px=pm[p.s]?.get(d)?.open;if(px){const invest=cash;pos={s:p.s,sh:invest*(1-COST)/px,entry:px};cash=0;}}}rm.set(d,risk);let e=cash;if(pos){const px=pm[pos.s]?.get(d)?.close;if(px)e=pos.sh*px;}peak=Math.max(peak,e);c.push({date:d,equity:e,drawdown:e/peak-1});}return{curve:c,risk:rm,ledger:l};}
function combine(coreC:EquityPoint[],macroC:EquityPoint[],risk:Map<string,boolean>){const mm=new Map(macroC.map(x=>[x.date,x.equity]));let e=1,peak=1,pc=coreC[0]?.equity??1,pm=mm.get(coreC[0]?.date)??1,pr=risk.get(coreC[0]?.date)??true;const z:EquityPoint[]=[];for(let i=0;i<coreC.length;i++){const d=coreC[i].date,mv=mm.get(d);if(mv==null)continue;const rc=i?coreC[i].equity/pc-1:0,mr=i?mv/pm-1:0,cr=risk.get(d)??pr;pc=coreC[i].equity;pm=mv;let f=1;if(i)f=cr===pr?1+(cr?rc:mr):(1+rc)*(1+mr);e*=f;pr=cr;peak=Math.max(peak,e);z.push({date:d,equity:e,drawdown:e/peak-1});}return z;}
function mergeLedger(a:Ledger,b:Ledger):Ledger{const l:Ledger={gain:{},loss:{},taxes:0,sales:a.sales+b.sales,turnover:a.turnover+b.turnover};for(const y of new Set([...Object.keys(a.gain),...Object.keys(b.gain),...Object.keys(a.loss),...Object.keys(b.loss)])){l.gain[y]=(a.gain[y]??0)+(b.gain[y]??0);l.loss[y]=(a.loss[y]??0)+(b.loss[y]??0)}return l;}
function slice(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function stress(coreC:EquityPoint[],macroC:EquityPoint[],risk:Map<string,boolean>,ret:number){const mm=new Map(macroC.map(x=>[x.date,x.equity]));let e=1,peak=1,pc=coreC[0]?.equity??1,pm=mm.get(coreC[0]?.date)??1,pr=risk.get(coreC[0]?.date)??true;const z:EquityPoint[]=[];for(let i=0;i<coreC.length;i++){const d=coreC[i].date,mv=mm.get(d);if(mv==null)continue;let rc=i?coreC[i].equity/pc-1:0,mr=i?mv/pm-1:0;pc=coreC[i].equity;pm=mv;if(mr>0)mr*=ret;const cr=risk.get(d)??pr;let f=1;if(i)f=cr===pr?1+(cr?rc:mr):(1+rc)*(1+mr);e*=f;pr=cr;peak=Math.max(peak,e);z.push({date:d,equity:e,drawdown:e/peak-1});}return z;}
function monthEnd(ps:PricePoint[]){const m=new Map<string,PricePoint>();for(const p of ps)m.set(p.date.slice(0,7),p);return [...m.values()].sort((a,b)=>a.date.localeCompare(b.date));}
function longHistory(q:PricePoint[],a:Record<string,PricePoint[]>,look:number){const qm=monthEnd(q).filter(x=>x.date>='2008-01-01'),maps=Object.fromEntries(Object.entries(a).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))]));let cash=1,pos:{s:string,sh:number}|null=null,peak=1;const curve:EquityPoint[]=[];for(let i=0;i<qm.length;i++){const sig=qm[i];if(i<9)continue;const ma=qm.slice(i-9,i+1).reduce((z,x)=>z+x.close,0)/10,risk=sig.close>ma,exec=nextUsTradingSession(sig.date);if(pos){const px=maps[pos.s]?.get(exec)?.open;if(px)cash=pos.sh*px*(1-COST);pos=null;}if(!risk){const n=look===3?63:126,rows=ASSETS.map(s=>{const x=a[s].filter(p=>p.date<=sig.date);return x.length>n?{s,r:x.at(-1)!.close/x.at(-(n+1))!.close-1}:null}).filter(Boolean) as {s:string,r:number}[];rows.sort((x,y)=>y.r-x.r);if(rows[0]?.r>0){const px=maps[rows[0].s]?.get(exec)?.open;if(px){pos={s:rows[0].s,sh:cash*(1-COST)/px};cash=0;}}}const nextSig=qm[i+1]?.date??'2026-08-25';const periodDates=q.filter(x=>x.date>=exec&&x.date<=nextSig).map(x=>x.date);for(const d of periodDates){let e=cash;if(pos){const px=maps[pos.s]?.get(d)?.close;if(px)e=pos.sh*px;}peak=Math.max(peak,e);curve.push({date:d,equity:e,drawdown:e/peak-1});}}
return curve;}
async function main(){const mk=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8')) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8')) as {history:UniverseMonth[]},u=[...uf.history].sort((x,y)=>x.asOf.localeCompare(y.asOf)),a:Record<string,PricePoint[]>={};for(const s of ASSETS)a[s]=await yahoo(s);const coreR=core(mk.histories,u),macro=macroSleeve(coreR.curve.map(x=>x.date),a,plans(mk.histories,u,a)),combined=combine(coreR.curve,macro.curve,macro.risk),ledger=mergeLedger(coreR.ledger,macro.ledger),after=taxCurve(combined,ledger),qLong=await yahoo('QQQ'),long3=longHistory(qLong,a,3),long6=longHistory(qLong,a,6),periods=[['2008-01-01','2012-12-31'],['2013-01-01','2019-12-31'],['2020-01-01','2026-08-25']];const out={generatedAt:new Date().toISOString(),validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,pit:true,nextOpen:true,cost:C,tax:TAX,warning:'Tax is annual realized-P&L approximation with 3y loss carry. Long-history macro test is structurally out-of-Core-sample but concept was selected after seeing recent data.'},core:{gross:performanceStats(coreR.curve)},macro3:{gross:performanceStats(combined),afterTax:performanceStats(after),taxPaidApprox:ledger.taxes,sales:ledger.sales,turnover:ledger.turnover},annualTax:[2022,2023,2024,2025,2026].map(y=>({y,afterTax:performanceStats(slice(after,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`)),gross:performanceStats(slice(combined,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))})),macroEdgeStress:[1,.75,.5,.25,0].map(r=>({retention:r,...performanceStats(stress(coreR.curve,macro.curve,macro.risk,r))})),longHistory:{look3:periods.map(([s,e])=>({period:`${s}_${e}`,...performanceStats(slice(long3,s,e))})),look6:periods.map(([s,e])=>({period:`${s}_${e}`,...performanceStats(slice(long6,s,e))})),full3:performanceStats(long3),full6:performanceStats(long6)}};const d=path.join(process.cwd(),'data/research/riskoff-macro-final-gate');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});