import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY as P} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import {performanceStats} from '../src/lib/backtest';
import type {EquityPoint,PricePoint,StrategyConfig,UniverseMonth} from '../src/lib/types';

type Fact={filed:string;period:string;quarter:string;revenue:number;operatingIncome:number|null;adsh:string;source_file:string;derivedQ4:boolean};
type FactsFile={provenance:any;facts:Record<string,Fact[]>};
type V='W70'|'W70_SALES25';
const C:StrategyConfig={...P,strategyId:'momentum-production-sales-accel-w70',allocation:{...P.allocation,baseTop1Weight:.7,concentratedTop1Weight:.7,maxTop1Weight:.7}} as StrategyConfig;
const ALIAS:Record<string,string>={GOOGL:'GOOG'};
const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const sd=(a:number[])=>{if(a.length<2)return 0;const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))};
const z=(x:number,m:number,s:number)=>s>1e-12?(x-m)/s:0;
const dayDiff=(a:string,b:string)=>Math.round((Date.parse(a+'T00:00:00Z')-Date.parse(b+'T00:00:00Z'))/86400000);
function yoyMatch(rows:Fact[],i:number){const cur=rows[i];let best=-1,err=1e9;for(let j=0;j<i;j++){const d=dayDiff(cur.period,rows[j].period);if(d>=320&&d<=410){const e=Math.abs(d-365);if(e<err){err=e;best=j}}}return best;}
function salesAccel(ff:FactsFile,symbol:string,date:string){const t=ALIAS[symbol]??symbol,src=ff.facts[t]??[],avail=src.filter(r=>r.filed<=date).sort((a,b)=>a.period.localeCompare(b.period)||a.filed.localeCompare(b.filed));const by=new Map<string,Fact>();for(const r of avail)by.set(r.period,r);const rows=[...by.values()].sort((a,b)=>a.period.localeCompare(b.period));if(rows.length<6)return null;const i=rows.length-1,j=i-1,y0=yoyMatch(rows,i),y1=yoyMatch(rows,j);if(y0<0||y1<0||!rows[y0].revenue||!rows[y1].revenue)return null;const g0=rows[i].revenue/rows[y0].revenue-1,g1=rows[j].revenue/rows[y1].revenue-1;const v=g0-g1;return Number.isFinite(v)?v:null;}
function baseSignal(u:UniverseMonth,h:Record<string,PricePoint[]>,q:PricePoint[],next:string){const s:any=buildMonthlySignal({universe:u,histories:h,qqq:q,nextSessionDate:next,config:C});if(s.selectedSymbols.length===2){s.targetWeights=[.7,.3];s.allocationMode='70/30'}return s;}
function rerank(u:UniverseMonth,h:Record<string,PricePoint[]>,q:PricePoint[],next:string,v:V,ff:FactsFile){const b:any=baseSignal(u,h,q,next);if(v==='W70'||!b.marketRiskOn)return b;const top10=b.candidates.filter((c:any)=>c.eligible&&c.score!=null).slice(0,10);if(top10.length<2)return b;const rows=top10.map((c:any)=>({c,f:salesAccel(ff,c.symbol,u.asOf)}));const fv=rows.map(r=>r.f).filter((x):x is number=>x!=null&&Number.isFinite(x));if(fv.length<4)return b;const sm=mean(top10.map((c:any)=>c.score)),ss=sd(top10.map((c:any)=>c.score)),fm=mean(fv),fs=sd(fv);const ranked=rows.map(r=>({c:r.c,f:r.f,combo:z(r.c.score,sm,ss)+.25*(r.f==null?0:z(r.f,fm,fs))})).sort((a,b)=>b.combo-a.combo||a.c.symbol.localeCompare(b.c.symbol));const sel=ranked.slice(0,2);return{...b,selectedSymbols:sel.map(x=>x.c.symbol),targetWeights:[.7,.3],allocationMode:'70/30',researchFactor:{name:'SALES_ACCEL',lambda:.25,coverage:fv.length/Math.max(1,top10.length)}};}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],v:V,ff:FactsFile){const q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date),di=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(C);const curve:EquityPoint[]=[],changes:any[]=[];for(let i=0;i<dates.length;i++){const date=dates[i];if(date<C.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),uu=um.get(date),base=uu?baseSignal(uu,h,q,next):null,sg=uu?rerank(uu,h,q,next,v,ff):null;if(uu&&v!=='W70'&&base&&sg&&base.selectedSymbols.join(',')!==sg.selectedSymbols.join(','))changes.push({date,base:base.selectedSymbols,factor:sg.selectedSymbols});const sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));st=transitionDay(st,{date,prices,qqqHistoryThroughClose:q.slice(0,(di.get(date)??i)+1),monthlySignal:sg,nextSessionDate:next},C);curve.push({date,equity:st.currentEquity,drawdown:st.drawdown});}return{curve,changes};}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const prev=[...c].reverse().find(p=>p.date<s),z0=prev?[prev,...x]:x,b=z0[0].equity;return z0.map(p=>({...p,equity:p.equity/b}));}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},ff=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/research/openfundex-fundamental-diagnostic/facts.json'),'utf8'))as FactsFile,u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),vs:V[]=['W70','W70_SALES25'],runs=Object.fromEntries(vs.map(v=>[v,sim(market.histories,u,v,ff)]))as Record<V,ReturnType<typeof sim>>;const years=[2020,2021,2022,2023,2024,2025,2026],annual=years.map(y=>({year:y,...Object.fromEntries(vs.map(v=>[v,performanceStats(sl(runs[v].curve,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))]))}));const periods=[['early2020_2023','2020-01-01','2023-12-31'],['late2024_2026','2024-01-01','2026-08-25']] as const;const out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,noLeverage:true,pit:true,nextOpen:true,freeDataOnly:true,factor:'SALES_ACCEL',lambda:.25,missingFactor:'neutral z=0; missingness is not a signal',architecture:'Production 0/20/80 Momentum Top10 -> SALES_ACCEL rerank -> Top2 W70; Production stop/circuit/recovery unchanged'},full:vs.map(v=>({variant:v,...performanceStats(runs[v].curve),changedMonths:runs[v].changes.length})),periods:Object.fromEntries(periods.map(([id,s,e])=>[id,Object.fromEntries(vs.map(v=>[v,performanceStats(sl(runs[v].curve,s,e))]))])),annual,changes:runs.W70_SALES25.changes};const d=path.join(process.cwd(),'data/research/sec-sales-accel-w70');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({...out,changes:out.changes.slice(0,20),changeCount:out.changes.length},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
