import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY as BASE} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import {performanceStats} from '../src/lib/backtest';
import type {EquityPoint,PricePoint,UniverseMonth} from '../src/lib/types';

const CONFIG:any={...BASE,strategyId:'momentum-sec-top10-rerank',momentum:{...BASE.momentum,oneMonth:0,threeMonth:.25,sixMonth:.75},allocation:{...BASE.allocation,baseTop1Weight:.60,concentratedTop1Weight:.70,concentrationZGap:.25,maxTop1Weight:.70}};
const UA='momentum-console-research/1.0 kensuke5704@users.noreply.github.com';
type F='BASE'|'SALES25'|'MARGIN25';
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
const sd=(x:number[])=>{if(x.length<2)return 0;const m=mean(x);return Math.sqrt(mean(x.map(v=>(v-m)**2)))};
const z=(v:number,m:number,s:number)=>s>1e-12?(v-m)/s:0;
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function getJson(url:string,retries=6){let last:any;for(let i=0;i<retries;i++){try{const r=await fetch(url,{headers:{'User-Agent':UA,'Accept':'application/json','Accept-Encoding':'gzip, deflate'}});if(r.ok)return await r.json();last=new Error(`${r.status} ${r.statusText}`);if(r.status===403||r.status===429)await sleep(2500*(i+1));else await sleep(700*(i+1));}catch(e){last=e;await sleep(1000*(i+1));}}throw last;}
type Obs={frame:string;filed:string;val:number;form:string};type Series={rev:Obs[];op:Obs[]};
const REV=['RevenueFromContractWithCustomerExcludingAssessedTax','Revenues','SalesRevenueNet','SalesRevenueGoodsNet','SalesRevenueServicesNet'];
function obs(cf:any,tags:string[]):Obs[]{const us=cf?.facts?.['us-gaap']??{};for(const t of tags){const a=us?.[t]?.units?.USD;if(!Array.isArray(a))continue;const r=a.filter((x:any)=>/^CY\d{4}Q[1-4]$/.test(x.frame??'')&&['10-Q','10-K','20-F','40-F'].includes(x.form)&&Number.isFinite(x.val)).map((x:any)=>({frame:x.frame,filed:x.filed,val:Number(x.val),form:x.form}));if(r.length>=6)return r;}return[];}
function up(rows:Obs[],date:string){const m=new Map<string,Obs>();for(const r of rows.filter(x=>x.filed<=date).sort((a,b)=>a.filed.localeCompare(b.filed)))m.set(r.frame,r);return m;}
function qi(f:string){const m=/^CY(\d{4})Q([1-4])$/.exec(f);return m?+m[1]*4+(+m[2]-1):null}function ff(i:number){return `CY${Math.floor(i/4)}Q${i%4+1}`}
function metric(s:Series,date:string){const r=up(s.rev,date),o=up(s.op,date),latest=[...r.keys()].sort((a,b)=>(qi(b)??0)-(qi(a)??0))[0];if(!latest)return null;const i=qi(latest);if(i===null)return null;const r0=r.get(latest)?.val,r4=r.get(ff(i-4))?.val,r1=r.get(ff(i-1))?.val,r5=r.get(ff(i-5))?.val;const y0=r0!=null&&r4!=null&&r4!==0?r0/r4-1:null,y1=r1!=null&&r5!=null&&r5!==0?r1/r5-1:null,sales=y0!=null&&y1!=null?y0-y1:null;let margin:null|number=null;const common=[...r.keys()].filter(f=>o.has(f)).sort((a,b)=>(qi(b)??0)-(qi(a)??0))[0];if(common){const j=qi(common)!;const rc=r.get(common)?.val,oc=o.get(common)?.val,ry=r.get(ff(j-4))?.val,oy=o.get(ff(j-4))?.val;if(rc!=null&&oc!=null&&ry!=null&&oy!=null&&rc!==0&&ry!==0)margin=oc/rc-oy/ry;}return{sales,margin};}
async function load(symbols:string[]){const ticks=await getJson('https://www.sec.gov/files/company_tickers.json');const tm=new Map<string,string>();for(const v of Object.values(ticks) as any[])tm.set(String(v.ticker).toUpperCase(),String(v.cik_str).padStart(10,'0'));const out=new Map<string,Series>(),fail:any[]=[];for(let i=0;i<symbols.length;i++){const sym=symbols[i],cik=tm.get(sym.toUpperCase());if(!cik){fail.push({sym,reason:'no-cik'});continue;}try{const cf=await getJson(`https://data.sec.gov/api/xbrl/companyfacts/CIK${cik}.json`);out.set(sym,{rev:obs(cf,REV),op:obs(cf,['OperatingIncomeLoss'])});console.log('SEC',i+1,'/',symbols.length,sym);}catch(e:any){fail.push({sym,reason:String(e?.message??e)});}await sleep(450);}return{out,fail};}
function baseSignal(u:UniverseMonth,h:Record<string,PricePoint[]>,q:PricePoint[],next:string){const s:any=buildMonthlySignal({universe:u,histories:h,qqq:q,nextSessionDate:next,config:CONFIG});if(s.selectedSymbols.length===2){const w=s.zGap!==null&&s.zGap>=.25?.7:.6;s.targetWeights=[w,1-w];}return s;}
function rerank(u:UniverseMonth,h:Record<string,PricePoint[]>,q:PricePoint[],next:string,f:F,series:Map<string,Series>){const b:any=baseSignal(u,h,q,next);if(f==='BASE'||!b.marketRiskOn)return b;const top10=b.candidates.filter((c:any)=>c.eligible&&c.score!=null).slice(0,10);const rows=top10.map((c:any)=>({c,m:series.get(c.symbol)?metric(series.get(c.symbol)!,u.asOf):null}));const vals=rows.map(x=>f==='SALES25'?x.m?.sales:x.m?.margin).filter((x):x is number=>x!=null&&Number.isFinite(x));if(vals.length<4)return b;const sm=mean(top10.map((x:any)=>x.score)),ss=sd(top10.map((x:any)=>x.score)),fm=mean(vals),fs=sd(vals);const ranked=rows.map(x=>{const fv=f==='SALES25'?x.m?.sales:x.m?.margin;return{c:x.c,combo:fv==null?-Infinity:z(x.c.score,sm,ss)+.25*z(fv,fm,fs)}}).sort((a,b)=>b.combo-a.combo||a.c.symbol.localeCompare(b.c.symbol));const sel=ranked.filter(x=>Number.isFinite(x.combo)).slice(0,2);if(sel.length<2)return b;const disp=sd(ranked.filter(x=>Number.isFinite(x.combo)).map(x=>x.combo)),zg=disp>0?(sel[0].combo-sel[1].combo)/disp:0,w=zg>=.25?.7:.6;return{...b,selectedSymbols:sel.map(x=>x.c.symbol),targetWeights:[w,1-w],zGap:zg,allocationMode:w===.7?'70/30':'60/40'};}
function sim(h:Record<string,PricePoint[]>,u:UniverseMonth[],f:F,series:Map<string,Series>){const q=[...h.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),ds=q.map(x=>x.date),ix=new Map(ds.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(h).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(CONFIG);const c:EquityPoint[]=[];for(let i=0;i<ds.length;i++){const d=ds[i];if(d<CONFIG.backtestStart)continue;const n=ds[i+1]??nextUsTradingSession(d),uu=um.get(d),sg=uu?rerank(uu,h,q,n,f,series):null,sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sg?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(d)]));st=transitionDay(st,{date:d,prices,qqqHistoryThroughClose:q.slice(0,(ix.get(d)??i)+1),monthlySignal:sg,nextSessionDate:n},CONFIG);c.push({date:d,equity:st.currentEquity,drawdown:st.drawdown});}return c;}
function sl(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}));}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].filter(x=>x.asOf>=CONFIG.backtestStart).sort((a,b)=>a.asOf.localeCompare(b.asOf)),q=market.histories.QQQ;const union=new Set<string>();for(const x of u){const s:any=baseSignal(x,market.histories,q,nextUsTradingSession(x.asOf));for(const c of s.candidates.filter((c:any)=>c.eligible&&c.score!=null).slice(0,10))union.add(c.symbol);}const symbols=[...union].sort();console.log('PIT Top10 union',symbols.length);const loaded=await load(symbols);console.log('loaded',loaded.out.size,'failed',loaded.fail.length);const fs:F[]=['BASE','SALES25','MARGIN25'],cur=Object.fromEntries(fs.map(f=>[f,sim(market.histories,u,f,loaded.out)]))as Record<F,EquityPoint[]>;const full=fs.map(f=>({variant:f,...performanceStats(cur[f])})),splits=[{tr:'2021-12-31',y:2022},{tr:'2022-12-31',y:2023},{tr:'2023-12-31',y:2024},{tr:'2024-12-31',y:2025},{tr:'2025-12-31',y:2026}],wf=splits.map(s=>{const rank=fs.map(f=>({f,stats:performanceStats(sl(cur[f],'2020-01-01',s.tr))})).sort((a,b)=>(b.stats.calmar??-99)-(a.stats.calmar??-99)),pick=rank[0].f,e=s.y===2026?'2026-08-25':`${s.y}-12-31`;return{trainThrough:s.tr,oosYear:s.y,pick,oos:performanceStats(sl(cur[pick],`${s.y}-01-01`,e)),base:performanceStats(sl(cur.BASE,`${s.y}-01-01`,e)),train:rank};});const out={generatedAt:new Date().toISOString(),validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,pit:true,nextOpen:true,secPIT:'Companyfacts observations filtered filed <= signal close',warning:'Top10 second-stage reranker only. Current SEC companyfacts can contain later restatements as separate filed observations; only observations whose filed date is already observable are admitted. Taxonomy/frame coverage varies.'},source:{pitTop10Union:symbols.length,loaded:loaded.out.size,failures:loaded.fail},full,wf};const d=path.join(process.cwd(),'data/research/sec-top10-rerank');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));}main().catch(e=>{console.error(e);process.exit(1)});