import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { buildMonthlySignal, monthlyCloses } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { performanceStats } from "../src/lib/backtest";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import type { EquityPoint, MonthlySignal, PricePoint, UniverseMonth, StrategyConfig } from "../src/lib/types";

type V={id:string,blend:number};
const VARS:V[]=[{id:"SKIP1_FULL",blend:1},{id:"SKIP1_HALF",blend:.5}];
const cfg:StrategyConfig={...PRODUCTION_STRATEGY,momentum:{...PRODUCTION_STRATEGY.momentum,threeMonth:.25,sixMonth:.75},allocation:{...PRODUCTION_STRATEGY.allocation,baseTop1Weight:.6,concentratedTop1Weight:.7}};
function skipScore(ps:PricePoint[],date:string){const m=monthlyCloses(ps).filter(p=>p.date<=date);if(m.length<7)return null;const p1=m.at(-2)!.close,p3=m.at(-4)!.close,p6=m.at(-7)!.close;return .25*(p1/p3-1)+.75*(p1/p6-1);}
function std(xs:number[]){if(!xs.length)return 0;const m=xs.reduce((a,b)=>a+b,0)/xs.length;return Math.sqrt(xs.reduce((a,b)=>a+(b-m)**2,0)/xs.length);}
function rerank(sig:MonthlySignal,hist:Record<string,PricePoint[]>,v:V){if(!sig.marketRiskOn)return sig;const e=sig.candidates.filter(c=>c.eligible&&c.score!==null).map(c=>{const sk=skipScore(hist[c.symbol]??[],sig.signalDate);return sk===null?null:{c,score:(1-v.blend)*c.score!+v.blend*sk};}).filter(Boolean) as {c:any,score:number}[];if(e.length<2)return {...sig,selectedSymbols:[],targetWeights:[],allocationMode:"CASH" as const,zGap:null};e.sort((a,b)=>b.score-a.score||a.c.symbol.localeCompare(b.c.symbol));const s=e.slice(0,2),disp=std(sig.candidates.filter(c=>c.eligible&&c.score!==null).map(c=>c.score!)),zg=disp>0?(s[0].c.score-s[1].c.score)/disp:0,top=zg>=.25?.7:.6;return {...sig,selectedSymbols:s.map(x=>x.c.symbol),targetWeights:[top,1-top],zGap:zg,allocationMode:top===.7?"70/30" as const:"50/50" as const};}
function sim(hist:Record<string,PricePoint[]>,u:UniverseMonth[],v:V|null){const q=[...(hist.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(u.map(x=>[x.asOf,x]));let st=initialEngineState(cfg);const curve:EquityPoint[]=[];for(let i=0;i<dates.length;i++){const date=dates[i];if(date<cfg.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),uu=um.get(date);let sig=uu?buildMonthlySignal({universe:uu,histories:hist,qqq:q,nextSessionDate:next,config:cfg}):null;if(sig){if(v)sig=rerank(sig,hist,v);else if(sig.selectedSymbols.length===2)sig.targetWeights=sig.zGap!==null&&sig.zGap>=.25?[.7,.3]:[.6,.4];}const sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));st=transitionDay(st,{date,prices,qqqHistoryThroughClose:q.slice(0,(idx.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},cfg);curve.push({date,equity:st.currentEquity,drawdown:st.drawdown});}return curve;}
function slice(c:EquityPoint[],y:number){const x=c.filter(p=>p.date>=`${y}-01-01`&&p.date<=(y===2026?"2026-08-25":`${y}-12-31`));if(!x.length)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}));}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>};const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]};const u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),base=sim(market.histories,u,null),rows=[] as any[];for(const v of VARS){const c=sim(market.histories,u,v);rows.push({variant:v,full:performanceStats(c),annual:[2020,2021,2022,2023,2024,2025,2026].map(y=>({y,candidate:performanceStats(slice(c,y)),baseline:performanceStats(slice(base,y))}))});}const output={generatedAt:new Date().toISOString(),validity:{freeDataOnly:true,noLeverage:true,trueOOS:false,warning:"Two predeclared skip-month variants; current W25 eligibility/gate/risk controls unchanged."},baseline:performanceStats(base),rows};const dir=path.join(process.cwd(),"data/research/skip-month-momentum-screen");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});