import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { initialEngineState, transitionDay, type EngineState } from "../src/lib/strategy/state-machine";
import type { MonthlySignal, PricePoint, UniverseMonth } from "../src/lib/types";

type MarketDataFile={histories:Record<string,PricePoint[]>}; type UniverseFile={history:UniverseMonth[]};
type Rng=()=>number; type MVal=number|null;
type Result={cagr:number;dd:number;wealth:number;exits:number;stops:number;circuits:number;investedMonths:number;months:number;rejectedBlocks:number};
const cfg=PRODUCTION_STRATEGY, PATHS=Number(process.env.STRUCTURAL_MC_PATHS??500), YEARS=Number(process.env.STRUCTURAL_MC_YEARS??5), BLOCK=20, WARM=252, H=YEARS*252, SEED=20260825;
function rng32(seed:number):Rng{let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;}}
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0; const sd=(x:number[])=>{const m=avg(x);return x.length?Math.sqrt(avg(x.map(v=>(v-m)**2))):0};
function pct(a:number[],p:number){a=[...a].sort((x,y)=>x-y);const z=(a.length-1)*p,l=Math.floor(z),h=Math.ceil(z),w=z-l;return a[l]*(1-w)+a[h]*w}
function latestU(us:UniverseMonth[],d:string){let out=us[0];for(const u of us){if(u.asOf>d)break;out=u}return out}
function ret(xs:MVal[],n:number){if(xs.length<=n)return null;const a=xs.at(-1),b=xs.at(-(n+1));return a!=null&&b!=null&&a>0&&b>0?a/b-1:null}
function signal(date:string,next:string|null,u:UniverseMonth,monthly:Map<string,MVal[]>):MonthlySignal{
 const q=monthly.get("QQQ")??[], ql=q.at(-1)??null, win=q.slice(-cfg.market.qqqMonthlyMaMonths); const qma=win.length===cfg.market.qqqMonthlyMaMonths&&win.every(x=>x!=null)?avg(win as number[]):null;
 const risk=ql!=null&&qma!=null&&ql>qma,q1=ret(q,1),q3=ret(q,3),q6=ret(q,6),qs=q1==null||q3==null||q6==null?null:.2*q3+.8*q6; const cs:any[]=[];
 for(const m of u.symbols){const x=monthly.get(m.symbol)??[],r1=ret(x,1),r3=ret(x,3),r6=ret(x,6);if(r1==null||r3==null||r6==null||qs==null){cs.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:null,qqqScore:qs,scoreSpread:null,eligible:false,exclusionReason:"INSUFFICIENT_PRICE_HISTORY",rank:null});continue}const s=.2*r3+.8*r6,reason=r1>=.8?"ONE_MONTH_SURGE":s<=qs?"NOT_ABOVE_QQQ":null;cs.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:s,qqqScore:qs,scoreSpread:s-qs,eligible:!reason,exclusionReason:reason,rank:null})}
 const el=cs.filter(x=>x.eligible).sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol));el.forEach((x,i)=>x.rank=i+1);const sel=risk?el.slice(0,2):[],valid=sel.length===2,disp=sd(el.map(x=>x.score)),zg=valid&&disp>0?(sel[0].score-sel[1].score)/disp:valid?0:null,conc=zg!=null&&zg>=.25,w=Math.min(.7,conc?.7:.5);
 return {strategyId:cfg.strategyId,signalMonth:date.slice(0,7),signalDate:date,executionDate:next,marketRiskOn:risk,qqqClose:ql,qqqMonthlyMa:qma,qqqScore:qs,universe:u.symbols.map(x=>x.symbol),candidates:cs,selectedSymbols:valid?sel.map(x=>x.symbol):[],targetWeights:valid?[w,1-w]:[],zGap:zg,allocationMode:!valid?"CASH":conc?"70/30":"50/50"} as MonthlySignal;
}
async function main(){const market=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8")) as MarketDataFile, uf=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8")) as UniverseFile, us=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),hist=market.histories,qqq=hist.QQQ;
 const src=qqq.filter(p=>p.date>=us[0].asOf).map(p=>p.date),targets=src.slice(-(WARM+H)),symbols=[...new Set(["QQQ",...us.flatMap(u=>u.symbols.map(x=>x.symbol))])],maps=new Map(symbols.map(s=>[s,new Map((hist[s]??[]).map(p=>[p.date,p]))]));
 const starts=src.map((_,i)=>i).filter(i=>i>=1&&i+BLOCK<=src.length),r=rng32(SEED),results:Result[]=[];
 function blockOK(start:number,held:string[]){for(let j=0;j<BLOCK;j++){const d=src[start+j],pd=src[start+j-1];for(const s of held){if(!maps.get(s)?.get(d)||!maps.get(s)?.get(pd))return false}}return true}
 for(let path=0;path<PATHS;path++){let state:EngineState=initialEngineState(cfg),syn=new Map<string,number>(symbols.map(s=>[s,100])),monthly=new Map<string,MVal[]>(symbols.map(s=>[s,[]])),qd:PricePoint[]=[],peak=1,maxdd=0,startEq=1,endEq=1,months=0,invM=0,rejected=0,ti=0,currentBlock:number[]=[];
  while(ti<targets.length){if(!currentBlock.length){const held=state.currentPositions.map(p=>p.symbol);let st:number|undefined;for(let tries=0;tries<500;tries++){const c=starts[Math.floor(r()*starts.length)];if(blockOK(c,held)){st=c;break}rejected++}if(st==null)throw new Error("No availability-compatible block");currentBlock=Array.from({length:Math.min(BLOCK,targets.length-ti)},(_,j)=>st!+j)}
   const si=currentBlock.shift()!,td=targets[ti],next=targets[ti+1]??null,sd=src[si],psd=src[si-1],prices:Record<string,PricePoint|undefined>={};
   for(const s of symbols){const cur=maps.get(s)?.get(sd),prev=maps.get(s)?.get(psd);if(!cur||!prev||prev.close<=0||cur.open<=0)continue;const pc=syn.get(s)??100,op=Math.max(.01,pc*(cur.open/prev.close)),cl=Math.max(.01,op*(cur.close/cur.open));syn.set(s,cl);prices[s]={date:td,open:op,high:Math.max(op,cl),low:Math.min(op,cl),close:cl}}
   if(!prices.QQQ)throw new Error("QQQ missing");qd.push(prices.QQQ);const me=next==null||next.slice(0,7)!==td.slice(0,7);let sig:MonthlySignal|null=null;
   if(me){for(const s of symbols)monthly.get(s)!.push(prices[s]?.close??null);const raw=latestU(us,sd),filtered={...raw,symbols:raw.symbols.filter(m=>prices[m.symbol]!=null)};sig=signal(td,next,filtered,monthly)}
   if(ti===WARM){state=initialEngineState(cfg);peak=1;maxdd=0;startEq=1}
   if(ti>=WARM){state=transitionDay(state,{date:td,prices,qqqHistoryThroughClose:qd,monthlySignal:sig,nextSessionDate:next},cfg);if(ti===WARM)startEq=state.currentEquity||1;endEq=state.currentEquity;peak=Math.max(peak,endEq);maxdd=Math.min(maxdd,endEq/peak-1);if(me){months++;if(state.currentPositions.length)invM++}}
   ti++;
  }
  const yrs=(Date.parse(targets.at(-1)!)-Date.parse(targets[WARM]))/(365.25*86400000),wealth=endEq/startEq,cagr=wealth**(1/yrs)-1,ex=state.events.filter(e=>e.type==="EXIT_OPEN");results.push({cagr,dd:maxdd,wealth,exits:ex.length,stops:ex.filter(e=>e.reason.includes("stop")).length,circuits:ex.filter(e=>e.reason.includes("circuit")).length,investedMonths:invM,months,rejectedBlocks:rejected});if((path+1)%100===0)console.log(`completed ${path+1}/${PATHS}`)
 }
 const c=results.map(x=>x.cagr),d=results.map(x=>x.dd),w=results.map(x=>x.wealth);const summary={generatedAt:new Date().toISOString(),strategyId:cfg.strategyId,methodology:{paths:PATHS,years:YEARS,blockTradingDays:BLOCK,warmupTradingDays:WARM,seed:SEED,availability:"No QQQ proxy imputation. Non-available symbols are excluded. New blocks must preserve price availability for currently held names."},distribution:{cagr:{p05:pct(c,.05),p25:pct(c,.25),median:pct(c,.5),p75:pct(c,.75),p95:pct(c,.95)},maxDrawdown:{adverseP05:pct(d,.05),p25:pct(d,.25),median:pct(d,.5),p75:pct(d,.75),p95:pct(d,.95)},finalWealth:{p05:pct(w,.05),median:pct(w,.5),p95:pct(w,.95)},probabilities:{cagrGe50:results.filter(x=>x.cagr>=.5).length/PATHS,cagrGe80:results.filter(x=>x.cagr>=.8).length/PATHS,cagrLt0:results.filter(x=>x.cagr<0).length/PATHS,maxDdLe30:results.filter(x=>x.dd<=-.3).length/PATHS,maxDdLe40:results.filter(x=>x.dd<=-.4).length/PATHS,maxDdLe50:results.filter(x=>x.dd<=-.5).length/PATHS,finalWealthLt1:results.filter(x=>x.wealth<1).length/PATHS},mechanics:{medianInvestedMonthShare:pct(results.map(x=>x.months?x.investedMonths/x.months:0),.5),medianExits:pct(results.map(x=>x.exits),.5),medianStops:pct(results.map(x=>x.stops),.5),medianCircuits:pct(results.map(x=>x.circuits),.5),medianRejectedBlocks:pct(results.map(x=>x.rejectedBlocks),.5)}}};
 const md=`# Availability-aware Structural Monte Carlo\n\nPaths **${PATHS}**, horizon **${YEARS}y**. No QQQ proxy imputation.\n\n|Metric|Result|\n|---|---:|\n|CAGR p5|${(summary.distribution.cagr.p05*100).toFixed(2)}%|\n|CAGR median|${(summary.distribution.cagr.median*100).toFixed(2)}%|\n|CAGR p95|${(summary.distribution.cagr.p95*100).toFixed(2)}%|\n|P(CAGR >= 50%)|${(summary.distribution.probabilities.cagrGe50*100).toFixed(2)}%|\n|P(CAGR >= 80%)|${(summary.distribution.probabilities.cagrGe80*100).toFixed(2)}%|\n|MaxDD median|${(summary.distribution.maxDrawdown.median*100).toFixed(2)}%|\n|Adverse DD p5|${(summary.distribution.maxDrawdown.adverseP05*100).toFixed(2)}%|\n|P(MaxDD <= -40%)|${(summary.distribution.probabilities.maxDdLe40*100).toFixed(2)}%|\n|5y loss probability|${(summary.distribution.probabilities.finalWealthLt1*100).toFixed(2)}%|\n|Final wealth median|${summary.distribution.finalWealth.median.toFixed(2)}x|\n|Median invested-month share|${(summary.distribution.mechanics.medianInvestedMonthShare*100).toFixed(2)}%|\n`;
 await mkdir(resolve("data/research/structural-monte-carlo"),{recursive:true});await writeFile(resolve("data/research/structural-monte-carlo/availability-aware.json"),JSON.stringify(summary,null,2));await writeFile(resolve("data/research/structural-monte-carlo/availability-aware.md"),md);console.log(md);console.log(`RESULT_JSON=${JSON.stringify(summary)}`)
}main().catch(e=>{console.error(e);process.exitCode=1});