import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import type { MonthlySignal, PricePoint, StrategyConfig, UniverseMonth } from "../src/lib/types";

type MarketDataFile={histories:Record<string,PricePoint[]>}; type UniverseFile={history:UniverseMonth[]};
type Variant={name:string; config:StrategyConfig; selector:"dynamic"|"fixed"};
const PATHS=Number(process.env.ABLATION_PATHS??300), YEARS=5, BLOCK=20, WARMUP=252, H=YEARS*252, SEED=20260825;
function rng32(seed:number){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0; const sd=(x:number[])=>{const m=avg(x);return x.length?Math.sqrt(avg(x.map(v=>(v-m)**2))):0};
const pct=(x:number[],p:number)=>{x=[...x].sort((a,b)=>a-b);const q=(x.length-1)*p,l=Math.floor(q),h=Math.ceil(q),w=q-l;return x[l]*(1-w)+x[h]*w};
const score=(r3:number,r6:number)=>.2*r3+.8*r6;
function latestUniverse(us:UniverseMonth[],d:string){let a=us[0];for(const u of us){if(u.asOf<=d)a=u;else break}return a}
function makeSignal(date:string,next:string|null,u:UniverseMonth,monthly:Map<string,number[]>,cfg:StrategyConfig,fixed?:string[]):MonthlySignal{
 const q=monthly.get("QQQ")??[], ret=(xs:number[],n:number)=>xs.length>n?xs.at(-1)!/xs.at(-(n+1))!-1:null; const q1=ret(q,1),q3=ret(q,3),q6=ret(q,6),qs=q1==null||q3==null||q6==null?null:score(q3,q6); const ma=q.slice(-cfg.market.qqqMonthlyMaMonths); const risk=q.length&&ma.length===cfg.market.qqqMonthlyMaMonths&&q.at(-1)!>avg(ma);
 const c:any[]=[]; for(const m of u.symbols){const xs=monthly.get(m.symbol)??[],r1=ret(xs,1),r3=ret(xs,3),r6=ret(xs,6);if(r1==null||r3==null||r6==null||qs==null){c.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:null,qqqScore:qs,scoreSpread:null,eligible:false,exclusionReason:"INSUFFICIENT_PRICE_HISTORY",rank:null});continue} const s=score(r3,r6),reason=r1>=cfg.momentum.surgeLimit?"ONE_MONTH_SURGE":s<=qs?"NOT_ABOVE_QQQ":null;c.push({symbol:m.symbol,oneMonth:r1,threeMonth:r3,sixMonth:r6,score:s,qqqScore:qs,scoreSpread:s-qs,eligible:!reason,exclusionReason:reason,rank:null})}
 let e=c.filter(x=>x.eligible&&x.score!=null).sort((a,b)=>b.score-a.score||a.symbol.localeCompare(b.symbol));e.forEach((x,i)=>x.rank=i+1);if(fixed?.length===2)e=fixed.map(s=>c.find(x=>x.symbol===s)).filter(Boolean); const sel=risk?e.slice(0,2):[],valid=sel.length===2,d=sd(c.filter(x=>x.eligible&&x.score!=null).map(x=>x.score)),zg=valid&&d>0?(sel[0].score-sel[1].score)/d:valid?0:null,conc=zg!=null&&zg>=cfg.allocation.concentrationZGap,top1=Math.min(cfg.allocation.maxTop1Weight,conc?cfg.allocation.concentratedTop1Weight:cfg.allocation.baseTop1Weight);
 return {strategyId:cfg.strategyId,signalMonth:date.slice(0,7),signalDate:date,executionDate:next,marketRiskOn:!!risk,qqqClose:q.at(-1)??null,qqqMonthlyMa:ma.length===cfg.market.qqqMonthlyMaMonths?avg(ma):null,qqqScore:qs,universe:u.symbols.map(x=>x.symbol),candidates:c,selectedSymbols:valid?sel.map(x=>x.symbol):[],targetWeights:valid?[top1,1-top1]:[],zGap:zg,allocationMode:!valid?"CASH":conc?"70/30":"50/50"} as MonthlySignal;
}
function cfgPatch(p:Partial<StrategyConfig>):StrategyConfig{return {...PRODUCTION_STRATEGY,...p,market:{...PRODUCTION_STRATEGY.market,...(p.market??{})},risk:{...PRODUCTION_STRATEGY.risk,...(p.risk??{})},recovery:{...PRODUCTION_STRATEGY.recovery,...(p.recovery??{})}} as StrategyConfig}
async function main(){const market=JSON.parse(await readFile(resolve("public/data/market-data.json"),"utf8")) as MarketDataFile;const uf=JSON.parse(await readFile(resolve("data/universe-history.json"),"utf8")) as UniverseFile;const us=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),hist=market.histories,qqq=hist.QQQ;const dates=qqq.filter(p=>p.date>=us[0].asOf).map(p=>p.date),target=dates.slice(-(WARMUP+H)),symbols=[...new Set(["QQQ",...us.flatMap(u=>u.symbols.map(x=>x.symbol))])],maps=new Map(symbols.map(s=>[s,new Map((hist[s]??[]).map(p=>[p.date,p]))]));
 const variants:Variant[]=[
  {name:"A Fixed Top2 + no risk",selector:"fixed",config:cfgPatch({market:{qqqMonthlyMaMonths:1} as any,risk:{individualStop:99,portfolioCircuit:99} as any,recovery:{qqqDailySmaDays:1,qqqMomentumDays:1,confirmationDays:1} as any})},
  {name:"B Dynamic Top2 + no risk",selector:"dynamic",config:cfgPatch({market:{qqqMonthlyMaMonths:1} as any,risk:{individualStop:99,portfolioCircuit:99} as any,recovery:{qqqDailySmaDays:1,qqqMomentumDays:1,confirmationDays:1} as any})},
  {name:"C + Market Gate",selector:"dynamic",config:cfgPatch({risk:{individualStop:99,portfolioCircuit:99} as any,recovery:{qqqDailySmaDays:1,qqqMomentumDays:1,confirmationDays:1} as any})},
  {name:"D + Stop",selector:"dynamic",config:cfgPatch({risk:{individualStop:.175,portfolioCircuit:99} as any,recovery:{qqqDailySmaDays:100,qqqMomentumDays:20,confirmationDays:10} as any})},
  {name:"E Full Production",selector:"dynamic",config:PRODUCTION_STRATEGY as StrategyConfig},
 ];
 const rr=rng32(SEED),starts=dates.map((_,i)=>i).filter(i=>i>=1&&i+BLOCK<dates.length),outputs:Record<string,{cagr:number[],dd:number[]}>={};for(const v of variants)outputs[v.name]={cagr:[],dd:[]};
 for(let p=0;p<PATHS;p++){const idx:number[]=[];while(idx.length<target.length){const s=starts[Math.floor(rr()*starts.length)];for(let j=0;j<BLOCK&&idx.length<target.length;j++)idx.push(s+j)}
  for(const v of variants){const syn=new Map(symbols.map(s=>[s,100])),monthly=new Map<string,number[]>(symbols.map(s=>[s,[]])),qd:PricePoint[]=[];let st=initialEngineState(v.config),peak=1,mdd=0,startEq=1,endEq=1,fixed:string[]|undefined;
   for(let ti=0;ti<target.length;ti++){const td=target[ti],next=target[ti+1]??null,si=idx[ti],sdte=dates[si],prev=dates[si-1],prices:Record<string,PricePoint>={};for(const s of symbols){const a=maps.get(s)?.get(sdte),b=maps.get(s)?.get(prev);if(!a||!b||a.open<=0||b.close<=0)continue;const pc=syn.get(s)!,o=pc*(a.open/b.close),c=o*(a.close/a.open);syn.set(s,c);prices[s]={date:td,open:o,high:Math.max(o,c),low:Math.min(o,c),close:c} as PricePoint}if(!prices.QQQ)continue;qd.push(prices.QQQ);const me=!next||next.slice(0,7)!==td.slice(0,7);let sig:MonthlySignal|null=null;if(me){for(const s of symbols){if(prices[s])monthly.get(s)!.push(syn.get(s)!)}const u=latestUniverse(us,sdte);if(v.selector==="fixed"&&!fixed){const tmp=makeSignal(td,next,u,monthly,v.config);if(tmp.selectedSymbols.length===2)fixed=tmp.selectedSymbols}sig=makeSignal(td,next,u,monthly,v.config,fixed)}if(ti===WARMUP){st=initialEngineState(v.config);peak=1;mdd=0;startEq=1}if(ti>=WARMUP){st=transitionDay(st,{date:td,prices,qqqHistoryThroughClose:qd,monthlySignal:sig,nextSessionDate:next},v.config);if(ti===WARMUP)startEq=st.currentEquity||1;endEq=st.currentEquity;peak=Math.max(peak,endEq);mdd=Math.min(mdd,endEq/peak-1)}}const years=(Date.parse(target.at(-1)!)-Date.parse(target[WARMUP]))/(365.25*86400000),fw=endEq/startEq;outputs[v.name].cagr.push(fw**(1/years)-1);outputs[v.name].dd.push(mdd)}
  if((p+1)%50===0)console.log(`completed ${p+1}/${PATHS}`)}
 const summary=Object.fromEntries(variants.map(v=>{const o=outputs[v.name];return[v.name,{cagr:{p05:pct(o.cagr,.05),median:pct(o.cagr,.5),p95:pct(o.cagr,.95)},maxDrawdown:{adverseP05:pct(o.dd,.05),median:pct(o.dd,.5)},probabilities:{cagrGe50:o.cagr.filter(x=>x>=.5).length/PATHS,cagrLt0:o.cagr.filter(x=>x<0).length/PATHS,ddLe40:o.dd.filter(x=>x<=-.4).length/PATHS}}]}));await mkdir(resolve("data/research/structural-monte-carlo"),{recursive:true});await writeFile(resolve("data/research/structural-monte-carlo/ablation.json"),JSON.stringify({generatedAt:new Date().toISOString(),paths:PATHS,summary},null,2));console.log("RESULT_JSON="+JSON.stringify({paths:PATHS,summary}))}
main().catch(e=>{console.error(e);process.exit(1)});
