import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { buildMonthlySignal, monthlyCloses } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import type { MonthlySignal, PricePoint, UniverseMonth } from "../src/lib/types";

const COST=PRODUCTION_STRATEGY.execution.transactionCost;
type TradeMeta={rank:1|2;symbol:string;entryDate:string;grossAllocation:number;entryPrice:number;targetWeight:number};
type TradeRow=TradeMeta&{exitDate:string;exitPrice:number;proceeds:number;pnl:number;returnOnAllocation:number;exitReason:string};
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:null;
const med=(x:number[])=>{if(!x.length)return null;const y=[...x].sort((a,b)=>a-b),m=Math.floor(y.length/2);return y.length%2?y[m]:(y[m-1]+y[m])/2};
const pct=(x:number|null)=>x===null?null:x*100;
function dailyFeature(points:PricePoint[],date:string){const p=[...points].filter(x=>x.date<=date).sort((a,b)=>a.date.localeCompare(b.date));const n=p.length,last=p.at(-1)?.close??null;if(!last)return{ret20:null,ret60:null,vol20:null,vol60:null,dist52wHigh:null};const ret=(d:number)=>n>d&&p[n-1-d]?.close?last/p[n-1-d].close-1:null;const vol=(d:number)=>{if(n<d+1)return null;const rs:number[]=[];for(let i=n-d;i<n;i++){const a=p[i-1]?.close,b=p[i]?.close;if(a&&b)rs.push(Math.log(b/a))}if(rs.length<d)return null;const mu=rs.reduce((a,b)=>a+b,0)/rs.length;return Math.sqrt(rs.reduce((a,b)=>a+(b-mu)**2,0)/rs.length)*Math.sqrt(252)};const h=p.slice(-252).reduce((m,x)=>Math.max(m,x.close),-Infinity);return{ret20:ret(20),ret60:ret(60),vol20:vol(20),vol60:vol(60),dist52wHigh:Number.isFinite(h)?last/h-1:null};}
function forward3m(points:PricePoint[],date:string){const m=monthlyCloses(points).filter(p=>p.date>=date);if(m.length<4)return null;return m[0].close&&m[3].close?m[3].close/m[0].close-1:null;}
function summarizeTrades(rows:TradeRow[]){const alloc=rows.map(r=>r.grossAllocation),rets=rows.map(r=>r.returnOnAllocation),pnls=rows.map(r=>r.pnl);return{trades:rows.length,wins:rows.filter(r=>r.pnl>0).length,winRate:rows.length?rows.filter(r=>r.pnl>0).length/rows.length:null,totalGrossAllocation:alloc.reduce((a,b)=>a+b,0),totalPnl:pnls.reduce((a,b)=>a+b,0),meanTradeReturn:avg(rets),medianTradeReturn:med(rets),weightedTradeReturn:alloc.reduce((a,b)=>a+b,0)?pnls.reduce((a,b)=>a+b,0)/alloc.reduce((a,b)=>a+b,0):null};}
function groupSummary(rows:any[]){const keys=["universeRank","oneMonth","threeMonth","sixMonth","score","scoreSpread","ret20","ret60","vol20","vol60","dist52wHigh","accel1v3"] as const;return Object.fromEntries(keys.map(k=>{const v=rows.map(r=>r[k]).filter((x:any)=>typeof x==="number"&&Number.isFinite(x));return[k,{n:v.length,mean:avg(v),median:med(v)}]}));}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>};const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]};const universe=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),qqq=[...(market.histories.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=qqq.map(p=>p.date),idx=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(market.histories).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])),um=new Map(universe.map(u=>[u.asOf,u]));let st=initialEngineState(PRODUCTION_STRATEGY);const active=new Map<string,TradeMeta>(),trades:TradeRow[]=[];
 for(let i=0;i<dates.length;i++){const date=dates[i];if(date<PRODUCTION_STRATEGY.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),u=um.get(date),sig=u?buildMonthlySignal({universe:u,histories:market.histories,qqq,nextSessionDate:next,config:PRODUCTION_STRATEGY}):null;const sy=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)]));const before=structuredClone(st),execSell=before.currentPositions.length>0&&(before.nextAction.type==="SELL_ALL_NEXT_OPEN"||before.nextAction.type==="MONTH_END_REBALANCE_NEXT_OPEN")&&before.nextAction.executionDate===date,execBuy=(before.nextAction.type==="BUY_NEXT_OPEN"||before.nextAction.type==="MONTH_END_REBALANCE_NEXT_OPEN")&&before.nextAction.executionDate===date;
  if(execSell){for(const p of before.currentPositions){const meta=active.get(p.symbol);if(!meta)continue;const px=prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice,proceeds=p.shares*px*(1-COST),pnl=proceeds-meta.grossAllocation;trades.push({...meta,exitDate:date,exitPrice:px,proceeds,pnl,returnOnAllocation:pnl/meta.grossAllocation,exitReason:before.nextAction.reason});active.delete(p.symbol)}}
  st=transitionDay(st,{date,prices,qqqHistoryThroughClose:qqq.slice(0,(idx.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},PRODUCTION_STRATEGY);
  if(execBuy&&before.pendingSignal?.selectedSymbols.length===2&&st.currentPositions.length===2){for(const p of st.currentPositions){const r=(before.pendingSignal.selectedSymbols.indexOf(p.symbol)+1) as 1|2;if(r!==1&&r!==2)continue;active.set(p.symbol,{rank:r,symbol:p.symbol,entryDate:date,grossAllocation:p.shares*p.entryPrice/(1-COST),entryPrice:p.entryPrice,targetWeight:p.targetWeight})}}
 }
 const rank1=trades.filter(r=>r.rank===1),rank2=trades.filter(r=>r.rank===2),totalPnl=trades.reduce((a,b)=>a+b.pnl,0);const byYear=Object.fromEntries([...new Set(trades.map(t=>t.exitDate.slice(0,4)))].sort().map(y=>[y,{rank1:summarizeTrades(rank1.filter(t=>t.exitDate.startsWith(y))),rank2:summarizeTrades(rank2.filter(t=>t.exitDate.startsWith(y)))}]));
 const winnerRows:any[]=[];for(const u of universe){if(u.asOf<PRODUCTION_STRATEGY.backtestStart)continue;const sig=buildMonthlySignal({universe:u,histories:market.histories,qqq,nextSessionDate:null,config:PRODUCTION_STRATEGY});const future=u.symbols.map(x=>({symbol:x.symbol,universeRank:x.universeRank,f:forward3m(market.histories[x.symbol]??[],u.asOf)})).filter(x=>x.f!==null) as {symbol:string;universeRank:number;f:number}[];if(!future.length)continue;future.sort((a,b)=>b.f-a.f);const w=future[0],c=sig.candidates.find(x=>x.symbol===w.symbol),d=dailyFeature(market.histories[w.symbol]??[],u.asOf),captured=sig.selectedSymbols.includes(w.symbol);let missReason="CAPTURED";if(!captured){if(!sig.marketRiskOn)missReason="MARKET_RISK_OFF";else if(!c)missReason="NO_CANDIDATE";else if(!c.eligible)missReason=c.exclusionReason??"INELIGIBLE";else missReason="ELIGIBLE_RANK_GT2";}winnerRows.push({date:u.asOf,symbol:w.symbol,universeRank:w.universeRank,forward3m:w.f,captured,missReason,eligible:c?.eligible??false,eligibleRank:c?.rank??null,oneMonth:c?.oneMonth??null,threeMonth:c?.threeMonth??null,sixMonth:c?.sixMonth??null,score:c?.score??null,scoreSpread:c?.scoreSpread??null,accel1v3:c?.oneMonth!=null&&c?.threeMonth!=null?c.oneMonth-c.threeMonth/3:null,...d});}
 const captured=winnerRows.filter(r=>r.captured),missed=winnerRows.filter(r=>!r.captured),reasonCounts=Object.fromEntries([...new Set(missed.map(r=>r.missReason))].sort().map(r=>[r,missed.filter(x=>x.missReason===r).length]));const eligibleMiss=missed.filter(r=>r.missReason==="ELIGIBLE_RANK_GT2");const rankBuckets=Object.fromEntries(["3-5","6-10","11-20","21+"].map(b=>[b,eligibleMiss.filter(r=>b==="3-5"?(r.eligibleRank>=3&&r.eligibleRank<=5):b==="6-10"?(r.eligibleRank>=6&&r.eligibleRank<=10):b==="11-20"?(r.eligibleRank>=11&&r.eligibleRank<=20):r.eligibleRank>=21).length]));
 const output={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,noLeverage:true,architectureHindsightRemains:true,tradeAttribution:"Production trades attributed by signal rank at entry; no alternate strategy is optimized.",winnerLabel:"Forward 3-month best return inside each PIT Top80 month; label is hindsight and used only for diagnosis.",featureTiming:"All diagnostic features use data on or before signal date."},top12:{all:summarizeTrades(trades),rank1:summarizeTrades(rank1),rank2:summarizeTrades(rank2),pnlContributionShare:{rank1:totalPnl?rank1.reduce((a,b)=>a+b.pnl,0)/totalPnl:null,rank2:totalPnl?rank2.reduce((a,b)=>a+b.pnl,0)/totalPnl:null},byYear},missedWinner:{months:winnerRows.length,captured:captured.length,captureRate:winnerRows.length?captured.length/winnerRows.length:null,missed:missed.length,reasonCounts,eligibleMissRankBuckets:rankBuckets,featureSummary:{captured:groupSummary(captured),missed:groupSummary(missed),eligibleRankGt2:groupSummary(eligibleMiss)},rows:winnerRows}};const dir=path.join(process.cwd(),"data/research/top12-missed-winner-diagnostic");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});