// research rerun 2026-08-30: trigger predeclared volume-imbalance diagnostic; no rule change
import fs from 'node:fs/promises';
import path from 'node:path';
import { PRODUCTION_STRATEGY } from '../src/lib/config';
import { buildMonthlySignal } from '../src/lib/strategy/momentum';
import type { PricePoint, UniverseMonth } from '../src/lib/types';

type VRow={date:string;open:number;close:number;volume:number};
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:null;
function corr(a:number[],b:number[]){if(a.length<5||a.length!==b.length)return null;const ma=mean(a)!,mb=mean(b)!;let n=0,da=0,db=0;for(let i=0;i<a.length;i++){const x=a[i]-ma,y=b[i]-mb;n+=x*y;da+=x*x;db+=y*y}return da>0&&db>0?n/Math.sqrt(da*db):null;}
async function yahoo(symbol:string){const a=Math.floor(Date.parse('2019-01-01T00:00:00Z')/1000),b=Math.floor(Date.parse('2026-09-01T00:00:00Z')/1000);const r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?period1=${a}&period2=${b}&interval=1d&events=div%2Csplits`,{headers:{'User-Agent':'Mozilla/5.0'}});if(!r.ok)return[];const j:any=await r.json(),x=j.chart?.result?.[0];if(!x)return[];const q=x.indicators.quote[0];return x.timestamp.map((t:number,i:number)=>q.close[i]!=null&&q.volume[i]!=null?{date:new Date(t*1000).toISOString().slice(0,10),open:q.open[i]??q.close[i],close:q.close[i],volume:q.volume[i]}:null).filter(Boolean) as VRow[];}
function imbalance(rows:VRow[],date:string){const x=rows.filter(r=>r.date<=date).slice(-20);if(x.length<20)return null;let signed=0,total=0;for(let i=1;i<x.length;i++){const v=x[i].volume;if(!(v>0))continue;const dir=x[i].close>x[i-1].close?1:x[i].close<x[i-1].close?-1:0;signed+=dir*v;total+=v;}return total>0?signed/total:null;}
function future(ps:PricePoint[],date:string,n:number){const x=ps.filter(p=>p.date>date&&p.open>0&&p.close>0);if(x.length<n)return null;return x[n-1].close/x[0].open-1;}
function quantileSpread(rows:any[],field:'r21'|'r63'){if(rows.length<10)return null;const s=[...rows].sort((a,b)=>a.imb-b.imb),k=Math.max(1,Math.floor(s.length*.25)),lo=s.slice(0,k).map(x=>x[field]),hi=s.slice(-k).map(x=>x[field]);return mean(hi)!-mean(lo)!;}
async function main(){const market=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8')) as {histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8')) as {history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),qqq=market.histories.QQQ??[];const months=u.filter(x=>x.asOf>=PRODUCTION_STRATEGY.backtestStart&&x.asOf<='2026-08-25');const need=new Set<string>();const topByDate=new Map<string,string[]>();for(const m of months){const sg=buildMonthlySignal({universe:m,histories:market.histories,qqq,nextSessionDate:null,config:PRODUCTION_STRATEGY});const top=sg.candidates.filter(c=>c.eligible&&c.score!=null).sort((a,b)=>(b.score??-Infinity)-(a.score??-Infinity)).slice(0,10).map(c=>c.symbol);topByDate.set(m.asOf,top);top.forEach(s=>need.add(s));}const vol:Record<string,VRow[]>={};for(const s of [...need]){vol[s]=await yahoo(s);await new Promise(r=>setTimeout(r,60));}const obs:any[]=[];for(const m of months){for(const s of topByDate.get(m.asOf)??[]){const imb=imbalance(vol[s]??[],m.asOf),r21=future(market.histories[s]??[],m.asOf,21),r63=future(market.histories[s]??[],m.asOf,63);if(imb!=null&&r21!=null&&r63!=null)obs.push({date:m.asOf,symbol:s,imb,r21,r63});}}
 const summ=(start:string,end:string)=>{const x=obs.filter(o=>o.date>=start&&o.date<=end);return{n:x.length,months:new Set(x.map(o=>o.date)).size,ic21:corr(x.map(o=>o.imb),x.map(o=>o.r21)),ic63:corr(x.map(o=>o.imb),x.map(o=>o.r63)),topBottom21:quantileSpread(x,'r21'),topBottom63:quantileSpread(x,'r63')};};const out={validity:{researchOnly:true,trueOOS:false,pit:true,parameterSearch:false,hypothesis:'Within monthly PIT Momentum Top10, higher trailing-20-session signed-volume imbalance predicts higher subsequent 21/63-session return.',signal:'sum(direction(close_t-close_t-1)*volume_t)/sum(volume_t), trailing 20 sessions through signal close.',gate:'Proceed only if both IC21 and IC63 are positive in both 2020-2023 and 2024-2026. Do not change sign/window after results.'},coverage:{symbols:need.size,observations:obs.length},early2020_2023:summ('2020-01-01','2023-12-31'),late2024_2026:summ('2024-01-01','2026-08-25')};console.log(JSON.stringify(out,null,2));const d=path.join(process.cwd(),'data/research/volume-imbalance-top10-diagnostic');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify({...out,observations:obs},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
