import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY as P} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,PositionState,PricePoint,StrategyConfig,UniverseMonth} from '../src/lib/types';
const TAX=.20315;
type L={gain:Record<string,number>;loss:Record<string,number>;taxes:number;sales:number};
const cfg=():StrategyConfig=>({...P,allocation:{...P.allocation,baseTop1Weight:.7,concentratedTop1Weight:.7,maxTop1Weight:.7}} as StrategyConfig);
function addPnl(l:L,pnl:number,d:string){const y=d.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++}
function salePnl(p:PositionState,px:number,c:StrategyConfig){const proceeds=p.shares*px*(1-c.execution.transactionCost),basis=p.shares*p.entryPrice;return proceeds-basis}
function taxed(curve:EquityPoint[],l:L){const ys=[...new Set(curve.map(p=>p.date.slice(0,4)))],tax:Record<string,number>={};let carry:{y:number,a:number}[]=[];for(const s of ys){const y=+s;carry=carry.filter(x=>y-x.y<=3);let n=(l.gain[s]??0)-(l.loss[s]??0);if(n>0){for(const x of carry){const u=Math.min(n,x.a);n-=u;x.a-=u;if(n<=0)break}carry=carry.filter(x=>x.a>1e-12);tax[s]=n*TAX}else if(n<0)carry.push({y,a:-n})}l.taxes=Object.values(tax).reduce((a,b)=>a+b,0);let e=curve[0]?.equity??1,prev=e,peak=e;return curve.map((p,i)=>{if(i)e*=p.equity/prev;prev=p.equity;const n=curve[i+1],y=p.date.slice(0,4);if((!n||n.date.slice(0,4)!==y)&&(tax[y]??0)>0)e=Math.max(0,e-(tax[y]??0)*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);return{date:p.date,equity:e,drawdown:e/peak-1}})}
function sim(hist:Record<string,PricePoint[]>,universe:UniverseMonth[]){const c=cfg(),q=[...hist.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date),di=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(universe.map(x=>[x.asOf,x]));let st=initialEngineState(c),prevBase=1;const curve:EquityPoint[]=[],l:L={gain:{},loss:{},taxes:0,sales:0};for(let i=0;i<dates.length;i++){const date=dates[i];if(date<c.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),u=um.get(date),sig=u?buildMonthlySignal({universe:u,histories:hist,qqq:q,nextSessionDate:next,config:c}):null,sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)])),before=structuredClone(st);if(before.currentPositions.length&&((before.nextAction.type==='SELL_ALL_NEXT_OPEN'||before.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN')&&before.nextAction.executionDate===date)){for(const p of before.currentPositions){const op=prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice;addPnl(l,salePnl(p,op,c),date)}}st=transitionDay(st,{date,prices,qqqHistoryThroughClose:q.slice(0,(di.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},c);curve.push({date,equity:st.currentEquity,drawdown:st.drawdown});prevBase=st.currentEquity}return{gross:curve,after:taxed(curve,l),l}}
function q(xs:number[],p:number){const a=[...xs].sort((x,y)=>x-y);if(!a.length)return null;const h=(a.length-1)*p,i=Math.floor(h),f=h-i;return i+1<a.length?a[i]*(1-f)+a[i+1]*f:a[i]}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),base=sim(m.histories,u);const winner=JSON.parse(await fs.readFile(path.join(process.cwd(),'scripts/w70-rolling-winner-dependence.ts'),'utf8').then(()=>fs.readFile(path.join(process.cwd(),'data/research/w70-rolling-winner-dependence/result.json'),'utf8')).catch(()=>Promise.resolve('{}'))).baseline?.selectedSymbols as string[]|undefined;let selected=winner;if(!selected){const {runBacktest}=await import('../src/lib/backtest');const bt=runBacktest({histories:m.histories,universeHistory:u,config:cfg()});selected=[...new Set(bt.events.flatMap(e=>e.symbols).filter(s=>s&&s!=='QQQ'))].sort()}const rows:any[]=[];for(const symbol of selected!){const uu=u.map(x=>({...x,symbols:x.symbols.filter(s=>s.symbol!==symbol)})),r=sim(m.histories,uu);rows.push({symbol,gross:performanceStats(r.gross),afterTax:performanceStats(r.after),taxPaidApprox:r.l.taxes,sales:r.l.sales});console.log('done',symbol)}rows.sort((a,b)=>a.afterTax.cagr-b.afterTax.cagr);const vals=rows.map(r=>r.afterTax.cagr),out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,taxApproximation:'20.315% annual realized P&L with 3-year loss carry; not exact broker tax-lot withholding.',reselectionAfterRemoval:true,parameterSearch:false,warning:'Distributional leave-one-out robustness diagnostic. Historical architecture and selected-ticker set remain visible; not a probability distribution of future returns.'},baseline:{gross:performanceStats(base.gross),afterTax:performanceStats(base.after),taxPaidApprox:base.l.taxes,sales:base.l.sales},distribution:{n:vals.length,min:q(vals,0),p10:q(vals,.10),p25:q(vals,.25),median:q(vals,.50),p75:q(vals,.75),p90:q(vals,.90),max:q(vals,1),countBelow40:vals.filter(x=>x<.40).length,countAtOrAbove40:vals.filter(x=>x>=.40).length},worst5:rows.slice(0,5).map(r=>({symbol:r.symbol,afterTaxCagr:r.afterTax.cagr,grossCagr:r.gross.cagr,maxDD:r.afterTax.maxDrawdown})),rows};const d=path.join(process.cwd(),'data/research/w70-winner-dependence-tax');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify({baseline:out.baseline,distribution:out.distribution,worst5:out.worst5},null,2))}main().catch(e=>{console.error(e);process.exit(1)});