import fs from 'node:fs/promises';
import path from 'node:path';
import {PRODUCTION_STRATEGY as P} from '../src/lib/config';
import {buildMonthlySignal} from '../src/lib/strategy/momentum';
import {initialEngineState,transitionDay} from '../src/lib/strategy/state-machine';
import {performanceStats} from '../src/lib/backtest';
import {nextUsTradingSession} from '../src/lib/trading-calendar';
import type {EquityPoint,PositionState,PricePoint,StrategyConfig,UniverseMonth} from '../src/lib/types';
const TAX=.20315;
type L={gain:Record<string,number>;loss:Record<string,number>;taxes:number;sales:number};
function cfg():StrategyConfig{return {...P,allocation:{...P.allocation,baseTop1Weight:.7,concentratedTop1Weight:.7,maxTop1Weight:.7}} as StrategyConfig}
function addPnl(l:L,pnl:number,d:string){const y=d.slice(0,4);if(pnl>=0)l.gain[y]=(l.gain[y]??0)+pnl;else l.loss[y]=(l.loss[y]??0)-pnl;l.sales++}
function salePnl(p:PositionState,px:number,c:StrategyConfig){const proceeds=p.shares*px*(1-c.execution.transactionCost),basis=p.shares*p.entryPrice;return proceeds-basis}
function taxed(curve:EquityPoint[],l:L){const ys=[...new Set(curve.map(p=>p.date.slice(0,4)))],tax:Record<string,number>={};let carry:{y:number,a:number}[]=[];for(const s of ys){const y=+s;carry=carry.filter(x=>y-x.y<=3);let n=(l.gain[s]??0)-(l.loss[s]??0);if(n>0){for(const x of carry){const u=Math.min(n,x.a);n-=u;x.a-=u;if(n<=0)break}carry=carry.filter(x=>x.a>1e-12);tax[s]=n*TAX}else if(n<0)carry.push({y,a:-n})}l.taxes=Object.values(tax).reduce((a,b)=>a+b,0);let e=curve[0]?.equity??1,prev=e,peak=e;return curve.map((p,i)=>{if(i)e*=p.equity/prev;prev=p.equity;const n=curve[i+1],y=p.date.slice(0,4);if((!n||n.date.slice(0,4)!==y)&&(tax[y]??0)>0)e=Math.max(0,e-(tax[y]??0)*(e/Math.max(p.equity,1e-12)));peak=Math.max(peak,e);return{date:p.date,equity:e,drawdown:e/peak-1}})}
function slice(c:EquityPoint[],s:string,e:string){const x=c.filter(p=>p.date>=s&&p.date<=e);if(x.length<2)return[];const b=x[0].equity;return x.map(p=>({...p,equity:p.equity/b}))}
function sim(hist:Record<string,PricePoint[]>,universe:UniverseMonth[],bridge:boolean){const c=cfg(),q=[...hist.QQQ].sort((a,b)=>a.date.localeCompare(b.date)),dates=q.map(x=>x.date),di=new Map(dates.map((d,i)=>[d,i])),pm=Object.fromEntries(Object.entries(hist).map(([s,p])=>[s,new Map(p.map(x=>[x.date,x]))])),um=new Map(universe.map(x=>[x.asOf,x]));let st=initialEngineState(c),prevBase=1,equity=1,peak=1,enterNext=false,exitNext=false,bridgeOn=false,bridgeCash=0,bridgeShares=0,bridgeBasis=0;const curve:EquityPoint[]=[],l:L={gain:{},loss:{},taxes:0,sales:0};for(let i=0;i<dates.length;i++){const date=dates[i];if(date<c.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),u=um.get(date),sig=u?buildMonthlySignal({universe:u,histories:hist,qqq:q,nextSessionDate:next,config:c}):null,sy=new Set(['QQQ',...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]),prices=Object.fromEntries([...sy].map(s=>[s,pm[s]?.get(date)])),before=structuredClone(st),beforeEq=st.currentEquity,wasInvested=before.currentPositions.length>0,qr=pm.QQQ?.get(date),qo=qr?.open??qr?.close,qc=qr?.close;
 // Base realized P&L is scaled to the capital actually following the base sleeve.
 if(before.currentPositions.length&&((before.nextAction.type==='SELL_ALL_NEXT_OPEN'||before.nextAction.type==='MONTH_END_REBALANCE_NEXT_OPEN')&&before.nextAction.executionDate===date)){const scale=!bridgeOn&&beforeEq>0?equity/beforeEq:1;for(const p of before.currentPositions){const op=prices[p.symbol]?.open??prices[p.symbol]?.close??p.currentPrice??p.entryPrice;addPnl(l,salePnl(p,op,c)*scale,date)}}
 st=transitionDay(st,{date,prices,qqqHistoryThroughClose:q.slice(0,(di.get(date)??i)+1),monthlySignal:sig,nextSessionDate:next},c);const nowInvested=st.currentPositions.length>0,enteredTop2=!wasInvested&&nowInvested,bf=prevBase>0?st.currentEquity/prevBase:1;
 if(!bridge){equity*=bf}else{
  if(exitNext&&bridgeOn&&qo){const proceeds=bridgeShares*qo*(1-c.execution.transactionCost);addPnl(l,proceeds-bridgeBasis,date);equity=bridgeCash+proceeds;bridgeOn=false;bridgeCash=bridgeShares=bridgeBasis=0;exitNext=false}
  if(enterNext&&!bridgeOn&&!nowInvested&&qo){bridgeCash=equity*.5;const notional=equity*.5;bridgeBasis=notional;bridgeShares=notional*(1-c.execution.transactionCost)/qo;bridgeOn=true;enterNext=false}
  if(enteredTop2&&bridgeOn&&qo){const proceeds=bridgeShares*qo*(1-c.execution.transactionCost);addPnl(l,proceeds-bridgeBasis,date);equity=bridgeCash+proceeds;bridgeOn=false;bridgeCash=bridgeShares=bridgeBasis=0;const top2Day=beforeEq>0?st.currentEquity/beforeEq:1;equity*=top2Day}
  else if(bridgeOn&&qc)equity=bridgeCash+bridgeShares*qc;
  else if(wasInvested||nowInvested)equity*=bf;
  if(bridgeOn&&sig&&sig.marketRiskOn===false)exitNext=true;
  if(!bridgeOn&&!enterNext&&!exitNext&&!nowInvested&&st.state==='WAITING_RECOVERY'&&st.marketRiskOn&&st.recoveryConsecutiveDays===1)enterNext=true;
  if(nowInvested){enterNext=false;exitNext=false}
 }
 peak=Math.max(peak,equity);curve.push({date,equity,drawdown:equity/peak-1});prevBase=st.currentEquity}
 return{gross:curve,after:taxed(curve,l),l}}
async function main(){const m=JSON.parse(await fs.readFile(path.join(process.cwd(),'public/data/market-data.json'),'utf8'))as{histories:Record<string,PricePoint[]>},uf=JSON.parse(await fs.readFile(path.join(process.cwd(),'data/universe-history.json'),'utf8'))as{history:UniverseMonth[]},u=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf)),a=sim(m.histories,u,false),b=sim(m.histories,u,true),years=[2022,2023,2024,2025,2026],out={generatedAt:new Date().toISOString(),validity:{researchOnly:true,trueOOS:false,noLeverage:true,taxApproximation:'20.315% annual realized P&L with 3-year loss carry; base sale P&L scaled to overlay capital; not exact broker tax-lot withholding.'},W70:{gross:performanceStats(a.gross),afterTax:performanceStats(a.after),taxPaidApprox:a.l.taxes,sales:a.l.sales},W70_B50_K1:{gross:performanceStats(b.gross),afterTax:performanceStats(b.after),taxPaidApprox:b.l.taxes,sales:b.l.sales},annual:years.map(y=>({year:y,W70:performanceStats(slice(a.after,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`)),W70_B50_K1:performanceStats(slice(b.after,`${y}-01-01`,y===2026?'2026-08-25':`${y}-12-31`))}))};const d=path.join(process.cwd(),'data/research/w70-recovery-bridge-tax');await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(d,'result.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2))}main().catch(e=>{console.error(e);process.exit(1)});