import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import type { EquityPoint, MonthlySignal, PricePoint, StrategyConfig, UniverseMonth } from "../src/lib/types";

type Metrics={start:string|null;end:string|null;days:number;totalReturn:number;cagr:number;maxDD:number;calmar:number|null};
function stats(c:EquityPoint[],s:string,e:string):Metrics{const r=c.filter(x=>x.date>=s&&x.date<=e);if(r.length<2)return{start:r[0]?.date??null,end:r.at(-1)?.date??null,days:r.length,totalReturn:0,cagr:0,maxDD:0,calmar:null};const f=r[0],l=r.at(-1)!;const yrs=Math.max(1/365.25,(Date.parse(l.date)-Date.parse(f.date))/(365.25*86400000));const totalReturn=l.equity/f.equity-1,cagr=(l.equity/f.equity)**(1/yrs)-1;let peak=f.equity,maxDD=0;for(const x of r){peak=Math.max(peak,x.equity);maxDD=Math.min(maxDD,x.equity/peak-1)}return{start:f.date,end:l.date,days:r.length,totalReturn,cagr,maxDD,calmar:maxDD<-1e-12?cagr/Math.abs(maxDD):null}}
function quant(v:number[],p:number){const x=v.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return null;const z=(x.length-1)*p,l=Math.floor(z),h=Math.ceil(z);return l===h?x[l]:x[l]*(h-z)+x[h]*(z-l)}
function mean(v:number[]){const x=v.filter(Number.isFinite);return x.length?x.reduce((a,b)=>a+b,0)/x.length:null}
function percentile(v:number[],y:number){const x=v.filter(Number.isFinite).sort((a,b)=>a-b);return x.length<=1?1:(x.filter(a=>a<=y).length-1)/(x.length-1)}

async function main(){
 const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>};
 const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]};
 const histories=market.histories,qqq=[...(histories.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date)),dates=qqq.map(x=>x.date),dateIndex=new Map(dates.map((d,i)=>[d,i]));
 const priceMaps=Object.fromEntries(Object.entries(histories).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])) as Record<string,Map<string,PricePoint>>;
 const universe=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));
 const mws=[{oneMonth:0,threeMonth:.5,sixMonth:.5,label:"0/50/50"},{oneMonth:0,threeMonth:.25,sixMonth:.75,label:"0/25/75"},{oneMonth:0,threeMonth:0,sixMonth:1,label:"0/0/100"},{oneMonth:.2,threeMonth:.3,sixMonth:.5,label:"20/30/50"}],us=[40,60,80],mas=[8,10,12],stops=[.15,.175,.2],circuits=[.125,.15,.175],recs=[5,10,15];
 type SigKey={key:string;u:number;signalConfig:StrategyConfig;signals:Map<string,MonthlySignal>};const sigGroups:SigKey[]=[];
 for(const mw of mws)for(const u of us)for(const ma of mas){const key=`mw${mw.label}-u${u}-ma${ma}`;const cfg:StrategyConfig={...PRODUCTION_STRATEGY,strategyId:`sig-${key}`,universe:{...PRODUCTION_STRATEGY.universe,size:u},momentum:{...PRODUCTION_STRATEGY.momentum,oneMonth:mw.oneMonth,threeMonth:mw.threeMonth,sixMonth:mw.sixMonth},market:{...PRODUCTION_STRATEGY.market,qqqMonthlyMaMonths:ma}};const sm=new Map<string,MonthlySignal>();for(const full of universe){const uni={...full,symbols:full.symbols.slice(0,u)};const i=dateIndex.get(uni.asOf);if(i===undefined)continue;const next=dates[i+1]??nextUsTradingSession(uni.asOf);sm.set(uni.asOf,buildMonthlySignal({universe:uni,histories,qqq,nextSessionDate:next,config:cfg}));}sigGroups.push({key,u,signalConfig:cfg,signals:sm})}
 console.log(`precomputed signal groups ${sigGroups.length}`);
 function simulate(signals:Map<string,MonthlySignal>,cfg:StrategyConfig):EquityPoint[]{let st=initialEngineState(cfg);const curve:EquityPoint[]=[],qh:PricePoint[]=[];for(let i=0;i<dates.length;i++){const date=dates[i];qh.push(qqq[i]);if(date<cfg.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),sig=signals.get(date)??null;const syms=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]);const prices=Object.fromEntries([...syms].map(s=>[s,priceMaps[s]?.get(date)]));st=transitionDay(st,{date,prices,qqqHistoryThroughClose:qh,monthlySignal:sig,nextSessionDate:next},cfg);curve.push({date,equity:st.currentEquity,drawdown:st.drawdown})}return curve}
 const sims:Array<{id:string;config:StrategyConfig;curve:EquityPoint[]}>=[];let count=0;for(const sg of sigGroups)for(const stop of stops)for(const circuit of circuits)for(const rec of recs){const id=`${sg.key}-s${stop}-c${circuit}-r${rec}`,config:StrategyConfig={...sg.signalConfig,strategyId:`wf-${id}`,risk:{individualStop:stop,portfolioCircuit:circuit},recovery:{...PRODUCTION_STRATEGY.recovery,confirmationDays:rec}};sims.push({id,config,curve:simulate(sg.signals,config)});count++;if(count%100===0)console.log(`simulated ${count}`)}
 const splits=[{trainEnd:"2021-12-31",oosStart:"2022-01-01",oosEnd:"2022-12-31",label:"2022"},{trainEnd:"2022-12-31",oosStart:"2023-01-01",oosEnd:"2023-12-31",label:"2023"},{trainEnd:"2023-12-31",oosStart:"2024-01-01",oosEnd:"2024-12-31",label:"2024"},{trainEnd:"2024-12-31",oosStart:"2025-01-01",oosEnd:"2025-12-31",label:"2025"},{trainEnd:"2025-12-31",oosStart:"2026-01-01",oosEnd:"2026-08-25",label:"2026-YTD"}];
 const results=[];for(const sp of splits){const rows=sims.map(x=>{const train=stats(x.curve,"2020-01-01",sp.trainEnd),oos=stats(x.curve,sp.oosStart,sp.oosEnd);return{id:x.id,config:x.config,train,oos,score:train.calmar??-Infinity}});const ranked=[...rows].sort((a,b)=>b.score-a.score||b.train.cagr-a.train.cagr||a.id.localeCompare(b.id)),n=Math.ceil(ranked.length*.1),top=ranked.slice(0,n),best=ranked[0],allR=rows.map(x=>x.oos.totalReturn),topR=top.map(x=>x.oos.totalReturn),allD=rows.map(x=>x.oos.maxDD),topD=top.map(x=>x.oos.maxDD),allMed=quant(allR,.5);results.push({...sp,candidateCount:rows.length,topDecileCount:n,bestTrain:{id:best.id,config:best.config,train:best.train,oos:best.oos,oosReturnPercentileAmongAllCandidates:percentile(allR,best.oos.totalReturn)},allCandidatesOOS:{returnMedian:allMed,returnP10:quant(allR,.1),returnP90:quant(allR,.9),maxDDMedian:quant(allD,.5),maxDDP10:quant(allD,.1),maxDDP90:quant(allD,.9)},topTrainDecileOOS:{returnMean:mean(topR),returnMedian:quant(topR,.5),returnP10:quant(topR,.1),returnP90:quant(topR,.9),maxDDMedian:quant(topD,.5),maxDDP10:quant(topD,.1),maxDDP90:quant(topD,.9),fractionPositive:topR.filter(x=>x>0).length/topR.length,fractionAboveAllMedian:topR.filter(x=>x>(allMed??Infinity)).length/topR.length},top10Ids:top.slice(0,10).map(x=>({id:x.id,trainScore:x.score,trainCagr:x.train.cagr,trainMaxDD:x.train.maxDD,oosReturn:x.oos.totalReturn,oosMaxDD:x.oos.maxDD}))})}
 const output={generatedAt:new Date().toISOString(),test:"nested pseudo-OOS parameter-transfer walk-forward",validity:{futureOosReturnsUsedForSelection:false,pointInTimeUniverseData:true,architectureFixedWithHindsight:true,candidateGridDefinedAfterFullHistoryWasKnown:true,thereforeTrueHistoricalOOS:false,primaryInference:"Does training-period parameter strength transfer to the next calendar year within the fixed strategy architecture?",warning:"Architecture and candidate-grid hindsight remain; early splits have short training histories. Primary inference is top-decile transfer, not a single optimized winner. Annual re-selection switching costs are not modeled because each candidate is evaluated as a continuous strategy state."},fixedArchitecture:{topN:2,surgeLimit:PRODUCTION_STRATEGY.momentum.surgeLimit,requireAboveQqqScore:PRODUCTION_STRATEGY.momentum.requireAboveQqqScore,allocation:PRODUCTION_STRATEGY.allocation,qqqDailySmaDays:PRODUCTION_STRATEGY.recovery.qqqDailySmaDays,qqqMomentumDays:PRODUCTION_STRATEGY.recovery.qqqMomentumDays,transactionCost:PRODUCTION_STRATEGY.execution.transactionCost},grid:{momentumWeights:mws,universeSizes:us,maMonths:mas,stops,circuits,recoveryDays:recs,candidateCount:sims.length},selector:"Training Calmar; evaluate next-year transfer of top training decile",splits:results};const dir=path.join(process.cwd(),"data/research/walkforward-parameter-transfer");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(output,null,2));console.log(JSON.stringify({count:sims.length,splits:results.map(s=>({label:s.label,best:s.bestTrain.id,bestOos:s.bestTrain.oos.totalReturn,bestPct:s.bestTrain.oosReturnPercentileAmongAllCandidates,topMedian:s.topTrainDecileOOS.returnMedian,allMedian:s.allCandidatesOOS.returnMedian,topAboveAll:s.topTrainDecileOOS.fractionAboveAllMedian}))},null,2));
}
main().catch(e=>{console.error(e);process.exit(1)});
