import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import type { EquityPoint, PricePoint, StrategyConfig, UniverseMonth } from "../src/lib/types";

type Metrics={start:string|null;end:string|null;days:number;totalReturn:number;cagr:number;maxDD:number;calmar:number|null};
function metrics(curve:EquityPoint[],start:string,end:string):Metrics{const rows=curve.filter(p=>p.date>=start&&p.date<=end);if(rows.length<2)return{start:rows[0]?.date??null,end:rows.at(-1)?.date??null,days:rows.length,totalReturn:0,cagr:0,maxDD:0,calmar:null};const f=rows[0],l=rows.at(-1)!;const years=Math.max(1/365.25,(Date.parse(l.date)-Date.parse(f.date))/(365.25*86400000));const totalReturn=l.equity/f.equity-1,cagr=(l.equity/f.equity)**(1/years)-1;let peak=f.equity,maxDD=0;for(const r of rows){peak=Math.max(peak,r.equity);maxDD=Math.min(maxDD,r.equity/peak-1)}return{start:f.date,end:l.date,days:rows.length,totalReturn,cagr,maxDD,calmar:maxDD<-1e-12?cagr/Math.abs(maxDD):null}}
function q(v:number[],q:number){const x=v.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return null;const p=(x.length-1)*q,l=Math.floor(p),h=Math.ceil(p);return l===h?x[l]:x[l]*(h-p)+x[h]*(p-l)}
function avg(v:number[]){const x=v.filter(Number.isFinite);return x.length?x.reduce((a,b)=>a+b,0)/x.length:null}
function pct(v:number[],value:number){const x=v.filter(Number.isFinite).sort((a,b)=>a-b);if(x.length<=1)return 1;return(x.filter(a=>a<=value).length-1)/(x.length-1)}

function simulate(histories:Record<string,PricePoint[]>,universeHistory:UniverseMonth[],config:StrategyConfig):EquityPoint[]{
 const qqq=[...(histories.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date));const dates=qqq.map(p=>p.date);const priceMaps=Object.fromEntries(Object.entries(histories).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))]));const ub=new Map(universeHistory.map(u=>[u.asOf,u]));let state=initialEngineState(config);const curve:EquityPoint[]=[];const qqqThrough:PricePoint[]=[];
 for(let i=0;i<dates.length;i++){const date=dates[i];qqqThrough.push(qqq[i]);if(date<config.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date);const u=ub.get(date);const signal=u?buildMonthlySignal({universe:u,histories,qqq,nextSessionDate:next,config}):null;const syms=new Set(["QQQ",...state.currentPositions.map(p=>p.symbol),...(state.pendingSignal?.selectedSymbols??[]),...state.nextAction.symbols,...(signal?.selectedSymbols??[])]);const prices=Object.fromEntries([...syms].map(s=>[s,priceMaps[s]?.get(date)]));state=transitionDay(state,{date,prices,qqqHistoryThroughClose:qqqThrough,monthlySignal:signal,nextSessionDate:next},config);curve.push({date,equity:state.currentEquity,drawdown:state.drawdown})}
 return curve;
}

async function main(){
 const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>};const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]};const histories=market.histories;const baseUniverse=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));
 const momentumWeights=[{oneMonth:0,threeMonth:.50,sixMonth:.50,label:"0/50/50"},{oneMonth:0,threeMonth:.25,sixMonth:.75,label:"0/25/75"},{oneMonth:0,threeMonth:0,sixMonth:1,label:"0/0/100"},{oneMonth:.20,threeMonth:.30,sixMonth:.50,label:"20/30/50"}];
 const universeSizes=[40,60,80],maMonths=[8,10,12],stops=[.15,.175,.20],circuits=[.125,.15,.175],recoveryDays=[5,10,15];
 const configs:Array<{id:string;config:StrategyConfig;u:number}>=[];for(const mw of momentumWeights)for(const u of universeSizes)for(const ma of maMonths)for(const stop of stops)for(const circuit of circuits)for(const recovery of recoveryDays){const id=`mw${mw.label}-u${u}-ma${ma}-s${stop}-c${circuit}-r${recovery}`;configs.push({id,u,config:{...PRODUCTION_STRATEGY,strategyId:`wf-${id}`,universe:{...PRODUCTION_STRATEGY.universe,size:u},momentum:{...PRODUCTION_STRATEGY.momentum,oneMonth:mw.oneMonth,threeMonth:mw.threeMonth,sixMonth:mw.sixMonth},market:{...PRODUCTION_STRATEGY.market,qqqMonthlyMaMonths:ma},risk:{individualStop:stop,portfolioCircuit:circuit},recovery:{...PRODUCTION_STRATEGY.recovery,confirmationDays:recovery}}})}
 const uc=new Map<number,UniverseMonth[]>();for(const u of universeSizes)uc.set(u,baseUniverse.map(m=>({...m,symbols:m.symbols.slice(0,u)})));
 const sims=[] as Array<{id:string;config:StrategyConfig;curve:EquityPoint[]}>;for(let i=0;i<configs.length;i++){const c=configs[i];sims.push({id:c.id,config:c.config,curve:simulate(histories,uc.get(c.u)!,c.config)});if((i+1)%100===0)console.log(`simulated ${i+1}/${configs.length}`)}
 const splits=[{trainEnd:"2021-12-31",oosStart:"2022-01-01",oosEnd:"2022-12-31",label:"2022"},{trainEnd:"2022-12-31",oosStart:"2023-01-01",oosEnd:"2023-12-31",label:"2023"},{trainEnd:"2023-12-31",oosStart:"2024-01-01",oosEnd:"2024-12-31",label:"2024"},{trainEnd:"2024-12-31",oosStart:"2025-01-01",oosEnd:"2025-12-31",label:"2025"},{trainEnd:"2025-12-31",oosStart:"2026-01-01",oosEnd:"2026-08-25",label:"2026-YTD"}];
 const outSplits=[];for(const sp of splits){const rows=sims.map(s=>{const train=metrics(s.curve,"2020-01-01",sp.trainEnd),oos=metrics(s.curve,sp.oosStart,sp.oosEnd);return{id:s.id,config:s.config,train,oos,score:train.calmar??-Infinity}});const ranked=[...rows].sort((a,b)=>b.score-a.score||b.train.cagr-a.train.cagr||a.id.localeCompare(b.id));const n=Math.ceil(ranked.length*.1),top=ranked.slice(0,n),best=ranked[0];const ar=rows.map(x=>x.oos.totalReturn),tr=top.map(x=>x.oos.totalReturn),ad=rows.map(x=>x.oos.maxDD),td=top.map(x=>x.oos.maxDD),am=q(ar,.5);outSplits.push({...sp,candidateCount:rows.length,topDecileCount:n,bestTrain:{id:best.id,config:best.config,train:best.train,oos:best.oos,oosReturnPercentileAmongAllCandidates:pct(ar,best.oos.totalReturn)},allCandidatesOOS:{returnMedian:am,returnP10:q(ar,.1),returnP90:q(ar,.9),maxDDMedian:q(ad,.5),maxDDP10:q(ad,.1),maxDDP90:q(ad,.9)},topTrainDecileOOS:{returnMean:avg(tr),returnMedian:q(tr,.5),returnP10:q(tr,.1),returnP90:q(tr,.9),maxDDMedian:q(td,.5),maxDDP10:q(td,.1),maxDDP90:q(td,.9),fractionPositive:tr.filter(x=>x>0).length/tr.length,fractionAboveAllMedian:tr.filter(x=>x>(am??Infinity)).length/tr.length},top10Ids:top.slice(0,10).map(x=>({id:x.id,trainScore:x.score,trainCagr:x.train.cagr,trainMaxDD:x.train.maxDD,oosReturn:x.oos.totalReturn,oosMaxDD:x.oos.maxDD}))})}
 const output={generatedAt:new Date().toISOString(),test:"nested pseudo-OOS parameter-transfer walk-forward",validity:{futureOosReturnsUsedForSelection:false,pointInTimeUniverseData:true,architectureFixedWithHindsight:true,candidateGridDefinedAfterFullHistoryWasKnown:true,thereforeTrueHistoricalOOS:false,primaryInference:"Does training-period parameter strength transfer to the next calendar year within the fixed strategy architecture?",warning:"Architecture and candidate-grid hindsight remain. Early splits have short training histories. Top-decile transfer is the primary result; single-winner performance is secondary."},fixedArchitecture:{topN:2,surgeLimit:PRODUCTION_STRATEGY.momentum.surgeLimit,requireAboveQqqScore:PRODUCTION_STRATEGY.momentum.requireAboveQqqScore,allocation:PRODUCTION_STRATEGY.allocation,qqqDailySmaDays:PRODUCTION_STRATEGY.recovery.qqqDailySmaDays,qqqMomentumDays:PRODUCTION_STRATEGY.recovery.qqqMomentumDays,transactionCost:PRODUCTION_STRATEGY.execution.transactionCost},grid:{momentumWeights,universeSizes,maMonths,stops,circuits,recoveryDays,candidateCount:configs.length},selector:"Training Calmar; primary inference from top 10% transfer to next year",splits:outSplits};const dir=path.join(process.cwd(),"data/research/walkforward-parameter-transfer");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(output,null,2));console.log(JSON.stringify({count:configs.length,splits:outSplits.map(s=>({label:s.label,best:s.bestTrain.id,bestOos:s.bestTrain.oos.totalReturn,bestPct:s.bestTrain.oosReturnPercentileAmongAllCandidates,topMedian:s.topTrainDecileOOS.returnMedian,allMedian:s.allCandidatesOOS.returnMedian,topAboveAll:s.topTrainDecileOOS.fractionAboveAllMedian}))},null,2));
}
main().catch(e=>{console.error(e);process.exit(1)});
