import fs from "node:fs/promises";
import path from "node:path";
import { PRODUCTION_STRATEGY } from "../src/lib/config";
import { buildMonthlySignal } from "../src/lib/strategy/momentum";
import { initialEngineState, transitionDay } from "../src/lib/strategy/state-machine";
import { nextUsTradingSession } from "../src/lib/trading-calendar";
import type { EquityPoint, PricePoint, StrategyConfig, UniverseMonth } from "../src/lib/types";

type Metrics={start:string|null;end:string|null;days:number;totalReturn:number;cagr:number;maxDD:number;calmar:number|null};
const qm=(v:number[],p:number)=>{const x=v.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return null;const z=(x.length-1)*p,l=Math.floor(z),h=Math.ceil(z);return l===h?x[l]:x[l]*(h-z)+x[h]*(z-l)};
const avg=(v:number[])=>{const x=v.filter(Number.isFinite);return x.length?x.reduce((a,b)=>a+b,0)/x.length:null};
const pct=(v:number[],y:number)=>{const x=v.filter(Number.isFinite).sort((a,b)=>a-b);return x.length<=1?1:(x.filter(a=>a<=y).length-1)/(x.length-1)};
function mt(c:EquityPoint[],s:string,e:string):Metrics{const r=c.filter(x=>x.date>=s&&x.date<=e);if(r.length<2)return{start:r[0]?.date??null,end:r.at(-1)?.date??null,days:r.length,totalReturn:0,cagr:0,maxDD:0,calmar:null};const f=r[0],l=r.at(-1)!;const yrs=Math.max(1/365.25,(Date.parse(l.date)-Date.parse(f.date))/(365.25*86400000));const totalReturn=l.equity/f.equity-1,cagr=(l.equity/f.equity)**(1/yrs)-1;let peak=f.equity,maxDD=0;for(const x of r){peak=Math.max(peak,x.equity);maxDD=Math.min(maxDD,x.equity/peak-1)}return{start:f.date,end:l.date,days:r.length,totalReturn,cagr,maxDD,calmar:maxDD<-1e-12?cagr/Math.abs(maxDD):null}}

async function main(){
 const market=JSON.parse(await fs.readFile(path.join(process.cwd(),"public/data/market-data.json"),"utf8")) as {histories:Record<string,PricePoint[]>};const uf=JSON.parse(await fs.readFile(path.join(process.cwd(),"data/universe-history.json"),"utf8")) as {history:UniverseMonth[]};const histories=market.histories;const qqq=[...(histories.QQQ??[])].sort((a,b)=>a.date.localeCompare(b.date));const dates=qqq.map(x=>x.date);const priceMaps=Object.fromEntries(Object.entries(histories).map(([s,ps])=>[s,new Map(ps.map(p=>[p.date,p]))])) as Record<string,Map<string,PricePoint>>;const baseU=[...uf.history].sort((a,b)=>a.asOf.localeCompare(b.asOf));
 const mws=[{oneMonth:0,threeMonth:.5,sixMonth:.5,label:"0/50/50"},{oneMonth:0,threeMonth:.25,sixMonth:.75,label:"0/25/75"},{oneMonth:0,threeMonth:0,sixMonth:1,label:"0/0/100"},{oneMonth:.2,threeMonth:.3,sixMonth:.5,label:"20/30/50"}],us=[40,60,80],mas=[8,10,12],stops=[.15,.175,.2],circs=[.125,.15,.175],recs=[5,10,15];
 const ub=new Map<number,Map<string,UniverseMonth>>();for(const u of us)ub.set(u,new Map(baseU.map(m=>[m.asOf,{...m,symbols:m.symbols.slice(0,u)}])));
 const configs:Array<{id:string;u:number;cfg:StrategyConfig}>=[];for(const mw of mws)for(const u of us)for(const ma of mas)for(const stop of stops)for(const circ of circs)for(const rec of recs){const id=`mw${mw.label}-u${u}-ma${ma}-s${stop}-c${circ}-r${rec}`;configs.push({id,u,cfg:{...PRODUCTION_STRATEGY,strategyId:`wf-${id}`,universe:{...PRODUCTION_STRATEGY.universe,size:u},momentum:{...PRODUCTION_STRATEGY.momentum,oneMonth:mw.oneMonth,threeMonth:mw.threeMonth,sixMonth:mw.sixMonth},market:{...PRODUCTION_STRATEGY.market,qqqMonthlyMaMonths:ma},risk:{individualStop:stop,portfolioCircuit:circ},recovery:{...PRODUCTION_STRATEGY.recovery,confirmationDays:rec}}})}
 function sim(u:number,cfg:StrategyConfig){let st=initialEngineState(cfg);const curve:EquityPoint[]=[],qh:PricePoint[]=[];const um=ub.get(u)!;for(let i=0;i<dates.length;i++){const date=dates[i];qh.push(qqq[i]);if(date<cfg.backtestStart)continue;const next=dates[i+1]??nextUsTradingSession(date),univ=um.get(date);const sig=univ?buildMonthlySignal({universe:univ,histories,qqq,nextSessionDate:next,config:cfg}):null;const syms=new Set(["QQQ",...st.currentPositions.map(p=>p.symbol),...(st.pendingSignal?.selectedSymbols??[]),...st.nextAction.symbols,...(sig?.selectedSymbols??[])]);const prices=Object.fromEntries([...syms].map(s=>[s,priceMaps[s]?.get(date)]));st=transitionDay(st,{date,prices,qqqHistoryThroughClose:qh,monthlySignal:sig,nextSessionDate:next},cfg);curve.push({date,equity:st.currentEquity,drawdown:st.drawdown})}return curve}
 const sims=[] as Array<{id:string;cfg:StrategyConfig;curve:EquityPoint[]}>;for(let i=0;i<configs.length;i++){const x=configs[i];sims.push({id:x.id,cfg:x.cfg,curve:sim(x.u,x.cfg)});if((i+1)%100===0)console.log(`simulated ${i+1}/${configs.length}`)}
 const splits=[{trainEnd:"2021-12-31",oosStart:"2022-01-01",oosEnd:"2022-12-31",label:"2022"},{trainEnd:"2022-12-31",oosStart:"2023-01-01",oosEnd:"2023-12-31",label:"2023"},{trainEnd:"2023-12-31",oosStart:"2024-01-01",oosEnd:"2024-12-31",label:"2024"},{trainEnd:"2024-12-31",oosStart:"2025-01-01",oosEnd:"2025-12-31",label:"2025"},{trainEnd:"2025-12-31",oosStart:"2026-01-01",oosEnd:"2026-08-25",label:"2026-YTD"}];
 const os=[];for(const sp of splits){const rows=sims.map(x=>{const train=mt(x.curve,"2020-01-01",sp.trainEnd),oos=mt(x.curve,sp.oosStart,sp.oosEnd);return{id:x.id,cfg:x.cfg,train,oos,score:train.calmar??-Infinity}});const rr=[...rows].sort((a,b)=>b.score-a.score||b.train.cagr-a.train.cagr||a.id.localeCompare(b.id)),n=Math.ceil(rr.length*.1),top=rr.slice(0,n),best=rr[0],ar=rows.map(x=>x.oos.totalReturn),tr=top.map(x=>x.oos.totalReturn),ad=rows.map(x=>x.oos.maxDD),td=top.map(x=>x.oos.maxDD),am=qm(ar,.5);os.push({...sp,candidateCount:rows.length,topDecileCount:n,bestTrain:{id:best.id,config:best.cfg,train:best.train,oos:best.oos,oosReturnPercentileAmongAllCandidates:pct(ar,best.oos.totalReturn)},allCandidatesOOS:{returnMedian:am,returnP10:qm(ar,.1),returnP90:qm(ar,.9),maxDDMedian:qm(ad,.5),maxDDP10:qm(ad,.1),maxDDP90:qm(ad,.9)},topTrainDecileOOS:{returnMean:avg(tr),returnMedian:qm(tr,.5),returnP10:qm(tr,.1),returnP90:qm(tr,.9),maxDDMedian:qm(td,.5),maxDDP10:qm(td,.1),maxDDP90:qm(td,.9),fractionPositive:tr.filter(x=>x>0).length/tr.length,fractionAboveAllMedian:tr.filter(x=>x>(am??Infinity)).length/tr.length},top10Ids:top.slice(0,10).map(x=>({id:x.id,trainScore:x.score,trainCagr:x.train.cagr,trainMaxDD:x.train.maxDD,oosReturn:x.oos.totalReturn,oosMaxDD:x.oos.maxDD}))})}
 const out={generatedAt:new Date().toISOString(),test:"nested pseudo-OOS parameter-transfer walk-forward",validity:{futureOosReturnsUsedForSelection:false,pointInTimeUniverseData:true,architectureFixedWithHindsight:true,candidateGridDefinedAfterFullHistoryWasKnown:true,thereforeTrueHistoricalOOS:false,primaryInference:"Does training-period parameter strength transfer to the next calendar year within the fixed strategy architecture?",warning:"Architecture and candidate-grid hindsight remain; early splits have short training histories. Primary inference is top-decile transfer, not a single optimized winner."},fixedArchitecture:{topN:2,surgeLimit:PRODUCTION_STRATEGY.momentum.surgeLimit,requireAboveQqqScore:PRODUCTION_STRATEGY.momentum.requireAboveQqqScore,allocation:PRODUCTION_STRATEGY.allocation,qqqDailySmaDays:PRODUCTION_STRATEGY.recovery.qqqDailySmaDays,qqqMomentumDays:PRODUCTION_STRATEGY.recovery.qqqMomentumDays,transactionCost:PRODUCTION_STRATEGY.execution.transactionCost},grid:{momentumWeights:mws,universeSizes:us,maMonths:mas,stops,circuits:circs,recoveryDays:recs,candidateCount:configs.length},selector:"Training Calmar; evaluate next-year transfer of top training decile",splits:os};const dir=path.join(process.cwd(),"data/research/walkforward-parameter-transfer");await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,"result.json"),JSON.stringify(out,null,2));console.log(JSON.stringify({count:configs.length,splits:os.map(s=>({label:s.label,best:s.bestTrain.id,bestOos:s.bestTrain.oos.totalReturn,bestPct:s.bestTrain.oosReturnPercentileAmongAllCandidates,topMedian:s.topTrainDecileOOS.returnMedian,allMedian:s.allCandidatesOOS.returnMedian,topAboveAll:s.topTrainDecileOOS.fractionAboveAllMedian}))},null,2));
}
main().catch(e=>{console.error(e);process.exit(1)});
